yt-project/yt

doc/source/examining/loading_data.rst
yt/frontends/stream/data_structures.py
yt/frontends/stream/io.py
yt/frontends/stream/tests/test_stream_unstructured.py
yt/visualization/volume_rendering/render_source.py
yt/visualization/volume_rendering/tests/test_mesh_render.py

This fixes support for multiple meshes in the streaming unstructured frontend. It also sets up mesh unions for that frontend, so that multiple meshes can be shown on the same plot.

[BUGFIX] Fix multiple mesh support for streaming unstructured datasets . Closes Issue #1350.

---

yt/frontends/enzo/io.py

Rather than returning None, we need to return an array filled with zeros. If we
don't do this then arrays with partially uninitialized data can find their way
back to the user.

[BUG] fix I/O for enzo Dark_Matter_Density field. Closes #1359

---

yt/visualization/profile_plotter.py
yt/visualization/tests/test_profile_plots.py

This fixes an issue reported by @pgrete on Slack. If we try to plot multiple fields but still have two or more profiles of at least one field we break the logic in this for loop. See the test I added for an example. The fix is a straightforward refactoring.

plot the same field multiple times along with other fields in ProfilePlot

---

clean.sh

Since yt has migrated from hg to git, the `clean.sh` script should be updated to use git.

Replace hg purge by git clean

---

CONTRIBUTING.rst

This incorporates suggestions that @mkcor made on Slack. These names are the "canonical" names for the roles they play in our workflow.

Use "origin" and "upstream" as names for remotes in CONTRIBUTING file

---

yt/data_objects/grid_patch.py
yt/data_objects/tests/test_fluxes.py

This fixes the issue reported by Joe Tomlinson on the mailing list and filed by me in #1368. The issue in his test script is that ('gas', 'x') has `units` of `code_length` but `output_units` of `cm`. Usually this doesn't matter for internal operations but since we are directly using `np.add` this distinction triggers an error.
Sadly yet another case where the distinction between `units` and `output_units` causes issues. In the long run I'd like to make a plan to get rid of `output_unit`, but for now we'll need fixes like this to avoid errors in user scripts.

Use output_units instead of units when generating ghost zones. closes #1368

---

yt/fields/field_info_container.py
yt/frontends/stream/tests/test_outputs.py

Closes #1344
I think this is all that needs to happen but let's see if this breaks any tests.

Use the original field's units when aliasing dimensionless fields.

---

doc/source/analyzing/generating_processed_data.rst
doc/source/cookbook/profile_with_standard_deviation.py
doc/source/cookbook/simple_plots.rst
yt/analysis_modules/halo_analysis/halo_callbacks.py
yt/data_objects/profiles.py

See the discussion in #1306 as well as [this mailing list thread](http://lists.spacepope.org/pipermail/yt-users-spacepope.org/2017-January/008372.html).
In principle we could make `variance` return the square of the `standard_deviation` but that would break old scripts, so I think we're stuck with this.

Deprecate profile.variance in favor of profile.standard_deviation

---

yt/analysis_modules/ppv_cube/tests/test_ppv.py
yt/data_objects/tests/test_boolean_regions.py
yt/data_objects/tests/test_covering_grid.py
yt/testing.py
yt/utilities/lib/image_samplers.pyx
yt/utilities/tests/test_particle_generator.py
yt/visualization/tests/test_particle_plot.py
yt/visualization/tests/test_plotwindow.py
yt/visualization/tests/test_profile_plots.py
yt/visualization/volume_rendering/tests/test_scene.py
yt/visualization/volume_rendering/tests/test_varia.py
yt/visualization/volume_rendering/tests/test_zbuff.py

This is an attempt to reduce the memory usage of the unit tests. Ideally this will unblock #1356.
Right now the peak memory usage of the unit tests is 4 gigabytes. Most of this is due to the plot window tests, which make use of a pattern where they allocate a bunch of plot objects at class level to avoid recalculating data. It turns out that `nose` deallocates these classes just before the test suite finishes, so this pattern substantially increases the peak memory usage of the test suite.
The fix there is to refactor tests that make use of the `setUpClass` function so that plot objects get allocated and then deallocated as soon as we need them. This drops the peak memory usage of the unit tests to 2 gigabytes or so.
The remaining major source of leaked memory seems to be the volume …

Reduce the memory usage of the unit tests

---

.travis.yml
yt/data_objects/tests/test_image_array.py
yt/tests/test_flake8.py
yt/units/tests/test_ytarray.py
yt/units/yt_array.py
yt/utilities/tests/test_config.py

This adds configuration for a travis builder. I've enabled support for Travis for yt-project/yt which I hope won't break other pull requests while this gets reviewed.
I tested this mainly in my fork and saw mysterious failures. Unfortunately the errors contained tracebacks in the multiprocessing module (nothing in yt or nose) and seemed to magically go away this evening. I think it might be due to flakyness on Travis's end? We'll see if it was a transient issue I was running into.
If the failures recur often we can at least make these tests run on a chron job or marked as allowed to fail until we can debug them as it will be nice to have some test coverage on a variety of python versions.
Next on my list is adding an Appveyor build for Windows testing and seeing if moving the MacOS build …

Add travis builds for various python versions and MacOS

---

.travis.yml

This makes error tracebacks on travis a bit nicer. It also makes it so that nose prints out the time each test takes to execute.

tweak travis config to not capture logs and to print timing info

---

yt/data_objects/construction_data_containers.py
yt/data_objects/grid_patch.py
yt/data_objects/tests/test_covering_grid.py
yt/fields/tests/test_fields.py
yt/geometry/particle_deposit.pyx

closes #1379
Suoqing triggered this by creating an `arbitrary_grid` object with non-uniform dimensions. This exposed an inconsistency in how the particle deposit operations work. Due to an assumption that grids are fortran-ordered in `grid_patch.py`, all particle deposit operations are done in a fortran ordered manner. However, the other ways we let users create grids (e.g. `arbitrary_grid`) are not assumed to be fortran ordered.
The fix would either be to make everything fortran ordered or, ~~as I've done here,~~ relax the assumption that grid data are fortran ordered in `grid_patch.py` and then update all the deposit operations to work with C ordered data.
~~I've checked and I'm pretty sure this won't trigger any user-visible changes, it was purely an internal bookkeeping thing.~~
EDIT: …

Do covering grid and arbitrary grid particle deposition on F order arrays

---

appveyor.yml
yt/geometry/coordinates/cartesian_coordinates.py
yt/utilities/lib/alt_ray_tracers.pyx
yt/utilities/lib/misc_utilities.pyx
yt/visualization/plot_modifications.py

closes #1254
Once this is merged we should be able to turn on automatic windows testing.
I decided to only run tests on Python3.6 because Appveyor only gives us one parallel build.

update appveyor config, fix windows test failures

---

yt/fields/astro_fields.py

There are a couple of astro fields that have a density-squared dependence and have a division by the proton mass to get a number density: `mazzotta_weighting` and `emission_measure`.
If the density is very small in cgs units, it is sometimes the case that the field itself is zero. I've altered the computation of the fields so that we divide the density by the proton mass first before doing anything else.

[bugfix] Fix precision issues for X-ray related fields

---

.travis.yml
scripts/iyt
setup.py
setupext.py
yt/funcs.py
yt/utilities/command_line.py
yt/utilities/png_writer.py
yt/visualization/plot_container.py
yt/visualization/plot_modifications.py
yt/visualization/plot_window.py
yt/visualization/profile_plotter.py

This includes a number of cleanups and improvements for our setup.py script.
* removes some now defunct logic related to the `__hg_version__.py` file. Rather than update this logic to work with git, I've opted to simply delete it. Please let me know if you want this to be updated to work with git.
* the setup.py script will now bail if you try to install yt on python 3.0, 3.1, 3.2, or 3.3.
* Makes the license description more accurate
* Defines minimum supported versions of our runtime dependencies. Thankfully `install_requires` works correctly with `pip` to install wheels if these requirements are not satisfied. I've chosen versions of these libraries from the past year or two to support.
* Adds a travis job to test that we still build and the unit tests pass for the minimum supported …

Setup improvements

---

yt/visualization/plot_modifications.py

This is a rethinking of [bitbucket PR 2492](https://bitbucket.org/yt_analysis/yt/pull-requests/2492). Rather than trying to handle periodicity in convert_to_plot (which does not always deal with plot windows spanning the full domain width) let's deal with periodicity before we pass data to convert_to_plot.
This avoids issues plotting halos in plot windows that don't span the full width of the domain.

Account for periodic boundary conditions in the halo callback

---

doc/helper_scripts/show_fields.py

This gets rid of severe sphinx warnings in `field_list.rst`:
```
--- orig        2017-05-17 10:09:08.942291989 -0500
+++ new 2017-05-17 10:09:38.528315781 -0500
@@ -7342,24 +7342,24 @@
('io', 'StarFormationRate')   :math:`\mathrm{M_\odot / \rm{yr}}`                                                      
('io', 'FormationTime')       :math:`\mathrm{\rm{code~time}}`                               ``creation_time``         
('io', 'Metallicity_00')                                                                    ``metallicity``           
-('io', 'uDotFB')              :math:`\mathrm{\rm{code~mass} \cdot \rm{code~velocity}^{2}}`  ````                      
-('io', 'uDotAV')              :math:`\mathrm{\rm{code~mass} \cdot \rm{code~velocity}^{2}}`  ````                      
-('io', …
```

[show_fields] Only print alias if it's non empty string

---

yt/utilities/parallel_tools/parallel_analysis_interface.py

This fixes an error that happens when yt improperly shuts down. I usually see it when I introduce a SyntaxError somewhere that only gets triggered when yt is partially imported.
Here's an example traceback:
```
File "/usr/local/bin/iyt", line 6, in <module>
exec(compile(open(__file__).read(), __file__, 'exec'))
File "/Users/goldbaum/Documents/yt-git/scripts/iyt", line 5, in <module>
from yt.mods import *
File "/Users/goldbaum/Documents/yt-git/yt/__init__.py", line 131, in <module>
from yt.data_objects.api import \
File "/Users/goldbaum/Documents/yt-git/yt/data_objects/api.py", line 46, in <module>
from . import construction_data_containers as __cdc
File "/Users/goldbaum/Documents/yt-git/yt/data_objects/construction_data_containers.py", line 65, in …
```

[bug] Fix cleanup error

---

doc/source/analyzing/objects.rst
yt/data_objects/data_containers.py
yt/data_objects/region_expression.py
yt/data_objects/tests/test_dataset_access.py

This allows you to use `ds.r` to get back FRB objects.  For instance, it is
natural to do something like:
```
ds.r[0.5, ::256j, ::256j]
```
and expect to get back a fixed resolution buffer.  Currently, this doesn't
work.  This adds that, along with tests and some more comments.

Adding FRB generation to ds.r

---

yt/__init__.py

Currently these docstrings are hilariously out of date. It's also clear that they're not commonly read. Rather than attempting to update all the detailed content in the docstring to reflect the way the code is currently structured I've opted to just delete most of it.
Looking at other packages, the docstring for the main package is generally quite short:
* Astropy: https://github.com/astropy/astropy/blob/master/astropy/__init__.py#L2
* IPython: https://github.com/ipython/ipython/blob/master/IPython/__init__.py#L2
In case anyone looking for information consults the docstring I've included a number of resources that are not likely to change often.

Update the docstring for the yt module. Closes #1362

---

doc/source/examining/loading_data.rst
yt/frontends/stream/data_structures.py
yt/frontends/stream/tests/test_stream_amrgrids.py
yt/utilities/exceptions.py

Don't allow to create Stream dataset with an invalid grid structure, i.e. when the grid edges on the *n*-th
refinement level are **not** aligned with the cell edges on the *n-1*-th level.
Fixes #1295

Validate AMR structure in load_amr_grids. Fixes #1295

---

yt/visualization/plot_window.py

Newer matplotlib versions can handle minor ticks, but only for linear and log scales, not for symlog scales (currently minor ticks are missing with symlog). With this PR, when symlog is used, the code will take over from matplotlib and generate its own minor ticks.

Add minorticks for colorbar when symlog is used

---

yt/utilities/lib/image_samplers.pyx
yt/visualization/volume_rendering/render_source.py
yt/visualization/volume_rendering/scene.py

closes #1410
Up until now, each VolumeSource and MeshSource was rotating volume rendering images for each source by 180 degrees. This is find when you're only dealing with one source but is completely wrong with multiple sources. Rather than doing the rotation in the source, we instead to do the rotation in the scene object after compositing all the images together. I *think* that this still gives the correct answer when annotating lines and grids, but we should manually verify.

only rotate volume rendering images after compositing all sources

---

yt/fields/particle_fields.py

On rare occasions, it may be the case that a dataset has particles without having a mass field for the particles. 
We use the shape of the particle mass field to create the `particle_ones` field. However, if a mass field doesn't exist, then the `particle_ones` field never gets created. This PR bases the creation of the `particle_ones` field off of the coordinate field just as the `mesh_id` below it.

[bugfix] Create the particle_ones field even if we don't have a particle mass field

---

doc/source/examining/Loading_Generic_Array_Data.ipynb
doc/source/examining/Loading_Generic_Particle_Data.ipynb
yt/fields/cosmology_fields.py
yt/frontends/stream/data_structures.py
yt/frontends/stream/fields.py
yt/frontends/stream/tests/test_stream_particles.py
yt/frontends/stream/tests/test_update_data.py
yt/utilities/particle_generator.py
yt/utilities/tests/test_particle_generator.py

This PR allows one to specify multiple particle field types when creating a stream dataset, i.e.:
```python
pdata = {}
for i, ax in enumerate("xyz"):
pdata["PartType0", "particle_position_%s" % ax] = (g["Coordinates"][:,i] / h, "kpc")
pdata["PartType0", "particle_velocity_%s" % ax] = (g["Velocities"][:,i], "km/s")
pdata["PartType1", "particle_position_%s" % ax] = (d["Coordinates"][:,i] / h, "kpc")
pdata["PartType1", "particle_velocity_%s" % ax] = (d["Velocities"][:,i], "km/s")
pdata["PartType4", "particle_position_%s" % ax] = (s["Coordinates"][:,i] / h, "kpc")
pdata["PartType4", "particle_velocity_%s" % ax] = (s["Velocities"][:,i], "km/s")
ds = yt.load_particles(pdata, length_unit="kpc", mass_unit="Msun", 
time_unit="Gyr", bbox=bbox, n_ref=64)
```
The stream datasets currently only allow …

Multiple particle types for stream datasets

---

yt/frontends/gadget/data_structures.py
yt/frontends/gadget/tests/test_outputs.py

Thanks to @weiguangcui for pointing out this issue which I unintentionally introduced.
I've added a test using a dataset that would have caught this issue if it were in our tests. @Xarthisius can you make sure the dataset I've added to the Gadget tests is staged with the correct path on the test box? So far we haven't added this dataset to the tests so it might not have been downloaded yet.

fix I/O issue with little endian Gadget snap format 2 data

---

yt/data_objects/construction_data_containers.py
yt/data_objects/data_containers.py
yt/data_objects/tests/test_fluxes.py

Fixes #1406 and #1407
This ensures the field value of an iscontour is interpreted in the units expected by the low-level isocontour machinery. In addition, this fixes another issue with field parameters not being correctly applied to volumetric blocks, which we use to generate ghost zones needed for the marching cubes algorithm.
I also added a new `surface_area` property of the `YTSurface` which returns the combined surface area of all of the polygons that make up the surface. In addition I made the `vertices` attribute of `YTSurface` a cached property which simplifies some logic.

Isocontour fixes and enhancements

---

yt/utilities/command_line.py

Before:
```
$ yt upload_notebook ~/Untitled0.ipynb 
File "/home/xarth/local/bin/yt", line 11, in <module>
load_entry_point('yt', 'console_scripts', 'yt')()
File "/home/xarth/codes/xarthisius/yt/yt/utilities/command_line.py", line 1391, in run_main
args.func(args)
File "/home/xarth/codes/xarthisius/yt/yt/utilities/command_line.py", line 214, in run
self(args)
File "/home/xarth/codes/xarthisius/yt/yt/utilities/command_line.py", line 886, in __call__
gc = _get_girder_client()
File "/home/xarth/codes/xarthisius/yt/yt/utilities/command_line.py", line 145, in _get_girder_client
gc.authenticate(apiKey=ytcfg.get("yt", "hub_api_key"))
File "/home/xarth/codes/girder/clients/python/girder_client/__init__.py", line 310, in authenticate
raise Exception('A user name …
```

Error out early if user doesn't have an API key

---

yt/utilities/lib/alt_ray_tracers.pyx

closes #1403
I suspect this is happening because of https://github.com/numpy/numpy/issues/9137 which I've reported upstream to NumPy. I'm not able to reproduce this on a local windows box though and I'm also not sure at all why the failures are random as I'm pretty sure these tests are supposed to be deterministic.
In any case, this should at least fix the type errors.
I'm going to manually re-trigger appveyor on this pull request a few times. Please don't merge until I say it's ok.

attempt to fix type errors in alt_ray_tracers.pyx

---

yt/data_objects/octree_subset.py

This addresses #1405 and does so by transposing the arrays returned when iterating over and accessing data inside an octree subset.  This should only affect things that require grid-like access, which I *believe* is exclusively off-axis projections at present.

Transposing octree data for particle octree subsets. Closes #1405.

---

doc/source/examining/loading_data.rst
yt/frontends/boxlib/io.py
yt/frontends/chombo/io.py
yt/frontends/enzo/fields.py
yt/frontends/enzo/io.py
yt/frontends/enzo/tests/test_outputs.py
yt/frontends/gdf/io.py
yt/frontends/open_pmd/io.py
yt/frontends/ytdata/io.py
yt/utilities/io_handler.py

This adds support for Enzo MHDCT fields, following the support @atmyers added for nodal WarpX data.
The implementation is relatively straightforward. I just needed to add support for I/O on these fields following more or less what the boxlib frontend does. I also needed to teach the enzo frontend which fields are expected to be nodal and what their expected nodal flags are. In principle we could read these data off disk like the boxlib frotend does but as far as I'm aware that data is currently not written out by Enzo so it needs to be hardcoded in the Enzo frontend.
While working on this I noticed a pattern where we do something like:
```
if selector.__class__.__name__ == "GridSelector":
```
many places in the codebase. Since this is arcane and wordy, I decided to globally replace it …

Add support for Enzo MHDCT fields

---

yt/frontends/stream/data_structures.py

The `update_field_names` function takes fields for stream frontends and make sure the field names are tuples. However, the exact same function is provided in `unitify_data`, and in fact these functions are called one right after the other, typically. I'm removing `update_field_names` as it appears to be superfluous.

Remove update_field_names from stream frontend

---

doc/source/examining/Loading_Generic_Array_Data.ipynb
doc/source/examining/loading_data.rst
yt/frontends/stream/data_structures.py
yt/frontends/stream/tests/test_outputs.py
yt/frontends/stream/tests/test_stream_particles.py
yt/utilities/exceptions.py
yt/utilities/particle_generator.py

This PR refactors the stream frontend and adds one feature and simplifies the API:
* Add sanity checks to make sure that every particle field for a given type is the same shape, and that all grid-based fields for a given grid are all the same shape and have the same shape as the grid dimensions.
* Once we have convinced ourselves that the particle fields all have the same shape, use them to determine the number of particles for a given grid. This removes the need to supply `number_of_particles` as a field to the data dictionary for grid-based stream frontends. If someone supplies this key, it will be harmlessly discarded.
The `unitify_data` function, where all of this action occurs, has been renamed to `process_data`.
I've updated the docs and tests.

Stream frontend: add sanity checks for field shapes and remove number_of_particles requirement

---

yt/frontends/ramses/data_structures.py

Sink particles in ramses are stored in a particular output file, but they need 'cloud particles' to compute the accretion.
These cloud particles are stored in the particle file, but they have no physical meaning. The way to determine that a particle is a cloud particle (and not a star or a DM particle) is that it has a negative index.
Thus we must be able to read negative indexes, which explains the change.

Allow negative indexes when reading RAMSES outputs.

---

yt/frontends/boxlib/data_structures.py

This is not necessary and may cause problems if the inputs or probins file is ill-formed.

Don't ever try to read inputs or probin files for Castro and Maestro.

---

yt/visualization/volume_rendering/input_events.py
yt/visualization/volume_rendering/shader_objects.py

This changes how the "help" command works in IDV to have it output all of the possible callbacks (usually only one) associated with a given key.  It also adds a check for when setting a uniform that is a `YTQuantity`.  Most commonly, this will happen when *not* taking the log of a field; in that case, the uniform setters get confused and break.  This changes that by knowing that `YTQuantity`'s are castable to floats.

Two minor IDV fixes for interactivity and non-logged fields

---

yt/utilities/lib/bounding_volume_hierarchy.pyx
yt/utilities/lib/grid_traversal.pxd
yt/utilities/lib/grid_traversal.pyx
yt/utilities/lib/image_samplers.pxd
yt/utilities/lib/image_samplers.pyx
yt/utilities/lib/lenses.pxd
yt/utilities/lib/lenses.pyx
yt/utilities/lib/mesh_traversal.pyx

Closes #1374
To evaluate this PR consider the following script:
```python
import yt
from yt.testing import fake_random_ds
from pympler import tracker
tracker = tracker.SummaryTracker()
ds = fake_random_ds(16)
sc = yt.create_scene(ds)
sc.render()
del sc
del ds
tracker.print_diff()
```
This is a little bit different from the script in #1374 in that it has the nice feature that the stuff between the creation of the `SummaryTracker` and the call to `tracker.print_diff` should in principle have no side effects.
Before this PR I get the following output:
```
types |   # objects |   total size
========================================================= | =========== | ============
<class 'numpy.ndarray |          10 |      6.01 MB
<class 'list |       12003 |      1.11 MB
<class 'str |       12509 …
```

Refactor volume rendering to eliminate need for ImageContainer struct

---

doc/source/reference/configuration.rst
tests/tests.yaml
yt/config.py
yt/data_objects/grid_patch.py
yt/frontends/enzo/data_structures.py
yt/frontends/enzo/tests/test_outputs.py
yt/frontends/stream/data_structures.py
yt/geometry/grid_geometry_handler.py
yt/utilities/lib/mesh_utilities.pyx

This is an attempt to fix #1431. I'm PRing now to see if this causes any test breakage.
There is an existing fix for this issue that is specific to the Enzo frontend that's already in the code. Unfortunately, It's hidden behind an undocumented configuration variable. I also suspect that it's doing too much work and that all we need to do is adjust the grid edges. I've opted to delete that old fix in favor of a solution that will work for all grid frontends and is always turned on.
TODO:

Ensure grid edges are consistent with edges computed by masks

---

yt/visualization/volume_rendering/render_source.py
yt/visualization/volume_rendering/scene.py

After noticing that `color` wasn't documented at all for `annotate_domain` I realized that the docstrings for other similar keyword arguments could be improved as well. This does that.

Improve docstrings for coloring of opaque sources in VR

---

yt/frontends/ytdata/io.py

This fixes some errors I encountered when working with some save_as_data-generated datasets with python3.

[bugfix] Use python3-safe hdf5 attribute reading.

---

yt/utilities/lib/particle_mesh_operations.pyx

Compiling yt with the latest development version of cython produces the following error:
https://gist.github.com/ngoldbaum/d107a60b1775e97e12b72b29506a822b
The issue is that we only cimport numpy in this file but don't import it.

Add missing numpy import to particle_mesh_operations.pyx

---

doc/source/analyzing/objects.rst
yt/data_objects/region_expression.py
yt/data_objects/selection_data_containers.py
yt/data_objects/tests/test_dataset_access.py
yt/funcs.py

This PR extends `ds.r` to allow it to return 0 and 1-dimensional data objects. For example:
```python
p = ds.r[0.1,0.3,0.5]
```
returns a `YTPoint` object, and 
```python
ray = ds.r[(300.0,"kpc"),:,(-200.0,"kpc")]
```
returns a `YTOrthoRay`.
Currently, I'm having trouble getting the rays to work, because for some reason composition of a `YTOrthoRay` with a region does not work (it yields empty arrays when querying fields).

Extend region expression to return points and rays

---

yt/units/tests/test_ytarray.py
yt/units/yt_array.py
yt/utilities/tests/test_minimal_representation.py

This updates yt for changes in Numpy 1.13.
Github isn't rendering the diff for yt_array.py, you need to manually expand it if you want to see the bulk of the changes in this PR.
You may be surprised by the size of the changes here - this is mostly to support a new feature in Numpy 1.13: `__array_ufunc__`. See [this page](https://github.com/numpy/numpy/blob/master/doc/neps/ufunc-overrides.rst#a-mechanism-for-overriding-ufuncs) for more details.
Briefly, defining `__array_ufunc__` allows us to skip much of the boilerplate in the definition of `YTArray`, since almost all array operations will now be handled by `__array_ufunc__`. This reduces overhead for many operations and also makes the overall implementation simpler.
Unfortunately, we still need to support older numpy releases. I've …

Update yt for Numpy 1.13

---

yt/data_objects/construction_data_containers.py

This eliminates usages of `dist_fac` in the examples. I think at one point this was necessary to get a model with a nice normalized size. However, currently this choice of dist_fac produces a model that is much, much bigger than the camera scale. Removing `dist_fac` seems to produce reasonably sized models in sketchfab and meshlab.
I also fixed an error due to an API change we made a while in the derived quantities.

Tweak docstrings for surface export operations

---

appveyor.yml
yt/geometry/grid_container.pyx
yt/utilities/lib/mesh_utilities.pyx

MSVC didn't add support for rint in `math.h` until 2013, so python2.7 needs a fallback.

fix compilation on windows python2.7

---

yt/utilities/lib/fnv_hash.pxd
yt/utilities/lib/fnv_hash.pyx

While trying to repurpose this FNV hash implementation for something in the demeshening, I found a couple of issues.
1. If we pass it non-ascii binary data, there will be values outside of 0-127. This will overflow the signed char we're currently using. The fix is to use unisgned chars. This wasn't an issue until now because we've been passing this function binary-encoded ascii data.
2. There's some python overhead that we can eliminate to improve performance.
I'd keep this in the demeshening for now but I wanted to see if this breaks anything so I'm PRing it separately to get the test suite run against it.

Improvements for FNV hash

---

tests/tests.yaml
yt/analysis_modules/absorption_spectrum/absorption_spectrum.py
yt/analysis_modules/halo_finding/halo_objects.py
yt/analysis_modules/photon_simulator/photon_models.py
yt/analysis_modules/photon_simulator/photon_simulator.py
yt/data_objects/construction_data_containers.py
yt/frontends/owls_subfind/io.py
yt/units/tests/test_ytarray.py
yt/units/yt_array.py

This is a followup to #1422. I missed the following case:
```
from yt.units import cm
[1, 1, 1]*cm + [1, 1, 1]
```
This *should* raise a `YTUnitOperationError` but currently does not. It looks like I broke that behavior in #1422 because we didn't have an explicit test.
This PR restores that behavior and adds explicit tests for addition and subtraction between arrays with units and dimensionless arrays.

fix issues with adding dimensionless data to data with units

---

doc/install_script.sh
doc/source/faq/index.rst
doc/source/help/index.rst
doc/source/installing.rst
doc/source/visualizing/unstructured_mesh_rendering.rst
doc/source/yt3differences.rst
tests/test_install_script.py
yt/utilities/command_line.py

Following up on the discussion from yt-dev, this implements the removal of the INST_CONDA option from the install script. I've also updated the docs to match. In addition, this now makes `yt update --all` a no-op. It was already deprecated.
I've tested this using `test_install_script.py` on my Mac. I'm also going to try testing on a Linux box as well.

Remove INST_CONDA option from install script

---

yt/data_objects/construction_data_containers.py

Closes #1483.
As the inline comment says, if there are less than n_procs io chunks, we only initialize the `_projected_units` dict on the root processor. The fix is to broadcast the units to all MPI ranks.
I didn't add a test because we don't have a parallel testing framework.

Fix parallel projections when there are less than nprocs io chunks. 

---

yt/fields/derived_field.py

Reading hdf5 files of stored `Ray` objects in python 3 can result in feeding yt unit information as `bytes` objects instead of strings. This is due to an [issue](https://github.com/h5py/h5py/issues/379) where h5py parses hdf5 attributes incorrectly.
This PR does a simple check to ensure unit information provided as a `bytes` object gets properly decoded.

Decode units given as bytes object

---

doc/source/examining/loading_data.rst

There are a couple issues with this documentation as-is:
* It still refers to `GadgetDataset` (probably from a time before we implemented support for loading gadget data with `yt.load`).
* The documentation for unit_base is wrong. You need to pass a tuple that looks like `(1.0, 'cm')`, not `('cm', 1.0)`. I think at one point this was correct, but we changed that a while ago to match how `(value, unit)` work in the rest of the codebase.
* It doesn't document that you can use e.g. `UnitLength_in_cm` to specify length units.
This fixes those issues. I also did some light copy-editing for readability.

Fix issues with documentation of unit_base keyword argument for loading gadget data

---

README.md

This was shamelessly stolen from the [metpy readme](https://github.com/Unidata/MetPy). I really like the gist of it and think it would be a good addition for our readme as well.

Add imposter syndrome disclaimer to readme

---

doc/source/reference/api/api.rst
doc/source/visualizing/plots.rst
yt/__init__.py
yt/frontends/stream/data_structures.py
yt/visualization/api.py
yt/visualization/plot_window.py
yt/visualization/tests/test_plotwindow.py

This PR doesn't do much, but it provides a wrapper function for `AxisAlignedSlicePlot` which sets the `axis` argument to `"z"`, so that one can plot 2D datasets without having to set an axis (`"z"` is the only one worth setting). 
It's almost too trivial to add, but I thought having a convenience function like this might be nice. 
Need to add to the documentation and (maybe) add a test.

plot_2d: plot 2d datasets

---

tests/tests.yaml
yt/frontends/flash/data_structures.py

This code dates back to January 2012, specifically git commit a471742895. The commit message for that change includes the following description:
> Sam suggested this fix to "finesse" the roundoff error when reading in FLASH bounding boxes. It's somewhat hackish, so if someone has a more elegant solution feel free to change it.
I *think* that the base issue @jzuhone was working around was fixed relatively recently by #1433, although I'm not 100% sure.
With this change, we now have the correct volume (up to round-off error?) for the FLASH dataset that had issues and no longer have artifacts in the slice visualizations:
```
In [2]: ad['cell_volume'].sum()
Out[2]: 0.01820000019222498 code_length**3
In [3]: ds.domain_width.prod()
Out[3]: 0.0182 code_length**3
```
This may change answers for …

Remove grid edge rounding in FLASH frontend. Fixes #1361

---

yt/visualization/fits_image.py
yt/visualization/tests/test_fits_image.py

The existing API for the various FITS image classes accepts either strings or tuples for field names, but not `DerivedField` objects, e.g. something like this:
```python
import yt
ds = yt.load("GasSloshing/sloshing_nomag2_hdf5_plt_cnt_0100")
fid = yt.FITSProjection(ds, "z", ds.fields.gas.density)
```
This PR changes the internal logic so that these objects are also accepted.

[bugfix] Allow FITS image classes to accept DerivedField objects

---

yt/geometry/selection_routines.pyx

Cython complains about having these two declarations on the same line:
```
[ 7/33] Cythonizing yt/geometry/selection_routines.pyx
warning: yt/geometry/selection_routines.pyx:1576:28: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
warning: yt/geometry/selection_routines.pyx:1576:34: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
```
It's a silly rule but the warning is annoying, so let's just fix it.

fix cython warning

---

yt/data_objects/construction_data_containers.py
yt/utilities/command_line.py
yt/utilities/exceptions.py

This change spares us `UserWarning: The configuration file ~/.yt/config is deprecated.  Please migrate your config to ~/.config/yt/ytrc by running: 'yt config migrate'` and a fail when launching `yt notebook`.
I admit that I did not bother running `yt config migrate` but edited my already existing `~/.config/yt/ytrc` file (and removed `~/.yt/config`).
Now `yt notebook` launches smoothly!

Update yt configuration path

---

appveyor.yml
yt/testing.py
yt/visualization/tests/test_callbacks.py
yt/visualization/tests/test_particle_plot.py
yt/visualization/tests/test_plotwindow.py
yt/visualization/tests/test_profile_plots.py
yt/visualization/volume_rendering/scene.py
yt/visualization/volume_rendering/tests/test_scene.py
yt/visualization/volume_rendering/tests/test_vr_cameras.py

This makes it so you can save pdf, eps, and ps files directly from the scene object, making use of matplotlib to handle the file format conversion issues. I made sure that if you save an image as a pdf and a png, the images you get back match orientation and appearance as closely as possible.
This is technically a new feature but it was simple enough to add that I went ahead and did it. Given the bug report (#1503) and the vagueness of the current docstrings I don't think it's crazy to expect yt to do the right thing if you tell it to save a pdf instead of a png.
~~Let me know if my use of pyplot is objectionable - it was easier to implement this using pyplot rather than using the OO interface. The pyplot import only happens if you tell yt to save something that's not a png so I think it …

Make scene.save() support saving pdf, ps, and eps files.

---

doc/source/analyzing/fields.rst

I changed link for a reference in the "Deposited Particle Fields" section (the link displays as "Section 2.2") to cloud-in-cell particle deposition to http://ta.twi.tudelft.nl/dv/users/lemmens/MThesis.TTH/chapter4.html (the link was broken due to "lemmens" being written as "Lemmens").

Fixes broken link in "Fields in yt" page

---

yt/visualization/tests/test_profile_plots.py

This loop doesn't actually do anything. I think it just causes these tests to run three times. Let's see if deleting it causes the answer tests to fail...

remove unnecessary loop over 'xyz' in phase plot answer tests

---

yt/frontends/ytdata/tests/test_outputs.py
yt/visualization/plot_window.py

This functionality was unintentionally broken last year by me. The problem is that the `ytdata` frontend reloads plot datasets as particle fields, which broke the logic of the guard I added that gives a nice error message if someone tries to plot a particle field in a grid dataset.
The fix is to not perform this check for `ytdata` plot datasets.
I also added tests to avoid future regressions.
This fixes #1444.

Restore support for visualizing YTSpatialPlotDataset instances. Fixes #1444

---

yt/utilities/file_handler.py

As I commented in the code I added, there are different variants of the netCDF format.
Reference: https://www.loc.gov/preservation/digital/formats/fdd/fdd000339.shtml
Now netCDF-4 Classic files can trigger `warn_netcdf()` too, if the `netcdf4` Python package is not installed.  If `h5py` is not installed either, `warn_h5py()` will get triggered first, since netCDF-4 files are HDF5 files.  That's all good, you want to install `h5py` and (then) `netcdf4`.
I need this change so that I can call `warn_netcdf()` in the future `netcdf` frontend and have it work for more netCDF files.
I'm not very comfortable with the absence of tests...  But I'm not sure where to start, since there are currently no tests for `warn_h5py()` or `warn_netcdf()`.

Let NetCDF-4 Classic files trigger warn_netcdf() as well

---

doc/source/cookbook/simple_1d_line_plot.py
doc/source/visualizing/plots.rst
tests/tests.yaml
yt/__init__.py
yt/visualization/api.py
yt/visualization/line_plot.py
yt/visualization/tests/test_line_plots.py

Creates an alternative `LinePlot` initializer for creating a `LinePlot` from a series of `LineObject`s. To reduce code duplication, some of the previous code in `_setup_plots` has been split into more atomic methods. 
A demonstration script (some unimportant parts removed):
```python
import yt
ds = yt.load("/home/lindsayad/projects/moose/modules/navier_stokes/tests/ins/lid_driven/gold/lid_driven_out.e", step=-1)
lines = []
lines.append(yt.LineObject([0, 0.5, 0], [1, 0.5, 0], ds, label='y = 0.5'))
lines.append(yt.LineObject([0, 0.25, 0], [1, 0.25, 0], ds, label='y = 0.25'))
plt = yt.LinePlot.from_lines(ds, [('all', 'vel_x'), ('all', 'vel_y')], lines, 100)
plt.save("multi_lines.png")
```
produces this image:
Documentation and a test are in progress.
Addresses #1505

Allow multiple sampling lines for LinePlot

---

yt/frontends/_skeleton/__init__.py
yt/frontends/_skeleton/api.py
yt/frontends/_skeleton/data_structures.py
yt/frontends/_skeleton/fields.py
yt/frontends/_skeleton/io.py

As I copied the contents of `yt/frontends/_skeleton/` to create a new frontend, I noticed some minor naming and styling inconsistencies.  I thought I would make all files pass `pep8` at the same time.  This way, warnings and errors won't propagate as we copy this boilerplate code.
Somehow `flake8` does not seem to detect anything...  Maybe that's my new install--yet another one.

Make boilerplate consistent and pep8 compliant

---

yt/data_objects/static_output.py
yt/fields/tests/test_fields.py

In order to override an on-disk field, it seems to be enough to remove it from the index's `field_list`. Let's see how many tests this breaks...

Make force_override work for on-disk fields (#1511)

---

yt/data_objects/particle_filters.py
yt/data_objects/static_output.py
yt/utilities/exceptions.py

Closes #1278
~~I'm not sure if this subtly breaks other particle filter behavior so let's see if this causes any test failures.~~
To make that more concrete, with this PR, the following script:
```
import yt
@yt.particle_filter(requires=["myField"], filtered_type='all')
def small_x(pfilter, data):
filter = data[(pfilter.filtered_type, "myField")] < 0
return filter
def myField(field, data):
return data["particle_position_x"]
snap = 'GadgetDiskGalaxy/snapshot_200.hdf5'
ds = yt.load(snap)
ds.add_particle_filter('small_x')
```
Will now error out with the following error message:
```
File "test.py", line 14, in <module>
ds.add_particle_filter('small_x')
File "/Users/goldbaum/Documents/yt-git-fixes/yt/data_objects/static_output.py", line 665, in …
```

Print a more descriptive error message when defining a particle filter fails with missing fields

---

doc/source/reference/api/api.rst
yt/visualization/fits_image.py

This PR adds the `FITSImageData` classes to the API docs and fixes an issue which was causing the documentation to display errors when calling the `info()` method (and causing an error every time `info()` was called).

[bugfix] API Docs for FITSImageData and a bugfix

---

doc/source/analyzing/objects.rst
yt/data_objects/region_expression.py
yt/data_objects/tests/test_dataset_access.py

Thanks to @lindseyad and @ngoldbaum's recent work with `LinePlot` and `LineBuffer`, I was able to incorporate fixed-resolution rays into `ds.r`. This works for both on-axis and off-axis arrays.
Examples:
```python
ortho_ray = ds.r[(0.1:0.6:500j,0.3,0.2]
start = [0.1, 0.2, 0.3]
end = [0.4, 0.5, 0.6] 
ray = ds.r[start:end:100j]
```
Tests and docs have been added.

Create fixed-resolution rays from region expression

---

doc/source/analyzing/analysis_modules/halo_catalogs.rst
doc/source/analyzing/units/3)_Comoving_units_and_code_units.ipynb
doc/source/reference/changelog.rst
doc/source/visualizing/plots.rst
yt/units/yt_array.py
yt/utilities/grid_data_format/docs/gdf_specification.txt

After recent update of software stack on doc builder builds now hang with:
```
Sphinx parallel build error:
UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in position 7752: ordinal not in range(128)
```
I updated only `RunNotebook` to version 0.2, but it pulled a lot of new updates in and I have no idea what exactly causes the issue.

Replace unicode double quotation mark with ascii

---

yt/frontends/enzo/tests/test_outputs.py
yt/geometry/selection_routines.pyx
yt/utilities/lib/fp_utils.pxd

With these changes, the script in #1432 produces the following image:
I've asked if we can use the test dataset linked in the issue in our test suite, since right now we don't have any extremely deep zoom-ins.

Avoid integer overflow issues in RegionSelector. Fixes #1432

---

doc/source/cookbook/particle_xvz_plot.py
tests/tests.yaml
yt/data_objects/profiles.py
yt/data_objects/tests/test_profiles.py
yt/utilities/lib/particle_mesh_operations.pyx
yt/visualization/particle_plots.py
yt/visualization/plot_container.py
yt/visualization/plot_window.py
yt/visualization/profile_plotter.py
yt/visualization/tests/test_particle_plot.py

Currently the `ParticleProfile` object is hard-coded to always use linearly spaced bins. It turns out that this requirement only needs to be imposed for CIC deposition, so I've relaxed it. This fixed #1448.
While adding improvements to `ParticleProfile` I noticed a number of issues with `PhasePlot` and `create_profile` that I also fix here. In particular:
* `PhasePlot` will now recreate profile objects only as needed when someone accesses the `profile` attribute or when we're about to save a plot to disk. This avoids unnecessary calls to `create_profile` when a user successively applies several customizations.
* `create_profile` will now do the right thing if you pass it an `extrema` dict like `{'density': (None, 1e-31)}` (the `None` will be interpreted as a request to find the minimum of …

Phase plot and ParticlePlot fixes and improvements

---

yt/funcs.py

Right now gitpython on conda-forge is stuck on version 2.1.1, which doesn't support opening the git repo as a context manager. I'm going to work on getting it updated in conda-forge, but it will take some doing since a lot of dependencies need to be updated as well.
For now let's just avoid erroring out if an old gitpython is installed.

avoid error on gitpython 2.1.1

---

yt/visualization/base_plot_types.py
yt/visualization/plot_container.py
yt/visualization/tests/test_plotwindow.py

If your data has zero as the extrema values yt crashes when it tries to take a `np.log10(data.min())` in `_init_image()` from `yt/visualization/base_plot_types.py`. This is fixed in the first commit about major ticks. Additionally `get_symlog_minorticks()` of `yt/visualization/plot_container.py`, needed a similar catch to properly added minor ticks, second commit.
Reproduction of the bugs are outlined in issue #1501.
Fixes #1501

Symlog zeroes catches passed to np.log10()

---

yt/data_objects/construction_data_containers.py
yt/data_objects/tests/test_covering_grid.py

Fixes #1527.
This fixes the test script in #1527. I'm not sure offhand why the restriction to only fill one field was added to `ArbitraryGrid._fill_fields`, but this seems to work.

Make arbitrary grid support filling multiple fields.

---

doc/source/reference/changelog.rst

There are still a few outstanding PRs that this doesn't include so it shouldn't be merged in until those are in.

add release notes for yt 3.4

---

yt/utilities/parallel_tools/parallel_analysis_interface.py

This fixes a bug I encountered while trying to get rockstar to run with python 3.  If we don't force integer division, the `mi` variable will be of float type, which is an improper argument for `np.unravel_index`.

Ensure integer division for index calculation.

---

README.md

This adds a link to the COC in the readme file, prominently near the top.

Linking to the code of conduct

---

doc/source/analyzing/analysis_modules/absorption_spectrum.rst
doc/source/analyzing/analysis_modules/cosmology_calculator.rst
doc/source/analyzing/analysis_modules/halo_mass_function.rst
doc/source/analyzing/analysis_modules/halo_transition.rst
doc/source/analyzing/analysis_modules/light_ray_generator.rst
doc/source/analyzing/filtering.rst
doc/source/analyzing/parallel_computation.rst
doc/source/analyzing/units/1)_Symbolic_Units.ipynb
doc/source/cookbook/Halo_Analysis.ipynb
doc/source/cookbook/complex_plots.rst
doc/source/cookbook/notebook_tutorial.rst
doc/source/cookbook/streamlines.py
doc/source/developing/releasing.rst
doc/source/developing/testing.rst
doc/source/examining/loading_data.rst
doc/source/examining/low_level_inspection.rst
doc/source/installing.rst
doc/source/intro/index.rst
doc/source/quickstart/2)_Data_Inspection.ipynb
doc/source/quickstart/index.rst
doc/source/reference/changelog.rst
doc/source/visualizing/callbacks.rst
doc/source/visualizing/mapserver.rst
doc/source/visualizing/plots.rst
doc/source/visualizing/streamlines.rst

I wanted to check out new spell checker for tech docs: [mwic](https://github.com/jwilk/mwic)
yt documentation is large enough to be a great test case :) This PR address some of the things that were found.

Fix typos in docs

---

doc/source/cookbook/particle_filter_sfr.py

Minor fix to the cookbook of calculating SFR. If I understand it correctly, the array index should be `j+1` instead of `j` since np.digitize returns the **right** bin of the data to be digitized.

Minor update for the cookbook of calculating SFR

---

yt/frontends/gamer/fields.py

Add the new particle field, "ParCreTime", which records the particle creation time, to the GAMER frontend. Currently, there are no document and test added along with this PR since the modification is really minimal.
- Code passes flake8 checker

Add the ParCreTime particle field to the GAMER frontend

---

yt/frontends/fits/data_structures.py
yt/visualization/plot_window.py

This PR ensures that if units are not specified for a FITS image that the units are set to dimensionless.
I also fixed a bug that prevented one using `plot_2d` with FITS datasets with celestial coordinates.
Closes Issue #1552.

Return dimensionless if we can't determine the field units for FITS datasets

---

yt/data_objects/static_output.py

Currently the dataset caching system does not store the args and kwargs passed to the dataset initializer when storing datasets for caching. This means that if a dataset is loaded multiple times with different arguments or keyword arguments, the dataset initializer will silently ignore the arguments and keyword arguments passed after the first call to `yt.load()`. This can cause issues in user scripts as well as the yt test suite, where we commonly try loading the same dataset multiple times in the same session.
Ultimately I'd like to get rid of the dataset caching system. Unfortunately, that's a bit difficult because dataset caching enables functionality elsewhere in the library, so we'd need to figure out how to maintain that functionality after removing the dataset cache. Definitely …

cache dataset args and kwargs in dataset cache keys

---

.travis.yml
yt/frontends/ytdata/tests/test_outputs.py
yt/utilities/grid_data_format/tests/test_writer.py

This is an attempt to fix our travis builds, which are currently failing due to two separate issues:
* Some tests need h5py to run but are not decorated with `requires_module('h5py')`. The fix is to add the decorator. We don't always assume h5py is installed because it's now an optional dependency.
* For some reason flake8 is failing on the travis build with minimal dependencies. I have no idea why it's failing and can't reproduce locally. It has something to do with flake8 not parsing our `setup.cfg` file for some reason. Rather than struggling to debug why this is happening, I've elected to disable flake8 on the minimal travis build. Flake8 will still run under python2.7 on the other python2.7 travis build.

Travis fixes

---

yt/analysis_modules/halo_analysis/halo_catalog.py

This adds a parallel-safe progress bar to HaloCatalog generation, which can be a very expensive process.  In my experience, I have added print statements to various callbacks just so I could know how things were proceeding.  This works much better, at least for me.

Add parallel progress bar to halo catalog.

---

yt/funcs.py

This should get rid of warnings about installing `python-hglib` when running answer tests.

Use git version for get_yt_version

---

yt/frontends/gadget/definitions.py

I think this is a typo, although I'm not 100% sure.

Fix a small typo in Gadget header spec

---

doc/source/analyzing/units/2)_Fields_and_unit_conversion.ipynb
doc/source/analyzing/units/6)_Unit_Equivalencies.ipynb
doc/source/analyzing/units/fields_and_unit_conversion.rst
yt/units/tests/test_ytarray.py
yt/units/yt_array.py

Both of these small enhancements are inspired in part by AstroPy's units API. 
1. Add the unit equivalency option to the `in_units` and `to` methods. This would basically amount to a consolidation of our API for converting between arrays in equivalent units. So instead of:
```python
kT = yt.YTQuantity(3.0, "keV")
T = kT.to_equivalent("K", "thermal")
```
one could do:
```python
kT = yt.YTQuantity(3.0, "keV")
T = kT.in_units("K", equivalence="thermal")
```
We would keep the original `to_equivalent` method around but change the documentation to use the new API, so this is fully backwards-compatible.
2. Add a `to_value` method that does the same thing as `in_units` but returns a bare NumPy array or floating-point number. 
Once we settle on final details of this API (if folks like these ideas …

Two small enhancements to YTArray and YTQuantity

---

yt/data_objects/grid_patch.py
yt/data_objects/octree_subset.py
yt/data_objects/unstructured_mesh.py

Use the ```__init__``` function on the superclass to ensure proper initialization and remove redundant inits in ```AMRGridPatch```, ```OctreeSubset``` and ```UnstructureMesh```. Closes #1571.

Superclass init for grid objects

---

yt/frontends/gadget/data_structures.py
yt/frontends/gadget/tests/test_outputs.py
yt/geometry/particle_geometry_handler.py

Some newer codes don't include everything that the original GADGET did
in their Header. This is not currently handled very gracefully in yt, and is a
particular issue for non-cosmological runs. If a hdf5 file is loaded that does
not have a Header/Redshift attribute yt crashes and can't continue (by default)
, whereas it should fall back gracefully.
Also, whilst doing this I noticed an error where a single-length array was being
used as a scalar. This is fixed also here, however I can submit that separately
if you would prefer.
- [N/A] New features are documented, with docstrings and narrative docs
- [N/A] Adds a test for any bugs fixed. Adds tests for new features.

Improve gadget loading fallback when some items are not present in the Header

---

doc/source/cookbook/fits_radio_cubes.ipynb
doc/source/cookbook/fits_xray_images.ipynb
doc/source/examining/loading_data.rst
yt/frontends/fits/misc.py
yt/utilities/on_demand_imports.py

Currently, there is a miscellaneous function, `PlotWindowWCS`, which uses the `wcsaxes` package to add celestial coordinates to a `PlotWindow` plot of a FITS dataset.
As of AstroPy version 1.3 (the current stable version of AstroPy is 2.0.2), this functionality has been moved into AstroPy proper, and the separate package itself is no longer being supported. This PR allows us to import `wcsaxes` from AstroPy instead, but allows for the old import of `wcsaxes` as well. 
Eventually, we will handle these plots in a more seamless way, but for now this is the best we can do.

Use AstroPy version of WCSAxes for plotting FITS datasets

---

yt/data_objects/static_output.py

We used to fall back to `ds.overlap_proj` for low-dimensionality data and data with refine_by different than a factor of 2. However, since 320c51b66 `overlap_proj` has not been present in the codebase.
This removes the code that falls back to `overlap_proj` since it is unconditionally dead code now (i.e. the `hasattr` checks in the code I've deleted will never be `True`).

[cleanup] Remove references to overlap_proj in Dataset initialization

---

yt/analysis_modules/level_sets/clump_handling.py
yt/analysis_modules/level_sets/tests/test_clump_finding.py

This fixes #1566 as reported by @Jose-Utreras.
The issue is that if `needs_grid_type` is `True`, the `'x'`, `'y'`, and `'z'`fields are always saved. If a user explicitly asks for them to be saved, then yt tries to save them twice, causing h5py to barf.
The fix is to check for this corner case and remove `'x'`, `'y'`, and `'z'` from the list of user fields to be saved.

Ignore "xyz" fields in clump.save_as_dataset if needs_grid_type is true. Fixes #1566 

---

tests/tests.yaml
yt/analysis_modules/halo_analysis/halo_catalog.py
yt/analysis_modules/halo_analysis/tests/test_halo_catalog.py

This fixes a bug where halo quantities returned without units will fail because of a forced unit conversion when compiling results.  I also added a test for this.

[bugfix] Check for units before converting quantities in HaloCatalog

---

yt/analysis_modules/level_sets/clump_handling.py

This fixes a corner case in clump finding where a child clump has no siblings, and so it is removed and its children are attached to its parent.  This already happens but the pointer from a child clump to its new parent was not being updated.  This issue manifests when the clumps are saved with `save_as_dataset` and reloaded.  The parent ids are not saved correctly and a `KeyError` occurs.
I also removed a duplicate line that probably appeared because of a bad merge a long time ago.

[bugfix] fix clump-finding corner case

---

yt/data_objects/data_containers.py

There is a call to `create_vector_fields` in `setup_fluid_fields` which is supposed to set up the magnetic fields in spherical and cylindrical coordinates. However, it does not happen, and this is because these fields expect a `bulk_magnetic_field` field parameter to exist and it does not. This PR adds this parameter.

[bugfix] Properly create curvilinear magnetic fields

---

tests/tests.yaml
yt/analysis_modules/cosmological_observation/light_cone/light_cone_projection.py
yt/analysis_modules/cosmological_observation/light_cone/tests/test_light_cone.py

This fixes a typo in the light cone projection routine where we were applying the wrong units to the projection array.  The fix itself can be see in [this commit](https://github.com/yt-project/yt/commit/10a349a3441218285d5c40efde0c07a92d7fee73).  I then simplify this code to use the `uconcatenate` function instead.  This was never caught because the units of this array get lost again later and because there are not any tests for the light cone generator.  However, this will produce an error in some circumstances.  I've added a relatively simple answer test so this module at least has something.

[bugfix] fix units in light cone projection

---

tests/tests.yaml
yt/frontends/ytdata/data_structures.py
yt/frontends/ytdata/tests/test_outputs.py

This fixes a bug in reloading arbitrary grids saved with `save_as_dataset`.  There was a small typo and some of the dataset attributes were not being set correctly.  I've added a test as well.  I'll wait to make sure the old tests are correct before incrementing the answer version.

[bugfix] properly set attributes for reloaded arbitrary grids

---

yt/data_objects/tests/test_profiles.py
yt/utilities/lib/misc_utilities.pyx

This issue was originally reported by yuta t on the mailing list. NaNs get introduced into the profile calculation if the first weight is zero. The fix is to skip entries that have weights equal to zero. I believe this won't change any answers unless NaNs were already being introduced, but let's see what the answer tests say.
See the test I added for an example script that this pull request fixes.

 Handle the case where the profile weight field has values equal to zero 

---

setup.cfg

In principle we could also just fix these but given that our tests are broken right now I'd rather just add ignores for the two new rules that are causing the failures in the flake8 test.
The two new rules we're ignoring are:
* E722 do not use bare except
* E741 ambiguous variable name
I think E722 is probably something worth fixing eventually but it will need a bit of care. I don't think E741 is worth fixing.

Add ignore rules for new flake8 rules

---

yt/visualization/plot_container.py
yt/visualization/tests/test_particle_plot.py

My attempt at solving issue #1582. This implements a 'hack' in the `_switch_ds()` method which enables the data to be swapped when doing a ParticleProjectionPlot. This is incredibly helpful when making movies.

Fix  _switch_ds() use with ParticleProjectionPlots

---

appveyor.yml

According to the appveyor docs, `Miniconda3` points to a relatively old base miniconda installation. Let's update to point at a newer one, which should avoid the issue we're seeing.

use newer miniconda base in appveyor config

---

tests/tests.yaml
yt/data_objects/static_output.py
yt/frontends/gadget/data_structures.py
yt/frontends/gizmo/fields.py
yt/frontends/sph/fields.py

This PR fixes #1610. As @ngoldbaum and @jzuhone suggested, a new unit `code_specific_energy` is registered and set to a sane default value as the unit for Gadget and Gizmo's internal energy field. There is a side effect that the unit change would propagate into other frontends inherited from `SPHDataset`. The relevant frontends' authors are notified to check if this is the desired behavior.
- #971 
- [Bitbucket PR 1392](https://bitbucket.org/yt_analysis/yt/pull-requests/1392)

Register code_specific_energy and correct GadgetDataset's internal energy unit

---

doc/source/cookbook/fits_radio_cubes.ipynb
doc/source/cookbook/fits_xray_images.ipynb
doc/source/help/index.rst

mfw i saw "github.org":
https://www.youtube.com/watch?v=cdEQmpVIE4A

fix broken links in documentation

---

yt/data_objects/grid_patch.py
yt/frontends/enzo/tests/test_outputs.py

Fixes #1601.
This fixes a regression that was unintentionally introduced by Andrew in [Bitbucket PR 2575](https://bitbucket.org/yt_analysis/yt/pull-requests/2575) which added support for nodal fields. In particular, there was a call to `np.squeeze` that was added to ensure the return value of field acceses on grid objects would have a dummy dimension added by the nodal field machinery removed.
This was fine for 3D data but for 2D data it changed the shape of the data returned from accessing a grid patch. This in turn broke contour finding in 2D because the contour finding machinery expected 3D grid patches but was handed 2D data.
The fix I've implemented is to avoid use of `np.squeeze` and instead only attach the extra dimensions for nodal fields if they are nontrivial. I'm pretty sure …

Ensure field accesses on 2D grids keep their dummy dimension

---

yt/visualization/plot_modifications.py
yt/visualization/tests/test_callbacks.py

A few plot modifications do work for 2D cylindrical geometry, but now they are excluded from support geometries.

Enable a few plot modifications for 2D cylindrical geometry

---

yt/frontends/boxlib/data_structures.py
yt/frontends/boxlib/tests/test_outputs.py

Fix the boolean parameter casting bug in the boxlib frontend.
Instead of calling `bool()` on a string, check to see if the string is equal to `"T"`
Fixes issue #1618 
See issue #1618 for test code.

Fix _guess_pcast bug in boxlib frontend with boolean parameter casting.

---

doc/source/reference/changelog.rst

I noticed that the docs pointed to the old credits file on bitbucket.  This updates to github.

Updating to point at github CREDITS file.

---

yt/units/unit_lookup_table.py

`rad` was defined with dimensions of `solid_angle`. But it should be `angle`.
I am not sure why this has not been caught unless my understanding of "rad" has been totally wrong.

[BUGFIX] "rad" should have dimensions of angle

---

yt/visualization/plot_container.py

This PR add the possibility to pass a tuple to the `save` method of a plot. This tuple is interpreted as the different components of a path using `os.path.join`. The resulting file name will then follow the same rules as before.
This helps to programatically store outputs in different folders.

Support tuple argument in save

---

yt/analysis_modules/level_sets/tests/test_clump_finding.py
yt/testing.py

This eliminates some deprecation warnings in our unit tests.

No longer need to pass number_of_particles when loading data

---

setupext.py

This is inspired by https://github.com/astropy/astropy-helpers/pull/346, which added detection for OpenMP support to astropy. Their approach is better than ours in that it:
* Links the program and tests to make sure it actually runs correctly
* Uses the distutils compiler API instead of relying on the `'CC'` environment variable
* Adds support for OpenMP on windows with MSVC
I've also added a small context manager to suppress the compiler output to stdout from the OpenMP test to avoid adding noise to the output from compiling yt. If compilation fails, we will still print the compiler output so I think this is fine.
Rather than using their exact approach, which manipulates the Extension objects after creating them, I'm instead just modifying the `check_for_openmp` function that already …

Improve OpenMP detection

---

yt/visualization/volume_rendering/render_source.py
yt/visualization/volume_rendering/tests/test_scene.py

This fixes #1595.
AFAICS this has simply never worked (see e.g. the examples in the yt 3.3.0 docs build). The cause is the use of a non-unit `color_stride` keyword argument to `zlines` in `CoordinateVectorSource`. Since the default stride is 1 and the existing API doesn't expose `color_stride`, we can simply delete it.
I've also added a test to make sure that the line annotations are actually drawing something with the correct color. I could probably add an image comparison test but I'd prefer to avoid that.

Fix volume rendering annotate_axes axes colors.

---

yt/analysis_modules/ppv_cube/ppv_cube.py
yt/analysis_modules/ppv_cube/ppv_utils.pyx
yt/analysis_modules/ppv_cube/tests/test_ppv.py

This PR ensures that we can still create a `PPVCube` if there is no temperature field in the dataset, since we can have velocity shifting and broadening without thermal broadening. 
An error will now be thrown if `thermal_broad=True` if there is no temperature field in the dataset.
A new unit test has been added, thanks to @e-koch.
Closes Issue #1539. Thanks to @e-koch for the bug report.

Make sure that PPVCube does not fail if there is no temperature field

---

doc/source/examining/loading_data.rst
yt/data_objects/particle_filters.py
yt/data_objects/static_output.py
yt/data_objects/tests/test_particle_filter.py
yt/frontends/ramses/data_structures.py
yt/frontends/ramses/definitions.py
yt/frontends/ramses/fields.py
yt/frontends/ramses/io.py
yt/frontends/ramses/tests/test_outputs.py
yt/utilities/exceptions.py

At the yearly Ramses User Meeting, it was decided to implement particle families in RAMSES. This includes a non-backward compatible change in the structure of the particle outputs, namely two 1-byte extra fields are included: a `particle_family` (the kind of the particle, e.g. stars, DM, …) and a `particle_tag` (the subtype of the particle, e.g. pop III stars, pop II stars, …).
The change is autocratically detectable because a new file `part_file_descriptor.txt` file is now outputted with the following structure:
```
1, variable_name_1, data_type
…
n, variable_name_n, data_type
```
The nice thing is that `data_type` is directly given using the table of https://docs.python.org/3.5/library/struct.html#format-characters, so it can be used to unpack the data.
This PR adds support for the …

RAMSES new particles

---

doc/source/examining/loading_data.rst
yt/frontends/ramses/data_structures.py
yt/frontends/ramses/hilbert.py
yt/frontends/ramses/tests/test_hilbert.py

Provide a new argument to the `yt.load` for ramses datasets to only load a subset of a simulation.
The drawback is that once you loaded your dataset, you cannot access any of the skipped domains.
The new argument won't change the dataset itself (same domain width, …) but only which domains are red from disk. This is useful for people doing zoom-in simulations (like me) or cosmological simulations (like me), as it prevents yt from loading the entire AMR structure and can result in significantly faster access to small parts of simulations.
It would be good to have a bit more tests, but I didn't have time until now, any help is welcome!

RAMSES bbox feature

---

yt/fields/particle_fields.py

I use RAMSES and when trying to get deposit fields (ptype_cic_velocity_x or y, z, age) I got the value off by a factor of scale_l / scale_t.
This PR solves my problem in my case...

solve bug when deposit velocity/age fields?

---

doc/source/analyzing/analysis_modules/absorption_spectrum.rst
doc/source/analyzing/analysis_modules/light_ray_generator.rst
yt/analysis_modules/absorption_spectrum/api.py
yt/analysis_modules/cosmological_observation/light_ray/api.py
yt/analysis_modules/halo_mass_function/api.py
yt/analysis_modules/star_analysis/api.py
yt/analysis_modules/sunrise_export/api.py
yt/analysis_modules/two_point_functions/api.py

These modules have been moved to the Trident package.
Also, update the links to the yt_attic.

Adding deprecation warnings for LightRay and AbsorptionSpectrum

---

setup.py

This should prevent people from being able to pip install yt on unsupported versions of python, assuming they have a sufficiently recent verision of pip installed.
When we drop support for Python 2.7 and Python 3.4 having this defined will also make it clearer what changes need to be made to drop support cleanly.
You can read more about python_requires and the version specification format in [PEP 440](https://www.python.org/dev/peps/pep-0440/).

Add python_requires to yt's setup() invocation

---

doc/source/analyzing/filtering.rst
yt/data_objects/particle_filters.py
yt/data_objects/static_output.py
yt/data_objects/tests/test_particle_filter.py

This PR allows the user to add a particle filter to the dataset without adding all the dependencies of the filter in advance.
Some particle filters depend on other filters (`filtered_type`). When `ds.add_particle_filter` is called, it will look if the `filtered_type` of this filter is in the `filter_registry`, which means the user has already defined the filter through `yt.particle_filter()` decorator or `yt.add_particle_filter()`. It will try to add the filter to the dataset first.

Automatically add particle filter dependencies if already defined

---

yt/fields/particle_fields.py
yt/frontends/athena/tests/test_outputs.py
yt/testing.py
yt/units/tests/test_unit_systems.py

Currently the default for the `skip_dataset_cache` config variable is `"True"`. However, before it used to be `"False"` and it looks like there are still a couple places in our test suite that assume `skip_dataset_cache` is False by default. This means that some of these tests (`test_units_override`) in particular are re-enabling the dataset cache midway through a run of the test suite, causing mysterious failures (e.g. what hapenned in #1634).
This adds a new decorator to handle the global configuration state. Eventually I'd like to rip out dataset caching entirely but that will be a bigger job.

do a better job of handling global config state for tests that disable the dataset cache

---

doc/source/visualizing/callbacks.rst
yt/visualization/plot_modifications.py

This PR adds the option to pass in matplotlib arguments to quiver annotations (such as changing the color of the arrows), whether for the generic quiver annotation methods or for the specific velocity or magnetic field annotation methods. 
I've updated docstrings, still need to update the docs themselves.

Pass in matplotlib arguments to quiver annotations

---

yt/frontends/boxlib/data_structures.py

Due to a change in AMReX, these file names can have either 4 or 5 digits now.

[Bugfix] Fix particle data file names in the Boxlib frontend

---

yt/visualization/plot_modifications.py

The annotate_contour callback passes 'color' as a keyword to contour from matplotlib, but this is not a known keyword. This appears to be the result of a typo in commit 9a2f4ff4a5; prior to then, the correct keyword (colors) was passed to the contour plot. This commit will have the effect of making all contours be black in color by default. As a result, it will change the behavior of, for example, the "[Overplotting Contours](http://yt-project.org/doc/cookbook/complex_plots.html?highlight=annotate_contour#overplotting-contours)" example from the cookbook. If the current behavior is desired, which ends up being the use of the default colormap provided by mpl's contour, then instead we could just empty out def_plot_args.

Fix the name of the colors keyword to matplotlib contour

---

yt/frontends/boxlib/data_structures.py

Python dictionaries are unordered, so of course the current code doesn't work...

[BUGFIX] Fix a bug in initializing the species charge / mass in the WarpX frontend.

---

yt/units/tests/test_ytarray.py
yt/units/yt_array.py

This fixes the recursion errors that we are seeing on Travis with NumPy 1.14.

add a special case for array scalars in YTArray.__str__

---

tests/tests.yaml

I merged #1664 while jenkins was down. Unfortunately I didn't realize that it causes some of the plot answers to fail (there are some plot answer tests that used the contour callback).
The fix is to increment the plot answers.

increment plot answers

---

yt/visualization/plot_modifications.py

An error was reported on the Trident mailing list by Kezman Saboi that a FLASH dataset was unable to generate an `annotate_ray()` on a `ProjectionPlot`.  After investigating, I found that we don't fully sanitize data coordinates in the plot_modifications (i.e. annotations).  The assumption is made that specified data coordinates are in `code_length`, when this particular coordinate was in `unitary` units, leading to the user's error.  This change explicitly forces the coordinates to be in `code_length` for coordinates used by the annotation machinery.

Ensuring plot annotations are in code_length units prior to plotting.

---

yt/frontends/gamer/data_structures.py
yt/frontends/gamer/definitions.py

This adds support for auto-detecting non-cartesian datasets in the GAMER frontend; note that it uses r-theta-z for cylindrical, which we make explicit here.

Add non-cartesian dataset support to the GAMER frontend

---

doc/source/developing/releasing.rst
scripts/pr_backport.py

This updates the PR backport script to function with git and github. It makes use of the github GraphQL API to gather information on the pull requests and then prompts the user about each pull request individually.
Note that this ended up a lot simpler than the old hg/bitbucket version, mostly because github provides richer information in the API and has a facility for generating diffs from a pull request.
This script was used to automate the process of generating #1647.

update pr backport script for git/github

---

yt/frontends/ytdata/data_structures.py
yt/frontends/ytdata/tests/test_outputs.py

This fixes a bug that shows up when you do:
```
ds = yt.load("enzo_tiny_cosmology/DD0046/DD0046")
proj = ds.proj("density", "x")
frb = proj.to_frb(1, (1000, 1000))
fn = frb.save_as_dataset(fields=["density"])
nds = yt.load(fn)
print (nds.data["density"])
```
The units of the domain right/left edges were being clobbered.  The added assert tests this functionality.

[bugfix] Keep units when setting domain edges for frb datasets.

---

yt/frontends/enzo/data_structures.py

This makes it possible to read in active particle fields that represent arrays. With this change I'm able to run the script from @john-regan's e-mail to the mailing list.

support active particle fields that map to arrays

---

yt/frontends/open_pmd/data_structures.py
yt/frontends/open_pmd/fields.py
yt/frontends/open_pmd/io.py
yt/frontends/open_pmd/misc.py
yt/frontends/open_pmd/tests/test_outputs.py
yt/utilities/on_demand_imports.py

Updated yt frontend to respect latest changes in openPMD standard.
Previously undefined behaviour that caused #1626 is still undefined in an updated version of the standard.
All possible scenarios not covered are now handled gracefully.
openPMD as a markup describes metadata on top of your simulation data.
Two such pieces of metadata are `meshesPath` and `particlesPath`, indicating a file location for mesh data and particle data, respectively.
openPMD versions 1.0.0 and 1.0.1 do not state whether these folders must exist for the file to be valid.
If either path does not exist, this will not raise exceptions in yt. All cases will be handled gracefully. It is assumed that such files contain no meshes and/or particles.
This PR also handles groupBased files differently than before.
These kind …

Updated and hardened openPMD frontend

---

doc/source/visualizing/plots.rst
yt/visualization/base_plot_types.py
yt/visualization/plot_window.py

This makes it possible to write scripts like the one I've added to the documentation. Before this PR it was not possible to simultaneously hide the plot axes *and* set the plot background color. I think we want to retain the default behavior of removing the axes frame to avoid changing existing plots.
However, we still want to provide an escape hatch if someone explicitly sets the plot background color. This implements that escape hatch.
This was motivated by a question from sheagk on freenode.

Make it possible to hide axes and set an axes background color

---

yt/units/yt_array.py

This is in response to Jason Tumlinson on the mailing list. They supplied a pickle file created with an old version of yt. Apparently on this version there was no unit lookup-table saved at all and instead just a number, which I'm interpreting as the unit name. It's possible that this will break for other old pickle files but this will at least allow yt to load the one example we know of.

attempt to restore support for very old pickle files

---

yt/frontends/gadget/data_structures.py

While looking at #1675 I noticed that we weren't being consistent in looking for the Gadget CGS unit constants for the specific energy units like we do for the other units. This fixes that. Note that this is independent of #1675.

Use CGS units to calculate Gadget specific energy units if available

---

setup.py
yt/analysis_modules/level_sets/clump_validators.py
yt/utilities/lib/misc_utilities.pyx

Graviational potential is now calculated using openmp threading.
- Remove progress bar in favour of parallel computations.
- Truncation now only works at a thread level as `total_potential` flagged for reduction and thus only accessible after the loop finishes. Please comment on whether this is acceptable or whether it'd be better to introduce a switch to change between parallel and serial calculation)
- Please also comment on the usage of `num_threads`, so that it's in line with general thread parallel coding style in yt

Added parallel cython support for calc grav potential.

---

yt/fields/vector_operations.py

Tangential vector components are currently incorrect when calculated for an object with a bulk velocity given that the magnitude does not include the bulk velocity whereas the _spherical terms are.
This is only an quick fix for the two mentioned functions. Generally, this affects more parts of the code, see #1686
Moreover, this fix relies on #1687 to give correct results as the theta and phi components are otherwise off.

[Bugfix] Calculation of tangential vector components

---

yt/fields/tests/test_vector_fields.py
yt/fields/vector_operations.py

As pointed out on slack today by @pgrete, currently some of the vector field components in curvilinear coordinates are incorrect. This is easiest to verify by computing the velocity magnitude in those coordinate systems and comparing with the answer in cartesian coordinates.
It turns out that for the past few years as far as I can see, the fields representing the spherical theta, spherical phi, and cylindrical theta coordinates of vector fields in yt have been incorrect.
The ultimate cause is the use of `resize_vector` on the coordinate arrays. This function strips data from the coordinate arrays, causing the wrong coordinate data to be fed into the functions that calculate the components of vectors in cylindrical and spherical coordinates.
The fix is to remove the use of `resize_vector` …

Fix incorrect vector field components in cylindrical and spherical cordinates

---

yt/frontends/ramses/data_structures.py
yt/frontends/ramses/definitions.py

* Use buffered IO for AMR (as we skim through it a lot)
* Skip reading useless stuff
For a zoom-in cosmological simulation with 4800 cores + 22 level of refinement, this makes the reading of the AMR go from 50s to 0.1s. The improvement comes from the fact that the `fpu.read_attrs` is *very* slow when reading lots of values (in this case 105600). `fpu.read_vector` is much faster at that.

RAMSES performance improvement

---

doc/source/cookbook/find_clumps.py
yt/visualization/plot_modifications.py

Clump objects from the clump finder have different field types than reloaded clump objects, so we specify the field type to make the `annotate_clumps` callback work with both.

Allow clump callback to work with loaded clump datasets.

---

yt/utilities/parallel_tools/parallel_analysis_interface.py

This will close [Issue #19](https://github.com/yt-project/yt_astro_analysis/issues/19) in `yt_astro_analysis`.
The `ParallelDummy` class was identifying class methods by checking if they were of type `MethodType`, which works in python 2.  In python 3, they are of type `function`, so the class object wasn't getting setup correctly.  This change works in both python 2 and 3.

[bugfix] make halo finders work in parallel in python3

---

yt/utilities/on_demand_imports.py
yt/visualization/fits_image.py
yt/visualization/tests/test_callbacks.py

Fixes some warnings generated by the plotting tests. Also adds a wrapper around `astropy.__version__` I needed because of an astropy deprecation.

fix warnings generated by the plotting tests

---

tests/tests.yaml
yt/frontends/gadget/data_structures.py

While reading the EAGLE simulation, the original yt output physical velocity (in cgs, or km/s, etc.) misses a factor of sqrt(a).
Expected: physical velocity [cm/s] = sqrt(a) * velocity_on_disk * 1e5
where 1e5 is the unit velocity in cm per second.
For details, please see the discussion in the mailing list.   I have also included the output before and after editing the code, which uses an EAGLE simulation with z=0.271. 
https://mail.python.org/mm3/archives/list/yt-users@python.org/thread/RP2FYIRCBAOYOYDS7WIATBYVH2TIK5NT/

Incorrect Velocity Unit with Reading EAGLE

---

setupext.py

On Comet frontend the default policy seems to restrict the maximum thread spawned by openmp, which lead to a failed openmp test:
```
./test_openmp 
libgomp: Thread creation failed: Resource temporarily unavailable
```
In order for the simple check to be successful, two threads are sufficient.

Setting fixed # OMP threads in test function to get around frontend policies.

---

setupext.py

This was missed when I added support for OpenMP on Windows in #1591. Thanks to @pgrete for pointing this out.

Allow OpenMP support on Windows

---

yt/visualization/particle_plots.py
yt/visualization/tests/test_particle_plot.py

When doing a `ParticlePlot` with positions, one expects that the outcome of it is a `ParticleProjectionPlot` object. However, depending on the order of the arguments, the user either get a `ParticleProjectionPlot` or a `ParticlePhasePlot`.
https://github.com/yt-project/yt/issues/1680

Updated PartilcePlot axis configuration (fix for Issue #1680)

---

doc/source/examining/loading_data.rst
doc/source/reference/api/api.rst

@saethlin pointed out on Slack today that the AHF frontend doens't show up in the API docs. It looks like adding that was missed in #1477. I've also added references to classes from the Gadget FOF frontend, which were also missing.
Lastly, I reworded the documentation to spell out AHF as Amiga Halo Finder, this makes the docs searchable for the phrase "Amiga" as well as "AHF".

add a few classes from the halo finder frontends to the API docs

---

yt/frontends/ramses/io.py

This changes the name of extra hydro fields to `hydro_xxx` instead of `particle_xxx`.

[RAMSES] Change name of extra hydro variable to `hydro_...`

---

tests/tests.yaml
yt/frontends/flash/io.py

If one does something like this:
```
import yt
ds = yt.load('GasSloshing/sloshing_nomag2_hdf5_plt_cnt_0150')
grid = ds.index.grids[-1]
d = grid['flash', 'dens']
print(d.dtype)
```
Right now this will print `float32`. This is a bit surprising because, for example, this:
```
import yt
ds = yt.load('GasSloshing/sloshing_nomag2_hdf5_plt_cnt_0150')
print(ad['flash', 'dens'].dtype)
```
will print `float64`.
While this change could lead to some additional memory and CPU overhead, particularly for large FLASH datasets, I think avoiding confusion and floating point underflow means that we should cast data to float64 after reading.

Ensure FLASH field accesses return data as a float64 dtype

---

yt/frontends/_skeleton/data_structures.py

I noticed in the yt code source style guide that subclasses should access super classes with the super() function. I've been looking through the skeleton files for adding a new frontend and I noticed that the `data_structures.py` file didn't call the super class `__init__` with this convention, so I've modified the file to be consistent with the documentation. 
- [x ] Code passes flake8 checker

updating data structures classes to call super class with super function

---

yt/visualization/base_plot_types.py

This fixes the issue @jsmidt reported on the mailing list last night and restores compatibility with matplotlib 2.2.0. Thank you very much for the detailed report and the script to reproduce the issue.
This ended up only being an issue for `radial_velocity` because it uses a `SymLogNorm` colorbar, so the units ended up getting passed to matplotlib via the `SymLogNorm` initializer.
I've also separately opened https://github.com/matplotlib/matplotlib/pull/10721 to fix the upstream regression.

pass floats to matplotlib for vmin and vmax

---

yt/frontends/flash/data_structures.py

It turns out that the FLASH data @kuochuanpan is working with has `"'cgs'"` as the value for the "unitsystem" parameter.
The fix is to strip the quotes.
I've never seen FLASH data that has this issue before but I think it's harmless to strip the quotes anyway, even if it's a rare issue.

strip quotes from FLASH unitsystem parameter. Fixes #1721

---

doc/install_script.sh

ppc64le (little endian 64-bit POWER) is a known Miniconda architecture on Linux; this fix allows the install script to work on this architecture (e.g. Summit at Oak Ridge).
Also fixes a bug when the Linux arch is unknown.

Add ppc64le to install_script list of known Miniconda Linux architectures

---

yt/analysis_modules/halo_analysis/halo_catalog.py
yt/analysis_modules/halo_finding/halo_objects.py

This speeds up yt fof/hop halo finding by bypassing the step where the halo lists are rejoined.  This step uses MPI broadcast calls for every quantity of every halo and so is a pretty large scaling bottleneck.  Since these halo finders are only called through the `HaloCatalog`, which then re-splits the halo list, we can skip the joining and re-splitting and simply let each processor operate on the halos it found.
This changes the answers only to the extent that the final halo catalog is no longer mass-sorted.
This is perhaps a bit hacky, but it could potentially be a huge speedup for large datasets, so it might be worth it.

[enhancement] Speeding up yt fof/hop halo finding.

---

yt/visualization/plot_modifications.py

As reported on IRC by Josh Wall, currently when you do, e.g. something like this:
```
plot = yt.SlicePlot(ds, 2, 'density')
plot.annotate_text((0, 0), 'text!', coord_system='plot')
plot.save()
```
You end up with a plot that has an inset box, even though the default `inset_box_args` is None. The problem is that `None` gets replaced by `{}` in the `TextLabelCallback`, which gets interpreted by matplotlib as "please draw an inset box with the default arguments".
The fix is not to replace the default `None` value with an empty dict.

set default inset box arguments to None instead of {}

---

yt/units/tests/test_units.py
yt/units/unit_registry.py

This adds a `list_same_dimensions` function to a `UnitRegistry` that returns the names of all base units in the lookup table for that registry, along with anything that exists in `unit_objs`, when supplied a `unit_object`.  For instance,
```python
arr = ds.domain_width
equiv = unit_registry.list_same_dimensions(arr.units)
```
would return `unitary`, `cm`, etc, for most datasets.

Adding list_same_dimensions to UnitRegistry

---

doc/source/examining/loading_data.rst
yt/frontends/ramses/definitions.py
yt/frontends/ramses/field_handlers.py
yt/frontends/ramses/fields.py
yt/frontends/ramses/particle_handlers.py
yt/frontends/ramses/tests/test_outputs.py

Recent changes in yt have broken support for the automatic detection of e.g. the `birth_time` of particles in RAMSES. This PR adds back some support for this using yt configuration.
- Now possible to configure system-wide or per folder the fields in the files using yt configuration
- Now possible to customize which `family` is associated to which particle type in yt.

Add custom definition

---

yt/analysis_modules/level_sets/contour_finder.py
yt/analysis_modules/level_sets/tests/test_clump_finding.py

This fixes the issue reported on the yt-users list by Dan Le.  Field parameters were not getting passed to the grid objects in the contour finder, so contouring/clump finding could not be done using fields that had them.

[bugfix] Pass field parameters in contour finder

---

yt/frontends/owls/fields.py
yt/frontends/owls/tests/test_outputs.py

Particle Filter cannot be set while using the EAGLE simulation.  It traces to the error of 'UnboundLocalError: local variable 'ftype' referenced before assignment'  at the following location: yt/frontends/owls/fields.pyc in setup_particle_fields(self, ptype).
This can be solved by adding an else-case, which set ftype=ptype.  This change is submitted to this pull request.

Fix Error in Defining Particle Filters in EAGLE

---

doc/source/developing/creating_derived_fields.rst
yt/fields/derived_field.py
yt/fields/field_detector.py
yt/fields/field_exceptions.py

Recently, in #1693  I changed the implementation of `FieldDetector.has_field_parameter` to return True only for known field parameters. This had the unintended consequence of breaking support for unknown field parameters, which subsequently caused the unit tests to start failing when #1732 from @brittonsmith was merged.
The fix is to make the field detection system check if a field has `ValidateParameter` validators registered before detecting whether that field has errors and add the needed field parameters.
I've also substantially simplified the parameter validation logic, completely removing `NeedsParameterValue`. I also added some documentation for `ValidateParameter.parameter_values`. I didn't add a test since the existing field tests are sufficient.

give ValidateParameter the ability to inject needed parameters into field detection

---

yt/frontends/ramses/io.py

I've had multiple person asking me how to decrease the level of verbosity of the RAMSES frontend. This is due to the fact that each particle file and fluid file will send an info saying `Reading ... file descriptor`. While this is OK for debugging it gets annoying when you have thousands of CPU.
This PR replaces the noisy `mylog.info` by `mylog.debug`.

Make ramses less noisy

---

yt/fields/xray_emission_fields.py

This fixes the issue reported by Andrea Negri on the mailing list.
SPH data might have zones with zero density and temperature. We paper over that by checking the final emissivity field for NaNs and replacing them with zeros.
The real fix for this is the demeshening, which will avoid creating SPH fields containing zeros.

Avoid NaNs in x-ray emission field calculation

---

yt/units/unit_lookup_table.py

I noticed this while working on `unyt`. `'d'` is the suggested SI symbol for `'day'` according to wikipedia, so I've moved it from the astropy compatibility section to the time units section. It's ok that we have two different names for day, we already have a number of other symbols that have different names but the same value.

fix definition of d unit

---

yt/funcs.py
yt/units/tests/test_ytarray.py

This makes it so yt raises an error if you pass it a (length, unit) tuple where the length is a quantity with units attached.
I guess this is a backward incompatible change? I could make it issue a warning and ignore the units on the array. I'd prefer to keep the error though so people don't accidentally request yt do something with ambiguous units.

Make the (length, unit) tuple parsing a bit more careful. Closes #1748 

---

yt/analysis_modules/cosmological_observation/cosmology_splice.py

This fixes the error message printed when the cosmology splice can't connect two datasets.  We were not correctly printing the values of the starting and ending redshifts that we were attempting to connect.

[bugfix] Fix error message in cosmology splice calculation.

---

setup.py

See https://stackoverflow.com/a/26737258/1382869 for more details about this. This is a new feature of the new pypi implementation (pypi.org).
This pypandoc hack never worked for some reason anyway.
Once this is merged and we do a release, the page for yt on pypi.org will look much nicer than it does right now:
http://pypi.org/project/yt
It won't look nice on the old pypi, but that's getting shut down on Monday anyway.

use pypi's new support for markdown readmes

---

yt/visualization/profile_plotter.py
yt/visualization/tests/test_profile_plots.py

Right now if you do:
```
yt.ProfilePlot(ds, 'density', 'temperature')
```
you get an unfriendly `AttributeError` generated inside the `ProfilePlot` initializer. Ditto for `PhasePlot`. Given the `SlicePlot` API, where we explicitly expect people to pass in a dataset, I think erroring out here is needlessly inconsistent.
This PR makes it so that if you pass a `Dataset` instance into the `ProfilePlot` or `PhasePlot` initializer, yt internally generates an `all_data` data object from the dataset. It also adds a check for whether a user passed in another kind of object and raises a more informative error message if someone does pass in something besides a dataset or a data object.

Make it possible to create a ProfilePlot and PhasePlot from a dataset

---

yt/visualization/volume_rendering/render_source.py
yt/visualization/volume_rendering/utils.py

I recently ran into an issue which I *believe* is due to a recent rebuild of pyembree on conda.  The size of the object changed in Cython, which caused importing to fail -- but *not* by throwing an `ImportError`.  Because the object size changed, it threw a `ValueError` instead.  This caused the entire `yt` import to fail.
I'm not *certain* but it's possible that there's a way that current conda installs might make this happen.  It was on my jupyterhub for class, so it's way less likely that I did something strange with the installation, as I don't have any development there.
Regardless, this fixes the issue.
(ping @scopatz as well)

Adding ImportError checks for pyembree

---

yt/frontends/ramses/data_structures.py
yt/frontends/ramses/field_handlers.py
yt/frontends/ramses/tests/test_outputs.py

Currently the RAMSES frontends reads the particle/rt field descriptors multiple times (ncpu times to be precise). This is useless as the fields detected are the same in all the files.
This PR adds some logic to store in the class the detected fields, as well as reset the detected field upon dataset change.
As a side effect, there is less information printed to the console as the detection only happens once per dataset.

Ramses lazy reading

---

yt/funcs.py

The current implementation would result in `FileNotFoundError` when a file in current directory (`'test.txt'` for example) is passed to `ensure_dir_exists`.
An alternative solution is to write `my_dir = os.path.dirname(os.path.abspath(path))` instead. Let me know if this one is prefered.

Fix an edge case in ensure_dir_exists

---

doc/source/conf.py
yt/analysis_modules/absorption_spectrum/absorption_spectrum.py
yt/analysis_modules/ppv_cube/ppv_cube.py
yt/analysis_modules/sunrise_export/sunrise_exporter.py
yt/analysis_modules/sunyaev_zeldovich/projection.py
yt/data_objects/construction_data_containers.py
yt/utilities/exceptions.py
yt/utilities/grid_data_format/writer.py
yt/utilities/particle_generator.py
yt/utilities/tests/test_particle_generator.py
yt/visualization/fits_image.py
yt/visualization/fixed_resolution.py
yt/visualization/tests/test_fits_image.py
yt/visualization/volume_rendering/image_handling.py

Eventually AstroPy is going to get rid of the `clobber` keyword when writing FITS files completely (it appears they tried recently but balked because of the volume of legacy code, see discussion at astropy/astropy#6381). Currently `overwrite` is recommended for overwriting files. 
This PR goes through the code wherever we use the `clobber` keyword argument and replaces it with `overwrite`, allowing `clobber` to be caught in `**kwargs` and issuing a deprecation warning if it is found.

Change "clobber" to "overwrite", add deprecation

---

doc/source/examining/loading_data.rst
yt/frontends/ramses/data_structures.py
yt/frontends/ramses/fields.py
yt/frontends/ramses/io.py
yt/frontends/ramses/particle_handlers.py
yt/frontends/ramses/tests/test_outputs.py
yt/funcs.py
yt/utilities/lib/cosmology_time.pyx

This supersedes #1463 and #1545.
This pull request makes the following changes:
* Restores the `particle_age` and `particle_metallicity` fields, which were unintentionally removed during the particle i/o refactoring that was recently merged.
* Deprecates the `particle_age` field. This field is actually the formation time of particles and shouldn't have ever been called an "age".
* Adds a `particle_formation_time` field. This is distinct from the values in the old `particle_age` in that particles present in the initial conditions will always have a `particle_formation_time` equal to zero. This makes it a bit easier to write particle filters for particles present in the initial conditions and avoids presenting negative formation times to the user, which doesn't make much sense.
* Adds a …

Refactor RAMSES age and formation time fields

---

yt/visualization/plot_window.py

This seems like a useful thing to enable, especially given the context of e.g. Stephanie Ho's message to the mailing list today:
https://mail.python.org/mm3/archives/list/yt-users@python.org/thread/4IFJKQOB4SBJC7DMR6RF4FVUIK37PXKC/
Here's an example notebook where I make use of this:
https://gist.github.com/ngoldbaum/123e5e93a638dcb0144372fc9920ba9d
@atmyers do you happen to remember why you blacklisted the particle callback in the first place?

allow the particle callback to work with ParticleProjectionPlot

---

yt/frontends/ramses/data_structures.py
yt/frontends/ramses/field_handlers.py
yt/frontends/ramses/particle_handlers.py

This is a very minor refactoring to prevent multiple warning when detecting extra fields (e.g. in the particle files or gravity files)

[RAMSES] Warn only once when detecting extra fields

---

yt/funcs.py

While working on #1747 I noticed it takes a lot of time to merely generate `index`:
```
86.197 <module>  ala.py:1
├─ 72.665 index  yt/data_objects/static_output.py:500
│  ├─ 71.706 __init__  yt/frontends/flash/data_structures.py:56
│  │  └─ 71.706 __init__  yt/geometry/geometry_handler.py:39
│  │     └─ 71.706 _setup_geometry  yt/geometry/grid_geometry_handler.py:43
│  │        ├─ 48.438 _parse_index  yt/frontends/flash/data_structures.py:90
│  │        │  └─ 48.071 __init__  yt/frontends/flash/data_structures.py:41
│  │        │     └─ 47.860 __init__  yt/data_objects/grid_patch.py:58
│  │        │        └─ 47.216 __init__  yt/data_objects/data_containers.py:1190
│  │        │           ├─ 34.421 __new__  yt/data_objects/derived_quantities.py:87
│  │        │           │  ├─ 29.787 …
```

Optimize yt.funcs:camelcase_to_underscore

---

doc/source/cookbook/calculating_information.rst
doc/source/cookbook/downsampling_amr.py
yt/data_objects/data_containers.py
yt/data_objects/tests/test_compose.py
yt/data_objects/tests/test_regions.py
yt/geometry/selection_routines.pyx

This pull request adds new properties named `max_level` and `min_level` to the `YTSelectionContainer` class. This allows us to add some logic that fires when `max_level` or `min_level` are set or changed by a user.
This also makes the `ComposeSelector` (which is created when one does some like `dobj = ds.some_data_object(..., data_source=other_dobj)`) inherit `max_level` and `min_level` from the value of `max_level` or `min_level` on the underlying data objects it is created from.
The reason why this PR is necessary is most easily seen from what happens when you currently run either of the two new tests I'm adding:
```python
import yt
from yt.testing import fake_amr_ds
ds = fake_amr_ds()
ad.max_level = 2
plot = yt.SlicePlot(ds, 2, 'density', data_source=ad)
plot.save() …
```

Improvements for data object max_level and min_level

---

yt/data_objects/octree_subset.py
yt/visualization/volume_rendering/off_axis_projection.py

Ping @earnric who motivated this work.
This pull request reduces the time to run the following script:
```python
import yt
ds = yt.load('output_00080/info_00080.txt')
m, c = ds.find_max(('gas', 'density'))
plot = yt.OffAxisProjectionPlot(ds, [1, 1, 1], 'density', center=c, width=(1, 'Mpc'))
plot.save()
```
from 127.795 s to 56.528 s, more than a 2x speedup!
I haven't yet done a line profile of the actual off-axis projection operation, but there are probably some other places to optimize this operation in the `off_axis_projection` function.

optimize octree off-axis projections

---

doc/source/examining/loading_data.rst
yt/fields/field_detector.py
yt/fields/magnetic_field.py
yt/fields/tests/test_magnetic_fields.py
yt/frontends/gizmo/fields.py
yt/frontends/gizmo/tests/test_outputs.py

A function to set up magnetic field aliases for particle dataset is implemented. And it is used to set up the magnetic field in GIZMO frontend.

Set up magnetic field in GIZMO frontend

---

doc/source/visualizing/callbacks.rst
doc/source/visualizing/plots.rst
yt/visualization/plot_modifications.py

This PR adds two tweaks to plot annotations.
* An offset for timestamps, e.g. if you want to make the timestamp shown on the plot to be (say) `ds.current_time` - 5 Gyr so that the zero is at a different time.
* A `format` argument for the `ScaleCallback` similar to the `time_format` argument for the `TimestampCallback`. 
Not sure what would be a good test here, still need to add notes to the narrative documentation. Suggestions welcome.

Annotation tweaks

---

doc/source/visualizing/callbacks.rst
yt/visualization/plot_modifications.py
yt/visualization/tests/test_callbacks.py

Added keyword arg to GridBoundaryCallback/annotate_grids that allows the user to choose which corner the grid id label is drawn (if draw_ids=True). If the location is unspecified or the specified location is garbage, default to the lower left.

Ability to choose grid label location with annotate_grids callback

---

tests/tests.yaml
yt/geometry/coordinates/geographic_coordinates.py
yt/geometry/coordinates/spherical_coordinates.py
yt/utilities/lib/pixelization_routines.pyx

The aitoff pixelizer does not get used very much.  It's used only when pixelizing along the radial axis in the spherical coordinate handler or in the geographic coordinate handler.
I have recently been poking at removing some of our machinery that operates in this space and replacing it with cartopy; the pixelizer would likely still be used in some form, but we would transition to using cartopy for all management of axes, etc.
In the process of poking at that, I began to work at examining some spherical and geographic datasets (specifically, from GEOS, which I have uploaded to http://use.yt/upload/ff63bba3 totaling 1.6 GB) and looking at slices.  The slices were manifestly incorrect:
(The axes, which I'm sure will draw attention, are pretty bad in that they assume cartesian shapes to a …

Coordinates for aitoff pixelizer

---

yt/data_objects/construction_data_containers.py
yt/data_objects/tests/test_fluxes.py

The `vertex_data` attribute is named `vertex_samples` now. I'm not sure when this change was made but it looks like it was at least five years ago.
I've added a test to make sure the code path that I've changed in `_export_ply` gets triggered by the tests.

fix AttributeError in _export_ply

---

yt/visualization/volume_rendering/tests/test_scene.py
yt/visualization/volume_rendering/transfer_functions.py

Starting with numpy 1.12, indexing an array with floats [raises an IndexError](https://docs.scipy.org/doc/numpy-1.12.0/release.html). This happens in the save_annotated function of the volume_rendering module. 
E.g. with numpy 1.13.3, matplotlib 2.2.2 and yt 3.4.1 (all installed via anaconda) I get:
> egaraldi@science05:/vol/3Drendering$ python customTF.py 
> step  5 ...
> yt : [INFO     ] 2018-05-22 11:52:09,551 Parameters: current_time              = 0.0
> yt : [INFO     ] 2018-05-22 11:52:09,551 Parameters: domain_dimensions         = [128 128 128]
> yt : [INFO     ] 2018-05-22 11:52:09,551 Parameters: domain_left_edge          = [-50. -50. -50.]
> yt : [INFO     ] 2018-05-22 11:52:09,552 Parameters: domain_right_edge         = [ 50.  50.  50.]
> yt : [INFO     ] 2018-05-22 …

Forced integer division in save_annotated to prevent errors in newer numpy versions

---

yt/fields/tests/test_fields.py
yt/units/yt_array.py

This fixes one of the issues Nick Gnedin reported on the mailing list. One of these days we'll be able to get rid of the distinction between `units` and `output_units` once and for all. For now we isolate the awfulness in this case by only using it for particle fields in `array_like_fields`. Currently `output_units` are only systematically handled in yt for particle fields. Another solution would be to make all fields respect it, but I'm certain that would cause more breakage.

array_like_field should only use output_units for particle fields

---

.codecov.yml

Updating the codecov configuration to allow the coverage to drop by 100%, and posting a success status.
This should fix the failed PR [1802](https://github.com/yt-project/yt/pull/1802).

Updating config to not fail the pushed patch

---

yt/analysis_modules/halo_analysis/enzofof_merger_tree.py

This fixes some python3 compatibility issues reported by Xiaoli Lian on the mailing list:
https://mail.python.org/mm3/archives/list/yt-users@python.org/thread/L2GC5YUPXHZCXYQ7RRPPJMIPVAKCTZ2W/
It turns out that this code has poor test coverage and I don't think was ever updated for python3. Thankfully the fixes were relatively straightforward, although there might be other issues that Xiaoli's test script didn't trigger.
I haven't carefully checked to make sure the outputs are still correct, but with this chnge Xiaoli's test script runs to completion without error.

fix py3 issues in Enzo FOF merger tree

---

yt/visualization/fixed_resolution.py
yt/visualization/tests/test_plotwindow.py

This avoids an ugly error if you happen to pass in floats to `set_buff_size` or when manually creating an FRB:
```python traceback
In [2]: plot.set_buff_size([400., 400.])
Out[2]: <yt.visualization.plot_window.AxisAlignedSlicePlot at 0x110a34780>
In [3]: plot.save()
yt : [INFO     ] 2018-05-23 11:01:39,357 Making a fixed resolution buffer of (('gas', 'density')) 400 by 400
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/Documents/yt-git-fixes/yt/mods.py in <module>()
----> 1 plot.save()
~/Documents/yt-git-fixes/yt/visualization/plot_container.py in newfunc(*args, **kwargs)
86         if hasattr(args[0], '_data_valid'):
87             if not args[0]._data_valid:
---> 88 …
```

ensure FRB buff_size is a two-element tuple of ints

---

yt/frontends/artio/fields.py

ARTIO frontend is missing densities of atomic species in the list of known fields. By default, these fields are treated as dimensionless, while they are not (have units of mass density).

Added missing known fields with nontrivial units 

---

yt/fields/field_detector.py
yt/frontends/artio/fields.py
yt/frontends/artio/tests/test_outputs.py

Currently there are already hacks in the artio frontend to avoid issues with field detection. These hacks make it so the artio particle age fields don't have the correct units during field detection, requiring users who make use of these fields in a derived field to also add similar hacks.
The fix is to make it so we don't pass invalid data during field detection to the artio frontend's helpers for converting from internal time units to physical time units.
This does mean adding an ARTIO-specific hack to the field detection machinery. Optimally we would have a way of telling the field detection machinery to draw from a range of possible values during field detection, but we don't have something like that yet.

Ensure artio particle age fields have the correct units during field detection

---

doc/source/cookbook/vol-annotated.py
yt/visualization/volume_rendering/scene.py
yt/visualization/volume_rendering/tests/test_scene.py
yt/visualization/volume_rendering/transfer_functions.py

Since #1793 the travis tests are intermittently failing in the call to save_annotated because of missing `DISPLAY` environment variable.
We don't really need pyplot at all and in principle real users would hit this error on e.g. a cluster or any other headless SSH session.
I've gone ahead and removed the usages of pyplot in `save_annotated` and functions called by `save_annotated`. This does make the resulting image change appearance slightly. Here's the output of `vol_annotated.py` in the documentation
old:
new:
Note how in the old version the text annotation doesn't actually appear because it's "off the page". I think the new format looks a bit cleaner. If people disagree I can certainly try to make the images match a bit more.

remove usage of pyplot for annotated volume rendering

---

yt/data_objects/tests/test_covering_grid.py
yt/data_objects/tests/test_fluxes.py
yt/data_objects/tests/test_points.py
yt/data_objects/tests/test_profiles.py
yt/testing.py

Removed real data usage from test cases
Updated test cases to use `fake_particle_ds` or `fake_random_ds` instead of real dataset and other such changes.
This should increase coverage and reduce runtime (both by small amount).

Updating tests to use fake dataset instead of real data

---

setup.py

This is no longer necessary now that `pypi` supports markdown readmes. I missed this in #1752.

remove pypandoc import check from sdist run

---

yt/data_objects/data_containers.py
yt/data_objects/tests/test_chunking.py

I have been poking at a `MultiIndex` that combines multiple datasets or index objects.  I've found that I've been able to implement nearly all of it outside of core changes to yt except for this.
This -- in the vein of the other context managers in the data container class -- sets up a holding system so that when you are in the context manager, you are free to use the data object in such a way that the index is not assumed to be the one it was built with.
One example usage would be something like this, which I'm using in the multi index object:
```
def _chunk_io(self, dobj, cache = True, local_only = False):
indices = getattr(dobj._current_chunk, "objs", dobj._chunk_info)
print(indices)
for ind in indices:
with dobj._ds_hold(ind.ds):
for c in ind._chunk_io(dobj, cache, local_only):
yield …
```

Adding a ds_hold operation to swap datasets

---

doc/source/visualizing/sketchfab.rst

This makes this widget visible from https://yt-project.org/docs/dev/visualizing/sketchfab.html

avoid mixed-content error in sketchfab docs

---

yt/data_objects/data_containers.py

We can't supply floats to ranges, so we need to use `//`.

Round to integer

---

yt/data_objects/tests/test_points.py

fixes #1823 
This should happen 2% of the time, so I guess I was just lucky to see this twice in a couple of days.

avoid possible IndexError in test_fast_find_field_values_at_points

---

yt/visualization/plot_modifications.py

This is necessary to adapt to a behavior change in matplotlib. Now we only set the keyword argument if we actually want to draw the inset box.

only set the bbox kwarg if we're actually drawing an inset box

---

yt/data_objects/data_containers.py

Fixes #1821
It turns out that the order of the list returned by `_identify_depdendencies`
is not stable across processors. I'm not sure exactly why, but sorting the list
of fields to get does seem to fix the issue.
I'm not sure how to test this without running the test in parallel, which isn't something we're really set up for.

sort the list of fields to read and generate

---

yt/visualization/plot_modifications.py

This fixes an issue reported by Stephanie Ho on the mailing list:
https://mail.python.org/mm3/archives/list/yt-users@python.org/message/VGZIRE7HO6APK4MKUSCIPI3TXC4PNMRL/
With this PR her script produces the following image:
The fix ended up being to avoid stripping units until we get to `convert_to_plot` and then inside `convert_to_plot` to ensure that all data are in code units before stripping units.
I haven't looked carefully at the other callbacks that call `convert_to_plot` although I think the changes I've made there are generally going to be safe and backward compatible.

Fix unit issues in PlotCallback.convert_to_plot and ParticleCallback

---

yt/frontends/boxlib/data_structures.py

This is an optimization for large AMReX datasets with no mesh refinement. In those cases, a significant amount of time can be spent in `_reconstruct_parent_child`, even though none of that work is needed when `max_level == 0`.

Return early from _reconstruct_parent_child in the boxlib frontend if max_level is 0.

---

doc/source/analyzing/generating_processed_data.rst
yt/data_objects/profiles.py
yt/data_objects/tests/test_profiles.py

I wanted to be able to use custom bins but still get the yt profile infrastructure. I just added a kwarg to override all of the other bin settings when given an argument, otherwise it's ignored. I have a notebook showing that it works/why I wanted this functionality with my dataset, but I'm not sure how's best to share it?
(also hi everyone, get ready for a bunch of planetary astro PRs :) )

Added ability to override profile bins to allow custom step sizes +tests

---

appveyor.yml

With this, AppVeyor coverage reports will be sent to yt's Codecov dashboard. Though, these reports are just a subset of Travis CI (since these also run only the unit tests) and do not add any additional value to the reporting portal. But the aim is to have coverage from all (Travis/AppVeyor/Jenkins) at yt's Codecov portal.

adding coverage report from appveyor

---

appveyor.yml

Reverting #1845 merge, since running nosetests with coverage is causing issues in python 2.7 in Appveyor.

reverting #1845 merge

---

yt/frontends/gadget_fof/data_structures.py
yt/frontends/owls_subfind/data_structures.py

This fixes the velocity unit similarly to the [bugfix for the Eagle frontend](https://github.com/yt-project/yt/pull/1675).
After reading through the subfind manual, I found a proper definition for `time_unit`, so I fixed that, too.  I also corrected similar errors in the OWLS_Subfind frontend.

[bugfix] Fixing velocity unit in gadget_fof frontend.

---

.travis.yml
appveyor.yml
yt/data_objects/construction_data_containers.py
yt/data_objects/data_containers.py
yt/data_objects/tests/test_clone.py
yt/data_objects/tests/test_connected_sets.py
yt/data_objects/tests/test_data_containers.py
yt/data_objects/tests/test_spheres.py

1. Removed dead code
2. Fixed few issues which were identified by adding more test cases
3. Increased coverage

Clean up and added test cases for `data_objects.data_containers`

---

tests/tests.yaml

Kacper updated matplotlib on the test box which broke a bunch of the answer tests. This updates the plot answers to unbreak those tests.

update plot answers for new matplotlib version

---

yt/geometry/coordinates/cylindrical_coordinates.py

The periodicity argument for cylindrical pixelization behaves
incorrectly; in particular, because the period is set to zero, this ends
up causing double-counting (and sometimes quad-counting) at the edges of
an FRB as the (orthogonal) pixelization routine iterates over the false
periods.  It does not make sense, in practice, to have periodicity in
the dimensions represented by an orthogonal pixelization in cylindrical
coordinates in almost any case, and so we disable it.
Closes #1669.

Default periodicity for cylindrical set to False

---

yt/frontends/exodus_ii/data_structures.py

It is possible for ExodusII to hold onto strong references in its
`is_valid` function, which interferes with things like FLASH being able
to call `is_valid` in some cases.  This shows up in `h5py` as an error
that the "file close degree doesn't match."
This should have no side effects, so if it does, that's trouble!

Use weak refs for ExodusII is_valid function

---

doc/source/examining/loading_data.rst

This fixes #1689 by adding a warning note about multipart gadget.

Add a note about loading data for multipart Gadget files.

---

yt/data_objects/tests/test_data_containers.py

Tests of `data_containers` were generating output files in yt's directory and not cleaning up after execution. 
Now, these files are generated in temporary directory and are deleted after the tests.
- [ X ] Code passes flake8 checker

clean-up generated files after the tests

---

yt/fields/fluid_fields.py
yt/fields/vector_operations.py
yt/frontends/athena/io.py
yt/frontends/chombo/io.py
yt/frontends/enzo/data_structures.py
yt/geometry/coordinates/coordinate_handler.py
yt/geometry/grid_geometry_handler.py
yt/utilities/io_handler.py
yt/utilities/math_utils.py
yt/utilities/nodal_data_utils.py
yt/utilities/parallel_tools/io_runner.py

This makes the unit tests run without any new warnings under numpy 1.15rc1 (which you can install from pip right now with `pip install -U --pre numpy`.
The main issue is the deprecation of non-tuple sequences as array indices. See https://github.com/numpy/numpy/pull/9686 for details. There was also one place where we used `Int64` instead of `int64` and NumPy has now grown slightly more picky about that.

fix usage of behavior deprecated in numpy 1.15

---

yt/data_objects/profiles.py

This fixes #1614.  Rather than intermittently failing, throw an error.

Adding an ill-defined profile error for 0-logs

---

yt/visualization/image_writer.py
yt/visualization/tests/test_image_writer.py
yt/visualization/tests/test_offaxisprojection.py

Adding testcases for `visualization.image_writer`

Adding testcases for visualization.image_writer

---

yt/visualization/profile_plotter.py
yt/visualization/tests/test_particle_plot.py
yt/visualization/tests/test_profile_plots.py

Currently `PhasePlot.set_log` seems to expect string field names. This PR adds a call to _determine_fields to allow accepting tuples as well as field objects. I've added a test as well.

allow PhasePlot.set_log to accept field tuples or objects as well as strings

---

yt/fields/tests/test_fields_plugins.py
yt/funcs.py

According to http://yt-project.org/doc/reference/configuration.html#the-plugin-file if you define a function in `my_plugins.py` then that function should be available in the yt namespace. However, that does not actually work right now.
Since this is a documented behavior and we had a user report that this behavior is broken, rather than modifying the docs to no longer say that this is possible, let's just add the functionality. 
This PR adds variables defined in `my_plugins.py` to the yt namespace if the variable is a function (e.g. `callable(var)` is `True`) and if its name doesn't shadow a name that's already in the yt namespace.
I've added tests for this behavior.

add functions defined in plugins file to yt namespace

---

tests/tests.yaml
yt/frontends/enzo/misc.py
yt/frontends/enzo/tests/test_outputs.py
yt/utilities/physical_ratios.py

Currently there are a number of hard-coded constants in the function that calculates the units for enzo cosmological data. I've gone ahead and replaced these hardcoded constants with calculations, which I've verified agree with what's there and what's in the Enzo source code.
This may cause some of the answer tests to fail since I'm changing the units for cosmology data slightly.
The goal here is to make our conversion from cosmology units to physical units as close as possible to what Enzo actually uses internally while at the same time making yt's source code easier to read.

directly calculate constants in enzo's cosmology units

---

yt/testing.py

This will fix the issues @MatthewTurk ran into in #1858 
@git-abhishek sorry for missing this in the initial code review. In general it's an antipattern in python to make the default value of a keyword argument an mutable type like a list or a dict. This is the #1 gotcha in this listing of python gotchas: http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments

fix issues with fake_octree_ds having hidden state

---

yt/visualization/tests/test_plotwindow.py

It is sufficient to test the plots for only `.png` format and not all the formats like `.eps`, `.pdf`, `.ps`.
Saving plot for other file formats increases disk I/O and leads to more runtime at Travis.

Keep only png format while doing plot.save() in visualization module

---

doc/source/yt4differences.rst
yt/data_objects/construction_data_containers.py
yt/frontends/sph/data_structures.py
yt/geometry/coordinates/cartesian_coordinates.py
yt/utilities/lib/pixelization_routines.pyx

Fixed normalization of some pixelization routines with the addition of two utility functions to normalize
The plots with the fix:
The plots without the fix:
NOTE: These fixes may break the tests, I'm not 100% sure.
- **NA** New features are documented, with docstrings and narrative docs
- **NA** Adds a test for any bugs fixed. Adds tests for new features.

yt-4.0 normalization fix

---

MANIFEST.in

Commit a271399f12da6a887d61aa9e5780209f0005f28d removed the static files required for the mapserver (to use online ones). This PR removes leftover paths listed in MANIFEST.in that point to non-existing file in the trunk.

Fixing removed files from manifest

---

yt/frontends/ramses/io.py
yt/frontends/ramses/tests/test_outputs.py

This fixes #1847.
Before the PR, we were looping on chunks one time per field type. However, since chunks is a generator, the second time, it would yield 0 chunk, resulting in an error.

[Bugfix] Dont loop twice over generator object

---

yt/frontends/boxlib/data_structures.py

This change affects the WarpX frontend. It will now use the particle species names stored in the plot file, rather than expected them to always be called `particle0`, `particle1`, etc...

Infer species names from the plot file, rather than hard-coding them.

---

yt/frontends/enzo/data_structures.py

This was originally reported to me by Paola Dominguez and Stefan Hackstein - I don't know their github handles so I'll e-mail them a link to this PR.
Take a look at this script:
```python
import yt
from matplotlib import pyplot as plt
ts = yt.load('gas_plus_dm_pancake/DD????/data????')
Bs, a_s = [], []
for ds in ts:
B1 = ds.index.grids[0]['magnetic_field_strength']
a = ds.scale_factor
Bs.append(B1.mean()*a**2)
a_s.append(a)
plt.loglog(a_s, Bs)
plt.ylim(1e-7, 1e-5)
plt.savefig('test.png')
```
That script uses this dataset: http://use.yt/upload/7844e216
Currently this script produces this image: https://i.imgur.com/flO8YZb.png (not a horizontal line)
With this PR it produces this image: https://i.imgur.com/D1EMcan.png (a horizontal line)
The script is sampling a grid that does not get …

use a different approach for calculating enzo magnetic units

---

scripts/iyt

This brings back the completion for the command `iyt` and adds new completion for tuple-based arguments. 
The following lines are now giving suggestions:
```ipython
> ds = yt.load('output_00080/info_00080.txt')
> ad = ds.all_data()
> ad['<TAB>
all deposit gas gravity index io ramses
> ds.r['g<TAB>
gas
> ds.r['gas', 't<TAB>
temperature tangential_over_velocity_magnitude tangential_velocity
```

[Improvement] ipython completion

---

yt/data_objects/selection_data_containers.py
yt/data_objects/tests/test_extract_regions.py
yt/geometry/selection_routines.pyx
yt/utilities/on_demand_imports.py

The selection method used to find particles in a "cut region" was using a brute force algorithm that was scaling as `npart * ncell`. For larger simulations, this would become the bottleneck. This PR improves the previous version using a tree-based algorithm.
The positions of the cells are stored in a KD-tree. Then for all the particles in the parent container, we look at the closest cell in the tree. There is then a selection step where we loop on all the neighbouring cells to check whether each particle is within the candidate cell.
Note: we should also think about how many neighbors we should query in general so that we are sure to find the cell containing the particle. This may require building a more complex distance function in units of the local dx, but I don't know how to do that …

[feature] Faster cut region query

---

yt/visualization/volume_rendering/off_axis_projection.py

Currently, when one attempts to specify a `north_vector` in an `off_axis_projection`, the code fails since it tries to access the `east_vector`, which hasn't yet been defined.  This addresses that and specifies the correct `east_vector`.

Fixes bug in Off Axis Projections in yt-4.0 [bugfix]

---

nose.cfg

This lets us more easily see what tests are running on travis. We've recently been seeing random test failures (probably due to using too much memory somewhere or a new memory leak) and I want to know what test it's dying on.

set verbosity to 2 in nose config

---

yt/frontends/boxlib/data_structures.py

Fixes `IndexError: list index out of range` while executing following script in windows:
```python
import yt
from yt.utilities.answer_testing.framework import data_dir_load
raw_fields = "Laser/plt00015"
ds = data_dir_load(raw_fields)
```
[Full error log](http://paste.yt-project.org/show/43/)

In boxlib/data_structures split using os.sep

---

doc/source/visualizing/callbacks.rst
yt/visualization/plot_modifications.py
yt/visualization/tests/test_callbacks.py

Adds a feature to the StreamlineCallback that suppresses streamline segments where the color field fails to meet a given threshold. Also added a test for the callback.
**Note:** It is doubtful that the test ran properly - I may be having issues with my nose installation. If someone could make certain that the test executes and passes that would be appreciated.
The feature was discussed in issue #1921.

Adds display_threshold option to StreamlineCallback

---

yt/utilities/lib/pixelization_routines.pyx
yt/visualization/volume_rendering/tests/test_off_axis_SPH.py

This fixes the issues @chummels described in #1902. The angular momentum vector was correct, but the rotation performed by the off-axis projection machinery was calculating the rotation matrix necessary to rotate the z-axis to the specified normal vector. However, what we wanted was the rotation matrix that does the inverse operation: rotating the the specified normal vector to the z-axis. The fix was just to add a call to `np.lingalg.inv` on the return statement for `get_rotation_matrix`. There are a couple other minor formatting changes, I also updated the tests which had encoded the incorrect answer before.

 use inverse matrix to do rotations for SPH off-axis projections 

---

yt/data_objects/derived_quantities.py

This adds the ability to specify a particle_type for the derived quantity for determining the angular momentum vector for a data object.  Currently yt will only calculate the angular momentum vector for all particles, not allow a user to specify *just* the gas, or *just* the DM particles.  This adds that functionality.  Examples in docstrings.

Adds ability to specify particle_type in angular momentum derived quantity

---

.travis.yml

I don't see any memory issues when I run the tests locally on a linux box. Since I'm still not sure what the problem is let's try papering it over by using the `sudo: required` hosts on travis which have more RAM.

use sudo infra on travis to get more RAM

---

.codecov.yml
tests/nose_runner.py

Generating coverage report at Jenkins and uploading it to yt's [codecov](https://codecov.io/gh/yt-project/yt).
- Due to `Coverage`, the runtime at Jenkins has increased which can be seen in [`py3` Jenkins run](https://tests.yt-project.org/job/yt_py3_git/375/console) where we exit due to reaching the timeout mark (90 mins). Either we have to increase the execution limit or disable `Coverage` at Jenkins (reject this PR).  
- The `subprocess` call with `codecov` command in the PR is just to check if uploading to yt's codecov works or not. If this PR is accepted, I need to update the PR by removing this call and adding this step in the Jenkins configuration file.

[Experiment] coverage report from jenkins

---

.travis.yml

As pointed out by @colinmarc we probably don't want to specify dist at all and definitely don't want 12.04.

don't specify dist in travis config

---

yt/utilities/answer_testing/framework.py

For an answer testing test, if we specify `prefix` then it should be compared against the data file in `prefix` directory of  `answer-store`.  However, it is not the case currently.
With this fix, all the answer tests could be executed with just one `nosetests` command.
For example, with the following command all the tests having the decorator `@attr("answer_test")` could be executed (all these tests are of type answer test).
```
nosetests --attr "answer_test" --with-answer-testing --nologcapture -d -v --local --local-dir=answer-store yt
```
Without this fix, we have to pass one more parameter 
`--answer-name="name_of_the_answer_file_in_answer_store"` and execute each of the answer tests one by one.

Fix implementation of AnswerTestingTest.prefix

---

yt/frontends/_skeleton/data_structures.py

There's no need to pass self to the superclass if you're using `super`. This avoids weird issues when setting up a new frontend.

fix uses of super in skeleton frontend

---

yt/utilities/lib/pixelization_routines.pyx
yt/visualization/volume_rendering/off_axis_projection.py
yt/visualization/volume_rendering/tests/test_off_axis_SPH.py

This implements the `north_vector` keyword for `off_axis_projection` and `OffAxisProjectionPlot` within the demeshening.  Had to apply a second rotation to the data to rotate the north-vector to the +y direction but now it works.  This closes issue #1907 .
As a demonstration, this script gives the following results showing that on-axis and off-axis projections are identical when using the appropriate axes:
```
import yt
fn = 'GadgetDiskGalaxy/snapshot_200.hdf5'
ds = yt.load(fn)
_, c = ds.find_max('density')
x = ds.arr([1,0,0], 'unitary')
y = ds.arr([0,1,0], 'unitary')
z = ds.arr([0,0,1], 'unitary')
yt.ProjectionPlot(ds, 'x', ('gas', 'density'), center=c, width=(200, 'kpc')).save('OnAxis_x.png')
yt.ProjectionPlot(ds, 'y', ('gas', 'density'), center=c, width=(200, …
```

[bugfix] Making north vector work with SPH off axis projections; fixes #1907

---

yt/utilities/answer_testing/framework.py
yt/utilities/exceptions.py

Please check #1905 
The earlier merged PR yt-project/yt#1905 had a bug identified while writing a new answer test to be run on Travis. This PR corrects that implementation.
With this fix, answer name could be specified in the answer test case
itself. As a  result, all the answer tests could be executed by just one
nosetests command. Earlier, this was not possible and one nose command
had to be run per answer test as --answer-name had to be specified for
each answer test.
In addition, prepend py-version before AnswerTestingTest.answer_name,
to avoid conflict in answer-store images
@brittonsmith @jwise77 @bwoshea

Fix answer testing plugin

---

setup.py

This change should get github statistics on our [project page](https://pypi.org/project/yt/) on pypi and still keep the other URLs.

Adding URLs to setup.py

---

yt/frontends/boxlib/data_structures.py

The Nyx frontend was using the presence of a `DM` subdirectory to determine whether particles exist or not. Apparently, this always gets created in Nyx, whether or not there are any particles present. However, the file `DM/Header` should only exist if particles are actually in the run.

Fix Issue #1948

---

tests/report_failed_answers.py

Use set() instead of list for `missing_answers` and `failed_answers`, since same anwer test could have iterations.
eg:
```python
for lens_type in ['plane-parallel', 'perspective']:
frame = 0
cam = sc.add_camera(ds, lens_type=lens_type)
cam.resolution = (1000, 1000)
cam.position = ds.arr(np.array([-4., 0., 0.]), 'code_length')
cam.switch_orientation(normal_vector=[1., 0., 0.],
north_vector=[0., 0., 1.])
cam.set_width(ds.domain_width*2.)
test1_prefix = '%s_%04d' % (lens_type, frame)
test1 = VRImageComparisonTest(sc, ds, test1_prefix, decimals)
test1.prefix = test1_prefix
test1.answer_name = test_name
yield test1
```
In this if no answer is present in the answer store, we will get 2 error messages but we only want it once.

Use set() instead of list, since same ans test could have iterations

---

yt/visualization/volume_rendering/off_axis_projection.py

Issue #1906 demonstrates how OffAxisProjections in demeshening project with weird units.  This PR fixes that issue by assuring that the path length unit is in the default length units for that dataset.  
This script demonstrates this solution (note how the zlims and units are the same for each on-axis/off-axis pair now):
```
import yt
ds = yt.load('FIRE_M12i_ref11/snapshot_600.hdf5')
yt.ProjectionPlot(ds, 'z', ('gas', 'density')).save('on.png')
yt.ProjectionPlot(ds, 'z', ('gas', 'temperature'), weight_field=('gas', 'density')).save('on_temp.png')
yt.OffAxisProjectionPlot(ds, [0,0,1], ('gas', 'density'), north_vector=[0,1,0]).save('off.png')
yt.OffAxisProjectionPlot(ds, [0,0,1], ('gas', 'temperature'), weight_field=('gas', 'density'), north_vector=[0,1,0]).save('off_temp.png')
```
On Axis …

[bugfix] Fixes OAP unit mismatch issue in OAPs. Fixes #1906

---

yt/visualization/base_plot_types.py
yt/visualization/tests/test_plotwindow.py

If you load a dataset that contains NaNs and make a plot through a field that contains NaNs and has values less than zero, you will get an error generated by matplotlib. The cause is us passing NaNs to matplotlib in our plotting code. The fix is to use `np.nanmin` and `np.nanmax` instead of `array.min` and `array.max` when setting up colorbars inside yt.
I've added a test that fails on the current master branch but passes with this PR.

Fix issues plotting data containing NaN

---

yt/visualization/tests/test_callbacks.py

This fixes the test for the contour callback when running the yt test suite with matplotlib 3.0.0 rc1. This was not noticed until now because before https://github.com/matplotlib/matplotlib/pull/10545 matplotlib did not complain about unprocessed keyword arguments. Not it does complain so we need to be more careful. As a bonus this test is now testing what it said it was testing.

fix name of text size keyword in contour callback test

---

yt/visualization/plot_modifications.py

I had a `SlicePlot` where I set the `center` and `width` arguments by hand with a specific unit, and then tried to set the `width` parameter in `annotate_particles` using `code_length`:
```python
slc = yt.SlicePlot(ds, "x", ['density'], width=(1.5, "Mpc"),
center=ds.arr([0.0, 0.0, 0.2], "Mpc"), origin='native')
slc.annotate_particles(3.0856e24, col='k', stride=100)
```
Two things happened here which prevented me from seeing the particles:
1. `annotate_particles` now assumes that the thing you pass in has units, either as a `YTQuantity` or as a `(value, unit)` tuple, so this fixes it so if you pass in a float it assumes `code_length`. 
2. If one mixes different types of length units in the current code, you end up somewhere down the line with combining `YTQuantity` instances in a list and …

[bugfix] Make sure that units are respected properly for particle annotations

---

yt/frontends/stream/data_structures.py

This makes the example render more nicely on sphinx. Here's what it looks like right now:
http://yt-project.org/doc/reference/api/yt.frontends.stream.data_structures.html?highlight=load_uniform_grid#yt.frontends.stream.data_structures.load_uniform_grid
I also deleted the last bit of the example because it wasn't really doing anything that meaningfully improved understanding of how to use the function (at least in my opinion).

fix formatting of example for load_uniform_grid

---

yt/frontends/boxlib/data_structures.py

This change is needed to properly read WarpX datasets that don't have particles.

[Bugfix] WarpX datasets with no particles

---

yt/frontends/gadget/io.py

There is an upstream bug with [h5py](https://github.com/h5py/h5py/issues/28) which means that when a file is opened with read/write (the default mode) the last modified time gets changed for the file, even if no modification is made.
This modification changes our file hash, so we regenerate kdtrees and octrees needlessly. This PR adds the `"r"` mode tag to force h5py to open in read-only.
```python
In [1]: import h5py
In [2]: import os
In [3]: os.path.getmtime('test.hdf5')
Out[3]: 1534969719.6641185
In [4]: f = h5py.File("test.hdf5")
In [5]: f.close()
In [6]: os.path.getmtime("test.hdf5")
Out[6]: 1534969745.043913
```

[bugfix] add read-only tag to h5py file load to prevent false modifying time

---

yt/data_objects/construction_data_containers.py
yt/geometry/coordinates/cartesian_coordinates.py

In the spring I was experimenting with doing particle projections using the kdtree. This didn't get much further than some experiments but I did make it so that the kdtree gets unconditionally generated. This is unnecessary and causes scaling issues for large datasets, so let's not do that.
Fixes #1973.

don't generate the kdtree for particle projections

---

yt/geometry/particle_oct_container.pyx
yt/utilities/lib/geometry_utils.pxd

This fixes the issues @AshKelly ran into with the test SWIFT dataset in #1962.
Ultimately the issue was due to going between float coordinates and int coordinates. The fix is just to avoid those conversions and calculate the int coordinates as we recurse.
In addition we converted some pointer arrays to memoryviews, that makes it easier to debug this code when it breaks.

 avoid float precision issues leading to overflow in bitmap index 

---

yt/visualization/volume_rendering/off_axis_projection.py

Fixes #1986.
This ensures we are referring to the same `smoothing_length` field we used to generate the projection above.

[yt-4.0] use an explicit field type to get the smoothing length unit

---

yt/geometry/particle_geometry_handler.py

I've been having problems on Caltech's cluster where yt fails when trying to access some particle-based datasets, because it tries to write the bitmask (.ewah) file when it thinks permissions are writable but they are not.  I don't know why os.access mis-reports this information, but it does.  This just avoids the failure if it cannot actually write the .ewah file.

[bugfix] Make extra check before writing bitmasks to avoid crash

---

.travis.yml
yt/data_objects/data_containers.py
yt/data_objects/profiles.py
yt/data_objects/tests/test_glue.py
yt/visualization/fits_image.py

The glue internal API changed, this adds a fix that avoids the `ImportError` that currently gets generated with the latest version of glue.
Since glue is a QT gui app, it's not straightforward to directly test this. Instead we're using the dummy base glue application class within testing to mock the full GUI app. This isn't perfect and we may want to rethink this if/when integration gets more extensive but this should allow us to detect breakage like changed internal imports in glue.

fix to_glue method, add test

---

yt/geometry/grid_geometry_handler.py

This is an alternative implementation of the bugfix PR #1912.
After @MatthewTurk's comment, I've implemented a fix that does not remove grids where the `filename` is None and instead allows them to be sorted and potentially operated on. This may be safer than what I did in PR #1912. Only one of these two should be accepted.

[bugfix] Alternate fix for PR #1912

---

yt/data_objects/data_containers.py
yt/data_objects/tests/test_data_containers.py

This PR add the possibility to create a new fields defined for a filtered particle type without the need to define it for its parent particle type. For example if you have a particle type `io` and a derived particle type that selects only the massive particles called `massive`, you can define for the latter only.
```python
import yt
ds = yt.load('ramses_new_format/output_00002/info_00002.txt')
def fun(field, data):
print(field)
return data[field.name[0], 'particle_mass']
ds.add_field(('star', 'mass'), function=fun, sampling_type='particle', units='g')
print('Accessing fields')
print(ds.r['star', 'mass'].shape)
print(ds.r['star', 'particle_mass'].shape)
```
This now prints
```
Accessing fields
Derived Field (star, mass): (units: g, particle field)
Derived Field (star, mass): (units: g, …
```

Improve derive fields

---

yt/units/yt_array.py

This backports an implementation of `__format__` from `unyt_array`. This makes it possible to do this:
```
>>> '{:.3f}'.format((km/3))
'0.333 km'
```
Without this PR you'd get:
```
>>> '{:.3f}'.format((km/3))
'0.333'
```

define __format__ on YTArray

---

yt/data_objects/derived_quantities.py

To find the location of the max of a field in the `SampleAtMaxFieldValues` class, we fill an array with `-HUGE` values and then fill this array with real data from chunks. If a chunk happens to have no values of the particular field, then the `-HUGE` values stay, which is fine because we are trying to find the maximum.
The problem is that `SampleAtMinFieldValues` inherits from this class but only changes the function from `argmax` to `argmin` without recognizing that the sign of the value that serves as the limit also needs to change for the operation to work correctly in case a chunk has no data.
In yt-4.0 this was manifesting itself in a weird way--trying to find the minimum potential of star particles from a Gadget simulation was giving the wrong answer because some chunks didn't have …

[bugfix] min/max location must use different signs for "huge" values

---

yt/data_objects/data_containers.py
yt/data_objects/particle_filters.py
yt/data_objects/tests/test_data_containers.py
yt/fields/derived_field.py

c497c942976465bcb88c99f29cca4f2485622992 in #1993 introduced a new bug (and solved another one!).
The bug appears for filtered particles, when a field inherited from the parent particle type is itself a derived field. Let `N` and `M` be the number of parent particles and filtered respectively.
Before #1993, yt would receive an array of length `N`. It would then try to apply a mask (that selects the filtered particles) of size `N` with `M` true values, so that the output is of shape `M`. In some cases it would not crash but would return an array with the wrong shape.
#1993 shortcircuits the field generation machinery so that yt would directly receive an array of size `M`, would still try to mask it with an array of size `M` and would crash.
This PR fixes this by adding a new `inherited` …

[bugfix] Particle filters

---

doc/source/visualizing/callbacks.rst
yt/visualization/plot_modifications.py

The width was off by a factor of two for the `annotate_halos` callback. For example, [this script](http://paste.yt-project.org/show/52/)
```
import yt
from yt.analysis_modules.halo_analysis.api import HaloCatalog
dds = yt.load("Enzo_64/DD0043/data0043")
hds = yt.load("rockstar_halos/halos_0.0.bin")
region = dds.box(dds.domain_center - 0.25*dds.domain_width,
dds.domain_center + 0.25*dds.domain_width)
hc = HaloCatalog(data_ds=dds, halos_ds=hds)
p = yt.ProjectionPlot(dds, "x", "density", weight_field="density",
data_source=dregion, width=0.5)
width = hds.quan(0.5*dds.domain_width[0])
p.annotate_halos(hc, width=(0.5, "code_length"))
p.save()
```
will give the following image:
https://i.imgur.com/t59d2Mw.png
After this fix, it gives:
https://i.imgur.com/Zzpylwj.png
In addition, I've made it so …

[bugfix, enhancement] Fix width in annotate_halos callback

---

yt/frontends/art/fields.py

TRIDENT requires fields named `O_nuclei_mass_density, C_nuclei_mass_density, Fe_nuclei_mass_density`, etc in order to use specific atoms in it's density calculations. If they are missing, then it uses an overall "metallicity" field and assumes solar abundance. 
Since ART tracks type Ia and type II SNe separately, and they have very different abundances, it would be more accurate to insert atom fields at this stage using that information, so that TRIDENT doesn't have to assume this.
This PR adds those fields to the setup_fluid_fields method.

create individual particle fields using SNIa and SNII metallicities 

---

doc/source/analyzing/objects.rst
yt/data_objects/derived_quantities.py
yt/data_objects/tests/test_derived_quantities.py
yt/utilities/exceptions.py

This pull request adds an option argument called "p_type" to a variety of derived quantities, such as center_of_mass and similar, which allows that derived quantity to be calculated for a given particle type only. 
This is a new feature that will aid in data analysis, allowing for example the spin paramter of stars or the centre of mass of DM to be calculated easily and quickly.
The default behaviour of all derived quantities has not been changed, as p_type defaults to "all". 
PS: Sorry, I also removed a bunch of trailing whitespaces which makes the pull request look messier than it actually is.

Derived quantity particles

---

yt/visualization/fixed_resolution.py

Resolves #1971.
With the same code, now we get the following image:
instead of the previous:

Support periodic BC in ParticleProjectionPlot

---

yt/frontends/gadget_fof/io.py

When there are fewer halos/subhalos than files, some files are empty of certain fields and we get an error trying to read.

[bugfix] Don't try to read data if particle count is zero.

---

yt/frontends/exodus_ii/io.py
yt/frontends/stream/io.py
yt/visualization/tests/test_mesh_slices.py

closes #1916 
This makes it so that data object accesses on unstructured mesh data return data with the correct shape (i.e. not equal to the shape of the total number of mesh elements in the dataset).
As far as I can tell, this was not a problem until now because the unstructured mesh pixelizer uses `ds.all_data()` to generate the data it needs to feed to the pixelizer. I think with this change in principle we could use a slice data object there.
Do I need to touch other places? I'm not sure. Maybe the PYNE/MOAB frontend? @munkm this might impact your Denuvo frontend.

add masked I/O to unstructured mesh frontends

---

yt/visualization/plot_modifications.py

This resolves yt-project/yt#1896. 
If `color` is included in the `plot_args` dictionary it is now changed to `colors`  and the behavior in `annotate_clumps()` is consistent with other annotate_ functions. Previously, passing `color` did nothing if passed as as a plot argument through `annotate_clumps()`.

allow for 'color' kwarg to be passed as a plot argument in annotate_clumps

---

yt/visualization/volume_rendering/lens.py

With this patch applied the script in the issue produces this:
The rendering with the perspective lens was actually correct, it just didn't look right from the angle used in the issue description. If you zoom out it's pretty clearly correct.

fix x/y mixup in plane parallel projection function. Fixes #1753

---

yt/data_objects/level_sets/tests/test_clump_finding.py

This is code from two years ago and I have no idea why we're only noticing this now, but, currently this test fails with the following error:
```
======================================================================
ERROR: yt.data_objects.level_sets.tests.test_clump_finding.test_clump_tree_save
----------------------------------------------------------------------
File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
diff --git a/yt/data_objects/level_sets/tests/test_clump_finding.py b/yt/data_objects/level_sets/tests/test_clump_finding.py
index e674ead02..640fe3e72 100644
self.test(*self.arg)
File "/Users/goldbaum/Documents/yt-git-fixes/yt/data_objects/level_sets/tests/test_clump_finding.py", line 134, in test_clump_tree_save …
```

fix attribute error in clump finding tests

---

yt/frontends/gadget/data_structures.py
yt/frontends/gadget/io.py
yt/frontends/gadget/testing.py
yt/frontends/gadget/tests/test_outputs.py

Currently, Gadget frontend assumes a fixed header size of 256, which is the standard value. But since header spec is already configurable, it would be more self-consistent to calculate header size from header spec instead, thus allowing for non-standard headers.
Resolves #1846.

[Gadget frontend] Calculate header size from header spec to allow for non-standard headers

---

yt/fields/fluid_fields.py

With the way the metallicity field is currently defined, changing the value of the solar metallicity changes the metallicity field in absolute (i.e., dimensionless units) rather that in units of `Zsun`. for example, the following script:
```
import yt
ds = yt.load("DD0046/DD0046")
print (ds.r['metallicity'].to(""))
del ds
ds = yt.load("DD0046/DD0046")
ds.unit_registry.modify('Zsun', 0.0204)
print (ds.r['metallicity'].to(""))
```
gives:
```
[9.83077184e-11 9.99523614e-11 1.00078951e-10 ... 7.38725398e-11
8.22170876e-11 8.92656217e-11] dimensionless
[1.54863124e-10 1.57453913e-10 1.57653328e-10 ... 1.16370642e-10
1.29515721e-10 1.40619203e-10] dimensionless
```
This is incorrect, as the dimensionless value is simply `metal_density / density` and should not change when the units change. …

[bugfix] Don't apply units to metallicity field.

---

yt/fields/tests/test_xray_fields.py

Unless I'm missing something, `FieldValue` test is independent of `axis`

Run xray fields value test only once for each object/field

---

yt/data_objects/profiles.py
yt/data_objects/tests/test_profiles.py
yt/utilities/exceptions.py

This fixes Issue #1609. We check that bin fields and profile fields are all of the correct shape. I also changed all instances of `filter` to `pfilter` since `filter` is a reserved word. Tests added as well.

Raise exception for profile fields of unequal shape.

---

doc/source/examining/loading_data.rst
yt/frontends/ahf/data_structures.py
yt/frontends/ahf/io.py
yt/frontends/gadget_fof/data_structures.py
yt/frontends/gadget_fof/io.py
yt/frontends/halo_catalog/data_structures.py
yt/frontends/halo_catalog/io.py
yt/frontends/halo_catalog/tests/test_outputs.py
yt/frontends/rockstar/data_structures.py
yt/frontends/rockstar/io.py
yt/testing.py

In this frontend, and likely others, particles on domain boundaries were being lost because the code to bump them in from the edges only existed in `_initialize_index` and none of the other functions in the io handler that read particles. This fixes that by implementing a class method on the data file for reading particle positions and doing the correction there rather than have three copies of the same code.
In addition, I implemented this with a cache since particle positions need to be read in for every field read. For the rather large dataset I was testing, this reduced the load time for a field from ~3.5s to ~0.5s (after the positions had been read in once). Of course, this will increase the steady-state memory use, but I think it's probably worth it (although I'm open to other …

[bugfix] catch particles on domain edges for Gadget_FOF data

---

README.md
doc/source/installing.rst
doc/source/visualizing/interactive_data_visualization.rst
doc/source/visualizing/unstructured_mesh_rendering.rst

Resolves #1718.
For the packages no longer hosted on `use.yt/with_conda`, I removed the references to installing from `use.yt/with_conda` in documents.
For the nightly builds, I've set up a new [repository](https://github.com/yt-project/conda-dev) for it.

Migrate from use.yt/with_conda

---

doc/source/examining/loading_data.rst
yt/frontends/gizmo/fields.py
yt/frontends/gizmo/tests/test_outputs.py

This PR aims to improve GIZMO frontend's field system. The following are done:
- The field list is cleaned up according to the GIZMO User Manual.
- New derived fields are added:
- Star creation time: `("PartType4", "creation_time")`
- Star age: `("PartType4", "creation_time")`
While I'm at it, if you have any suggestions about GIZMO fields, I'm willing to add them to this PR.

Improve GIZMO fields

---

yt/visualization/base_plot_types.py
yt/visualization/plot_container.py
yt/visualization/plot_window.py
yt/visualization/profile_plotter.py
yt/visualization/tests/test_plotwindow.py

This sets the axis background color to always be set by yt, defaulting to matplotlib's default (white with 100% alpha). When a user customizes it rather than actually manipulating the axis background color then, we store that color as metadata in a private dictionary. Then, when we create the plot, we set the color on the axes for the plot while we initialize it.

store axes background as plot metadata and set in setup_plots. Closes #2016

---

doc/source/analyzing/analysis_modules/clump_finding.rst
doc/source/cookbook/find_clumps.py
yt/analysis_modules/level_sets/api.py
yt/data_objects/level_sets/api.py
yt/data_objects/level_sets/clump_handling.py

This fixes the issue reported by @stonnes on the mailing list where a clump finding operation would sometimes end with:
```
TypeError: 'NoneType' object is not iterable
```
In doing this, I found the practice of initializing `Clump.children` to None to result in overly cumbersome if statements, so I changed the default to be an empty list. I have also deprecated the `get_lowest_clumps` function in favor of a `Clump.leaves` property. Finally, I removed two functions that have been deprecated for more than few stable releases now.

minor clump refactor

---

yt/utilities/lib/bitarray.pxd
yt/utilities/lib/bitarray.pyx
yt/utilities/lib/tests/test_bitarray.py

This fixes some logic in the (uncompressed) bitarray module.  This is distinct from the EWAH module in that it doesn't make any effort to compress the arrays and it makes it easy to convert them to and from numpy arrays.  One of the downsides is that right now it's hardcoded to be 8-bit arrays to minimize waste, which also maximizes overhead of doing logical ops.
In the past, there were two major issues -- the first being the `val` was used, which broke things like casting to 0 or 1, and we also were incorrectly turning off bits.  This fixes both, and adds tests for them.
I'm cherry picking this from some grid visitors work to simplify that ultimate pull request.

Fixing logic in bitarray module

---

yt/data_objects/static_output.py
yt/frontends/ytdata/utilities.py
yt/units/unit_registry.py
yt/units/unit_systems.py

During the creation of a `Dataset` instance it is assigned a `UnitSystem`, which the end-user can specify. Upon importing `yt` a number of `UnitSystem` instances are automatically created, such as "cgs", "mks", "galactic", etc. One of these is specified to `yt.load` (or the default) and it is assigned as the `Dataset`'s unit system. 
If done in this way, the `UnitSystem` does not have the correct `UnitRegistry` object. This PR fixes that problem by enforcing that a new `UnitSystem` instance is created which is associated with the `Dataset`'s `UnitRegistry`.  
I'm not thrilled about this solution, but the other solutions I came up with were messier than this, and I thought doing a `deepcopy` or something similar of the original `UnitSystem` instance and simply fixing the registry was a bad …

[bugfix] A Dataset's UnitSystem should have its UnitRegistry

---

yt/analysis_modules/cosmological_observation/light_cone/light_cone_projection.py
yt/data_objects/data_containers.py
yt/data_objects/profiles.py
yt/data_objects/static_output.py
yt/data_objects/tests/test_profiles.py
yt/data_objects/tests/test_projection.py
yt/fields/field_info_container.py
yt/geometry/coordinates/cartesian_coordinates.py
yt/geometry/selection_routines.pyx
yt/geometry/tests/test_particle_octree.py

Closes #1849.
Merging #1799 caused the breakage Matt ran into in #1849. It turns out that `('gas', 'cell_volume')` has `units='code_length**3'` but `output_units='cm**3'`, so it turns out I wasn't correct that only particle fields use `output_units`.
The fix (I think) is to make `units` and `output_units` the same for the fluid index aliases created in the function this PR modifies.
I'm not sure if this will pass the tests so I am opening this PR to get the full test suite run against this change.

Don't override the units for fluid index aliases

---

yt/data_objects/data_containers.py

Octree data has a little bit more indirection in how it stores data than the grid frontends. To catch this extra bit of cached data I needed to add a more logic to the `_chunked_read` context manager so that old cached I/O results don't pollute future field accesses.

avoid using cached field data in chunked reads. fixes #1874

---

yt/visualization/plot_window.py

The docstring was missing. It is now documented that the argument of this method is a boolean.

Add docstring to PlotWindow.set_antialias()

---

doc/source/visualizing/plots.rst
yt/visualization/particle_plots.py

This closes Issue #1608. I've added examples of using fields and weight fields so show the difference between the two and expanded the docstrings a bit.

Expand documentation of fields and weight_fields in particle plots

---

doc/source/reference/api/api.rst
doc/source/visualizing/callbacks.rst
yt/data_objects/level_sets/clump_handling.py
yt/data_objects/level_sets/tests/test_clump_finding.py

Currently the clump `info` attribute is only populated by `clump.save_as_dataset`. This PR makes it so that information is calculated for all clump objects when the clump is initially created.
@brittonsmith I'd very much appreciate any insight you might have on whether this will have unintended consequences elsewhere.

ensure clump info is calculated when clumps are created

---

doc/source/analyzing/analysis_modules/clump_finding.rst

As pointed out on the mailing list, the documentation doesn't spell out how to access the clump info. This adds a short example illustrating what to do.

mention how to access clump info

---

yt/geometry/selection_routines.pyx

Thanks to @centipete for the original report.
The issue was that the default slice coordinate (0, the middle of the domain) happens to fall exactly at a grid boundary. This was triggering pathological behavior in the slice selector which led to an out of bounds access. The fix here was to clip the integer coordinates calculated by the slice selector to prevent out of bounds access. This clipping should only be an issue for slices exactly at grid boundaries, since otherwise we would be dealing with a different grid where there is some overlap.

clip slice integer coordinates to avoid seg fault in slice selector

---

yt/frontends/flash/io.py
yt/frontends/gadget/io.py
yt/frontends/gadget_fof/io.py
yt/frontends/halo_catalog/io.py
yt/frontends/http_stream/io.py
yt/frontends/owls_subfind/io.py
yt/frontends/rockstar/io.py
yt/frontends/sdf/io.py
yt/frontends/stream/io.py
yt/frontends/tipsy/io.py
yt/frontends/ytdata/io.py

Added an extra keyword to the datafiles sort, so they don't just use the filename, but also use the start particle as well - this should fix subfiles loading in a random order.
fixes #2059 
- **NA** New features are documented, with docstrings and narrative docs
- **NA** Adds a test for any bugs fixed. Adds tests for new features.

[bugfix] yt-4.0 random order particle loading fix

---

yt/fields/particle_fields.py

Currently fields like "particle_angular_momentum" end up going through one of these code paths and triggering deprecation warnings. Let's use the new names for these fields internally. The deprecated field names are still available for use with this change, we just don't use them as dependencies for other fields in the yt field system anymore.

avoid use of deprecated field names internally

---

yt/frontends/ytdata/api.py

This makes it possible to do something like `nosetests yt.frontends.ytdata.tests.test_outputs:test_plot_data` to only run one of the tests in the ytdata frontend. Due to the magic we use to avoid exposing the skeleton frontend publicly, this needs to be manually added, see here if you don't know what I'm talking about: https://github.com/yt-project/yt/blob/master/yt/frontends/api.py#L52-L58

add tests to ytdata frontend api

---

.travis.yml

Since github's downtime Sunday and yesterday all of our mac builds have been timing out. I'm not sure why this is happening now and not before this weekend, but one way to speed up the builds is to skip generating the coverage reports which require a lot of disk churning on the very very slow disks that the travis mac builders have.
Hopefully this is a temporary thing and we can turn this back on later.

disable coverage on mac builds for now to avoid timeouts

---

setup.cfg
yt/data_objects/time_series.py
yt/startup_tasks.py
yt/utilities/parallel_tools/parallel_analysis_interface.py

These three flake8 errors were showing up as failures on a few recent
builds, and were all straightforward fixes.

Fixing three flake8 errors

---

doc/source/reference/api/api.rst

While helping a user I noticed that `load_octree` doesn't show up in the API docs. This fixes that omission.

include load_octree in the API docs

---

tests/test_requirements.txt

Those two packages are needed for tests.yt-project.org:
- pyyaml for `test_runner.py`
- mpi4py for some tests/cookbook recipes

Add missing dependencies for Jenkins

---

yt/utilities/answer_testing/framework.py

This should (hopefully) fix occasional answer test failures for image comparison tests that save more than one image to disk. The sorting of the list returned by `glob.glob` is arbitrary, so the ordering of images we get back is also arbitrary.
I wouldn't be surprised if some of the existing answers were sensitive to this ordering.

sort image paths before reading them in image comparison tests

---

.coveragerc
.travis.yml

This updates the travis configuration to use newer base images on Linux and MacOS and fixes a couple issues I noticed while working on #1966.
In particular:
* Use xcode 10.1 as the base image on MacOS. Homebrew only supports the most recent versions of MacOS with binaries and now that xcode7.3 is no longer supported, we have to build a bunch of dependencies from source. On xcode 10.1 we'll get binaries so the builds will be much faster.
* Ensure we're using the correct name for the pip executable in the test environment
* Use a xenial (16.06) base image on linux for faster builds and access to newer packages.

Travis build improvements

---

yt/utilities/lib/line_integral_convolution.pyx

In the regions with zero vector field values, the line integral convolution (LIC) just creates noise. This PR removes these regions from LIC, which is particular useful when the non-cartesian simulation region does not fill the entire plot canvas.

remove noise from line integral convolution in zero-value regions

---

setup.py

In the future cython will be changing the default `language_level` to 3. This may break yt's cython extensions in unpredictable ways. Rather than explicitly trying to deal with that breakage and set `language_level` to 3 right now, let's set it globally to 2. Individual files should be able to override this setting and we will be able to change the `language_level` in a piecemeal fashion going forward.

avoid breakage with future cython release by explicitly setting language_level

---

yt/fields/astro_fields.py

yt has a derived field known as `"mazzotta_weighting"` whose sole function is to provide a weight for projections which approximates temperature maps of galaxy clusters taken by Chandra or XMM-Newton. Reference is Equation 15 of http://adsabs.harvard.edu/abs/2004MNRAS.354...10M.
I was looking at this field again today and noticed that it has the wrong exponent! I introduced it into yt way-back-when, and I've used it quite a bit, but I don't know who else has. In any case, here is the fix.

[bugfix] Fix incorrect weight function for cluster temperatures

---

yt/utilities/lib/ewah_bool_wrap.pyx
yt/utilities/lib/geometry_utils.pxd

This modifies some of the EWAH code to use more cython-like idioms and to reduce some of the lines of code.  It should produce *no* changes, and if it does, that is a bug.  I have not identified changes in my testing.
There are a few other places that we could use Cython idioms for iteration and the like, but I have not yet applied these changes there, as I'm not 100% certain it would improve overall readability (and I want to avoid copy-on-assignment).

Use Cython C++ idioms for EWAH

---

yt/geometry/selection_routines.pyx

We can't use uint8 for access along a dimension with more than 255
cells.

This breaks for dim > 255, so upcast.

---

yt/geometry/particle_deposit.pyx
yt/utilities/exceptions.py

The error was generating a string formatting exception. The fix is to make sure we use a formatted string.

fix error message for low dimensionality data in CIC deposit

---

yt/data_objects/selection_data_containers.py
yt/fields/angular_momentum.py
yt/fields/tests/test_angular_momentum.py
yt/testing.py
yt/utilities/lib/misc_utilities.pyx

Until now, there was a mistake in the computation of angular momentum which was leading to the angular momentum units being messed up.

Correct computation of angular momentum

---

yt/data_objects/construction_data_containers.py
yt/data_objects/tests/test_covering_grid.py

This PR associates the unit registry of the YTArray edge in \_sanitize\_edge with that of the dataset that the arbitrary grid is being constructed for. This is needed because if the user passes non-dataset units for the edge, i.e.
```python
ag = ds.arbitrary_grid(left_edge = [0,0,0] * yt.units.kpc,
right_edge = [1,1,1] * yt.units.kpc,
dims = [32,32,32])
```
then when yt attempts to get the data, there was a UnitParseError. This fixes that error.
[Issue #2087](https://github.com/yt-project/yt/issues/2087)

Associated arbitrary grid edge unit registry with dataset unit registry for issue #2087

---

yt/__init__.py

Somehow this was missed. Let's fix this to avoid further confusion.

fix version number in __init__.py

---

yt/frontends/gadget/io.py
yt/frontends/gadget/tests/test_outputs.py

Some low-level routines (in the test case in the bug report it was the selection machinery) expect raw field data from the low-level I/O routines to be in native byte order. However, here we're reading bigendian data and pass it directly to those low-level routines. This breaks on little endian architectures.
The fix is to ensure the data are in native byte order after we read it in.
Ping @weiguangcui and maybe @MatthewTurk to look this over?

ensure gadget binary field data are in native endianness

---

doc/source/analyzing/generating_processed_data.rst

The documentation was incorrect -- YTRay objects are not ordered.  I fixed the docs.

update the docs to reflect the fact that rays are not ordered.

---

.travis.yml
yt/frontends/gadget/tests/test_outputs.py
yt/visualization/volume_rendering/tests/test_scene.py

I tried to add a test for this but couldn't figure out how to straightforwardly make the python environment we run our tests in read-only to emulate the debian build environment. Rather than wasting a bunch more time trying to get that to work I'll just fix the issues @olebole reported and try to be vigilant going forward.

Run tests in temporary directory. Fixes #2123.

---

doc/source/installing.rst

with `conda` and not `pip`
Installing yt from sources without `pip`, but using `conda develop` was not documented. In particular, since yt is not a pure python project, some building is required and hence a simple `conda develop .` isn't enough. The additional `-b` flag triggers the build.
no code here, just doc...

Add documentation on how to install dev version within anaconda

---

yt/frontends/stream/io.py

This fixes the following `FutureWarning` issued in numpy 1.16:
```
yt/yt/frontends/stream/io.py:175: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
```
This shows up when running halo finders using the yt_astro_analysis `HaloCatalog`, which uses the stream frontend.

[bugfix] fix numpy 1.16 future warning.

---

doc/source/cookbook/extract_fixed_resolution_data.py
yt/frontends/chombo/data_structures.py
yt/frontends/chombo/io.py
yt/frontends/enzo/io.py
yt/frontends/enzo_p/io.py
yt/frontends/gadget_fof/data_structures.py
yt/frontends/gadget_fof/io.py
yt/frontends/gdf/io.py
yt/frontends/halo_catalog/data_structures.py
yt/frontends/open_pmd/data_structures.py
yt/frontends/owls_subfind/io.py
yt/frontends/ytdata/io.py
yt/frontends/ytdata/utilities.py

As of h5py 2.9.0, reading a dataset via `dataset.value` has been deprecated in favor of `dataset[()]`. This updates all `.value` calls to get rid of the deprecation warning. This syntax is supported in h5py 2.8.0, which I believe is what we have listed for the minimum h5py version.

Replace deprecated h5py syntax

---

yt/data_objects/static_output.py
yt/frontends/gadget/data_structures.py
yt/frontends/gadget/io.py

Using some data from @jcoughlin11 , I found that there were some things for binary data that had not been updated in yt-4.0.  This is just a set of two minor fixes for that that bring it in line -- the first is calling the right header validation and the second is to only remove `_sph_ptype` if it's actually used.

Fixing minor issues with some binary-format Gadget

---

yt/frontends/artio/data_structures.py

[Fixes issue 2137](https://github.com/yt-project/yt/issues/2137)
ARTIO datasets with multiple N-body species were not working correctly. This update allows the individual species to be accessed individually, but also creates a particle union to access all N-body species at once. 
I have not added tests for this, as this problems does not happen with the currently available ARTIO datasets.

Added support for multiresolution N-body particles for artio frontend

---

yt/data_objects/static_output.py

This PR update `find_max` and `find_min` so that the coordinates printed out on screen are in code length and consistent with the returned values.

print out position in code_length for find_max and find_min

---

doc/source/analyzing/analysis_modules/cosmology_calculator.rst
tests/test_requirements.txt
yt/data_objects/static_output.py
yt/data_objects/time_series.py
yt/frontends/ahf/data_structures.py
yt/frontends/enzo/data_structures.py
yt/frontends/enzo/simulation_handling.py
yt/frontends/enzo/tests/test_outputs.py
yt/frontends/gadget/data_structures.py
yt/frontends/rockstar/data_structures.py
yt/frontends/tipsy/data_structures.py
yt/utilities/cosmology.py
yt/utilities/on_demand_imports.py
yt/utilities/tests/cosmology_answers.yml
yt/utilities/tests/test_cosmology.py

Update: I've finally come back to this and it should now be in a finished state.
This adds the relativistic component of the energy density of the universe, `omega_radiation`, to the cosmology calculations.  Since there is no analytic solution to the Friedmann equations when `omega_radiation` > 0, we now numerically integrate using the trapezoid rule and then linearly interpolate in log(a) vs. log(t).
To get `z_from_t`, we reverse that table and interpolate. In this case, I also iteratively adjust the bounds of the log(a) table to be outside of the calculated log(a) values. This makes sure the integration is accurate and the ends of the table. This is most important at the high redshift end.
It's also important to note that the previous `z_from_t` and `t_from_z` calculations did not …

[enhancement] Add relativistic component to cosmology calculations

---

tests/test_requirements.txt

see https://github.com/yt-project/yt/network/alert/tests/test_requirements.txt/pyyaml/open
I don't think Britton could have known about this ahead of time...

address github vulnerability warning

---

yt/fields/tests/test_fields_plugins.py
yt/funcs.py

This fixes an issue that @drenniks reported today on slack.
Without this fix, the test I modified fails with the following traceback:
```
======================================================================
ERROR: testCustomField (yt.fields.tests.test_fields_plugins.TestPluginFile)
----------------------------------------------------------------------
File "/Users/goldbaum/Documents/yt-git-fixes/yt/fields/tests/test_fields_plugins.py", line 77, in testCustomField
assert yt.myfunc() == 12
File "/Users/goldbaum/.config/yt/my_plugins.py", line 8, in myfunc
return constant*4
NameError: name 'constant' is not defined
```
The problem is that, as noted in the exec documentation:
> If exec gets two separate objects as globals and locals, the code will be …

ensure the global namespace in the plugins file is preserved

---

yt/frontends/enzo_p/io.py
yt/frontends/enzo_p/misc.py

This PR fixes the following bugs. It showed up when I read a dataset with 2x2x1 root blocks.
1. Blocks were being read in the incorrect row/column ordering, which wasn't noticeable with cubic blocks.
2. Handle root block splitting with one block in a dimension

Fixing enzo-p frontend bugs.

---

yt/utilities/cython_fortran_utils.pyx

According to https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=vs-2017, on windows, fopen will do locale-specific translations if you open the file in "r" mode. If you open it in "rb" mode this will not happen, which is the behavior we want.
I tested this on a windows box and am now able to load the file linked in the issue. We don't appear to have tests for `FortranFile` so it's not clear to me how to add a test for this.

make FortranFile open files in binary mode. closes #2147

---

yt/frontends/gadget/io.py
yt/frontends/sph/io.py
yt/frontends/tipsy/io.py
yt/geometry/particle_geometry_handler.py
yt/geometry/selection_routines.pyx

This PR improves the performance of scripts like this one:
```python
import yt
import h5py
import time
from pyinstrument import Profiler
ds = yt.load('GadgetDiskGalaxy/snapshot_200.hdf5')
ds.index
data = ds.all_data()
start = time.time()
data[('PartType0', 'Coordinates')]
print(time.time() - start)
```
Before this PR, on my mac laptop with an SSD, this script prints 1.6224758625030518. After it prints 0.17824316024780273, so about a 10x improvement by skipping a lot of unnecessary calls to the selection machinery. We're still not as fast as calling h5py directly because the chunking system needs to first load in the data and then copy it into a result array, so there are some extra copies and array allocations that don't happen for the pure h5py case.
This optimization was requested by …

[yt-4.0] optimize accessing data through ds.all_data() for SPH

---

doc/source/analyzing/parallel_computation.rst
yt/data_objects/time_series.py

The DatasetSeries piter() did not have the dynamic option. I've added it in this PR.

Adding dynamic parallelism to DatasetSeries piter

---

yt/convenience.py
yt/frontends/gadget/data_structures.py
yt/frontends/gadget/tests/test_outputs.py
yt/frontends/gizmo/data_structures.py
yt/frontends/owls/data_structures.py

Currently, for a multi-file Gadget snapshot, yt requires that the first file be passed, e.g. snapshot_000.0, to yt.load(). This is a straightforward fix for that. It allows multi-file snapshots to be passed by the base name of the snapshot. The only thing I'm not sure of is how other data formats handle multi-file outputs, so it might be better to delegate this to a separate function that can have a different case for each code, rather than simply putting it directly in load().
- [ x] Code passes flake8 checker

Gadget read

---

doc/source/developing/releasing.rst

This adds some clarifications in the release docs that I thought would be helpful. 
* explicitly lists the remote ssh address to copy the tarball, rather than assuming a ssh config is set up
* switches the ordering of updating the conda-forge and building wheels sections so that the wheels section comes right before uploading to PyPI. 
* while tagging is specific to a commit hash, it's probably a good practice tag from the stable branch so a clarification has been added about that. 
* updates the notes about being an owner or maintainer of yt on PyPI

add clarification to release docs on multibuild, tagging, scp

---

.travis.yml
tests/test_minimal_requirements.txt
tests/test_requirements.txt

This should hopefully fix the travis build failures in #2169.

install numpy and cython before other dependencies

---

doc/source/visualizing/plots.rst
yt/visualization/plot_container.py
yt/visualization/plot_window.py
yt/visualization/profile_plotter.py
yt/visualization/tests/test_profile_plots.py

Moved show/hide_colorbar and show/hide_axes from PlotWindow to PlotContainer. Added property function in profile_plotter.py so that PlotWindow implementation of these functions works with ProfilePlot.
Added note in yt document that PhasePlot has similar attributes, such as show and hide colorbar, as SlicePlot.
Resolves #1736

Phase plot showhide colorbar

---

.pep8speaks.yml

This adds a pep8speaks yml configuration file, currently duplicating
some information in setup.cfg.
PEP8-Speaks is a bot that executes *just* PEP-8 style checks and leaves
comments on pull requests.  For more information:
https://pep8speaks.com
This can enable much more concise information about style changes, and
we think it may even be able to provide suggested diffs and changes to
pull requests upon request.  This way, stylistic changes can be done
without a lot of fuss, and one doesn't need to dive into travis results
to figure out what's up.

Add a pep8speaks yml file

---

yt/data_objects/selection_data_containers.py

This takes care of another `yt-4.0` FIXME. Support for rays that go outside the domain does not exist in yt 3 either, so for now I just added a warning message. At some point, I would like to return the `periodic_ray` functionality that I moved to trident to create a boolean object that combines all the non-periodic segments together. Getting proper `t` and `dts` fields is non-trivial, so I'd like to save that for later.

Add warning for rays outside domain.

---

.pep8speaks.yml

It turns out that pep8 speaks looks at the branch into which you are
merging when it finds the config, so we have to duplicate that here.

Adding pep8speaks config for yt-4.0

---

yt/data_objects/construction_data_containers.py

When a field's `units` and `output_units` are different, the SPH projection would make inconsistent assumptions. In [this line](https://github.com/yt-project/yt/blob/ed52fb30a47b3ef04231eb4f9612a5a75280b510/yt/data_objects/construction_data_containers.py#L345), `units` is assumed, while in [this line](https://github.com/yt-project/yt/blob/ed52fb30a47b3ef04231eb4f9612a5a75280b510/yt/geometry/coordinates/cartesian_coordinates.py#L295), `output_units` is assumed.
This fix makes sure `output_units` is used consistenely.

Fix projection units

---

yt/frontends/tipsy/io.py

#2146 unintentionally broke tipsy I/O as revealed by the tests in #2172. This fixes it by ensuring that `hsml` is always defined by the time we use the selector.

fix tipsy IO via ds.all_data()

---

yt/frontends/rockstar/data_structures.py

This fixes the `halo_plotting.py` recipe in the cookbook which is currently failing in the tests for #2172

add missing argument to RockstarBinaryFile initializer

---

yt/utilities/lib/cyoctree.pyx

Ensure that `children` get initialised to zero in cyoctree
closes #2196

[bugfix] yt-4.0 cyoctree fix

---

yt/data_objects/level_sets/clump_handling.py

This fixes the Clump finding issue reported by @stonnes on the mailing list. The contour finder was previously always running with the maximum value as the maximum of the data container and not the maximum value provided by the user. This produced poorly defined behavior. Now, we explicitly provide the min/max values to the contour algorithm.

[bugfix] Set max value in contour finder to be max value in clump finder.

---

yt/frontends/ahf/io.py
yt/frontends/gadget_fof/data_structures.py
yt/frontends/gadget_fof/io.py
yt/frontends/halo_catalog/data_structures.py
yt/frontends/halo_catalog/io.py
yt/frontends/rockstar/io.py

The `gadget_fof` frontend was giving the following error when loading data:
```
File "test.py", line 4, in <module>
ds.field_list
File "/Users/britton/Documents/work/yt/yt-4.0/yt/data_objects/static_output.py", line 556, in field_list
return self.index.field_list
File "/Users/britton/Documents/work/yt/yt-4.0/yt/data_objects/static_output.py", line 514, in index
self, dataset_type=self.dataset_type)
File "/Users/britton/Documents/work/yt/yt-4.0/yt/frontends/gadget_fof/data_structures.py", line 48, in __init__
super(GadgetFOFParticleIndex, self).__init__(ds, dataset_type)
File "/Users/britton/Documents/work/yt/yt-4.0/yt/geometry/particle_geometry_handler.py", line 42, in __init__
super(ParticleIndex, self).__init__(ds, dataset_type)
File …
```

[bugfix] fix particle index initialization in gadget_fof frontend

---

yt/frontends/ramses/data_structures.py

This fixes a crash reported by @suniverse on yt's slack. I guess we could also make sure `bbox` is initialized to a default value before this line if that makes more sense but I'll defer to @cphyc on this.

fix crash in check for ramses non-hilbert ordering

---

yt/units/tests/test_ytarray.py
yt/units/yt_array.py

This adds the missing "axis" argument to the stack ufunc.

[BUGFIX] Fix missing argument in stack ufunc

---

setup.py

Sort .so input file list
so that EnzoHop.cpython-37m-x86_64-linux-gnu.so builds in a reproducible way
in spite of indeterministic filesystem readdir order
and http://bugs.python.org/issue30461
See https://reproducible-builds.org/ for why this is good.
Without this patch, building the openSUSE python-yt package always had variations in /usr/lib64/python3.7/site-packages/yt/analysis_modules/halo_finding/hop/EnzoHop.cpython-37m-x86_64-linux-gnu.so machine code.
This PR was done while working on reproducible builds for openSUSE.

Sort .so input file list

---

doc/source/cookbook/complex_plots.rst
doc/source/cookbook/image_resolution.py
doc/source/visualizing/plots.rst
yt/visualization/plot_window.py
yt/visualization/tests/test_plotwindow.py

Added `buff_size` argument (and added to docstring) for `ProjectionPlot`, `OffAxisSlicePlot`, `OffAxisProjectionPlot`, and `AxisAlignedSlicePlot`, which gets passed along to `PWViewerMPL`, which then gets passed on to `FixedResolutionBuffer`.
Wasn't a way to create a higher resolution image with the `ProjectionPlot` command (at least, not that I could find).  Your refinement was effectively limited by the `buff_size`.

expose buff_size argument to wrappers around PWViewerMPL in plot_window.py

---

yt/utilities/tests/test_cosmology.py

This adds a test of a loaded dataset's cosmology calculator that will fail if the cosmology calculator and the dataset share the same unit registry.

Add test of dataset cosmology.

---

tests/tests.yaml
yt/frontends/ytdata/tests/test_old_outputs.py
yt/frontends/ytdata/tests/test_outputs.py

This adds tests for pre-existing `ytdata` datasets. The tests are equivalent to the currently existing tests, except they load testing data instead of create it with `yt.save_as_dataset`.
The test datasets can be generated by running `yt/frontends/ytdata/tests/test_outputs.py` after setting the `GENERATE_YTDATA=1` as an environment variable.
I've opened a [PR on the website repo](https://github.com/yt-project/website/pull/54) to add the relevant testing data.

Add tests for old ytdata datasets.

---

yt/data_objects/selection_data_containers.py
yt/data_objects/tests/test_extract_regions.py

This closes Issue #2233.
When chained cut regions do io chunking, only the conditionals of the last cut region are applied. Conditionals from parent cut regions are ignored. This only shows up when calculating derived quantities.
The solution implemented here changes how cut regions derived from other cut regions are initialized. Instead of creating a chain of objects that rely on each's parent, we add the conditionals from the parent cut region and create the new one from the parent's base object. Anecdotally, this also appears to speed up field access as we're only applying conditionals once.

[bugfix] fix io chunking for chained cut regions

---

yt/frontends/boxlib/data_structures.py

Updates search string for git hashes in the BoxLib frontend for Castro to account for a change made to this string in Castro release 17.02.
In release 17.02, Castro changed the string used to prefix git hashes in plotfiles to use the words "git describe" instead of "git hash". This PR updates the search string for these git hashes accordingly.
This test script prints the git hashes from a Castro dataset:
```
import yt
ds = yt.load("ignition_16_plt00001")
for k in ds.parameters.keys():
if "git" in k:
print("{} = {}".format(k, ds.parameters[k]))
```
Presently, no git hashes are printed in the following output:
```
yt : [INFO     ] 2019-04-10 16:12:02,751 Parameters: current_time              = 0.1
yt : [INFO     ] 2019-04-10 16:12:02,751 Parameters: domain_dimensions         = [16 16 16]
yt …
```

Update for Castro git hash prefix in plotfiles

---

appveyor.yml
yt/frontends/arepo/io.py

This got missed in the final cleanup steps in the recent Arepo frontend merge.

[bugfix] Arepo smoothing length is supposed to be float64

---

yt/frontends/arepo/io.py

In the Gadget frontend we apply a fix if there is a mismatch in precision between the positions and the smoothing length fields stored on-disk. Apparently this fix is also necessary for the Arepo frontend if we construct "smoothing lengths" from the density and mass fields.
Fixes issue #2242.

[bugfix] Make sure Arepo "smoothing length" has correct dtype

---

yt/visualization/fixed_resolution.py
yt/visualization/plot_window.py

Fix set_buff_size issue for OffAxisProjectionPlot

---

yt/funcs.py

I've wrapped this decode in a conditional because I believe that
gitpython versions may have changed this behavior, and I don't want to
mess it up for any previous versions.

Adding conditional string decode.  Fixes #2223.

---

yt/fields/magnetic_field.py
yt/frontends/arepo/data_structures.py
yt/frontends/arepo/fields.py
yt/frontends/arepo/tests/test_outputs.py
yt/frontends/gadget/io.py
yt/frontends/gizmo/data_structures.py
yt/frontends/gizmo/fields.py
yt/frontends/gizmo/tests/test_outputs.py

This PR fixes some issues with the Arepo and Gizmo frontends in terms of magnetic fields.
* The aliases to "local" magnetic fields (e.g. `("gas","magnetic_field_x")`) were not being set. This happened because the magnetic fields were being handled after the other aliases had been set up.
* The correct magnetic units were not being set in these frontends. I know that what I have done below is correct for Arepo, someone more familiar with Gizmo (perhaps @chummels?) should check what I have done here for that.
* I added a new test for Arepo with a new dataset, and we also now test the Gizmo MHD dataset for the magnetic field aliases. 
* I fixed an unrelated bug in Gadget's I/O handler (which both of these frontends use) which occurred when the selector was `all_data` and one tried to …

[bugfix] Fix aliases and units for magnetic fields in SPH frontends

---

yt/frontends/gadget/io.py

I introduced a bug in Gadget I/O in a previous PR of mine. If `mask` is `None` after selecting points from the selector, we shouldn't try to sum it. In this case, we won't need to compute the sum anyway because the loop will be continued a couple of lines down.

[bugfix] Don't try to sum a mask if it is None

---

yt/frontends/gadget/io.py

Another nit I discovered by poking around. Some Gadget-based frontends (e.g. Arepo) have to generate their own smoothing lengths. Normally when this field is asked for it's already been generated for data selection purposes, but there is the case of selecting all data where it hasn't. This PR ensures that the smoothing lengths are always generated if they are needed.

[bugfix] Generate smoothing length if it's needed for frontends which don't have it

---

doc/source/analyzing/domain_analysis/XrayEmissionFields.ipynb
yt/fields/tests/test_xray_fields.py
yt/fields/xray_emission_fields.py

This PR updates the X-ray emission fields machinery so that it works with all datasets, including SPH, in yt-4.0. It also adds a new `dist` keyword argument so that intensity fields can be created for local, non-cosmological sources.

Refactor X-ray emission fields for yt-4.0

---

doc/source/examining/loading_data.rst
doc/source/visualizing/FITSImageData.ipynb
yt/data_objects/construction_data_containers.py
yt/data_objects/data_containers.py
yt/frontends/fits/data_structures.py
yt/frontends/fits/fields.py
yt/frontends/fits/io.py
yt/visualization/fits_image.py
yt/visualization/fixed_resolution.py
yt/visualization/tests/test_fits_image.py

This PR introduces improvements to FITS file writing and reading. Specifically:
1. Specifies a new standard for writing metadata to FITS files using the `FITSImageData` class and its subclasses. This standard uses the header to write unit information and other metadata to the FITS file so that when it is read back into yt as a dataset it is more self-describing. 
2. Defines a new class, `YTFITSDataset`, which is a subclass of `FITSDataset` which looks specifically for this header metadata.
3. Simplifies the logic in `FITSHierarchy` for determining units.
4. Makes the `"beam"` unit part of `SkyDataFITSDataset`. 
5. Adds a `convolve` method to `FITSImageData` instances to convolve them with any kernel created using AstroPy or a simple Gaussian kernel.
6. Specifies that the default image …

Improvements to reading / writing FITS images

---

yt/geometry/particle_geometry_handler.py

This is a follow-on to #2146; I'm trying to cut down the overhead of yt to increase its usability in similar-looking applications (datasets >10 GB, but few operations on the dataset).
This PR halves the runtime of scripts such as mentioned in #2146 on our system, for 4-file MassiveFIRE snapshots. On such snapshots yt used to redundantly scan the backing HDF5 files 243 times for what Datasets they contain.

Cache the result of _identify_fields to improve dataset initialization speed

---

tests/tests.yaml
yt/frontends/boxlib/data_structures.py
yt/frontends/boxlib/io.py

This simply ignores the ghost zones if they are present in the file.

[BUGFIX] [Boxlib frontend] Handle the case where the raw_fields were written out with ghost zones

---

yt/frontends/open_pmd/data_structures.py
yt/frontends/open_pmd/fields.py

As of version 1.1.0, both mesh and particle data are optional in the OpenPMD format. This allows yt to read these datasets.

[BUGFIX] [OpenPMD frontend] Allow openpmd files that don't have any particles

---

yt/frontends/art/fields.py

edit: resubmitting PR because it was too dirty last time and I couldn't get to the bottom of it. This is just my commits with all the changes now. @chummels 
Several months ago, I added these _specific_metal_density fields to ART in order to take advantage in TRIDENT of the fact that ART tracks SNIa metal and SNII metal separately. However, the old version had a problem which meant it was not reading the correct "atom" when it actually evaluated _specific_metal_density.
This defines a different _specific_metal_density function for each atom density field (that's what the outer nested function is doing, creating those functions), so that it accesses it correctly when it gets there. The old version of this would call `_specific_metal_density` _after_ cycling through all the atoms in the …

fix art specific_metal_field definition

---

yt/data_objects/construction_data_containers.py
yt/data_objects/tests/test_covering_grid.py

This fixes Issue #2263.
The basic issue is that field parameters weren't getting passed down to the region held in `self._data_source`. I've added a new test as well. Thanks to @RicardaBeckmann for reporting this issue.

[bugfix] Pass field parameters down in CoveringGrids

---

yt/frontends/ytdata/io.py
yt/frontends/ytdata/tests/test_outputs.py

Without this fix, array fields loaded by the `ytdata` frontend will be calculated to have size `(nparticles, nparticles, dimensions)`, instead of just `(nparticles, dimensions)`.

[bugfix] Fix field size for array fields in ytdata.

---

yt/data_objects/construction_data_containers.py
yt/data_objects/data_containers.py
yt/data_objects/profiles.py
yt/data_objects/selection_data_containers.py
yt/data_objects/static_output.py
yt/data_objects/tests/test_octree.py
yt/fields/derived_field.py
yt/fields/field_info_container.py
yt/fields/tests/test_sph_fields.py
yt/frontends/arepo/io.py
yt/frontends/gadget/data_structures.py
yt/frontends/gadget/io.py
yt/frontends/owls/fields.py
yt/frontends/sph/data_structures.py
yt/frontends/stream/data_structures.py
yt/frontends/stream/io.py
yt/frontends/swift/data_structures.py
yt/frontends/swift/io.py
yt/frontends/tipsy/data_structures.py
yt/frontends/tipsy/io.py
yt/geometry/coordinates/cartesian_coordinates.py
yt/geometry/particle_geometry_handler.py
yt/visualization/plot_window.py
yt/visualization/volume_rendering/off_axis_projection.py

This is a WIP PR to enable SPH visualization of filtered particle types which have an original type which is SPH. 
A side effect of the work here will be to (at least in theory) make multiple SPH particle types possible, since the core of it is to change the private attribute `Dataset._sph_ptype` to `Dataset._sph_ptypes`, where the latter is a tuple.
Currently I'm able to make slices and projections correctly but otherwise at the moment I'm sure some things are broken.

Enable SPH visualization of filtered particle types

---

yt/frontends/tipsy/io.py

Fixes #2276.
The tipsy chunking was not correctly subchunking, and this seemed to only show up when the particular ordering and sizes of the particle types was set in a specific way.  This would always have a "hard fail", so there have to my knowledge this has not been the source of any quiet failures.
What this does is simplify the particle offset calculation.  Instead of our previous way of doing things, which I could not quite parse out (and which was probably dating from before we did any subchunking) the new way is to compute a global offset for *each particle type* and then offset into that based on `data_file.start`.  I also terminate earlier when trying to read particles that aren't in a sub-chunk.
This uses data from @claytonstrawn .
My verification script, which I ran with …

Simplify and correct tipsy sub-chunking.

---

yt/frontends/boxlib/data_structures.py

A recent change to WarpX broke reading the output in yt when "Rigid Injected" particle species were used. This un-breaks it.

[BUGFIX] Fix for WarpX datasets where 'rigid injected' species are used.

---

yt/frontends/gadget/io.py

[bugfix] Don't try to read fields if no particles present.

---

yt/frontends/exodus_ii/data_structures.py
yt/frontends/exodus_ii/io.py
yt/frontends/stream/data_structures.py

Certain Exodus II data output would not load properly; fixes to this were supplied by Kris Beckwith. Additionally, annotating mesh lines onto slices of semi-structured data (2D forced to 3D) failed because of how the connectivity matrix was returned.
Issues #2272 and #2273

Bugfixes for Exodus II and Semi-Structured Frontends

---

yt/data_objects/data_containers.py
yt/data_objects/image_array.py
yt/data_objects/static_output.py
yt/data_objects/tests/test_compose.py
yt/data_objects/tests/test_image_array.py
yt/fields/angular_momentum.py
yt/fields/field_detector.py
yt/fields/particle_fields.py
yt/frontends/gdf/data_structures.py
yt/frontends/ytdata/data_structures.py
yt/geometry/geometry_handler.py
yt/utilities/amr_kdtree/amr_kdtree.py
yt/utilities/parallel_tools/parallel_analysis_interface.py
yt/visualization/fixed_resolution.py
yt/visualization/plot_modifications.py
yt/visualization/volume_rendering/camera.py
yt/visualization/volume_rendering/old_camera.py
yt/visualization/volume_rendering/scene.py

The `input_units` kwarg is deprecated in unyt. This was giving enough deprecation warnings to cause tests of other packages to fail because the logs were too long.

Replace deprecated input_units kwarg with units.

---

yt/frontends/gadget/tests/test_outputs.py
yt/frontends/gizmo/tests/test_outputs.py
yt/frontends/owls/tests/test_outputs.py
yt/frontends/ramses/tests/test_outputs.py
yt/utilities/answer_testing/framework.py

The `sph_answer` tests need updating for yt-4.0. This PR is a WIP to update them. Things that have to be done:

Fix SPH answer tests in yt-4.0

---

yt/frontends/tipsy/data_structures.py

This PR fixes a very small bug introduced in the Tipsy frontend reported by @ibutsky. The `hubble_constant` was being passed as a NumPy array with one value instead of a floating-point value, which is expected by `unyt` when constructing new units. 
Closes Issue https://github.com/yt-project/yt/issues/2299.

[bugfix] Fix Tipsy bug introduced by unyt

---

doc/helper_scripts/show_fields.py

This PR fixes an error that I encountered while trying to build the documentation locally for the yt-4.0 branch on my machine with Python 3.6.5 and unyt 2.3.0. When trying to build the html documentation with sphinx I encountered this error (I've only copied the last part):
```
Exception occurred:
File "/Users/madicken/python/anaconda/envs/ytdev/lib/python3.6/subprocess.py", line 418, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/Users/madicken/python/anaconda/envs/ytdev/bin/python3.6', './helper_scripts/show_fields.py']' returned non-zero exit status 1. 
```
running this file with python showed an issue with our list of units in the `./doc/helper_scripts/show_fields.py` file. 
```
$ python ./helper_scripts/show_fields.py
yt : [INFO     ] 2019-08-19 …
```

[bugfix] fix unit error for au in docs build

---

yt/utilities/lib/bounded_priority_queue.pxd
yt/utilities/lib/bounded_priority_queue.pyx
yt/utilities/lib/tests/test_nn.py

This PR fixes #2326. The example code crashes because memoryviews don't have a `resize` method. It's tricky to resize a numpy array in cython.

Solve the cython numpy array resizing issue

---

yt/data_objects/static_output.py
yt/frontends/gadget/io.py
yt/frontends/owls/fields.py
yt/units/tests/test_magnetic_code_units.py

This PR fixes incorrect conversions between code units for magnetic fields and other magnetic field units. It ensures that no matter what unit system we are using and no matter what unit the magnetic field has, the conversions happen correctly. I added a test for this.
I threw in two other bug fixes for good measure:
* `OWLSFieldInfo` did not define ionized hydrogen fields.
* Deriving the mass field for Gadget datasets (and their derivatives) was not happening correctly when 1) the mass value is in the mass array and 2) the `is_all_data` selector is being used.

[bugfix] Fix code magnetic units, etc

---

yt/visualization/plot_modifications.py

There's seems to be a certain degree of unpredictability in MPL regarding choice of line styles for contouring. This PR adds a default: *solid* line, kwarg to our invocation of `Axes().contour()`

Explicitly default to solid lines in contours

---

doc/source/visualizing/volume_rendering.rst

Remove a double full stop in yt/doc/source/visualizing/volume_rendering.rst

doc:  Fix minor typo

---

yt/visualization/_mpl_imports.py
yt/visualization/base_plot_types.py

This should close #2309.  It adds support for saving additional formats supported by matplotlib.

Add support for new image format saving

---

doc/source/analyzing/objects.rst
tests/test_requirements.txt
yt/data_objects/data_containers.py
yt/data_objects/selection_data_containers.py
yt/data_objects/tests/test_spheres.py
yt/funcs.py
yt/utilities/on_demand_imports.py

This PR adds a "minimum sphere" function that creates a minimum bounding sphere around a set of points. This is useful to get the smallest spherical volume that contains e.g. some particles.
This is the same as https://github.com/yt-project/yt/pull/2283 but to be merged onto yt-4.0.

[FEATURE] Add "minimal sphere" implementation

---

yt/fields/species_fields.py
yt/frontends/gizmo/fields.py
yt/frontends/owls/fields.py

This is a quick follow-on to PR #2336. 
We should not set up the alias between `X_p0_density` and `X_density` fields if the frontend defines an `X_density` field for abundance information which does not have an ionization state. 
This PR also adds the `El_number_density` field to `OWLSFieldInfo` and `GizmoFieldInfo`.

Various species density issues

---

yt/units/tests/test_ytarray.py
yt/units/yt_array.py

At present, this adds a diagnostic test for the `np.clip` function that
should help us to identify why builds are now failing on appveyor for
python 3.6 with recursion counts at `yt/frontends/ytdata/io.py` line
351.

[BUGFIX] Fix build failure on Windows

---

yt/frontends/fits/data_structures.py
yt/frontends/fits/misc.py

Creating a ds9 region with `yt.frontends.fits.misc.ds9_region` produces the error below
as in the FITS radio cubes notebook in the documentation:
http://yt-project.org/docs/dev/cookbook/fits_radio_cubes.html
```
~/.local/lib64/python3.6/site-packages/astropy/io/fits/header.py in _cardindex(self, key)
1652
1653         if not indices:
-> 1654             raise KeyError("Keyword {!r} not found.".format(keyword))
1655
1656         try:
KeyError: "Keyword 'NAXIS1' not found."
```
This fixes the error below when creating a ds9 region. The FITS header created by
the `astropy.wcs.WCS.to_header` only contains WCS related keywords, and the required `NAXIS` keywords have to be supplied after calling `to_header`.
In SpectralCubeFITSDataset, the coordinate description in wcs_2d can be equivalently …

Append required FITS keywords in header

---

yt/utilities/lib/pixelization_routines.pyx

In the other pixelizers, we signify the image buffer as untouched by using NaN values.  This implements that for the `pixelize_mesh_elements` routine as well.  This should fix #2305.
One side effect, which I am hesitantly in favor of, is that now the if you do not set a background color, the values not part of the mesh will not be the 0 point of the colormap colormap, but will instead be white (by default).
Without setting a background color:
And with the script in #2305:

Initialize mesh background to nan

---

yt/utilities/configure.py

Running `yt config migrate` on a config file without the `pluginfilename`
option returns the following error.
```python
Writing a new config file to: /home/mdevalbo/.config/yt/ytrc
Backing up the old config file: /home/mdevalbo/.yt/config.bak
File "/usr/lib/python3.7/configparser.py", line 788, in get
value = d[option]
File "/usr/lib/python3.7/collections/__init__.py", line 916, in __getitem__
return self.__missing__(key)            # support subclasses that define __missing__
File "/usr/lib/python3.7/collections/__init__.py", line 908, in __missing__
raise KeyError(key)
KeyError: 'pluginfilename'
During handling of the above exception, another exception occurred:
File "/home/mdevalbo/.local/bin/yt", line 11, in …
```

Check if pluginfilename option is specified in ytrc

---

yt/frontends/enzo/tests/test_outputs.py

I noticed that the `test.__name__()` call in the kh2d test in the enzo frontend referred to the toro1d test rather than the kh2d test. This is a minor fix that updates that line.

fix kh2d test name

---

doc/source/analyzing/fields.rst
yt/fields/angular_momentum.py
yt/fields/particle_fields.py
yt/fields/tests/test_angular_momentum.py
yt/fields/tests/test_particle_fields.py
yt/geometry/selection_routines.pyx
yt/utilities/lib/misc_utilities.pyx

This is one of those PRs which basically led one down a rabbit hole, finding several issues along the way. 
1. The `DiskSelector` was computing selections incorrectly for SPH particles. 
2. The `relative_particle_position` and `relative_particle_velocity` fields were using `modify_reference_frame` to compute the relative fields. This takes a normal vector and then returns the relative coordinates in a rotated coordinate system, in which the new normal vector is the z-axis. However, the fields for particle positions in spherical and cylindrical coordinates (such as radius, etc.) were assuming the `normal` field parameter was the original one instead and using the relative fields, which gave incorrect results. I'm changing here the way the relative fields are computed, consistent with the …

[bugfix] Fixing issues with particles

---

doc/source/visualizing/FITSImageData.ipynb
yt/visualization/fixed_resolution.py
yt/visualization/plot_window.py

The `FixedResolutionBuffer` class has a method `to_fits_data` that exports the fields in the buffer to a `FITSImageData` instance. This PR exposes that method to the `PlotWindow` class.

export directly from PlotWindow to FITS data

---

yt/visualization/tests/test_geo_projections.py

In the cartopy testing file we've disabled the OSNI projection in the unit tests due to potential incompatibilities that might be caused with shapely/GEOS. However, this wasn't done in the answer tests. I'm guessing that we've been lucky so far to not have encountered this failure, because it was an issue when we first added cartopy support. I think because we've disabled this projection in the unit tests, it's reasonable to also do it in the answer tests.  I've also included a link to the issue as a comment line in the test so it's clear why we've disabled it.

disable OSNI projection answer test

---

tests/test_requirements.txt
yt/frontends/ramses/data_structures.py
yt/frontends/ramses/tests/test_outputs.py
yt/utilities/on_demand_imports.py

This adds the automatic loading of the `namelist.txt` file which contains the parameter file RAMSES used to produce the output.
This relies on the package `f90nml` being installed (for the tests). If the package is absent, `ds.parameters['namelist']` contains an error message.

Ramses read namelist

---

yt/data_objects/derived_quantities.py

In the `yt-4.0` branch, the `WeightedVariance` derived quantity (and thus the `std` method of data containers which is downstream from it) has a couple of bugs. 
1. If one runs into a case where some chunks have a weight which sums to zero, the code returns floating-point zeros to be used in the final variance calculation. However, the chunks with data are not dimensionless in general, and so when one attempts to add everything together you get a `IterableUnitCoercionError`. This PR fixes that by dropping the units during the calculating and assigning them at the end. 
2. I also noticed after fixing 1. that the answers given were not the same as if one had simply computed the weighted variance by hand using NumPy on the data object's field. I tracked this second error down to commit …

[bugfix] WeightedVariance is broken in a couple of ways in yt-4.0

---

yt/fields/vector_operations.py

The usage of "is" comparison here was breaking the generation of the `_cartesian_x` field for polar geometries. The fix is to use == comparison.
Ping @neutrinoceros

fix incorrect usage of is comparison with == comparison

---

yt/visualization/plot_window.py

propose a fix for https://github.com/yt-project/yt/issues/2353
the fix is very simple but I'm not 100% confident it will not break anything else.

Correctly set plot axes units to "code length" for datasets loaded with `unit_system="code"`

---

doc/source/visualizing/unstructured_mesh_rendering.rst

The commit included in this PR adds an explanation to the doc about
why the rendered color is not continuous when rendering two-part
unstructured mesh and how to explicitly set each colormap bound
for a continuous color plot.

Add an instruction to the doc about continuous mesh colormap

---

yt/frontends/amrvac/data_structures.py

Solves issue 2361.
Marked as WIP because I realised that I don't see a good reason to use `setdefaultattr` for the three affected dataset attributes, which are derived units, merely aliasing more fondamental units normalisation factors.
I'll wait for the tests to run once before I rewrite this without `setdefaultattr`.

[AMRVAC] fix derived unit parsing

---

appveyor.yml

The appveyor tests are currently failing with the following error:
```
======================================================================
ERROR: Test cosmology calculator functions against previously calculated values.
----------------------------------------------------------------------
File "C:\Miniconda36-x64\envs\test\lib\site-packages\nose\case.py", line 197, in runTest
self.test(*self.arg)
File "C:\projects\yt\yt\utilities\tests\test_cosmology.py", line 227, in test_cosmology_calculator_answers
data = yaml.load(open(fn, 'r'), Loader=yaml.FullLoader)
File "C:\Miniconda36-x64\envs\test\lib\site-packages\yaml\__init__.py", line 70, in load
loader = Loader(stream)
File "C:\projects\yt\yt\utilities\on_demand_imports.py", line 32, in __call__
raise …
```

install pyyaml on appveyor

---

yt/data_objects/time_series.py

fixes https://github.com/yt-project/yt/issues/2365
`DatasetSeries.kwargs` were not properly passed down to child instance created by slicing. This commit fixes it.
Ideally this behaviour should be tested. I never added tests for yt's core yet so guidance might be useful.

fix issue 2365

---

tests/tests.yaml
yt/frontends/athena/data_structures.py
yt/funcs.py

This problem showed up in the pytest PR (#2286).
We were able to verify that using unsorted glob did *not* result in any differences in *derived* products, only in the actual index order of the grids post-reconstruction.
(Also the view sure was nice up on my [high horse](https://github.com/yt-project/yt/pull/2286), but ... :grimacing:)

Use sorted glob in athena

---

yt/data_objects/image_array.py

This PR addresses Issue #2359, in which ImageArray.save(filename) was appending an extra file extension to filename if one was already present (e.g., my_image.png -> my_image.png.png).
https://github.com/yt-project/yt/issues/2359

Fixed extra extension added by ImageArray.save()

---

yt/visualization/plot_window.py
yt/visualization/tests/test_plotwindow.py

Fix issue #2370 
Simply add an if statement to cover the spherical 2D case, and it works like a charm.
See for example :

Add support for spherical geometries in plot_2d

---

yt/frontends/amrvac/tests/test_outputs.py

After the acceptance of  https://github.com/yt-project/website/pull/69, the dataset stored on the website should be eligible to tests, so I'm uncommenting the corresponding test block

[ARMVAC] restore jet test

---

doc/source/examining/loading_data.rst
tests/tests.yaml
yt/frontends/amrvac/data_structures.py
yt/frontends/amrvac/tests/test_outputs.py

The AMRVAC code (amrvac.org) uses specific normalisations based on a helium abundance.
When specifying normalisations, amrvac has only three degrees of freedom: a unit length and unit number density should always be specified, together with either a unit temperature or unit length. These normalisations are however _never_ saved in the dataset and should hence by supplied by the user through `ds = yt.load(amrvacdataset, units_override={})`.
This PR extends the `_set_code_unit_attributes()` method in the newly accepted AMRVAC frontend (#2321) to ensure consistency and correct re-normalisation of code units between AMRVAC and yt. It also provides support for additional yt override possibilities (like time, mass, etc) while maintaining consistency.

[AMRVAC] ensure consistent renormalisation of amrvac datasets

---

doc/source/reference/code_support.rst

add missing AMRVAC entry to the "code support" documentation page.

[AMRVAC] add AMRVAC entry to code_support.rst

---

yt/frontends/amrvac/__init__.py
yt/frontends/amrvac/data_structures.py
yt/frontends/amrvac/io.py

Following @munkm's advice, propagate numpy's docstring styling to AMRVAC's frontend.
Add one liner docstrings to internal methods that are subclassed from `Dataset` and were missing documentation.
While I was at it, I changed one or two internal variable names, hopefully making them clearer. I also changed `AMRVACDataset.parse_geometry()` to `AMRVACDataset._parse_geometry()` to make it clear it is not intented to be exposed.

[AMRVAC] applied numpy docstring style to most of AMRVAC's frontend

---

yt/frontends/flash/data_structures.py
yt/frontends/open_pmd/data_structures.py
yt/frontends/open_pmd/misc.py
yt/frontends/ramses/data_structures.py
yt/utilities/grid_data_format/conversion/conversion_athena.py
yt/visualization/plot_container.py
yt/visualization/profile_plotter.py

In Python 3.8, the usage of `is` in some context raises a
warning. This is due to the fact that `is` checks for equality of
object, while `==` checks for equality of their value (as is expected
in the code).

Fix python 3.8 warnings

---

yt/frontends/chombo/io.py

In the CHOMBO frontend, I encounter a bug when reading datasets containing ghost cells.
The issue is when doing the slice, a minus sign should be a plus sign, in order to filter out only the "right-hand side" ghost cells.  
I tried some of my datasets (from GRChombo) and now the code works well. 
Please check that this (small) change make sense.

chombo frontend :: solved bug related to slice the ghost cells out

---

yt/geometry/particle_geometry_handler.py

After examining #2383, I came to believe that this logic was inverted.
In short, I believe that if `is_all_data` is `True`, we should be using
all of the data without validating.  If it is `False`, we should check
for collisions.

Switch logic for using all-data in particle IO

---

appveyor.yml

This should fix the failures that started cropping up on appveyor recently. I'm going to report this upstream as a regression.

install sympy 1.4 on appveyor to work around regression in 1.5

---

yt/fields/fluid_vector_fields.py

This PR fixes a typo in the z-component of the vorticity in the field `_vorticity_z`.   
The first term (dvy/dx) in the z-component of the vorticity is incorrect in the `_vorticity_z` field.  Consequently, the field `_vorticity_magnitude` is also affected.  This PR fixes the typo.

Fix typo in _vorticity_z field definition

---

doc/source/examining/loading_data.rst
yt/frontends/amrvac/data_structures.py
yt/frontends/amrvac/fields.py

**note:**
~For now, this branch is based on #2376, I'll rebase it onto master once the former is merged.~ ✅ 
Add kinetic energy density, thermal pressure, sound speed, and mach number to derived fields.
This is made possible since there's an api for passing configuration "parfiles" at load time, so we can now reconstruct the equation of state that was used in the run.
I suppose it would suffice to update the answer tests to cover this. However, I am not certain that derived fields are thoroughly tested for. Any clue on this @munkm ?
~This will need immediate extension to the mhd case, but I'd suggest to keep that for a following PR.~
**edit:** actually, the mhd case is the only missing bit to make this PR complete and it does not look that much more work, so I might as well include it …

[AMRVAC] add derived fields for hydro runs

---

yt/data_objects/grid_patch.py

This reduces by a fair amount the total time spent generating ghost zones; we avoid lots of unit checking (and slicing/copying of unitful arrays) by using views into the dataset.
This should be covered by all the extant unit tests.

Speed up ghost zone generation.

---

yt/frontends/boxlib/data_structures.py

Castro now stores additional parameters in the job_info file, separated with a blank line and or the heading "fortin parameters".  This change has the front end ignore these lines, so we can read in all the parameters.  Without this change, yt crashes while reading the latest Castro plotfiles.

skip blank lines when reading parameters

---

yt/fields/astro_fields.py
yt/fields/xray_emission_fields.py
yt/frontends/gamer/fields.py
yt/frontends/stream/data_structures.py
yt/geometry/coordinates/cartesian_coordinates.py
yt/utilities/command_line.py
yt/visualization/fits_image.py
yt/visualization/tests/test_fits_image.py

Sorry for the grab-bag PR. This addresses a number of issues that I came across
in daily use of yt-4.0 over the past couple of months. They are as follows:
* The APEC emissivity models need to be scaled by `n_H*n_e`, where `n_H` is the _total_ hydrogen number density, but I was only scaling it by the free proton density. Similarly, the `emission_measure` field needs to have the same scaling. I have also updated the `apec_emissivity` file, which now has the `n_H*n_e` scaling. 
* When SPH pixelization of any kind is done, one must ensure that all of the arrays being passed to the various Cython routines are in the same base, in this case code units. Otherwise scaling factors might be very off (i.e., because "mass" might be in 'g' and "density" might be in code units unless all of the units …

[bugfix] Various bug fixes which came up in daily use of yt-4.0

---

yt/visualization/plot_container.py

With numpy 1.18.1, np.linspace has become more cautious and won't accept floats as input for an integer number of points.
explicitly set dtype to int for variables used as the 3rd argument of np.linspace (npoints)
I encountered the bug while creating a yt.plot_2d of a polar dataset, I'll try to reproduce with fake data in order to add a test.

bugfix for numpy 1.18

---

yt/geometry/selection_routines.pyx

After PR #2391 was merged, I encountered a few cases of `all_data` selection returning empty arrays. It seems in some cases the region edges are not in code units.

[bugifx] Make sure region edge units are in code_length.

---

yt/frontends/ramses/tests/test_outputs.py
yt/units/yt_array.py
yt/visualization/fixed_resolution.py

I noticed in a few places we have imports of packages that are defined in `on_demand_imports` being imported without that functionality. This PR updates them to use the utility function available for the specified package.

update imports to use utility function 

---

setup.py

This patch helps to speed up `yt`'s build time by parallelizing both `cythonize` and disutils' extension build.
Before:
```bash
$ time python setup.py build_ext
real	4m25.461s
user	4m24.232s
sys	0m6.524s
```
After (on my 4core/8HT laptop) :
```bash
$ time python setup.py build_ext
real	1m32.580s
user	10m40.215s
sys	0m12.188s
```

Use all available cores for both cythonize and build_ext

---

setup.py

Minor tweak to PR #2438 , instead of returning `None` in `_get_cpu_count`, return 0. Now it matches default value of `cythonize` and it's more clear in `build_extensions`.

[setup] return 0 as number of cpus on windows to disable parallel build

---

.travis.yml
yt/units/tests/test_ytarray.py
yt/units/yt_array.py
yt/visualization/color_maps.py

This should fix the issues reported in yt-project/yt#2445 caused by updates in our upstream packages. 
For the yt_units errors I followed the same approach taken in yt-project/unyt#115. Thanks @ngoldbaum; your work made this a lot easer for me.

add support for numpy 1.18.1 

---

yt/utilities/lib/grid_traversal.pxd

Documentation for yt's grid traversal function walk_volume.
This ensures future maintainers and users are provided a basic understanding of walk_volume. Since it is such a large function, future steps may incorporate breaking the function up into two pieces, initialization and traversal.

Documentation for walk_volume

---

yt/fields/astro_fields.py

For the two fields below (`dynamical_time` and `jeans_mass`), conversion to code units was not possible because the constants don't use the unit registry of the dataset and when you do `x = a * b`, `x` has the unit registry of `a`. I fix this issue by moving the constants to after the arrays that use the dataset's unit registry.

[bugfix] allow code units in two derived fields

---

yt/data_objects/data_containers.py

I was working on #2446 and noticed another bug.
Apparently argmin and argmax are heavily code-duplicated from one another, and some convenience functionality of argmax was not ported to argmin, so this PR fixes it.
It would be healthier to deduplicate this code but for now this hotfix should do :)

fix an inconsistency between argmax and argmin methods in YTDataContainer class

---

doc/source/analyzing/fields.rst
yt/data_objects/static_output.py

Expands the doc about particle field deposition. Previously, the function `ds.add_deposited_particle_field` was never mentioned in the doc.
It also updates the docstring of the deposition method to match its accepted values.

Improve doc + fix docstring in deposition

---

doc/source/installing.rst

I noticed that the docs states python 3.5 OR 3.6 was required to install from source. I propose to state that 3.5 is the minimal without further detail instead.
It might be a place where we want to drop mentions of python 2 also.

Allow PY37 and PY38 in the docs

---

yt/frontends/enzo_p/data_structures.py
yt/frontends/enzo_p/misc.py
yt/frontends/enzo_p/tests/test_misc.py

Enzo-p grids are split across one or more "blocks". Previously, the frontend supported loading a dataset with a grid split across multiple blocks. This pull request fixed a bug that had prevented the loading of a grid stored in a single block.
I added an additional case to the unit test for the `get_block_info` function. However, I have not added a test demonstrating that the front-end can now load in a single-block dataset because it would involve a new answer test dataset. I'm not sure how necessary that is.

Enzo-p Frontend Bugfix to Load Single Block Datasets

---

yt/utilities/definitions.py
yt/visualization/plot_modifications.py

This resolves the bug reported in yt-project/yt#2432 . Now when a dataset loaded using `unit_system=code` and `annotate_timestamp()` is called, the time returned is in `code_time`. 
With the fix applied, the plot looks like so:
Let me know if you'd like a test added for this fix.

[bugfix] Update annotate_timestamp to work with "code" unit system 

---

yt/visualization/plot_modifications.py

I noticed that using a plain list of integers as a "center" argument in plot callback `annotate_sphere` was working as expected with `coordinate_system=plot` but not with  `coordinate_system=data`. I monkey-fix it by forcing conversion to floats during sanitizing.
as an example:
```python
import yt
ds = yt.testing.fake_amr_ds(fields=["density"])
p = yt.SlicePlot(ds, "z", "density")
p.annotate_sphere(radius=0.4, center=[0,0], coord_system="plot")
p.annotate_sphere(radius=0.4, center=[0,0,0], coord_system="data") 
```

hotfix an inconsistency in annotate_sphere callback

---

.gitignore

Documenation files are generated by sphinx-apidoc

Add API documentation path to .gitignore

---

yt/data_objects/construction_data_containers.py

_con_args must be a tuple for our parsing to work in some cases.

Fixing streamlines attribute

---

yt/frontends/gadget/io.py

This hits a corner case of selecting a particle with "all data" in a multi-file binary gadget file where the particle does not have variable mass.

Mask is a slice in some cases, not an array.

---

yt/data_objects/profiles.py

It seems that some old profiles that were saved with `yt.save_as_dataset` did not save the `accumulation` attribute and so loading them fails with a `KeyError`. This fixes that by using the `get` function with an appropriate default. I also took the opportunity to do some small code cleanup in the surrounding lines.

[bugfix] use dict.get to pull attributes that may not exist

---

yt/frontends/amrvac/data_structures.py

Very straightforward PR, I noticed that `ds.min_level` was always returning 0 for amrvac datasets, even those where the whole grid is actually refined.

[AMRVAC] add missing min_level

---

doc/source/reference/api/api.rst
doc/source/visualizing/plots.rst
yt/__init__.py
yt/visualization/api.py
yt/visualization/color_maps.py
yt/visualization/eps_writer.py
yt/visualization/plot_container.py

The idea here is to uniformise the existing Colorbar api by using a single naming convention ('cbar' -> 'colorbar')
Considering the existing methods
- set_colorbar_label
- show_colorbar
- set_cbar_minorticks
I propose to just use "colorbar" everywhere with one change.
I'm keeping the old method for backwards compatibility but I also set a deprecation warning. I don't think this is common practice around here so it's unclear when the "deprecated" method should be removed (I'd suggest yt 4.0 to make it cleaner, but since I'm not sure we'll get a release before this one, it may be a bit of a rush).

deprecate ImagePlotContainer.set_cbar_minorticks 

---

.travis.yml
appveyor.yml
tests/test_requirements.txt

Following fixes were applied:
* Specify the mpl version on appveyor (mpl==3.2.0 contains a bug)
* Bump mpi4py to fix build failure on Travis
* Add -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H to CFLAGS to fix Cartopy
build on Travis

Update CI recipes to fix recent failures

---

yt/data_objects/static_output.py
yt/utilities/answer_testing/framework.py

this is a follow up to #2475 
~I added a test to the answer test framework to ensure the error corrected in #2475 doesn't show up again in the future. Admittedly the test is in fact necessary but not sufficient, as broken frontends may consistently pass it, unless there's a test dataset that happens to be fully refined.~
edit : the PR's focus was changed to making the Dataset.min_level attribute consistent with the actual value, mimicking the existing Dataset.max_level property

A consistent implementation for Dataset.min_level

---

yt/utilities/load_sample.py

There was an issue with load_sample that a dataset would get loaded, but the ds ended up being a NoneType. The load_sample function wasn't returning the loader, which is fixed in this PR.

Fix load_sample function

---

doc/source/analyzing/objects.rst

During our yt tutorial today, it came up that the disk region was a little confusing in that the height is measured from the midplane and not top to bottom of the cylinder.  This PR adds a clarification to the region objects overview docs.

clarify that the "height" in a disk region is from the midplane

---

CONTRIBUTING.rst

@zingale and I noticed that our communication channels said that IRC is the first stop for communication. Given that we're generally using slack more now, this should probably be removed.

remove IRC from communication channels

---

doc/source/reference/configuration.rst

fix #2439 
It's possible that doing this (stripping `"` and `'` from values in the rcfile) is actually not a good idea for reasons I'm not aware of.

Update documentation to reflect usage of rcfile (no brackets allowed)

---

doc/source/analyzing/astropy_integrations.rst
doc/source/analyzing/generating_processed_data.rst
doc/source/conf.py
yt/data_objects/data_containers.py
yt/data_objects/profiles.py
yt/data_objects/tests/test_data_containers.py
yt/data_objects/tests/test_profiles.py

yt already has some capability to export fields from a data container to [pandas `DataFrame`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html) objects. This PR adds the capability to export the same kind of data to an [AstroPy QTable](https://docs.astropy.org/en/stable/api/astropy.table.QTable.html), which is a similar object and preserves the unit information. 
I've also added this export capability for both types to 1D profile objects, with an option for exporting unused bins (with masking) or leaving them out. 
I've added documentation for all of these features and new tests.

Export data container and profile fields to AstroPy QTables and pandas DataFrames

---

doc/source/visualizing/callbacks.rst
yt/visualization/plot_modifications.py

I’m looking to extend support for some of them to non-cartesian geometries.
As an experiment, I’ve just added “polar” to the list of supported geometries in `LinePlotCallback` and `SpherePlotCallback`. It seems to work just fine, though there's one case where the behaviour might not be what the user expects. Namely, with `coord_system="data"`, the start-point and end-point coordinates are passed as cartesian coords, instead of the actual data coordinate system.
For instance
```python
import yt
ds = yt.load("amrvac/bw_polar_2D0000.dat")
p = yt.plot_2d(ds, "density")
p.annotate_line([-2, 1, 0], [2, -1, 0], coord_system="data")
```
This looks fine-ish to me as long as it is documented as such, which seems to me like the way to go, as of now.

extend support of some plot callbacks to polar geometries

---

yt/utilities/png_writer.py

As noted in https://github.com/matplotlib/matplotlib/pull/15095,
matplotlib's png module now only takes file-like objects.  This should
fix our usage of it to conform with that.

Update to matplotlib's current png interface

---

yt/data_objects/region_expression.py
yt/data_objects/tests/test_dataset_access.py

Currently, `ds.r[...]` only works with 3D datasets (hardcoded limitation). I'm extending it to 2D datasets. As I'm writing this, it stands as a proof of concept because some use cases are not treated yet.
```python
ds = yt.load("amrvac/bw_2d0000.dat")
p1 = yt.plot_2d(ds, "density")
p1.set_figure_size(3)
p1.save("/tmp/spherical_alldata")
r = ds.r[:, np.pi/3:2/3*np.pi]
p2 = yt.plot_2d(ds, "density", data_source=r)
p2.set_figure_size(3)
p2.save("/tmp/spherical_azim_selection")
r = ds.r[1.3:2.6, np.pi/3:2/3*np.pi]
p3 = yt.plot_2d(ds, "density", data_source=r)
p3.set_figure_size(3)
p3.save("/tmp/spherical_2d_selection")
```
- any idea what sort of test should be added ?
- as of now, I don't understand the purpose of the `nslices` variable in `RegionExpression.__getitem__` so I'm only dealing …

Extend region expression to 2d datasets

---

doc/source/developing/testing.rst
tests/tests.yaml
yt/geometry/coordinates/coordinate_handler.py
yt/geometry/coordinates/cylindrical_coordinates.py
yt/geometry/coordinates/geographic_coordinates.py
yt/geometry/coordinates/spherical_coordinates.py
yt/geometry/coordinates/tests/test_axial_pixelization.py
yt/geometry/coordinates/tests/test_cylindrical_coordinates.py
yt/testing.py
yt/utilities/answer_testing/framework.py

Fix #2480 
@matthewturk was **one** character away from this fix in the embedded discussion.
I spent an unreasonable amount of time trying to find _where_ I could write a workaround the matplotlib warning triggered by using `np.nan` as a filler value, but in the end I discovered that, while `-np.inf` indeed breaks everything (as noted by @chverbeke)  `np.inf` will do the job perfectly.
Issue solved, no warning, no problem 👏 
For closure, I tested this using
- matplotlib 3.1.3
- 1.18.1

hotfix: bug in cylindrical coordinates background color with log norm

---

README.md

This should resolve yt-project/yt#2216 for the yt source repo; I've added a few things:
- A donation badge to to the top of the readme
- A short section at the bottom of the readme that we're a numfocus-sponsored project.

add donation badge and numfocus section to README

---

yt/data_objects/static_output.py
yt/fields/field_info_container.py
yt/fields/fluid_fields.py
yt/fields/tests/test_fields.py

Gradient computation is marginally more complex in curvilinear geometries.
Here I give a first sketch of an extension for `Dataset.add_gradient_fields` to `cylindrical` and `polar` coordinates.
Note that, for a `"polar"` (2D) dataset, plotting a meaningful gradient field in the radial direction is currently tricky because of boundary issues. Indeed the two usual workarounds are compromised, respectively because
- it makes little sense to assume/overwrite periodicity in that particular direction
- selecting a radially narrow region with e.g. `ds.r[1:2, :]` is currently not working in 2D, but a fix is in the making here https://github.com/yt-project/yt/pull/2482
I'll add visualisation examples here when this point is solved.
about the second point: I made a choice in the computation of the …

Extend Dataset.add_gradient_fields to curvilinear geometries

---

yt/frontends/artio/fields.py

This resolves the issue reported in yt-project/yt#2481
I've added pressure units based on the discussion in that PR, but I'd love for any users or contributors that are familiar with that code to weigh in here. Does this introduce any weird changes? I've looked at the logs and it seems like @matthewturk was the last to touch the units part of this frontend, but the commit message for the comment seems to stem from a conversation with Sam and Doug? 
Anyways, let me know if this works. 
Updates the pressure field units in the artio frontend to be `code_mass / (code_length * code_time**2)`. With this patch, the pressure field has the units talked about in the issue. 
input:
```
ds.field_info['gas','temperature']
ds.field_info['gas','density']
ds.field_info['gas','pressure']
```
output:
``` …
```

update pressure units for artio frontend

---

yt/visualization/plot_modifications.py

Consider the following script 
```python
import yt
yt.mylog.setLevel(30)
ds = yt.testing.fake_amr_ds()
sp = yt.SlicePlot(ds, "z", "Density")
sp.annotate_grids()
```
Currently, this will log the following warning
```
yt : [WARNING  ] 2020-04-11 15:28:30,915 Supplied id_loc but draw_ids is False. Not drawing grid ids
```
Despite the fact that the user did not supply any value to those parameters.
This change ensures that the warning only appears if a collision is detected in user defined values.

refactor annotate_grids callback

---

yt/frontends/amrvac/data_structures.py

hotfix a bug in amrvac frontend where 'default' geometry would cause a ValueError to be raised.

[AMRVAC] bugfix geometry parsing

---

yt/frontends/arepo/fields.py

Addressing issue #2433
This PR puts the units into the field GFM_StellarFormationTime which is otherwise given as dimensionless.

putting in units in for the AREPO GFM_StellarFormationTime

---

yt/visualization/plot_container.py

fix a bug in PlotContainer.set_minorticks  where passing booleans would always set the property to `False`.
This is cherry picked from https://github.com/yt-project/yt/pull/2525, to be applicable independently.

fix a bug in PlotContainer.set_minorticks 

---

yt/frontends/athena/fields.py

This is necessary so that the primary item in a binary operation in unyt has the necessary entry in the unit registry (specifically code_pressure).

Change order of operations.

---

doc/source/reference/configuration.rst
yt/funcs.py

As a user, I find the plugin feature of yt too restrictive as it currently allows to have only *one* plugin file per system, which makes it a unsuited for more local definitions. Say I have a project-specific-folder full of notebooks to analyse closely related datasets, then it makes sense to me to have companion a plugin file within the same folder. It would make it easier for me to work with collaborators if we simply share the notebooks' folder, and none of us would have to worry about collisions with our own private, system-wide plugins.
This change makes this use-case possible so that a user can organise a folder such as:
```bash
.
└── notebooks
├── yt_pluging.py
    └── notebook.ipynb
```
where `notebook.ipynb` would open as
```python
import yt
yt.enable_plugins("yt_pluging.py")
```

Allow for local plugin file (not system wide)

---

yt/visualization/tests/test_callbacks.py

I realised that my test in the just-merged PR https://github.com/yt-project/yt/pull/2525
wasn't catching a potential bug where callback decorated with `@accepts_all_fields`, called for one field would apply to all existing fields.

Test enhancement for #2525

---

yt/funcs.py

With recent enough versions of matplotlib and if PIL (pillow) is installed, matplotlib is able to export to jpeg.
When it's not, it raises perfectly sensible errors such as
```
ValueError: Format "jpg" is not supported.
Supported formats: eps, pdf, pgf, png, ps, raw, rgba, svg, svgz.
```
Thus, I don't think there's a good case for preventing exporting to jpg within yt, which is currently the case because of how `get_image_suffix` is implemented.

add explicit support for jpeg exports

---

doc/source/visualizing/callbacks.rst
yt/visualization/plot_window.py

The `annotate_clear()` method takes an optional index of the annotation to remove, but there
is not high-level method to see the indices of the currently applied annotations. This adds a list_annotations() method to allow us to see what annotations are currently applied.
This reissues #2498.

add a list_annotations() method

---

tests/tests.yaml
yt/utilities/answer_testing/framework.py

This changes our testing to *not* compare `weight_field` in our projection values tests, and it also changes our tests to return unitful arrays from the `FieldValues` test.
I believe that this *should* pass as-is, and then I will update the `tests.yaml` to store new versions of the tests so we retain units in them.
Following this, we can unblock #2568 , where we will identify the items that need updates there, as well.

Store unitful field values and don't compare weight fields

---

yt/data_objects/profiles.py
yt/data_objects/tests/test_profiles.py

This adds units to profile weight fields, so the following works.
```
ds = yt.load(...)
p = yt.create_profile(..., weight_field=<not None>)
print (p.weight.units)
```
Currently `p.weight` is just a numpy array without units.

[bugfix] add units to profile weight field

---

tests/tests.yaml
yt/visualization/plot_window.py

fix #2543 
I tried respecting the original intended logic tree but I didn't test in the case `MPL_VERSION < 2.0`.
I expect a lot of image comparison tests should fail because, as it turns out, colorbar minor ticks are in fact supposed to be _on_ by default, althewhile being impossible to actually draw in log transforms with MPL > 2.
A work around those failure would be to embrace the de facto default behaviour (no colorbar minor ticks).

bugfix colormap minorticks

---

yt/frontends/enzo/simulation_handling.py

Properly initialize `my_initial_time` in `EnzoSimulation.get_time_series`

[EnzoSimulation] Ensure that my_initial_time is initialized. Fixes #2578

---

tests/tests.yaml
yt/frontends/boxlib/data_structures.py
yt/utilities/answer_testing/framework.py
yt/utilities/answer_testing/utils.py

This is a test PR to see if we get any failures that are not *answer value* failures if we change the base unit system for answer tests to `code` universally.
If this works, I will update this with a bit more of the rationale, and I will post to the yt mailing list.  It is not mergable as-is.

Change the default answer test unit system to code

---

setup.py

In python3.8 on OSX multiprocessing switched from *fork*ing to *spawn*ing. In order to prevent parallel cythonize messing up the concurrency `setup()` has to be executed only on the main process.

Execute setup only on a parent thread to prevent a failure with spawn

---

yt/data_objects/static_output.py

This coerces `mx`, `my`, and `mz` to `code_length` prior to creating an array.  It only does this for *dimensionless* quantities, as this is where we're *specifically* hitting the issue with the AMRVAC frontend.
This eliminates a couple hundred test failures in #2437.  In the absence of a hetereogeneously-united array, this is the best I could figure out.

Coerce mx, my, mz to code-length

---

yt/frontends/boxlib/io.py

I was trying to read raw fields from a plotfiles coming from a WarpX simulation and I encountered a bug occuring when there is no ghost cells. The bug occurs when doing something like:
```python
import yt
ds = yt.load("diags/diag100200")
Ex_raw = ad['raw','Ex_aux']
```
And the error message is:
```
File "./analysis_reduced_diags.py", line 58, in <module>
Ex_raw = ad['raw','Ex_aux'].to_ndarray()[:,0]
File ".../yt/data_objects/data_containers.py", line 256, in __getitem__
self.get_data(f)
File ".../yt/data_objects/data_containers.py", line 1571, in get_data
fluids, self, self._current_chunk)
File ".../yt/geometry/geometry_handler.py", line 244, in _read_fluid_fields
chunk_size)
File ".../yt/frontends/boxlib/io.py", line 66, in …
```

Fix bug with raw fields when there is no ghost cells

---

tests/tests.yaml
yt/convenience.py
yt/tests/test_load_from_path.py

this is a second try after #2392 
This PR is targeting yt-4.0 as the feature is much more easy to write for python 3.6 and above.
if we want to support python 3.5 too, an additional step is required to convert pathlike-non-str input to str.

allow loading from path objects (py3.6 or above)

---

yt/visualization/plot_container.py

Because `set_zlim` only accepts floats, combining `pw.set_zlim` with `pw.set_unit` can create some unexpected results. For instance, this script is valid though hardly reliable
```python
import yt
ds = yt.testing.fake_amr_ds(fields=["density"])
p = yt.SlicePlot(ds, "z", "density")
my_min, _ = ds.find_min("density")    # returns a YTQuantity in cgs 
p.set_unit("density", "kg/mm**3")
zmin = my_min.value  # naive conversion to float 
p.set_zlim("density", zmin=zmin, zmax=10*zmin)   # <- now, it is incorrectly assumed that zmin is expressed in  "kg/mm**3"
```
With this change, set_zlim correctly handles zmin and zmax if they are YTQuantity objects, or tuples that convert to it.

make set_zlim units aware (sanitize zmin and zmax)

---

yt/visualization/plot_window.py

This fixes the issue reported on the mailing list where the center keyword was having no effect on projections made after using `save_as_dataset`.

[bugfix] Pass center kwarg on to reloaded projection dataset.

---

doc/source/analyzing/analysis_modules/absorption_spectrum.rst
doc/source/developing/external_analysis.rst
yt/analysis_modules/cosmological_observation/light_cone/tests/test_light_cone.py
yt/units/yt_array.py
yt/utilities/answer_testing/answer_tests.py

h5py is changing to require the mode (`'r'`, `'w'`, etc) specified when `h5py.File` is used.  The Debian version of h5py has already applied the upstream commits making this mandatory, which require this patch.
For reference: This was [Debian#960573](https://bugs.debian.org/960573), and we [fixed this locally in release 3.6.0-3](https://salsa.debian.org/debian-astro-team/yt/-/blob/6cf4a4d9ee190913b3648cd2291738f4cb601cf7/debian/patches/Add-mode-argument-to-h5py.File.patch).

Add mode argument to h5py.File

---

yt/frontends/gadget/data_structures.py
yt/frontends/sdf/data_structures.py
yt/frontends/tipsy/data_structures.py
yt/geometry/particle_geometry_handler.py

Added a `ds.domain_override` when a `bbox` is applied to a dataset. This prevents the particle index from caching which ensures the particle selection is correct. Fixes #2612 
- *NA* New features are documented, with docstrings and narrative docs
- *NA* Adds a test for any bugs fixed. Adds tests for new features.

[yt-4.0] added domain_overrride to fix bbox

---

yt/visualization/plot_modifications.py

This fixes an issue reported on the mailing list. If `annotate_scale` is called with `coeff` set but `unit` not set, `coeff` is clobbered and set to 1.

[bugfix] Don't clobber coeff if units not given in annotate_scale

---

yt/units/yt_array.py

When saving an array to hdf5 file open the file read/write if it exists, create it otherwise.
Without this PR documentation build is failing.

Use 'a' mode for saving arrays to hdf. Fixes #2642

---

yt/frontends/ahf/tests/test_outputs.py
yt/frontends/arepo/tests/test_outputs.py
yt/frontends/art/tests/test_outputs.py
yt/frontends/eagle/tests/test_outputs.py
yt/frontends/flash/tests/test_outputs.py
yt/frontends/gadget/tests/test_outputs.py
yt/frontends/gadget_fof/tests/test_outputs.py
yt/frontends/owls/tests/test_outputs.py
yt/frontends/rockstar/tests/test_outputs.py
yt/frontends/swift/tests/test_outputs.py
yt/frontends/tipsy/tests/test_outputs.py
yt/testing.py

This starts to pull some code out of the particle tests specifically and putting them in the base class, as per #2616 .
Please feel free to push to this branch.

Abstract some particle tests

---

yt/frontends/flash/tests/test_outputs.py
yt/utilities/answer_testing/framework.py

This adds answer tests for the nbody-only dataset in FLASH, and will allow other nbody-only answer tests to be added as well.
This uses the `ParticleProjectionPlot` to generate the data.  This is a blocker for #2437 but needs to be reviewed independently.

Adding nbody answer tests using particle plots

---

yt/geometry/coordinates/cartesian_coordinates.py

This showed up when generating the gallery using the `TipsyGalaxy` dataset.  What would happen is that if you set the width to `(1.0, 'unitary')` it would extend the *plot* beyond the edge of the domain, which would then create a *region* that went beyond the edge of the domain, and then break because the dataset wasn't periodic.  This prevents that from happening.

Don't allow edges to extend beyond domain for SPH region sources.

---

yt/fields/field_aliases.py
yt/frontends/artio/fields.py

Modified ARTIO variable names to YTEP-0003 conventions for Issue #2608 
Question:  @provider10 and I would like to make sure that folks using the other field names can easily use (and know to use) the back-compatibility functionality. We are open to any thoughts or suggestions for putting in a specific error message for ARTIO users to let them know that they are missing the if the ds._setup_deprecated_fields() if the user has not added it, which we can add before this PR is merged.
Addresses: Issue #2608

Modified artio frontend fields to ytep 0003 conv: Issue/2608/artio

---

doc/source/cookbook/find_clumps.py
doc/source/reference/api/api.rst
doc/source/visualizing/callbacks.rst
yt/visualization/plot_window.py

Makes the functionality of the `annotate_clear` method, well, clearer, by changing it to `clear_annotations`.
Addresses https://github.com/yt-project/yt/issues/2564

annotate_clear -> clear_annotations

---

yt/geometry/selection_routines.pyx

Prior to this PR the code says if the edges of the selected region are equal to the domain edges then we need to return **every** particle stored on disk.
This is **not true** if a bounding box has been applied. I've added a check for a `_domain_override`
This fixes the example I posted in #2612

[yt-4.0] check for bbox before reverting to all_data

---

yt/data_objects/static_output.py
yt/frontends/_skeleton/data_structures.py
yt/frontends/ahf/data_structures.py
yt/frontends/art/data_structures.py
yt/frontends/artio/data_structures.py
yt/frontends/chombo/data_structures.py
yt/frontends/enzo/data_structures.py
yt/frontends/enzo_p/data_structures.py
yt/frontends/fits/data_structures.py
yt/frontends/flash/data_structures.py
yt/frontends/gadget/data_structures.py
yt/frontends/gadget_fof/data_structures.py
yt/frontends/gamer/data_structures.py
yt/frontends/owls_subfind/data_structures.py
yt/frontends/ramses/data_structures.py
yt/frontends/rockstar/data_structures.py
yt/frontends/sdf/data_structures.py
yt/frontends/tipsy/data_structures.py
yt/frontends/ytdata/data_structures.py

(Originally intended as part of #2556, but this change affects a lot of files and is much easier to review separately so I'm opening a dedicated PR.)
Most code frontends copy-paste the same exact line to set up `Dataset.unique_identifier`.
By making it a property, with a setter for rare cases where we _don't_ want to use the widespread implementation, we keep flexibility while reducing copied code.
⚠️ The following frontends required very minor adjustments that _may_ change the behaviour for this attribute, though I think it's unlikely. Namely
- sdf : had a try/except block with no specific exception to catch, I don't see what's there to be caught so I just removed it
- enzo : was defaulting to the same exact identifier constructor than default _except_ it was converting it to `str`. …

Dataset abstraction: Default unique identifier

---

yt/frontends/enzo_p/fields.py

By changing the order of operations we no longer raise RecursionError.

Changing the order of ops to prevent unyt error. Fixes #2662

---

yt/utilities/load_sample.py

building on top of #2417, use progress bar already offered by pooch.
I chose to set `pbar=True` by default. Also this capability requires tqdm to be installed.

add progress bar display for yt.load_sample() (requires tqdm)

---

tests/tests.yaml
yt/frontends/amrvac/tests/test_outputs.py

@Xarthisius  brought up on Slack that answer testing time is currently dominated by AMRVAC's tests because of the shear number of fields tested against.
This is an attempt at reducing this testing time by checking a reduced number of derived field that should still hit every on-disk fields.

CI: optimize testing time for AMRVAC

---

tests/tests.yaml
yt/frontends/arepo/tests/test_outputs.py
yt/frontends/owls_subfind/tests/test_outputs.py
yt/frontends/ramses/tests/test_outputs.py
yt/testing.py
yt/utilities/tests/test_minimal_representation.py

WIthout this, *any* test wrapped with `requires_file` isn't run and is marked as ok by the testing suite.
A quick grep through the code indicates that this affects 200 tests :(.

[BUGFIX] Call function wrapped with requires_file

---

yt/frontends/ramses/data_structures.py

Recent versions of f90nml (>=1.2.0), which is used to read the parameter file RAMSES uses, fail with a `StopIteration` instead of `ValueError`. This PR adapts to capture this new exception.

[BUGFIX] Prevent RAMSES fail with recent versions of `f90nml`

---

yt/data_objects/octree_subset.py
yt/geometry/tests/test_particle_deposit.py

Fixes mesh sampling functions. This was due to "convert_to_units" being an in-place operation, so that there were no positions passed to the mesh deposition mechanism.

[BUGFIX] ValueError with mesh deposition mechanism

---

setup.py

This allows the user to set a maximum number of cores to use for the build. This is helpful on shared systems where jobs using all available cores get terminated.

Allow throttling of number of cores for build.

---

yt/frontends/arepo/tests/test_outputs.py
yt/frontends/open_pmd/tests/test_outputs.py

This should fix the OpenPMD errors appearing in #2677.
Update: I sneaked in a minor cosmetic fix for Arepo, that I botched in #2677. It's only avoiding doing the same thing twice.

Update OpenPMD test to include 'nbody' ptype

---

yt/frontends/art/io.py

This is a bugfix to resolve yt-project/yt#2646 . 
A similar fix was implemented in yt-project/yt#2448. Here I've made the last argument in logspace explicitly labeled with the `num` kwarg, so it's consistent with updated numpy docs. I also call `int` on the variable so we don't get the error reported in the issue. 
I also updated an inline comment to be consistent with this change in the code. 
Note: this is a quick bugfix for the art frontend. I'll probably submit a later PR to address similar ambiguities in the codebase. 
@claytonstrawn I can load art frontend files with this fix applied.

[bugfix] update art frontend to be compatible with numpy 1.18

---

yt/testing.py

As noted in #2677, we're getting errors with Rockstar.  The arrays differ by about 1e-14, which is likely due to roundtripping unit conversions in different precisions.  This allows for wiggle room in the comparison of 5 units in the last place of the floating point values.

Fix Rockstar PSC tests with a nulp check

---

tests/tests.yaml
yt/frontends/amrvac/tests/test_outputs.py

This fixes the filename used in tests to match what we have on disk.
Note: I also noticed that `Richtmyer_Meshkov_dust_2D` was missing on the testing box, so this PR should yield a lot of NoOldAnswer. I'll bump answer store, once I see that's the case.

Fix khi_cartesian_2D filename

---

setup.py

I was not able to get yt to compile on NASA's Pleiades machine because of errors when compiling `ewah_bool_wrap.pxd`. Setting the C++11 flag fixes it. 
Fixes issue #2685.

[bugfix] ewah_bool_wrap needs C++11 on some Linux machines

---

yt/frontends/art/data_structures.py
yt/frontends/art/io.py
yt/frontends/art/tests/test_outputs.py

Removes tests that are intended for particle datasets. They were incorrectly run on ART, an octree dataset.

[BUGFIX] Art: fix dm_only frontend

---

yt/data_objects/static_output.py
yt/fields/local_fields.py

Very quick PR to promote a warning message to error since it "warns" on code doing nothing.
(as a user I personally set logger to error level and this feels like something even I should be informed of)
I'm noting that there's a lot of code duplication in those functions, I'll try to address that in a separate PR.

promote log message from warning to error in add_field methods

---

yt/convenience.py
yt/data_objects/tests/test_time_series.py
yt/data_objects/time_series.py

This is part of an effort to harmonise and simplify the data loading api.
This PR includes the following improvements to `DatasetSeries`:
- deprecate `DatasetSeries.from_filenames()` because it's redundant since `DatasetSeries.__new__` was added, and I suspect it is not used
- fix a docstring inconsistency
- add tests for pattern detection
- refactor the pattern parsing function (simplify + add `'~'` token expansion, to improve consistency between `DatasetSeries()` and `yt.load()`)
⚠️ **minor backward incompatibility**
I changed the error raised in the pattern parsing function to `FileNotFoundError` to better reflect the issue, this could potentially break downstream code that relies on this function throwing `YTOutputNotIdentified`, though it seems very unlikely.

Time series enhancements

---

appveyor.yml
setup.py
tests/test_minimal_requirements.txt
tests/test_requirements.txt

We had been installing unyt from git, but this bumps the requirement to
the newly-released 2.7.2.

Bump unyt to 2.7.2

---

yt/testing.py

This offsets the particle selection centers, as in unitary coordinates
that cross over the origin the left edge is not at 0, 'unitary'.  This
makes checks for periodicity in these cases (i.e., PKDGrav) more useful.

Offset particle selection test for unitary coords

---

yt/visualization/profile_plotter.py

Because of the way it's currently implemented, `ProfilePlot` produces unintuitive results when passed `x_log=None`, which is effectively, equivalent has passing `x_log=True` despite the fact that `bool(None)==False`.
with this change, the following produce the same result
```python
import yt
ds = yt.testing.fake_random_ds(128)
yt.ProfilePlot(ds, 'y', ['density', "velocity_magnitude"], n_bins=500, x_log=None)
yt.ProfilePlot(ds, 'y', ['density', "velocity_magnitude"], n_bins=500, x_log=0)
yt.ProfilePlot(ds, 'y', ['density', "velocity_magnitude"], n_bins=500, x_log=False)
```
This issue was reported on slack by Jack Jenkins.
I'm opening this as a draft since there may be other appropriate changes to ProfilePlot.__init__() that could go with it.

fix an unintuitive behaviour in ProfilePlot

---

yt/data_objects/data_containers.py
yt/data_objects/region_expression.py

fix #2397
This is a simple implementation of the `_ipython_key_completion_` method for data objects.
**example**
**limitation**
I couldn't find how to make it work with the double key syntax yet, e.g
```python
ad["gas", "<TAB>
```

Fields autocompletion for data objects

---

yt/frontends/gadget_fof/data_structures.py
yt/frontends/gadget_fof/io.py
yt/frontends/gadget_fof/tests/test_outputs.py

This adds the IDs particle type to the list of particle types to check
in the Gadget FOF frontend.  It should eliminate the error seen in the
test suite on Fido.

Make sure we include IDs as a particle type in Gadget FOF

---

yt/visualization/profile_plotter.py

Fixing a couple typos in the docstring examples in yt/visualization/profile_plotter.py for ProfilePlot and PhasePlot

Docstring example corrections for profile_plotter

---

tests/test_requirements.txt
yt/frontends/ytdata/data_structures.py
yt/frontends/ytdata/tests/test_old_outputs.py
yt/frontends/ytdata/tests/test_outputs.py
yt/frontends/ytdata/tests/test_unit.py

This fixes the ytdata tests for me.  What was happening:
```
f.attrs.get("con_args")
```
was returning
```
array([b'axis', b'coord'], dtype='|S5')
```
So when this was getting `eval`'d, it was trying to eval `axiscoord` (or
`normalcenter`) which didn't exist.  So instead let's pull the
individual values, decode them, and assign them.

[BUGFIX] Update con_args parsing for current h5py

---

.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
CONTRIBUTING.rst
setup.cfg
tests/lint_requirements.txt
yt/exthook.py
yt/funcs.py
yt/testing.py

[isort](https://pypi.org/project/isort/) is a tool that automatically sorts import statements.
It can be configured as a precommit hook too, so it should not be necessary to have this kind of PR, updating the whole code base more than once.
Imo, the 4.0 release would be a nice time to include this kind of nitpicky change, though I can easily imagine how the present PR would clog the yt-4.0 -> master merge, so I wouldn't suggest considering it for a merge ahead of this major task.
CURRENT STATE: This PR should include everything needed to smoothly adopt isort, but doesn't run it on the code base as it used to.
- ~OPTIONAL: add a precommit hook ?~ (Done in #2600)

Style: enforce import ordering with isort (YTEP0037 1/6)

---

pyproject.toml

In my work on #2596, I had to tweak the newly added `pyproject.toml` file (required by black for configuration) to make installation of yt with `pip install -e` work properly across python versions (>=3.6).
In order to validate it, I'm opening this separate PR to introduce the file to the repo without all black-related changes.
This file may introduce redundancy with `.travis.yml`, `setup.py`. Sadly, it won't be mergeable with `setup.cfg`, which we use to configure flake8 (currently not supporting pyproject.toml).

Add pyproject.toml (YTEP0037 3/6)

---

tests/lint_requirements.txt
yt/data_objects/tests/test_fluxes.py
yt/frontends/tipsy/data_structures.py
yt/geometry/tests/test_particle_octree.py

We currently run flake8 3.6 on travis. A more recent release (3.8) catches precedently undetected errors.
Important note: there are _more_ errors than the ones I patch here.
This PR is specifically targeted at errors that can't be solved automatically with black.
Namely, these are almost exclusively string formatting errors, with either too many or not enough substitutions declared, as compared with the number of placeholders.

ci: bump flake8 linter version, fix newly detected errors (YTEP0037 2/6)

---

CONTRIBUTING.rst
COPYING.txt
yt/frontends/adaptahop/__init__.py
yt/frontends/adaptahop/data_structures.py
yt/frontends/adaptahop/definitions.py
yt/frontends/adaptahop/fields.py
yt/frontends/adaptahop/io.py
yt/frontends/amrvac/__init__.py
yt/frontends/amrvac/api.py
yt/frontends/amrvac/data_structures.py
yt/frontends/amrvac/fields.py
yt/frontends/amrvac/io.py

Quoting `CONTRIBUTING.rst`
>Source code style guide
>-----------------------
>...
> * We no longer have a copyright blurb in every source file.
This PR removes the surviving occurrences of the copyright header in two frontends and removes the above line from the contributing guide.

Cleanup copyright blurb

---

yt/utilities/png_writer.py

fix #2752
I also simplified `call_png_write_png` since it had two required positional arguments that were actually not used.

hotfix: support matplotlib 3.3.0

---

.pre-commit-config.yaml

As support to #2592 and #2596, add a precommit hook configuration file to allow devs to install  isort, black and flake8 as hooks locally.

Add precommit hooks for flake8, isort and black (YTEP0037 5/6)

---

.git-blame-ignore-revs

I thought I added this already in #2749 but apparently I messed up.
This adds a `.git-blame-ignore-revs` file to mark automated commits as ignorable to git blame, see https://github.com/psf/black#migrating-your-code-style-without-ruining-git-blame

add ignore list for git blame

---

yt/data_objects/region_expression.py

Very simple refactor for `RegionExpression.__getitem__` :
- simplify existing code with try block
- add flexibility for single-slice expansion (previously only expanded to 3D)
```python
ds = yt.load("amrvac/bw_2d0000.dat")
ds.r[1:2]
old >> YTDimensionalityError: Dimensionality specified was 3 but we need 2
new >> YTSlice (bw_2d0000.dat): , axis=2, coord=0.5 cm
```

fix: automatic slice->region expansion support for 1D and 2D datasets

---

.travis.yml
doc/Makefile
tests/test_requirements.txt
tests/tests.yaml
yt/funcs.py
yt/geometry/oct_container.pyx
yt/utilities/command_line.py
yt/utilities/lib/pixelization_routines.pyx
yt/utilities/png_writer.py
yt/utilities/tests/test_config.py
yt/visualization/base_plot_types.py

I'm bumping a few dependencies to minimal versions that have binary wheels for py38 in order to avoid building them each time. In particular `pandas` takes some time to build.

Update test dependencies

---

.travis.yml

Trying to shave off a few minutes of the OSX build. A lot of time is being spent installing and updating things we're not even using.

Disable homebrew update during Travis/OSX build

---

.travis.yml

Put all linting stages in parallel.
This also make black _actually_ be called.

Parallel linting pass

---

appveyor.yml
tests/test_minimal_requirements.txt
tests/test_requirements.txt
yt/data_objects/tests/test_projection.py
yt/data_objects/tests/test_slice.py
yt/visualization/tests/test_particle_plot.py

Currently 10 unit tests account for **25%** of build time on Travis (and I assume appveyor):
```
[success] 5.40% yt.data_objects.tests.test_projection.test_projection: 82.3893s
[success] 4.90% yt.visualization.tests.test_particle_plot.TestParticlePhasePlotSave.test_particle_phase_plot: 74.7280s
[success] 3.55% yt.visualization.tests.test_geo_projections.TestGeoProjections.test_geo_projections: 54.0847s
[success] 2.49% yt.frontends.gadget.tests.test_outputs.test_gadget_binary: 37.9936s
[success] 2.21% yt.visualization.tests.test_particle_plot.TestParticleProjectionPlotSave.test_particle_plot_c: 33.6426s
[success] 1.80% yt.data_objects.tests.test_slice.test_slice: 27.3991s
[success] 1.62% yt.visualization.volume_rendering.tests.test_scene.RotationTest.test_rotation: 24.6765s
[success] 1.14% …
```

Random tests optimization (take 2)

---

yt/frontends/arepo/data_structures.py
yt/utilities/lib/cykdtree/tests/test_kdtree.py

This partly addresses #2666, namely B001 "bare excepts".
This is also a follow up to #2474, and it shows that these kind of code degradation will continue to pop up until we have a linting tool to catch them (flake8-bugbear does the job here !)

fix flake8-bugbear B001 (bare excepts) (YTEP0037 6/6 part 5)

---

yt/testing.py

This addresses part of #2666, namely B008 "Do not perform function calls in argument defaults". The solution here is simply to ignore this error locally since it's only triggered in lines where calling a function in default attrs is the intended behaviour (in test functions).

ignore flake8-bugbear B008 errors (YTEP0037 6/6 part 3)

---

yt/data_objects/profiles.py
yt/data_objects/static_output.py

This partly addresses #2666, namely B010 "Do not call setattr with a constant attribute value"

fix flake8-bugbear B010 errors (YTEP0037 6/6 part 6)

---

yt/visualization/volume_rendering/tests/test_off_axis_SPH.py

This partly addresses #2666, namely it fixes B011 (avoid assert False)

fix flake8-bugbear B011 errors  (YTEP0037 6/6 part 7)

---

doc/source/cookbook/amrkdtree_downsampling.py
doc/source/cookbook/camera_movement.py
doc/source/cookbook/opaque_rendering.py
doc/source/cookbook/sigma_clip.py
doc/source/cookbook/various_lens.py
yt/utilities/answer_testing/answer_tests.py
yt/utilities/answer_testing/framework.py
yt/visualization/volume_rendering/tests/test_lenses.py

This PR removes unnecessary and very costly `.render()` call, since `Scene.save()` explicitly calls `Scene.render()`.

Remove all occurences of VR.render() called right before VR.save()

---

yt/fields/field_info_container.py

fix a broken raise statement (missing positional argument in `YTFieldNotFound` init).
While I'm at it, I'm changing the pattern to EAFP.
edit:
Wait. This error is actually encapsulating another one that's pretty much identical
```python
KeyError: 'No field named blblblb'
During handling of the above exception, another exception occurred:
YTFieldNotFound 
YTFieldNotFound: Could not find field 'blblblb' in MYFILE.
```
So I think the best course of action is simply to get rid of this redundant error-chaining.
But there's worse: I'm getting this while I'm trying to *add* a field to a dataset, so none of these errors makes much sense to me.
-> this is a different problem and is actually fixed with #2638

Hotfix broken raise statement

---

doc/source/cookbook/tests/test_cookbook.py
setup.py
setupext.py
tests/nose_runner.py
yt/frontends/art/io.py
yt/utilities/lodgeit.py

Apparently I missed stuff in https://github.com/yt-project/yt/pull/2641, so here's a follow up

cleanup: remove version checks for python 3

---

doc/source/intro/index.rst
tests/test_requirements.txt

This should fix #2769. Changes in `doc/source/intro/index.rst` are purely cosmetic to trigger docs build for this PR.

Bump IPython version for py38 support. Fixes #2741

---

setup.cfg
tests/lint_requirements.txt
yt/data_objects/data_containers.py
yt/data_objects/particle_container.py
yt/data_objects/selection_data_containers.py
yt/frontends/fits/data_structures.py
yt/frontends/open_pmd/data_structures.py
yt/utilities/answer_testing/answer_tests.py
yt/utilities/lib/cykdtree/plot.py
yt/visualization/eps_writer.py

This PR adds flake8-bugbear to the linting stage for Travis. CI _should_ fail until PRs attached to #2666 are merged.

ci: add flake8-bugbear to travis linting (YTEP0037 6/6 part 0)

---

yt/frontends/gadget/data_structures.py
yt/frontends/gizmo/data_structures.py
yt/frontends/owls/data_structures.py

This PR updates the file detection logic to take .kdtree files into account.

Ignore .kdtree file while detecting format. Fixes #2778

---

tests/tests.yaml
yt/frontends/arepo/fields.py
yt/frontends/arepo/io.py
yt/frontends/eagle/fields.py
yt/frontends/gadget/data_structures.py
yt/frontends/gadget/fields.py
yt/frontends/gadget/io.py
yt/frontends/owls/fields.py

A number of frontends are derived from the `GadgetHDF5Dataset` class (and its associated field info and index classes). Most of the time, the `SmoothingLength` field is included in the dataset, but if not, it needs to be generated. This PR provides the code needed to generate the smoothing length in the event it does not exist. 
If a dataset does not have the `SmoothingLength` field, this PR generates a set of smoothing lengths for the SPH particles which are stored to auxiliary file(s), the number of such files depending on the number of files in the dataset itself. Then the smoothing lengths are read from these files.
I had to touch a lot more files than I would have liked in order to make sure all the parts worked together. This also has side-effects on Arepo datasets (which also do …

Support for Gadget HDF5-like datasets without smoothing lengths included

---

doc/source/visualizing/Volume_Rendering_Tutorial.ipynb
doc/source/visualizing/volume_rendering.rst
yt/visualization/volume_rendering/scene.py
yt/visualization/volume_rendering/tests/test_save_render.py
yt/visualization/volume_rendering/volume_rendering.py

Adds an optional `render` boolean argument to `scene.save()`. Default behavior is `render=True` in which case `scene.save()` will call `scene.render()` prior to saving the image array. If `render=False`, will write the most recently rendered image array if it exists. Useful for avoiding unnecessary calls to `scene.render()` when saving at a range of `sigma_clip` values or when saving an image from a notebook after calling `sc.show()`. 
Includes updates to relevant docstrings. 
Addresses #2733

Adds render option to scene.save to avoid re-rendering

---

setupext.py

I had to make this change to ensure that conda-forge-built environments
were detected by the `in_conda_env` function.

Allow in_conda_env to look for conda-forge

---

.github/workflows/slash-command-dispatch.yml

This PR implements three chatops style commands: `example` (which we can later disable), `rebase` and `black`.
It does not yet work, and will need both the repository for the slash commands transferred over to `yt-project` (it's currently at https://github.com/matthewturk/slash-command-processor ) and the personal access token set correctly.
I also think there's a possibility we want to change some of the parameters, maybe even add `isort`, and set @yt-fido to be the user in charge.  I am planning to issue a PR to YTEP-0037 as well.

Slash commands

---

.github/PULL_REQUEST_TEMPLATE.md
.pre-commit-config.yaml
tests/lint_requirements.txt

Something I did not consider when I added the pre-commit hooks is the order in which they trigger :
sometimes `flake8` errors are automatically fixed by `black` or `isort` so it's cleaner to run the `flake8` check last.
Note to early adopters: once this goes in, you won't need to reinstall the hooks to take advantage of this change :)
I'm also changing the PR template to reflect this order (may save a few minutes of work to contributors if they don't realise most of there flake8 errors can be solved automatically).

update pre-commit hooks

---

setup.cfg
yt/data_objects/data_containers.py
yt/data_objects/region_expression.py
yt/data_objects/tests/test_regions.py

Region selection mostly feels like array slicing with magic, though there's one way to write array slicing that is currently not supported in yt : ellipsis `...` !
This PR adds support for this by expanding an ellipsis into the required number of `slice` instances.
For reference here's yt's current behaviour:
```python
ds = yt.testing.fake_amr_ds()
reg1 = ds.r[...]  # is equivalent to ds.r[:,:,:]
old >> TypeError: object of type 'ellipsis' has no len()
reg2 = ds.r[(1, "cm"), ...]  # is equivalent to ds.r[(1, "cm"),:,:]
old >> YTDimensionalityError: Dimensionality specified was 2 but we need 3
reg3 = ds.r[..., (1, "cm"), ...]  
old >> RuntimeError: unyt_quantity values must be numeric
new >> IndexError: an index can only have a single ellipsis ('...')
```
Note: I'm not currently aware of …

add support for region selection with numpy-like ellipsis syntax

---

doc/install_script.sh

Since we no longer set the INST_PY3 variable, we don't need to check it.  This resulted in a syntax error previously, although it was able to finish the script.

This fixes a non-fatal error in the install script.

---

setupext.py

Turns out, you can't append to a string.  I don't know quite why this happened the way that it did for me, but some combination of environmental variables did it.  This fixes the build on my system.

Fix conda_env embree checks

---

yt/data_objects/static_output.py
yt/data_objects/tests/test_data_containers.py
yt/utilities/exceptions.py

Currently, when `Dataset._get_field_info()` is fed bad data (unfindable field), it raises an error which contains a seemingly random `ftype` value, unrelated to external input.
This fixes it
```python
import yt
ds = yt.testing.fake_amr_ds()
ds.r["hello"]
old >> YTFieldNotFound: Could not find field '('stream', 'hello')' in AMRGridData.
new >> YTFieldNotFound: Could not find field ('unknown', 'hello') in AMRGridData.
```

Fix Dataset._get_field_info() error message for unfindable field

---

doc/source/cookbook/amrkdtree_downsampling.py
yt/visualization/volume_rendering/transfer_functions.py

The exponent in the latex label needs to be in `{}` if it is not a positive single digit, otherwise it does not render entirely as a superscript.

fix latex rendering of the transfer function

---

yt/frontends/amrvac/data_structures.py

follow up to #2715 and fix #2710
Renouncing interpolation/smoothing allows to generate _a_ plot. It has artefacts but it's clearly better than just throwing an error imo.
This is a _hotfix_, it's clean but it doesn't address the root problem which is that we don't have proper ghost-zone reconstruction yet in the frontend.
```python
import yt
ds = yt.load("amrvac/jk20200500.dat")
ds.periodicity = 3*[True]
plot = yt.plot_2d(ds, "vorticity_magnitude")
plot.save("/tmp/jake2")
plot.annotate_grids()
plot.save("/tmp/jake2_grid")
>> RuntimeWarning: ghost-zones interpolation/smoothing is not currently supported for AMRVAC data.
```

[AMRVAC] hotfix for ghost-zones dependent fields computations

---

yt/visualization/volume_rendering/tests/test_lenses.py
yt/visualization/volume_rendering/tests/test_scene.py
yt/visualization/volume_rendering/tests/test_sigma_clip.py
yt/visualization/volume_rendering/tests/test_varia.py

This PR modifies the tests to avoid situation where code paths are tested more than once, e.g. it's sufficient to rotate vr scene once instead of 5 times to check if it works. Same goes for rendering the same scene over and over again for each possible image suffix...

Remove some redundancy in VR tests

---

yt/data_objects/grid_patch.py

This pull request corrects how `AMRGridPatch` handles sibling grids (`OverlappingSiblings`) when calculating `child_mask` and `child_index_mask` by passing `dlevel=0` to all relevant calls to `_fill_child_mask`. This parameter specifies the number of refinement levels by which the two grids differ and is used to compare indices between them. The default value of `dlevel=1` is appropriate for true child grids (in the sense that they belong to the next highest refinement level),  but for siblings at the same level this should be called with `dlevel=0`.
This appears to have been addressed a while back in 8ef99073fa8fbd5b4b4af3cb828e801815ee3ede, but it was (unintentionally it seems) reverted with fcaa302a89f4edb8ffb23d9cef60c9a7717a89a5.

Correct child mask for sibling grids

---

README.md

The coverage badge is currently essentially useless since we do not upload test reports at the moment.
I think it'd be preferable to deactivate it until we have a way of generating coverage reports that doesn't significantly impede the CI speed. 
Not really a "fix", but related to https://github.com/yt-project/yt/issues/2780

Deactivate coverage badge

---

.pre-commit-config.yaml
.travis.yml
tests/lint_requirements.txt

A very quick followup to the "flyting" Prs we just merged. Flynt just got a new `--version` option so there's no need for the workaround on Travis anymore.

update flynt version

---

yt/frontends/stream/tests/test_stream_unstructured.py
yt/geometry/selection_routines.pyx

This adds a check to the `SliceSelector`.  When we are slicing along an axis that is greater than or equal to the dimensionality of the dataset, we want to always say "yes" we are selecting a zone.
Note that I did not modify the grid selection, since it *should* work out of the box with the way we clip to the edges.
There may be other objects that need this, but Slice is the most obvious one from my reading.
This should fix the Phantom Bugs in the other PRs, and I've also added a test (that fails without this changeset) to verify it's working.

Add a check for reduced dimensionality slices

---

yt/data_objects/static_output.py

This fix inconsistencies between `Dataset.find_min` and `Dataset.find_max` methods by making special cases of a new, more general class method `Dataset._find_extremum`.
For non-cartesian datasets, `find_min` didn't contain the "hack" from `find_max` to handle dimensionless coords
```python
import yt
ds = yt.load("amrvac/bw_2d0000.dat") # polar dataset
ds.find_max("density")
>> (unyt_quantity(6.9545098e-24, 'g/cm**3'), unyt_array([1.5703125 , 1.71756761, 0.5       ], 'code_length'))
ds.find_min("density")
old >> IterableUnitCoercionError: Received a list or tuple of quantities with nonuniform units: [unyt_quantity(0.9921875, 'cm'), unyt_quantity(3.16613635, '(dimensionless)'), unyt_quantity(0.5, 'cm')]
new >> (unyt_quantity(2.82470365e-25, 'g/cm**3'), unyt_array([2.0078125 , 1.55950623, …
```

fix: min/max detection consistency

---

doc/source/reference/api/api.rst
yt/frontends/amrvac/__init__.py
yt/frontends/amrvac/api.py
yt/frontends/amrvac/io.py
yt/frontends/amrvac/tests/test_read_amrvac_namelist.py

automatically expand '~' token… and natively support pathlike objects

[AMRVAC] fix: improve read_amrvac_namelist api 

---

yt/data_objects/construction_data_containers.py
yt/fields/field_exceptions.py
yt/geometry/selection_routines.pyx

A semi-fix to #2710 
The core issue in #2710 is that we don't have ghost-zone reconstruction in the AMRVAC frontend.
With this change, instead of crashing, yt logs an error message pointing to the defective class for lacking ghost-on support.
Results are obviously buggy (see below) but it's still better than nothing and at least the user gets a better idea what's wrong.

fix: log error instead of crashing in smoothed grid computation if ghost-zones can't be reconstructed

---

yt/data_objects/octree_subset.py
yt/frontends/ramses/data_structures.py

Adds support for vertex centred data. This has the effect of making isocontours possible on octree datasets using the same API as for the rest of yt.
This should be merged after #2425 has been merged. I marked it as draft to prevent people from reviewing it, since many files have been modified in the aforementioned PRs.
This allows for example to export a dataset to [sketchfab](https://skfb.ly/6SXyJ).
Note that in its current form, the isosurface algorithm does work. However, it is very slow as it performs the marching cube algorithm on each _individual oct_. It also returns a non-connected set of points (that represent the isosurface), since the output of the marching cube algorithms aren't stitched together. Note that a quick hack would be to merge vertices of the isosurface if they are …

Support vertex centred data

---

yt/data_objects/octree_subset.py
yt/frontends/adaptahop/data_structures.py
yt/frontends/art/data_structures.py
yt/frontends/gadget_fof/data_structures.py
yt/frontends/halo_catalog/data_structures.py
yt/frontends/owls_subfind/data_structures.py
yt/geometry/particle_geometry_handler.py

This converts two attributes of `ParticleIndex`, `data_files` and `total_particles`, into properties that call `ParticleIndex._setup_filenames` under the hood. This reduces a little bit of code duplication and should eliminate any instances of `_setup_filenames` being called more than once.

[refactor] Convert data_files and total_particles into properties

---

yt/frontends/arepo/io.py
yt/frontends/gadget/io.py
yt/frontends/sph/data_structures.py
yt/frontends/tipsy/io.py

This PR defers the generation of the KDTree in `_generate_smoothing_length` until all checks for existing hsmls fail, by simply passing the index as an argument.

Avoid generating kdtree until it's really required. Fixes #2854

---

yt/frontends/ytdata/tests/test_unit.py
yt/visualization/fixed_resolution.py

This fixes Issue #2858. The array dimensions of the FRB were being saved as NX,NY when they should have been saved as NY,NX.

[bugfix] fix saved FRB dimensions

---

doc/source/cookbook/multiplot_export_to_mpl.py
yt/frontends/moab/data_structures.py
yt/frontends/moab/io.py

This fixes the call to PyNE::mesh that now uses `pymoab` in place of `pytaps`
Thx to @kkiesling and @pshriwise for the help on this!

Update moab frontend

---

.github/workflows/style-checks.yaml
.travis.yml

fix https://github.com/yt-project/yt/issues/2839
Here's what it look like when triggered on a PR against a master branch that already includes this file
https://github.com/neutrinoceros2/yt/pull/1

add a style check GH workflow

---

yt/geometry/grid_geometry_handler.py
yt/geometry/tests/test_grid_container.py
yt/visualization/plot_window.py

quoting [Python's official documentation](https://docs.python.org/3/library/exceptions.html#AssertionError)
> exception AssertionError
Raised when an assert statement fails.
This PR replaces a handful of `raise AssertionError` found in the code base with more appropriate errors (namely `TypeError` and `ValueError`). It also adds a deprecation warning for `SlicePlot`'s argument `axis`.
Note that I purposely left untouched a few `raise AssertionError` found in tests/testing framework because I _think_ it may be ok to use it there.

cleanup: replace AssertionError raise statements where undue

---

doc/source/reference/configuration.rst
yt/data_objects/time_series.py
yt/frontends/enzo/simulation_handling.py
yt/frontends/exodus_ii/simulation_handling.py
yt/frontends/gadget/simulation_handling.py
yt/loaders.py
yt/tests/test_load_errors.py
yt/utilities/command_line.py
yt/utilities/exceptions.py

This is a follow up to #2695.
Rationale:
In discussing #2695 with @matthewturk , I realised the word "output" is a bit weird in the context this error is used, since the data in question is an _input_ to `yt.load()` (but in general is an _output_ from a simulation, hence the term).
This change makes the original error a subclass of the new one, so as not to break any downstream code that relies on catching it.
Opening as a draft until #2695 is accepted.

Rename YTOutputNotIdentified to YTUnidentifiedDataType

---

yt/data_objects/grid_patch.py
yt/frontends/boxlib/io.py

in recent versions of numpy, this pattern is deprecated:
```python
arr[[slice(None) for _ in range(3)]]
```
and one gets this warning:
```
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different
```
I discovered the places this pattern was used in yt by checking the logs on Travis.
Note that this is not a bug _yet_, but I'm still using the label since it will become an error.

fix np deprecation warnings for non-tuple sequence in multi-dim indexing

---

yt/fields/fluid_vector_fields.py

Working on #2848 I opened Pandora's box and found several bugs in shear computation.
This fixes them.
Namely, the function used dimensionality checks where really, what we want is to know wether velocity component are available. The difference is important for AMRVAC datasets, for instance, where one can run a model in a 2D box, but all velocity components are still present.
In particular, if called with 1D data, the intermediate variable `f` would end up unbounded (which is how I discovered this).
So in summary:
- correctly include all terms in shear computation for datasets with more velocity components than dimensions (so mostly AMRVAC I think)
- raise a reasonable error on purpose (`ValueError`) if called with data that only has 1 velocity component, instead of a defacto …

fix: unbounded variable in shear calculation

---

doc/extensions/pythonscript_sphinxext.py
setupext.py
yt/data_objects/construction_data_containers.py
yt/data_objects/data_containers.py
yt/data_objects/particle_trajectories.py
yt/data_objects/profiles.py
yt/data_objects/time_series.py
yt/fields/xray_emission_fields.py
yt/frontends/enzo/data_structures.py
yt/frontends/enzo_p/io.py
yt/frontends/exodus_ii/data_structures.py
yt/frontends/flash/data_structures.py
yt/frontends/gamer/data_structures.py
yt/frontends/gdf/data_structures.py
yt/frontends/stream/data_structures.py
yt/funcs.py
yt/loaders.py
yt/testing.py
yt/utilities/answer_testing/utils.py
yt/utilities/command_line.py
yt/utilities/exceptions.py
yt/utilities/lib/pixelization_routines.pyx
yt/utilities/particle_generator.py
yt/visualization/color_maps.py
yt/visualization/image_writer.py
yt/visualization/plot_modifications.py
yt/visualization/plot_window.py
yt/visualization/volume_rendering/interactive_vr_helpers.py

Pylint is now able to detect places from `raise Exception from parent_exception` pattern would be meaningful, namely when exception are wrapped into more friendly ones.
Here is the difference between the two patterns:
```python
try:
assert(False)
except AssertionError:
raise FriendlyError
try:
assert(False)
except AssertionError as e:
raise FriendlyError from e
```
The second indicates more clearly what's actually going on and reflects the developer's intention best in almost every cases.
Generating the report
```bash
pip install git+https://github.com/PyCQA/pylint
pylint yt | grep W707
```
Additionally pylint detects "too broad exceptions" (W703), notably where we simply use `except Exception`, which in most cases is an overkill. Not going to fix all of them here, only the ones that also …

cleanup: wrapped exceptions

---

doc/source/faq/index.rst
doc/source/reference/configuration.rst
yt/__init__.py
yt/mods.py
yt/utilities/logger.py
yt/utilities/tests/test_set_log_level.py

It is often useful to change the logging level at runtime. Currently, the recommended way to do this is by importing the logger object itself and call its `setLevel` method.
I propose the addition of a user facing method `yt.set_log_level` that provides the following benefit:
- avoid importing ytLogger itself (especially under the somewhat confusing alias "mylog")
- more user-friendly interface: recognise lower-case strings as aliases for integers logging levels, also produce more readable user code for people that are not used to logging in general (which I guess is most of the user base)
- add a string alias "ALL" (or "all") for logging level `1`, which isn't in the standard library but fits other parts of yt rather nicely.
here's a dummy example
```python
import yt
for lvl in ("all", …
```

expose ytLogger.setLevel with a user facing method yt.set_log_level

---

yt/frontends/halo_catalog/data_structures.py

This was broken by PR #2857. We just need to set the attributes properly now that they're properties. I'd rather do this than make a setter for `total_particles` because we don't really want anyone setting that.
PR #2857 should have failed a halo container test, but the data must not be on the testing box. @Xarthisius, can you put the [tiny_fof_halos](http://yt-project.org/data/tiny_fof_halos.tar.gz) dataset on the testing box?

[bugfix] fix yt halo container

---

yt/loaders.py

I noticed the name of the first arg in load sample changed from name to fn, even though this argument is specific to a file name. I've changed it back because name is clearer.
I've also fixed the import of pooch.Untar() since it was transferred with an error.

More fixes for load_sample

---

yt/geometry/selection_routines.pxd
yt/geometry/selection_routines.pyx

This provided sane values for the reduced dimension while selecting region of a 2d mesh. Not a full and proper fix, but hopefully will make the annoying error on travis go away. It's similar to #2539 but I hope to merge this before we figure out a proper fix for 2D data.

Fix uninitialized values in bbox selection

---

.github/workflows/style-checks.yaml

Another hotfix for the GH style checks workflow. I noticed that currently, one gets duplicate notifications when something is wrong since the workflow is triggered both on the main repo side and the fork.

hotfix: only trigger style checks on PR (avoid duplicated runs)

---

yt/data_objects/data_containers.py
yt/data_objects/tests/test_center_squeeze.py

Squeezes the center array to remove extra dimensions so that the user can supply center arrays of arbitrary shape (e.g., shape of `(1,3)`, `(3,1)`, `(1,3,1)`, etc. are reduced to `(3,)`). Fixes issue #2393

Squeeze domain center array in data_containers

---

yt/loaders.py

Logic deciding whether to untar a file downloaded by pooch was accidentally reversed in 853621cc5a1d74e9eba532e1962376cd6a921b32 . Originally reported by @chrishavlin on slack.

[load_sample] Don't try to untar hdf5 files

---

.github/workflows/rules-checks.yaml
yt/frontends/gadget/io.py
yt/frontends/gamer/data_structures.py
yt/frontends/gdf/data_structures.py
yt/frontends/open_pmd/data_structures.py
yt/frontends/open_pmd/fields.py
yt/geometry/geometry_handler.py
yt/utilities/grid_data_format/conversion/conversion_athena.py
yt/utilities/grid_data_format/tests/test_writer.py
yt/utilities/minimal_representation.py

`h5py` deprecated their `dataset.value` attribute and now recommend using `dataset[()]` instead.
The change was already performed in most of the code, this PR adresses the remaining occurrences.

Solve some h5py deprecation warnings

---

yt/loaders.py

We have a bunch of docstrings formatted as doctests example throughout the code base. This is an invaluable resource for documentation and testing. Right now we don't have the infrastructure to validate them and I would assume that most of them are in fact slightly broken.
This PR fixes the docstrings in yt/loaders.py, which is the first module I tried.
Pytest is incredibly handy once again and it can be used to validate this work:
```
pytest --doctest-modules yt/loaders.py
```
In the future we should probably add `pytest  --doctest-modules` to our CI workflows. This could be done in a group-effort PR starting with a GH workflow addition so everyone could see the errors to be solved.

[doctest] fix docstrings in yt.loaders

---

tests/test_requirements.txt

Jenkins needs mpl<3.3 for test to pass right now. New set of answers is generated in #2902, but this should go in to prevent blocking other PRs.

[hotfix] Downgrade mpl until PR#2902 is merged

---

.travis.yml
tests/test_prerequirements.txt
tests/tests.yaml
yt/visualization/tests/test_particle_plot.py

This PR introduces additional file (`tests/test_prerequirements.txt`) that can be used to install basic packages required by anything in `test_requirements.txt` (I'm looking at you Cartopy...). It allows me to remove hardcoded deps that are currently defined in the Jenkins' job. I also dropped pinning mpl to 3.1.3, so there's a high chance this will fail and will require some answers to be regenerated.

Add reqs that needs to be installed before test_requirements.txt

---

yt/data_objects/static_output.py

Just noticed we lost the inheritance from abc.ABC (from #2556) in `Dataset`, as a side effect of #2823 
fix it.

hotfix: make Dataset an abstract class again

---

yt/data_objects/tests/test_time_series.py
yt/data_objects/time_series.py

fix #2633 
This is a very light change, but the branch is based on top of #2695 (merged ! 🎉 )
Reason: in order to avoid type checking with `isinstance(output, str)` and allow allow pathlike types to be treated equally, I use this pattern to determine if an output represents loaded or loadable data
```python
try:
return load(output) # loadable data ?
except TypeError:
return output # assumed loaded data
```
... and this pattern is only relevant if `load` is able to throw `TypeError`. To a certain extent, this proves the point I made in #2695 : it makes for a more maintainable code base.
Based on master, I would need to catch `YTOutputNotIdentified`, which would not be specific enough and could cause very weird behaviour downstream.

fix: add support to init from pathlike objects for time series

---

tests/tests.yaml
yt/frontends/boxlib/data_structures.py
yt/frontends/boxlib/tests/test_outputs.py

this is part of #2806, I want to see if it breaks stuff on its own.
`WarpXDataset._is_valid` is probably too permissive as it stands, it makes other classes easily interfere with it.
adresses #2708
Edit: found more bugs along the way (and added tests)

fix: refactor boxlib dataformat validators (code deduplication), fix bugs revealed on the way there

---

yt/fields/particle_fields.py

... as well as particle_velocity_relative fields.
These fields were deprecated in yt 3.5.0, but the deprecation warnings are still showing up in our own test reports, I think it's ok to remove it now.

cleanup: remove deprecated particle_position_relative field

---

yt/utilities/png_writer.py

This is a reissue of the PR yt-project/yt#2800

Reissue #2800: backport #2754 to stable 

---

tests/tests.yaml
yt/visualization/particle_plots.py
yt/visualization/profile_plotter.py

Future proof yt for matplotlib 3.5.
rationale:
mpl 3.3 deprecated the current default behaviour in `Axis.pcolormesh(x, y, c)`, see details there
https://matplotlib.org/3.3.1/gallery/images_contours_and_fields/pcolormesh_grids.html#sphx-glr-gallery-images-contours-and-fields-pcolormesh-grids-py
This is only used in `yt.PhasePlot`. In short, the easiest fix is to explicitly pass a `shading` value. The current default `"flat"` will break in mpl 3.5, so the easiest fix is to use `"nearest"` instead, which will output very similar but not quite identical results (we'd need to update answers).
Just in case someone would absolutely need to use the `"flat"` shading again, it's easy enough to expose it in yt. This also allows to use the `"gouraud"` shading mode for phase plots, see the following …

fix: adapt PhasePlot's to future upstream api change in matplotlib

---

appveyor.yml

As proposed by @Xarthisius on Slack, let's cut the testing time on windows by half and only test against Python 3.8
note: this is superseded by https://github.com/yt-project/yt/pull/2908 !

ci: only test against latest python version on windows to reduce CI bottleneck

---

tests/tests.yaml
yt/utilities/answer_testing/framework.py
yt/utilities/lib/pixelization_routines.pyx

Recent changes meant to ensure that SPH pixelization routines respect periodicity (#2731) introduced a couple of minor issues:
1. Indices used for periodic passes overlapped with indices used to iterate over buffer array in some places (see pseudo code below):
```
for xi in range(2):
...
for yi in range(2):
...
for xi in range(x0, x1):
...
for yi in range(y0, y1):
```
As result, periodic passes never actually happen if inner loops set `xi` and `yi` to value >0
1. Particle y-position in 2nd x pass was incremented twice due to the use of `+=`:
```
for xi in range(2):
px += xiterv[xi]
for yi in range(2):
py += yiterv[yi]  # <---- This will happen twice if periodic in x
```
This PR updates outer loops in SPH pixelization routines to use unique indices, and fixes particle positions by using …

Fix indexing issues in sph pixelization

---

yt/frontends/gadget/testing.py
yt/geometry/grid_container.pyx

CI logs still contain one FutureWarning from numpy
for instance
```
yt/geometry/tests/test_grid_container.py::test_grid_arrays_view
/Users/clm/.pyenv/versions/3.8.5/envs/yt_dev/lib/python3.8/site-packages/numpy/core/_internal.py:38: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
format = dtype(obj[0], align=align)
```
This fixes it. However, I expect this to break the minimal setup run so I'll open as a draft for now.

fix a FutureWarning from numpy

---

yt/data_objects/static_output.py

This fixes a "Heinseinbug" I encounter in a complicated notebook + yt plugin situation, and that I can't seem to reproduce simply for now.
In my plugin file I have a line
```python
ds.find_max("density")  # ds is a polar 2D dataset
```
that raises a `unyt.exceptions.IterableUnitCoercionError`.
I'm sorry to open a bugfix when I can't clearly expose the bug in question, but I do hope the fix is uncontroversial and can be accepted as is. I don't have enough time on my hands to inspect this further :/

bugfix: fix a brittle array conversion

---

.pre-commit-config.yaml
pyproject.toml
setup.cfg
tests/lint_requirements.txt
yt/utilities/lib/basic_octree.pyx
yt/utilities/lib/grid_traversal.pyx

Moving the isort conf from setup.cfg to pyproject.toml (recommended by isort's doc), and using `profile="black"` to simplify the configuration, guaranteeing we won't get conflicts between isort and black.
While I'm at it I bumped isort's version. I doesn't affect the stability of the code base right now (almost 0 churn except for 2 additional newlines) but there were a number of bugfix since last time so it seems worth the shot.

Simplify isort conf

---

yt/utilities/lib/pixelization_routines.pyx

This PR parallelizes sph kernel projection using OpenMP. On my laptop the speed up is modarate (<0.5 for 4 cores), but it yields a significant improvement on testing infra:
```
$ time python doc/source/cookbook/image_resolution.py   # without this patch
real	16m6.577s
user	16m5.294s
sys	0m4.467s
$ time python doc/source/cookbook/image_resolution.py # with this patch, all cores (40)
real	3m11.529s
user	23m2.800s
sys	0m14.970s
$ export OMP_NUM_THREADS=8  # the default setting we use during a test suite build
$ time python doc/source/cookbook/image_resolution.py 
real	4m9.637s
user	14m26.263s
sys	0m2.226s
```

Parallelize pixelize_sph_kernel_projection. Fixes #2682

---

yt/utilities/logger.py

The log filtering added in PR #2871 introduced a small issue when the logger is called as `mylog.info(message, arg1, arg2, ...)`. Within the logger, only the `msg` attribute was being used to check for similarity to the last log. This caused the prints that happen in `yt.load` to be skipped since they all use the same formatting string.

[bugfix] Construct log message using args.

---

yt/frontends/gadget/data_structures.py

This fixes an issue that popped up with gadget dark matter-only data where it would try to check for smoothing lengths in sph types even if the sph types aren't present. Now we check for present sph types first.
I guess we are not testing dm-only gadget data. I can try to arrange for some to be added to the test suite at some point soon.

[bugfix] Allow for gadget datasets with no sph types.

---

yt/frontends/boxlib/data_structures.py

This supersedes #2787 and adresses the issue at the frontend level. Turns out there is actually more than one place where periodicity is incorrectly or inconsistently parsed.

[BOXLIB] consistent parsing for periodicity parameters

---

tests/test_requirements.txt

Per https://github.com/Toblerity/Shapely#source-distributions we need to make sure that *shapely* is installed properly...

Ensure that shapely is built from source. Fixes #2941

---

setupext.py

Currently, when one of the Cython extensions fails to compile in a parallel build process, it does not stop the build. In the best case scenario the process will fail during install step with a cryptic:
```
error: can't copy 'build/lib/yt/geometry/particle_oct_container.cpython-36m-x86_64-linux-gnu.so': doesn't exist or not a regular file
```
or in the worst case it will silently create a faulty wheel that will install yt, which will fail during import.
This PR properly raises any exception raised in parallel build threads resulting in fatal error stopping the entire install process after build extensions phase.
```
export CC=$(which gcc-5)
export CXX=$(which g++-5)
python3 -m pip wheel .
```

Properly raise exceptions that occur during parallel build

---

.pre-commit-config.yaml

Our current pre-commit configuration file isn't future proof:
```bash
pre-commit-validate-config .pre-commit-config.yaml
```
outputs
```
[WARNING] normalizing pre-commit configuration to a top-level map.  support for top level list will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
```
This fixes it.
While I'm at it I also release a strict python version requirement for the black hook since I noticed it broke on my machine after I cleaned it. The error in question, and its solution, was found here https://github.com/pre-commit/pre-commit/issues/1375

futurefix: normalize pre-commit configuration

---

yt/geometry/selection_routines.pxd
yt/geometry/selection_routines.pyx
yt/geometry/tests/test_pickleable_selections.py

This PR adds support for pickling the geometric `selector` objects in `yt/geometry/selection_routines.pyx` (`PointSelector`,`SphereSelector`,`RegionSelector`, `DiskSelector`, `CuttingPlaneSelector`,`SliceSelector`,  `OrthoRaySelector`,`RaySelector`,`EllipsoidSelector`). A subsequent PR will add pickle support for the remaining `selector` types.

adds pickleability to geometric selection objects

---

yt/frontends/amrvac/__init__.py
yt/frontends/amrvac/data_structures.py
yt/frontends/amrvac/tests/test_read_amrvac_namelist.py

Remove dead import statements from `yt/frontends/amrvac/__init__.py`
The only important difference is that `read_amrvac_parfiles` should not be imported on the user side from `yt.frontends.amrvac` but from `yt.frontends.amrvac.api`. I expect to be the only user potentially affected by this change since since function is not well known.

cleanup amrvac frontend __init__.py

---

yt/data_objects/static_output.py

When we made static output into an ABC, the arguments to `MutableAttribute` all got disabled.  That made our nice "show the ytarray stuff in a ipywidgetsy-way" stop working.  This turns it back on.

Re-enable displaying the arrays on datasets

---

yt/frontends/flash/io.py

It's basically noop PR. It works around h5py/h5py#1757 and avoids slightly [ambiguous behavior](https://numpy.org/doc/stable/user/basics.indexing.html#dealing-with-variable-numbers-of-indices-within-programs) with tuples.

Avoid using tuples to index h5 datasets

---

yt/utilities/parameter_file_storage.py

This PR fixes a bug in the on-disk dataset parameter file storage. 
To reproduce the bug on master, enable in the on disk parameter file storage in the `ytrc` config with `StoreParameterFiles = True` then on importing yt you'll get this error: 
```python
>>> import yt
File "<stdin>", line 1, in <module>
File "/home/chavlin/src/yt/yt/__init__.py", line 80, in <module>
from yt.data_objects.api import (
File "/home/chavlin/src/yt/yt/data_objects/api.py", line 1, in <module>
from . import construction_data_containers as __cdc, selection_objects as __sdc
File "/home/chavlin/src/yt/yt/data_objects/construction_data_containers.py", line 14, in <module>
from yt.data_objects.selection_objects.data_selection_objects import (
File …
```

switch csv writer file IO mode for python 3

---

tests/tests.yaml
yt/geometry/selection_routines.pyx

This is a tentative fix for issue #2720, but needs some discussion! The origin of the bug in #2720 is a floating point comparison. The `SelectorObject` traverses grid coordinates by incrementing positions in a nested loop while the `AMRGridPatch.select_fcoords` re-calculates the same coordinates by multiplication of indices, resulting in small differences at the level of floating point precision. Since the `CutRegion` selector identifies masked coordinates by comparison of floating point values, these differences lead to points not being selected that should be.
The current fix in this PR feels a bit hacky -- simply changing how the `SelectorObject` nested loop calculates coordinates are calculated seems to have been sufficient, but there may be a better fix (e.g., have the …

cut region AMRGrid selector fix

---

yt/visualization/base_plot_types.py

the warning in question is seen in Jenkins logs, e.g.
```
/home/fido/workspace/yt_py38_git/yt/visualization/base_plot_types.py:274:
MatplotlibDeprecationWarning: Passing parameters norm and vmin/vmax simultaneously is deprecated since 3.3 
and will become an error two minor releases later. Please pass vmin/vmax directly to the norm when creating it.
self.image = self.axes.imshow(
```

futurefix: fix a deprecation warning from mpl 3.3

---

yt/data_objects/construction_data_containers.py
yt/data_objects/selection_objects/slices.py

We shouldn't necessarily fail if we call `.plot()` on slices or projections
outside of the notebook, since it's also useful just to get a `PlotWindow`
object back.  This catches the one non-fatal Exception.

Allow .plot() to run outside of the notebook

---

pyproject.toml

fix installation against python 3.9

---

tests/lint_requirements.txt
yt/utilities/parallel_tools/parallel_analysis_interface.py

A new feature in flake8-bugbear detects pointless comparisons, here I think the problem is that `==` was used instead of `=`.

fix: bump bugbear to latest version and fix newly detected bugs

---

doc/source/developing/releasing.rst

This PR updates some of the developing docs to be more current with our release process. Some of the improvements are:
- nothing that multibuild wheels upload to anaconda.org rather than rackspace
- A PR to the yt-feedstock for conda forge is triggered after a PyPI release is detected automatically, so I moved the conda forge updating to after the PyPI release notes

Minor updates to the dev docs 

---

yt/frontends/ramses/data_structures.py
yt/frontends/ramses/tests/test_outputs.py
yt/geometry/oct_container.pyx
yt/geometry/oct_geometry_handler.py
yt/geometry/oct_visitors.pxd
yt/geometry/oct_visitors.pyx

This enables support for more than 1 ghost zones with octree datasets.
Also add a minor speed improvement of the mesh-sampling implementation (always start with the largest domain).

Enable ghost zones > 1 for octrees

---

tests/report_failed_answers.py

Avoid adding a '.' at the end of download urls so that they remain valid when clicked.

add whitespace between url and '.' to make link clickable.

---

yt/frontends/athena_pp/data_structures.py
yt/frontends/athena_pp/io.py

* Read coordinates in one op instead of for loop over grids
* Do not override default _chunk_io to properly chunk grid reads
The main issue was a custom `_chunk_io` that was for some reason returning chunks of size 1, which in turn resulted in very costly reads of 16^3 floats for each grid. Let's see if the default works fine and tests pass.

Optimize Athena++ i/o

---

setup.py
setupext.py
yt/geometry/particle_oct_container.pyx
yt/utilities/lib/cykdtree/kdtree.pyx
yt/utilities/lib/cykdtree/utils.pyx
yt/utilities/lib/cyoctree.pyx
yt/utilities/lib/field_interpolation_tables.pxd
yt/utilities/lib/geometry_utils.pyx
yt/utilities/lib/grid_traversal.pyx
yt/utilities/lib/image_samplers.pyx
yt/utilities/lib/misc_utilities.pyx
yt/utilities/lib/partitioned_grid.pyx
yt/utilities/lib/pixelization_routines.pyx
yt/utilities/lib/platform_dep.h
yt/utilities/lib/platform_dep_math.hpp

Use GCC 5 to trigger compiler errors with non-default  C++14 compilers.
Follow-up to regressions from #2575 and #2610
Fix #2892
```
export CC=$(which gcc-5)
export CXX=$(which g++-5)
python3 -m pip wheel -v .
```

Fix GCC 5 Builds

---

yt/frontends/boxlib/data_structures.py
yt/frontends/boxlib/tests/test_outputs.py

another take at #2806, fix #2805 
The test pass locally, but I expect it to fail in CI since I'm not sure how the `tar.gz` file is untared there.
This change also required a fix affecting the common validation for all boxlib datasets, so I also expect surprises there.

fix: implement AMReXDataset._is_valid

---

tests/test_minimal_requirements.txt
tests/test_requirements.txt
yt/data_objects/tests/test_projection.py
yt/data_objects/tests/test_slice.py
yt/utilities/tests/test_config.py
yt/visualization/tests/test_particle_plot.py

Rationale:
`mock` was standardized in Python 3.3

maint: drop mock as a third party dependency 

---

yt/data_objects/static_output.py
yt/utilities/math_utils.py
yt/visualization/plot_modifications.py

Fix a number of `raise SyntaxError` which are really `ValueError`s.
There's a slight possibility of backwards compatibility breakage if any downstream code is currently catching any of those as `SyntaxError` but I hope this is not likely enough to prevent us from performing this clean up.

fix: replace all spurious occurences of 'raise SyntaxError'
