yt-project/yt

doc/install_script.sh

closes #1343
Pretty straightforward. Let me know if you think the text I added needs massaging.

make the install script bail on unsupported operating systems

---

CONTRIBUTING.rst

Hello!
Since I had to fork and clone from GitHub, I went through the contribution guidelines once more.  I made some terms and placeholders consistent, in order to avoid confusion or distraction.
Also, I made the doctest code PEP-8 compliant and Python 3 compatible (and fixed the final output).

Harmonize placeholders and improve style.

---

yt/frontends/stream/data_structures.py
yt/frontends/stream/tests/test_stream_unstructured.py

This fixes another bug in the streaming unstructured frontend identified by Kyle Parfrey. I've also added a new test that would have caught the error.

[Bugfix] Meshes with multiple fields in the streaming unstructured frontend

---

doc/source/cookbook/complex_plots.rst
doc/source/cookbook/render_two_fields.py

Adds a cookbook recipe showing how to volume render multiple VolumeSources.

[doc] recipe demonstrating how to render two fields. Closes #675

---

doc/source/cookbook/power_spectrum_example.py
yt/analysis_modules/cosmological_observation/light_cone/light_cone.py

I updated the building environment for docs. This popped out. Let's see if that's the only issue.

Docs fixes

---

yt/visualization/tests/test_mesh_slices.py

This is mitigation for #1394 but does not fix the underlying issue. I've disabled this to avoid spurious seg faults on Travis.

disable seg faulty test

---

doc/install_script.sh

closes #1401
This should fix the issues reported by @astroboylrx in the issue.

Fix YT_DIR and INST_GIT semantics. 

---

yt/frontends/art/data_structures.py

[art] use integer division

---

doc/source/examining/loading_data.rst
tests/tests.yaml
yt/frontends/api.py
yt/frontends/enzo_p/api.py
yt/frontends/enzo_p/data_structures.py
yt/frontends/enzo_p/definitions.py
yt/frontends/enzo_p/fields.py
yt/frontends/enzo_p/io.py
yt/frontends/enzo_p/misc.py
yt/frontends/enzo_p/tests/test_outputs.py

One more time from the top.
This adds a basic Enzo-P frontend representing the current state of Enzo-P hdf5 output. This will be a work in progress for a little while as the Enzo-P format solidifies.
Currently missing (as they are also missing from the format):
units
particles
runtime parameters

Add Enzo-P frontend

---

README.md

Add numfocus badge to the readme

---

tests/tests.yaml
yt/data_objects/grid_patch.py

I hit this on a 2D WarpX dataset with mesh refinement for some reason...

[BUGFIX] Fix clamping bug in _prepare_grid

---

doc/source/examining/loading_data.rst
yt/frontends/ramses/data_structures.py
yt/frontends/ramses/tests/test_outputs.py

Provides support for arbitrary information in the particle output file. This is useful for people that are adding extra information to the particles.

[RAMSES] Support for custom particle fields

---

yt/geometry/selection_routines.pyx

This explicitly allocates and deallocates the `IntegrationAccumulator` objects.  I believe these were being passed by some mechanism that was creating shallow copies, and thus breaking them during the sampling operation.  It took me a while to track this down, but both examples in #1484 work now.

Explicitly allocate/deallocate IntegrationAccumulator. Fixes #1484.

---

doc/source/help/index.rst
doc/source/reference/command-line.rst
yt/config.py
yt/utilities/command_line.py
yt/utilities/exceptions.py

This PR add `upload` subcommand that allows to upload files to `http://use.yt/upload/` with nice progress bar.

Add wrapper for curl uploader

---

doc/source/examining/loading_data.rst
yt/frontends/ramses/data_structures.py
yt/frontends/ramses/fields.py
yt/frontends/ramses/tests/test_outputs.py

This is a redo of #1449. I've pushed some commits on top of @sacielo's changes to add tests and do some minor cleanup.

Automatically identify Ramses-RT fields

---

tests/tests.yaml
yt/frontends/boxlib/data_structures.py
yt/frontends/boxlib/fields.py
yt/frontends/boxlib/tests/test_outputs.py

This is needed to support datasets with mesh refinement.

Be smarter about parsing the WarpX header file.

---

yt/visualization/eps_writer.py

I believe this PR fixes #1497.

Ensure keys in eps_writer.py are lists for Python 3. Fixes #1497

---

CONTRIBUTING.rst

Thanks for pointing this out @mkcor!

Fix link to flake8 docs. Fixes #1507

---

yt/analysis_modules/halo_finding/rockstar/rockstar.py
yt/analysis_modules/halo_finding/rockstar/rockstar_interface.pyx

@pgrete it would be great if you could test this.

Fixes for rockstar under python3. closes #1412

---

doc/source/examining/loading_data.rst
tests/tests.yaml
yt/frontends/ahf/__init__.py
yt/frontends/ahf/api.py
yt/frontends/ahf/data_structures.py
yt/frontends/ahf/fields.py
yt/frontends/ahf/io.py
yt/frontends/ahf/tests/test_outputs.py
yt/frontends/api.py

Add a frontend for the [AHF](http://popia.ft.uam.es/AHF) halo catalogs.

Add AHF frontend

---

yt/visualization/fits_image.py

I found two more problems with `FITSImageData`
1. It turns out I hadn't quite completely fixed the `.info()` method after all. Now it is fixed for AstroPy 1 and 2. 
2. I also fixed a bug related to combining two `FITSImageData` instances together.

[bugfix] More FITSImageData fixes

---

tests/tests.yaml
yt/frontends/ahf/data_structures.py
yt/frontends/ahf/tests/test_outputs.py

Might need to bump the answer numbers, let's see.

fix issue with AHF answer tests. Fixes #1528.

---

yt/frontends/tipsy/io.py

Right now if a file matching the tipsy aux file glob pattern is present in the
output directory, we attempt to parse the file as a valid tipsy aux file
die with a ValueError. Instead, let's detect this case and remove the field
from the list of detected tipsy auxiliary fields.
This was found in the context of swithing between mainline and the demeshening
branch. In the demeshening we create sidecar files (in particular, one named
`galaxy.00300.kdtree`) that are detected by mailine yt as auxiliary
files. However, this would happen for users as well if they happen to have a
file with a name matching the aux file glob pattern we use in their output
directory.

Handle invalid tipsy aux files

---

yt/frontends/ramses/data_structures.py
yt/frontends/ramses/tests/test_outputs.py

This should fix https://github.com/yt-project/yt/issues/1554.

[RAMSES] autodetect extra fields

---

doc/source/examining/loading_data.rst
yt/frontends/ramses/data_structures.py
yt/frontends/ramses/fields.py
yt/frontends/ramses/io.py
yt/frontends/ramses/tests/test_outputs.py

This PR adds support for sink particles in RAMSES, where sink particles are usually SMBH.

[RAMSES] Add support for sink particles

---

tests/tests.yaml
yt/frontends/boxlib/fields.py

[BUGFIX] Correct typo in WarpX field definitions.

---

yt/frontends/enzo/data_structures.py

Fixes issue #1584

---

yt/visualization/plot_modifications.py

closes #1632, see that issue for details.

Ensure plot bounds are in code units for quiver callback

---

yt/frontends/stream/data_structures.py
yt/frontends/stream/tests/test_stream_particles.py

Fixes #1600
Most of the logic is to generate a nice error message. Here's what the logging looks like when you trigger this case:
```
yt : [INFO     ] 2017-11-01 11:31:48,157 Parameters: current_time              = 0.0
yt : [INFO     ] 2017-11-01 11:31:48,157 Parameters: domain_dimensions         = [16 16 16]
yt : [INFO     ] 2017-11-01 11:31:48,158 Parameters: domain_left_edge          = [-1.5 -1.5 -1.5]
yt : [INFO     ] 2017-11-01 11:31:48,158 Parameters: domain_right_edge         = [ 1.5  1.5  1.5]
yt : [INFO     ] 2017-11-01 11:31:48,158 Parameters: cosmological_simulation   = 0.0
yt : [WARNING  ] 2017-11-01 11:31:48,159 Discarding 39 particles (out of 1000) that are outside bounding box. Set bbox=[[-1.5962920126617606, 1.5], [-1.5, 1.5], [-1.5, 1.5]] to avoid this in the future.
``` …

screen particles outside the domain for load_uniform_grid and load_amr_grids

---

doc/source/cookbook/complex_plots.rst
doc/source/cookbook/multiplot_phaseplot.py

This PR adds a cookbook example to illustrate how to use PhasePlot in a multipanel plot.

Add the cookbook of multipanel phaseplot

---

doc/source/analyzing/parallel_computation.rst
yt/data_objects/construction_data_containers.py

Parallel covering grid

---

CONTRIBUTING.rst
COPYING.txt
README.md
doc/cheatsheet.tex
doc/install_script.sh
doc/source/about/index.rst
doc/source/developing/creating_frontend.rst
doc/source/help/index.rst
setup.py
yt/mods.py
yt/utilities/command_line.py

This updates all the mailing list locations.

Update mailing list locations.

---

doc/source/visualizing/callbacks.rst

fixes #1650 
Thanks to @grapenut for the report.

update copy/pasted API docs for timestamp callback

---

yt/frontends/gadget/io.py
yt/frontends/gadget/tests/test_outputs.py

Fix the ParticleIDs issue for Gadget binary snapshots

---

doc/source/visualizing/plots.rst
yt/visualization/profile_plotter.py
yt/visualization/tests/test_profile_plots.py

This adds the methods, set_xlabel and set_ylabel to the ProfilePlot. It builds on the x_title and y_title features already included.
This is my first contribution, please let me know if I've messed up. (I probably have)
Fixes issue [#1298](https://github.com/yt-project/yt/issues/1298)

Added set_*label - command for ProfilePlot. Addresses Issue #1298

---

yt/data_objects/static_output.py

Fixes two minor problems with usage of `find_field_values_at_points`. The bugs fixed were small / typos.

Fixed two minor bugs (typos)

---

doc/source/visualizing/plots.rst
yt/visualization/profile_plotter.py
yt/visualization/tests/test_profile_plots.py

With this change we can add plot title and add annotations in ProfilePlot.
https://github.com/yt-project/yt/issues/1599

Profile plot annotate title and text. Addresses Issue #1599

---

CONTRIBUTING.rst

Update Astropy Code of Conduct URL

Update Astropy Code of Conduct URL

---

yt/frontends/ramses/data_structures.py
yt/frontends/ramses/field_handlers.py
yt/frontends/ramses/fields.py
yt/frontends/ramses/tests/test_outputs.py

Add support for `grav_XXXXX.outYYYYY` files.
This PR adds support for the gravity files used by RAMSES. It reads the gravity at cell location and loads the acceleration in the 'gas' fields (as well as the potential, if found).

[RAMSES] Read poisson

---

doc/README
doc/docstring_idioms.txt
doc/source/_templates/layout.html
doc/source/conf.py
doc/source/cookbook/notebook_tutorial.rst
doc/source/reference/changelog.rst
doc/source/sharing_data.rst
doc/source/visualizing/sketchfab.rst

Fixing a few URLs and permanent redirects

Fix a few broken URLs and permanent redirects in docs

---

tests/tests.yaml
yt/analysis_modules/halo_finding/rockstar/rockstar.py
yt/analysis_modules/halo_finding/rockstar/rockstar_interface.pyx

When ported over, this will fix Issue [19](https://github.com/yt-project/yt_astro_analysis/issues/18) of [yt_astro_analysis](https://github.com/yt-project/yt_astro_analysis).
Thanks to @Xarthisius for figuring out the string issue from the first commit.

Fix yt-rockstar interface for Python 3

---

yt/frontends/stream/data_structures.py

This fixes some formatting and makes something about how the data is provided slightly clearer.

Fix some unstructured mesh docs

---

yt/data_objects/profiles.py

As suggested by @annarosen84 in #1773.

mention the default weight field in the create_profile doc

---

yt/data_objects/selection_data_containers.py

Make the documentation for the radius parameter of `YTSphere` mention `(radius, unit)` tuples and `YTQuantity`.

Improve the documentation for the radius parameter of YTSphere

---

yt/data_objects/tests/test_particle_filter.py

Removing decorator @requires_file() that makes the test case dependent on real data.

Removing the dependency from real datasets

---

.codecov.yml
.coveragerc
.travis.yml
README.md
nose.cfg

Switching to Codecov from Coveralls.

Codecov Integration

---

yt/data_objects/image_array.py
yt/data_objects/tests/test_image_array.py

Updated the corresponding test cases to increase coverage.

Enhanced test cases for image_array.py in data_objects

---

CONTRIBUTING.rst

Link on current documentation directs to a 404. This fixes the link
None applies
- ~[ ] Code passes flake8 checker~
- ~[ ] New features are documented, with docstrings and narrative docs~
- ~[ ] Adds a test for any bugs fixed. Adds tests for new features.~

Fixes link about relicensing post

---

yt/frontends/ramses/data_structures.py
yt/frontends/ramses/field_handlers.py
yt/frontends/ramses/io.py
yt/frontends/ramses/particle_handlers.py

As Ramses dumps lots of files, it is sometimes necessary to group the files in subfolders, so that the output is spread across multiple folders. This PR adds support for this feature.

Ramses groupsize

---

yt/utilities/lib/pixelization_routines.pyx

I had added a few more comments to the projection function. This made the code a bit easier for me to read and maybe helpful for future contributors.

updated the comments to sph slice projection

---

yt/data_objects/particle_filters.py
yt/data_objects/tests/test_particle_filter.py

Adding more test cases for particle filter to increase coverage.

Added more tests for particle filter

---

setup.py

remove duplicated comment

---

.travis.yml
doc/source/installing.rst
setup.py

I *think* this is everything I need to do to drop Python3.4 support. Please let me know if I'm missing something.

drop support for Python3.4

---

yt/data_objects/selection_data_containers.py
yt/funcs.py
yt/tests/test_funcs.py

Input validation for selection data containers 

---

yt/visualization/tests/test_profile_plots.py

Refactored code.
Plots were getting generated in yt's source code directory. Further, these files were not deleted after completion.

Refactor, save png to temporary directory, clean-up temp dir after tests

---

.gitignore
doc/source/quickstart/index.rst

Hi @ngoldbaum,
This PR is the first in a series... 
I was going through the [quickstart](https://yt-project.org/doc/quickstart/index.html) after a fresh setup, so I didn't have jupyter installed in my conda env (yet).
Running `git status` also prompted the update to the `.gitignore` file.

Specify that you need jupyter to run quickstart notebooks.

---

README.md

Conda environments are becoming the standard in the SciPy/PyData ecosystem (I would point to @jakevdp's materials: https://speakerdeck.com/jakevdp/pydata-101 or https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/) so I thought we could reflect this more explicitly in our setup instructions.
NA

Update install instructions to match SciPy ecosystem.

---

yt/utilities/command_line.py

Hi @ngoldbaum,
With this change, launching `yt notebook` does not throw a deprecation warning any more. Should I write a test for it?

Address deprecation warning about IPython.html.

---

yt/data_objects/particle_trajectories.py
yt/data_objects/tests/test_particle_trajectories.py
yt/data_objects/time_series.py
yt/testing.py

This adds the possibility to select a specific particle type when doing particle trajectories

[Improvement] Support particle types in particle trajectories

---

yt/frontends/art/data_structures.py
yt/frontends/art/io.py

Two changes to fix problems with ART frontend. First changes an int check, while the other removes an unnecsscary check for files that causes load issues.

Art Frontend Fix

---

yt/frontends/gadget/tests/test_outputs.py

Updating the swift file path to work with the new test file.

updated keplerian ring file path

---

yt/analysis_modules/cosmological_observation/api.py
yt/analysis_modules/cosmological_observation/light_cone/api.py
yt/analysis_modules/halo_analysis/api.py
yt/analysis_modules/halo_finding/api.py
yt/analysis_modules/ppv_cube/api.py
yt/analysis_modules/radmc3d_export/api.py
yt/analysis_modules/sunyaev_zeldovich/api.py

This add deprecation warnings to all of the analysis modules that have been moved over to yt_astro_analysis.

Deprecating analysis modules in favor of yt_astro_analysis

---

yt/units/yt_array.py

this backports https://github.com/yt-project/unyt/pull/52

add YTArray.argsort

---

yt/data_objects/level_sets/clump_handling.py

I spent a little time trying to get pickling to work again, realized that i'd also have to pickle a reference to the underlying dataset, and pickling datasets are already broken. That means fixing this is a huge undertaking that involves fixing several other issues as well. Let's not worry about that when we already have a perfectly good replacement for pickling clumps that outputs files that things besides python can read.
Note that this isn't any worse than the status quo, where this is broken. In fact it's a little bit better because now the user will know what to do instead of seeing an opaque error related to yt doing something incorrect internally.

make pickling clump objects raise an error. Fixes #1898

---

doc/source/analyzing/parallel_computation.rst
yt/data_objects/time_series.py

This fixes Issue #1830. I also corrected a small mistake in the `piter` docstring.

Adding documentation on multi-level parallelism.

---

yt/fields/particle_fields.py

Deprecate particle_position_relative and particle_velocity_relative

---

tests/nose_runner.py

Thanks to @Xarthisius for the catch.

ensure base arguments are passed to all tests

---

yt/data_objects/grid_patch.py
yt/frontends/boxlib/io.py
yt/utilities/nodal_data_utils.py

Do not merge this yet - seeing if the tests pass.

Some changes needed to make nodal data work in 2D

---

yt/frontends/flash/fields.py

[bugfix] fix unit for divB in FLASH frontend

---

yt/visualization/volume_rendering/off_axis_projection.py

This hopefully allows the off axis projection to successfully deal with derived fields.
fixes #2066

[bugfix] yt-4.0 added extra check to deal with derived fields

---

doc/source/examining/loading_data.rst

This may or may not be the cause of occasional doc failures, but it did
show up in the log for #1844.

Making unicode ellipsis into three periods

---

yt/data_objects/level_sets/clump_handling.py

This prevents an `UnboundLocalError` if you don't specify any fields:
```python
File "clump_find.py", line 50, in <module>
master_clump.save_as_dataset(clump_file)
File "/usr/local/shared/python/2.7.6-gcc/lib/python2.7/site-packages/yt/analysis_modules/level_sets/clump_handling.py", line 360, in save_as_dataset
clump_info.update(field_data)
UnboundLocalError: local variable 'field_data' referenced before assignment
```

Clump.save_as_dataset: Only update with field_data if it is defined

---

setup.cfg

Let's get these flake8 nits fixed for 4.0, so our tests can all pass there, too!

Updating flake8 nits for yt-4.0

---

yt/data_objects/time_series.py
yt/startup_tasks.py
yt/utilities/parallel_tools/parallel_analysis_interface.py

I should have included this in the previous PR, but I did not.

Fixing actual, real Flake8 errors.

---

yt/frontends/ramses/data_structures.py
yt/frontends/ramses/field_handlers.py
yt/frontends/ramses/particle_handlers.py

This PR fixes a small bug in Python3 that was preventing from using groups with yt. It also enables the possibility to have variable speed of light for RT runs.

[RAMSES] Fix RT and groups

---

yt/visualization/eps_writer.py

This addition allow the user to rotate an arrow. Before it was only horizontal.

Adding option to rotate arrows in the EPS writer

---

MANIFEST.in

ensure map.js is included in the sdist for the mapserver. closes #2157

---

doc/source/developing/releasing.rst

Madicken volunteered to look this over after I showed her yt's release process today.

update docs on doing a release to reflect building binaries

---

yt/visualization/plot_modifications.py

Dunno if there are other places in yt where we need to do the same sort of wrapping around yt_astro_analysis which may or may not be installed.

add support for yt_astro_analysis in the halo plot modification

---

yt/frontends/stream/data_structures.py

This clears one of the yt-4.0 FIXMEs. I've added additional code comments and docstrings relating to loading and identifying SPH data in the stream frontend.

[yt-4.0 FIXME] Update docs and code comments on loading SPH data in stream frontend.

---

.github/config.yml

We have not yet enabled a welcome bot
( https://probot.github.io/apps/welcome/ ) but this will configure it
when/if we do.

Adding a welcomebot config.

---

.pep8speaks.yml

escape out astrick

---

.pep8speaks.yml

I was multiply defining `ignore` when the second one should have been
`exclude`.

Change pep8speaks config ignore to exclude

---

appveyor.yml

This should hopefully fix the windows test failures we're seeing on #2230.

fix appveyor builds

---

yt/data_objects/octree_subset.py

Correctly guess array shape in cases with single oct

---

yt/frontends/ramses/data_structures.py
yt/frontends/ramses/definitions.py
yt/frontends/ramses/tests/test_outputs.py
yt/utilities/cython_fortran_utils.pyx

[Fortran] Support empty records

---

doc/source/analyzing/filtering.rst

This is a companion PR to yt-project/yt#1964. In that PR some minor docfixes were requested and haven't been included yet, so I've created this PR to supplement it so that the original PR can be merged. 
If I missed any other nits from that PR, let me know and I'll add them here.

Docfixes for cut_region feature 

---

yt/utilities/parallel_tools/task_queue.py

Fix iterator in Python 3.7

---

yt/data_objects/data_containers.py
yt/frontends/artio/data_structures.py
yt/frontends/enzo/simulation_handling.py
yt/frontends/gadget/simulation_handling.py
yt/frontends/gadget_fof/io.py
yt/frontends/owls_subfind/io.py
yt/frontends/sdf/io.py
yt/frontends/stream/data_structures.py
yt/frontends/ytdata/data_structures.py
yt/funcs.py
yt/utilities/sdf.py
yt/visualization/plot_modifications.py
yt/visualization/plot_window.py

`mylog.warn` now gives a deprecation warning.

Replace deprecated logging.warn with logging.warning.

---

yt/frontends/gamer/data_structures.py

Correctly identify the periodic boundary condition in the GAMER frontend.

[bugfix] Fix periodicity in gamer

---

yt/visualization/plot_modifications.py

For some reason, data used to compute vector field was passed in cgs...

Use proper units for pixelization of quiver fields. Fixes #2291

---

yt/frontends/gadget_fof/data_structures.py
yt/frontends/gadget_fof/io.py

Minor updates to the GadgetFOFHaloDataset to be yt-4.0 compliant.

[bugfix] Update GadgetFOFHaloDataset for yt-4.0.

---

yt/frontends/enzo/simulation_handling.py
yt/frontends/gadget/simulation_handling.py

This updates Gadget and Enzo's time-series classes to work with Unyt.

[bugfix] make simulation handling work with Unyt

---

doc/source/analyzing/fields.rst
yt/fields/particle_fields.py
yt/geometry/tests/test_neighbor_search.py
yt/testing.py

I'm reopening this from #1347.  It needs at least:

Neighbor value

---

yt/units/tests/test_ytarray.py
yt/units/yt_array.py

This backports https://github.com/yt-project/unyt/pull/102/files to fix
some issues with `np.clip`.

Backporting unyt PR 102 for clip

---

doc/source/analyzing/Particle_Trajectories.ipynb
doc/source/analyzing/analysis_modules/SZ_projections.ipynb
doc/source/analyzing/analysis_modules/XrayEmissionFields.ipynb
doc/source/analyzing/units/1)_Symbolic_Units.ipynb
doc/source/analyzing/units/2)_Fields_and_unit_conversion.ipynb
doc/source/analyzing/units/3)_Comoving_units_and_code_units.ipynb
doc/source/analyzing/units/4)_Comparing_units_from_different_datasets.ipynb
doc/source/cookbook/custom_colorbar_tickmarks.ipynb
doc/source/cookbook/fits_xray_images.ipynb
doc/source/cookbook/geographic_xforms_and_projections.ipynb
doc/source/cookbook/notebook_tutorial.rst
doc/source/cookbook/tipsy_and_yt.ipynb
doc/source/cookbook/yt_gadget_analysis.ipynb
doc/source/cookbook/yt_gadget_owls_analysis.ipynb
doc/source/examining/Loading_Generic_Array_Data.ipynb
doc/source/quickstart/1)_Introduction.ipynb
doc/source/visualizing/FITSImageData.ipynb

Updating external URLs in jupyter notebooks and other minor edits.

Some updates in ipython notebooks

---

yt/frontends/sdf/tests/test_outputs.py

Trying to speed up SDF test by using NCSA mirror.

Use mirror copy of SDF data

---

CONTRIBUTING.rst

Correct reference label for new contributor issues in github.

Correct reference to new-contributor-friendly issues

---

yt/frontends/arepo/data_structures.py
yt/frontends/arepo/fields.py

This PR adds the fields for magnetic divergence and pressure to the Arepo frontend.

Adding more Arepo fields

---

yt/frontends/ramses/data_structures.py
yt/frontends/ramses/field_handlers.py
yt/frontends/ramses/fields.py
yt/frontends/ramses/io.py
yt/frontends/ramses/tests/test_outputs.py

This pull request ensures that magnetic fields in RAMSES follow both yt naming convention, and are loaded with the correct units. In this way, magnetic fields from RAMSES outputs can be handled consistently by yt, and derived magnetic quantities such as the plasma beta and Alfven speed become available to users. 
Before this fix, magnetic fields in RAMSES were loaded into yt as dimensionless extra fluid fields which severely limited their use for analysis, and made derived magnetic quantities unavailable. 
This pull request also adds the magnetic divergence per cell, divB, as an extra magnetic fields, which is a commonly used diagnostic to monitor that magnetic simulations are running as expected.

Update magnetic field handling for RAMSES

---

doc/source/reference/api/api.rst

Complete api documentation for the frontend.
fixes #2374 
~wip: waiting for PR #2369 to be merged to bundle the corresponding documentation here~ **done**

[AMRVAC] complete api doc for amrvac's frontend.

---

tests/tests.yaml
yt/frontends/amrvac/fields.py

will fix https://github.com/yt-project/yt/issues/2375 (missing a clear definition for the unit atm)

[AMRVAC] fix energy field name and unit

---

yt/visualization/color_maps.py

fix #2389 
Was much easier a fix than I anticipated when writing the issue 🎉

Correctly register reversed versions of cmocean cmaps

---

yt/frontends/amrvac/data_structures.py

Improves the logging verbosity when parsing "geometry" from the datafile or from user input (geometry_override).

[AMRVAC] Small improvements on logging

---

CONTRIBUTING.rst

This is a small set of changes to the documentation on developing for yt. I thought these would be helpful clarifications for potential new contributors.

minor updates to documentation on contributing with git

---

appveyor.yml
tests/test_requirements.txt
yt/units/unit_object.py
yt/units/yt_array.py

This fixes test failures on the latest version of sympy. I will also be issuing a PR with a similar fix for unyt.

add support for sympy 1.5

---

yt/visualization/plot_window.py

I want code that thinks for me. Therefore, I'm proposing to make yt smarter than myself and catch absurd values for zooming factors early rather than downstream.

raise a meaningful error on negative and zero zooming factors

---

MANIFEST.in
appveyor.yml
doc/install_script.sh
doc/source/examining/loading_data.rst
doc/source/quickstart/1)_Introduction.ipynb
doc/source/quickstart/2)_Data_Inspection.ipynb
doc/source/quickstart/3)_Simple_Visualization.ipynb
doc/source/quickstart/4)_Data_Objects_and_Time_Series.ipynb
doc/source/quickstart/5)_Derived_Fields_and_Profiles.ipynb
doc/source/quickstart/6)_Volume_Rendering.ipynb
tests/test_install_script.py
tests/test_requirements.txt
yt/__init__.py
yt/sample_data_registry.json
yt/utilities/load_sample.py
yt/utilities/on_demand_imports.py
yt/utilities/sample_data.py
yt/utilities/tests/test_load_sample.py

This PR posits implementing the [pooch package](https://www.fatiando.org/pooch/latest/index.html) in order to fetch sample data that is not already stored locally.
An example use-case is when performing answer tests, as these require a lot of sample data in order to run. Rather than have the user have to manually download all of the data needed for the tests they want to run, this would enable them to simply run their desired tests and, if the data isn't already present on their machine, download and load the required sample data automatically (with appropriate log messages to indicate exactly what is going on).

Using pooch to fetch remote data files

---

.travis.yml

Travis seems to be throwing a warning and an error message when validating our current travis config file. This PR should remove the issues causing them. [example here](https://travis-ci.org/yt-project/yt/builds/649100075/config?utm_medium=notification&utm_source=github_status)

Fix warnings due to travis configuration file

---

setup.py

Matplotlib now has a trove classifier, so let's add it!
https://twitter.com/matplotlib/status/1235216347925286913

adding matplotlib to trove classifiers

---

yt/utilities/lib/grid_traversal.pxd
yt/utilities/lib/volume_container.pxd

Adds documentation for  the struct ```VolumeContainer``` and ```vc_index```.

Documentation for VolumeContainer and related function.

---

doc/cheatsheet.tex
doc/source/quickstart/index.rst

[doc] Update hub references in documentation

---

doc/source/installing.rst

yt has been packaged in some platforms. It could be useful to include a list of
packages and versions in those repositories in the installation documentation to
keep track of where the project is packaged.
https://repology.org/project/python:yt/versions
For some reason Gentoo's `sci-visualization/yt` is not in this list but will report it
and hopefully it will get fixed soon.

[doc] Add existing packages in the documentation

---

yt/frontends/stream/data_structures.py

hotfix an error induced recently by https://github.com/yt-project/yt/pull/2478

fix an error where StreamHierarchy doesn't set self.min_level

---

yt/visualization/plot_modifications.py

Some of the callbacks (annotate_grids, annotate_cells) were not respecting physical size of the FRB and assumed that it's expressed in `code_length`.

Set physical/plot bounds consistently across all callbacks. Fixes #2293

---

yt/utilities/png_writer.py

Conform to matplotlib 3.2+ API

---

doc/source/analyzing/astropy_integrations.rst
doc/source/analyzing/generating_processed_data.rst
doc/source/analyzing/index.rst
doc/source/examining/loading_data.rst
yt/analysis_modules/sunyaev_zeldovich/projection.py
yt/data_objects/construction_data_containers.py
yt/data_objects/data_containers.py
yt/frontends/open_pmd/fields.py
yt/frontends/ramses/field_handlers.py
yt/frontends/ramses/particle_handlers.py
yt/utilities/answer_testing/utils.py
yt/visualization/fits_image.py
yt/visualization/plot_container.py
yt/visualization/plot_window.py
yt/visualization/profile_plotter.py

Starting point:
```
dumping object inventory... done
build succeeded, 137 warnings.
```
let's see how many I've fixed.

Various doc syntax fixes

---

yt/visualization/color_maps.py

add reversed version of turbo colormap

---

yt/data_objects/static_output.py

Refactor Dataset.box to accept mixed input forms (list of YTQuantity VS YTArray)
Fix #2560

refactor Dataset.box (hotfix #2560)

---

yt/testing.py

[bugfix] Put pytest import inside function.

---

doc/source/analyzing/analysis_modules/absorption_spectrum.rst
doc/source/examining/loading_data.rst
doc/source/reference/changelog.rst

Fix some typos in documentation

Fix some typos in documentation

---

yt/visualization/eps_writer.py

Remove unused arg (`len(fields)`) in string formatting.

Remove unused arg in string formatting

---

yt/frontends/flash/data_structures.py
yt/frontends/open_pmd/data_structures.py
yt/frontends/ramses/data_structures.py
yt/utilities/grid_data_format/conversion/conversion_athena.py
yt/visualization/plot_container.py
yt/visualization/profile_plotter.py

This is pretty much the same as #2386, but aimed at the yt-4.0 branch.

Hotfix literal comparisons (yt 4.0)

---

yt/frontends/_skeleton/data_structures.py

This is a very minor docstring enhancement in the skeleton frontend noting the need to make the _is_valid method unique.

add clarification about uniqueness in _is_valid method

---

yt/funcs.py

Fixes `AttributeError: module 'urllib' has no attribute 'request'` when trying to download owls ion data.
It apears python3 requires `import urllib.request`

[yt-4.0] urllib bugfix

---

setup.py

fixed `setup.py` typo. Noticed when building today.

[yt-4.0] setup typo

---

yt/geometry/particle_oct_container.pyx

I thought I had incremented the bitmask version in #2575, but I had not.  This needs to go in pretty quickly as the bitmasks all need to be re-generated.

Update bitmask_version for #2575

---

yt/frontends/adaptahop/data_structures.py
yt/frontends/adaptahop/io.py
yt/frontends/adaptahop/tests/test_outputs.py
yt/frontends/halo_catalog/data_structures.py

This fixes the support of the AdaptaHOP halo finder frontend for yt-4.
Should fix the errors appearing in #2677 .

[BUGFIX] adaptahop frontend

---

yt/frontends/enzo/tests/test_outputs.py

This addresses the issues in #2677 for Enzo tests by updating the results they are looking for.

Updating enzo active particle tests

---

CONTRIBUTING.rst

This adds black and pre-commit hooks to the contributing documentation
it follows https://github.com/yt-project/yt/pull/2596 and anticipates on https://github.com/yt-project/yt/pull/2600 being merged

YTEP0037 (doc) add black and pre-commit hooks sections to CONTRIBUTING.rst

---

yt/data_objects/static_output.py
yt/frontends/ytdata/data_structures.py
yt/testing.py
yt/utilities/command_line.py

This addresses part of #2666, namely B009 "Do not call getattr with a constant attribute value".

fix flake8-bugbear B009 (YTEP0037 6/6, part 2)

---

yt/frontends/flash/data_structures.py
yt/frontends/open_pmd/data_structures.py

This addresses part of #2666, namely B014 "Redundant exception types"

fix flake8-bugbear B014 errors (redundancy in exception catching) (YTEP0037 6/6, part 4)

---

setup.cfg
yt/data_objects/analyzer_objects.py
yt/data_objects/time_series.py
yt/frontends/art/io.py
yt/utilities/decompose.py
yt/visualization/volume_rendering/old_camera.py

fix 2 flake8 errors throughout the code base and remove them from the ignoramus's list

Flake8 errors fixup

---

doc/source/examining/low_level_inspection.rst
yt/data_objects/static_output.py
yt/frontends/_skeleton/data_structures.py
yt/frontends/_skeleton/io.py
yt/frontends/enzo/io.py
yt/frontends/gadget_fof/data_structures.py
yt/geometry/geometry_handler.py
yt/geometry/grid_geometry_handler.py
yt/utilities/io_handler.py

At @brittonsmith and @jzuhone's joined request, here's #2553, reforged for yt-4.0 (and python 3 only 🎉).
Haven't been able to test this locally yet, so let's see what happens (inheritance + metaclasses conflicts seem very likely).
Fix https://github.com/yt-project/yt/issues/2426

Abstract data structures

---

setup.cfg
yt/data_objects/data_containers.py
yt/data_objects/particle_container.py
yt/data_objects/selection_data_containers.py
yt/frontends/fits/data_structures.py
yt/frontends/open_pmd/data_structures.py
yt/utilities/answer_testing/answer_tests.py
yt/utilities/lib/cykdtree/plot.py
yt/visualization/eps_writer.py

this addresses part of the problems reported in #2666, namely B006 "Do not use mutable data structures for argument defaults."

fix flake8-bugbear B006 (YTEP0037 6/6, part 1)

---

doc/source/visualizing/callbacks.rst
yt/visualization/color_maps.py
yt/visualization/eps_writer.py
yt/visualization/line_plot.py

A few fixes for errors and warnings found by Jenkins

Misc fixes to issues found during docs building

---

yt/frontends/boxlib/api.py

Very quick addition to the public api for AMReX classes

add missing entries to boxlib frontend api

---

.github/mergeable.yml

mark ~'proposal'~, 'dead code' and 'refactor' as acceptable labels in the eye of the "mergeable" bot.

add 2 labels to mergeable list

---

yt/utilities/tests/test_amr_kdtree.py

A dead test, probably better to remove it than trying to revive it after so long.

remove a test that's been disabled for 7 yrs

---

doc/source/examining/loading_data.rst

While trying to fix a build error related to sphinx-3.2.0 I encountered a few red herrings. This PR fixes them anyway.

docs: Fix syntax errors in loading_data

---

.travis.yml

twin sister of https://github.com/yt-project/slash-command-processor/pull/3

Print versions of checkers on Travis

---

tests/tests.yaml
yt/data_objects/construction_data_containers.py
yt/data_objects/selection_data_containers.py
yt/geometry/coordinates/cartesian_coordinates.py
yt/utilities/lib/pixelization_routines.pyx

This PR makes changes to SPH pixelization for slices, projections, and arbitrary grids which use scatter smoothing to ensure they respect periodicity. This was not true previous to this PR, so (for example) if you had a periodic box simulation and you made a projection near a domain edge the regions outside the box would be blank.
I also discovered a bug in region selection for SPH particles when the region crosses a periodic boundary which is fixed here. 
The pixelization methods which use "gather" smoothing appear to not need any changes. 
I don't think this works for off-axis projections because in that case the particle positions are rotated to the new frame first and then projected. So we need to figure out how to handle that.
Also need to decide if answer testing is sufficient or if …

[bugfix] Ensure SPH visualizations respect periodicity

---

.github/workflows/style-checks.yaml

Hotfix following https://github.com/yt-project/yt/pull/2862 : trigger the linting workflow on pull requests as well

trigger style check workflow on PR

---

yt/frontends/arepo/io.py
yt/frontends/gadget/io.py
yt/frontends/gadget_fof/io.py
yt/frontends/halo_catalog/data_structures.py
yt/frontends/halo_catalog/io.py
yt/frontends/swift/data_structures.py
yt/frontends/swift/io.py
yt/frontends/swift/tests/test_outputs.py
yt/frontends/ytdata/io.py
yt/loaders.py

Quick fix for `yt.load_sample` that I broke in my refactor #2832

hotfix a refactoring mistake that broke load_sample

---

yt/data_objects/time_series.py
yt/loaders.py
yt/utilities/exceptions.py

Fix a formatting mistake from #2818

hotfix error message format

---

yt/fields/field_info_container.py
yt/utilities/lib/misc_utilities.pyx

fix a missing not implemented error discovered with #2851

add a missing NotImplementedError

---

yt/utilities/logger.py

If there's any appetite for  https://github.com/yt-project/yt/issues/2865, here's the fix
fix https://github.com/yt-project/yt/issues/2865
fix https://github.com/yt-project/yt/issues/2859
Inserting this at the end of `yt/__init__.py`
```python
for _ in range(30):
mylog.critical("All work and no play makes Jack a dull boy.")
```
and running
```bash
python -c "import yt"
```
```
yt : [CRITICAL ] 2020-08-16 19:24:52,893 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,893 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,894 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,894 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,894 All work and no play makes Jack a dull …
```

Add a filter to ytLogger to avoid duplicated successive entries

---

.travis.yml
tests/nose_runner.py
tests/test_requirements.txt

This PR should be merged before #2800 It ports all the necessary changes to testing infra in order to ensure that current stable branch passes all tests.

Ensure that all test suites work on stable

---

yt/funcs.py

same as #2898, for `yt/funcs.py`

[doctest] fix errors in yt.funcs docstrings

---

tests/test_requirements.txt

Bump mpl to 3.3 for tests

---

yt/geometry/grid_geometry_handler.py

Fixes #2838. The bug is happening when particles are found for some reason at the boundary of grids.

Bugfix 2838

---

tests/tests.yaml
yt/visualization/base_plot_types.py
yt/visualization/image_writer.py
yt/visualization/tests/test_offaxisprojection.py

Fix: matplotlib deprecation warnings

---

doc/source/cookbook/geographic_xforms_and_projections.ipynb
doc/source/cookbook/yt_gadget_analysis.ipynb

remove unused imports in cookbook notebooks

---

yt/frontends/ramses/data_structures.py

[bugfix] RAMSES: do not fail when impossible to convert from conformal → physical time. 

---

yt/sample_data_registry.json

This is an attempt at fixing #2699 by auto-discovering missing load names.
I used the following script to auto-update the json file.
```python
import wget
import json
from pathlib import Path
import tarfile
import requests
import tempfile
import yt
from yt.utilities.exceptions import YTUnidentifiedDataType
import struct
from urllib.error import HTTPError
MAX_SIZE = 1e9  # 1 Gb
blacklist = ["output_00080_halos.tar.gz", "acisf05356N003_evt2.fits.gz", "CompactObjects.tar.gz"]
reg_file = "yt/sample_data_registry.json"
with open(reg_file) as fh:
reg = json.load(fh)
for name, data in reg.items():
if data["load_name"] or name in blacklist:
continue
response = requests.head(data["url"])
try:
if int(response.headers["Content-Length"]) > MAX_SIZE:
continue
except KeyError:
pass
print(f"Looking for …
```

fix: autocomplete some missing entries in sample data registry file

---

MANIFEST.in

This should resolve yt-project/yt#2532
Includes cosmology_answers.yml in the MANIFEST.in file

ensure cosmology_answers.yml will be included in distribution

---

tests/ci_install.sh

In order to avoid things like: https://github.com/yt-project/yt/runs/1551929677?check_suite_focus=true

Update apt cache to avoid random missing packages

---

setup.py

#2893 broke yt_idv downstream. This should fix the problem.

fix: add more_itertools to requirements in setup.py

---

README.md

minor visual enhancement for README.md

doc: markup shell snippets in README.md

---

conftest.py
tests/nose_runner.py
tests/test_install_script.py

address minor instabilities detected by newly deployed pre-commit hooks, merge asap please :)

fix: align code base with pre-commit hooks

---

tests/test_requirements.txt

There seems to be something fishy happening with cftime 1.3.1 on windows, trying to fix this.

[bugfix] Prevent v1.3.1 of cftime (upstream dep)

---

yt/__init__.py
yt/_maintenance/deprecation.py
yt/config.py
yt/data_objects/index_subobjects/octree_subset.py
yt/data_objects/static_output.py
yt/data_objects/time_series.py
yt/fields/field_info_container.py
yt/fields/particle_fields.py
yt/fields/species_fields.py
yt/loaders.py
yt/utilities/amr_kdtree/amr_kdtree.py
yt/utilities/answer_testing/framework.py
yt/utilities/exceptions.py
yt/visualization/color_maps.py
yt/visualization/eps_writer.py
yt/visualization/image_writer.py
yt/visualization/plot_container.py
yt/visualization/plot_window.py

Reverts yt-project/yt#3035
This created import cycles that are hard to fix without spaghetti code (see #3039).

Revert "Add possibility to silence some warnings"

---

yt/funcs.py

This updates the `is_root` and `only_on_root` functions for the new configuration.

Update is_root and only_on_root functions.

---

yt/data_objects/time_series.py

I am under the impression that this method could be simplified... to the point of not being necessary any more.
Trying to naively remove it and see what breaks.
edit: nothing ! 🎉

exp: remove DatasetSeries.__iter__

---

CONTRIBUTING.rst
pyproject.toml

doc: add short descriptions of main code formatters

---

.pre-commit-config.yaml
setup.cfg
tests/report_failed_answers.py
yt/data_objects/construction_data_containers.py
yt/data_objects/selection_objects/ray.py
yt/data_objects/static_output.py
yt/frontends/nc4_cm1/data_structures.py
yt/frontends/ramses/data_structures.py
yt/frontends/stream/data_structures.py

This [flake8 plugging](https://github.com/globality-corp/flake8-logging-format) enforces the change that was performed in #2820 by @cphyc (and more). I'm also fixing a couple of mistakes that survived the previous PR or were introduced since then: Using this plugging will provide stability.
edit 1: here's the report from running this at a point before #2820
[g.log](https://github.com/yt-project/yt/files/5980515/g.log)

CI: enforce consistent string formatting syntax in logger calls

---

yt/funcs.py

fix another FutureWarning from numpy

---

yt/funcs.py

This is related to but not part of YTEP-0039 and is pretty straightforward.

cleanup: remove seemingly unused pbar class

---

yt/data_objects/construction_data_containers.py
yt/utilities/command_line.py
yt/utilities/on_demand_imports.py

This is an alternative PR to #3098, and hopefully less controversial

make requests a part of yt.utilities.on_demand_imports

---

CONTRIBUTING.rst

See the current broken build for this page
https://yt-project.org/docs/dev/developing/developing.html#automatically-checking-and-fixing-code-style

doc: fix hyperlink formatting

---

yt/fields/vector_operations.py

At the moment, the current fields cannot be computed for octree datasets (RAMSES & ART).
```python
import yt
ds = yt.load_sample("output_00080")
ds.r["gas", "shear_mach"]       # raises RuntimeError
ds.r["gas", "average_density"]  # raises YTFieldNotFound
```
The script should be able to run till the end. Note that it may catch some `yt.fields.field_exceptions.NeedsParameter` exceptions.
```python
import yt
from tqdm import tqdm
ds = yt.load_sample("output_00080")
for ftype, fname in tqdm(np.random.permutation(ds.derived_field_list)):
if "cutting_plane" in fname:  # need to skip cutting planes as they require a cutting plane!
continue
if fname in ("shear_mach", "average_density"):  # these trigger catastrophic failures, skip them
continue …
```

[bugfix] Fix field calculation for octrees

---

yt/data_objects/construction_data_containers.py
yt/data_objects/tests/test_points.py
yt/frontends/exodus_ii/data_structures.py
yt/frontends/tipsy/io.py
yt/geometry/_selection_routines/data_collection_selector.pxi
yt/testing.py
yt/utilities/answer_testing/framework.py
yt/utilities/particle_generator.py
yt/utilities/sdf.py
yt/visualization/eps_writer.py

As I was searching logs for an explicit mention of a future version of numpy that will break the current state of yt, I was able to fix _some_ of the existing warnings (definitely not all, some are much harder to track down than others).

Fix some numpy deprecation warnings

---

yt/loaders.py

This is an attempt at fixing a bug reported by @matthewturk on Slack.
I think the bug is plateform dependent and I don't have time to properly test it just yet, so I'm opening early in hopes that @matthewturk can test it locally first.

hotfix: yt.load_sample + yt_data_dir unset

---

tests/tests.yaml
yt/utilities/answer_testing/framework.py
yt/visualization/tests/test_profile_plots.py

Follows #3101 by bumping answer tests. This PR should be merged after #3101 is itself merged as it shares all but 2 commits.
Updates to the answer are in https://github.com/yt-project/answer-store/pull/18.

[2/2] No ambiguous fields automatic — bump answer tests

---

yt/data_objects/level_sets/contour_finder.py
yt/data_objects/particle_trajectories.py
yt/frontends/athena_pp/data_structures.py
yt/frontends/enzo/data_structures.py
yt/frontends/enzo_p/data_structures.py
yt/geometry/particle_geometry_handler.py
yt/geometry/particle_oct_container.pyx
yt/utilities/answer_testing/framework.py
yt/utilities/particle_generator.py
yt/visualization/streamlines.py

Since moving to an external version of `tqdm` (I think), the progress bars using a zero-based counting variable have all been off by one. This fixes that.

Update pbars for off-by-one

---

yt/frontends/amrvac/fields.py

This change was suggested by @kiradorn over slack

fix: add temperature to known fields list for AMRVAC

---

yt/visualization/plot_container.py

Follow up to #3175, #3212 and complementary to #3207
This reintroduces the possibly to use unprefixed colormaps from cmocean, using isolated adapter code that can be dropped after the 4.0 release, and adding a visible deprecation warning were due.
The change is documented in #3207 (where I'll suggest changes to account for this adaptation).

add a visible deprecation warning for unprefixed cmocean maps

---

yt/fields/field_detector.py
yt/frontends/gadget/io.py

I need to check if that doesn't introduce any unnecessary overhead, but on the bright side it removes a lot of hardcoded information.

Use io._vector_fields to get a field shape. Fixes #3191

---

doc/source/analyzing/fields.rst
doc/source/reference/field_list.rst
doc/source/yt4differences.rst

This is my attempt to better flesh out the yt4 diffs docs page. Partially addresses Issue #3231 .

Filling out the yt4 diffs docs page

---

.pre-commit-config.yaml
CONTRIBUTING.rst
doc/source/analyzing/domain_analysis/clump_finding.rst
doc/source/analyzing/domain_analysis/cosmology_calculator.rst
doc/source/analyzing/domain_analysis/index.rst
doc/source/analyzing/fields.rst
doc/source/analyzing/filtering.rst
doc/source/analyzing/generating_processed_data.rst
doc/source/analyzing/objects.rst
doc/source/analyzing/units.rst
doc/source/cookbook/complex_plots.rst
doc/source/examining/loading_data.rst
doc/source/installing.rst
doc/source/reference/changelog.rst
doc/source/reference/configuration.rst
doc/source/visualizing/geographic_projections_and_transforms.rst
doc/source/visualizing/plots.rst
doc/source/visualizing/unstructured_mesh_rendering.rst
doc/source/visualizing/volume_rendering.rst
doc/source/yt3differences.rst

follow up to #3264 with a pre-commit hook for future-proofing

Fix docs barticks

---

doc/source/analyzing/fields.rst
doc/source/analyzing/time_series_analysis.rst
doc/source/cookbook/time_series_profiles.py
doc/source/visualizing/callbacks.rst
doc/source/visualizing/plots.rst
tests/tests.yaml
yt/utilities/amr_kdtree/amr_kdtree.py
yt/visualization/plot_window.py
yt/visualization/tests/test_plotwindow.py

I discovered some deprecated functionalities are still used internally or documented as usable while they really aren't (add_volume_weighted_smoothed_field)

maint: cleanup usage and mentions of deprecated material

---

yt/loaders.py

Was looking for something else, stumbled upon this low-hanging fruit

code deduplication, reuse lookup_on_disk_data in load_simulation

---

yt/loaders.py

got the opportunity to catch and fix this while testing #3258

load_sample: add a clear error message for datasets missing website registration

---

doc/source/analyzing/fields.rst
doc/source/analyzing/objects.rst

This adds -- and removes! -- documentation about particle deposit fields.
Fixes #2218.

Adding notes about particle deposit fields.

---

yt/sample_data_registry.json

This is a hotfix to #3280. Fix #3178 (again)

hotfix broken urls for amrvac data samples

---

yt/loaders.py

fix load_sample's signature

---

yt/data_objects/static_output.py
yt/frontends/arepo/tests/test_outputs.py

Add some more uniqueness to `unique_identifier`

Make uniq_id a little bit more unique

---

yt/sample_data_registry.json

load_sample: fixup broken load_kwargs for athena datasets

---

tests/tests.yaml

bump answers for local_halos tests

---

yt/loaders.py
yt/sample_data_registry.json

Fix #3335 
This is based on top of #3336 to avoid breaking stuff by solving conflicts, so it should be merged later, and I'm opening as a draft to signal this.

load_sample: add support to load dataset series via wildcards

---

CONTRIBUTING.rst

This is a handful of changes to match what we currently do in yt, as of 4.0.  I read the rest and it all seems pretty good and modern.

Updating developer guide for 4.0

---

doc/source/yt4differences.rst

I have gone through all the yt4 diffs that are there, and I think this should finish it up.  I think with this we can close #3231.

Fill out more yt 4 differences

---

yt/data_objects/static_output.py
yt/geometry/particle_geometry_handler.py
yt/geometry/particle_oct_container.pyx

Fixes #3192
This PR accomplishes two specific goals.  The first is that it enables, in the case of smoothed particles, an on-the-fly adjustment of the `index_order2` value.
What happens in many cases with the default `index_order2` value is that we have some gas particles that have very large smoothing lengths; this often happens with small, isolated datasets -- particles out at the edges have big `hsml` values.  It's very expensive to manage these at high `index_order2` values, since that involves lots of setting things to 1, lots of map accesses, etc.  It also is not broadly *useful* since even if they collide at coarse levels, they are so big that the degree of collision is pretty minimal.
This allows those cases to dynamically update the `index_order2` value to be representative of …

Add a heuristic for resetting index_order2

---

yt/data_objects/particle_trajectories.py
yt/fields/derived_field.py
yt/utilities/parallel_tools/parallel_analysis_interface.py

This is a continuous effort to update the particle trajectories.
It fixes:
- a bug when passing large amount of data that was causing MPI to overflow its allowed limits. The workaround is to split the data in smaller chunks of more reasonable size (at the cost of more MPI broadcast operations)
- fix an issue with a non-existing property (`particle_type`) which may have disappeared at some point.

Fixing particle trajectories

---

yt/funcs.py
yt/loaders.py
yt/tests/test_load_sample.py

fix #3266
(the typo in the title is real, but I decided to keep it as an Easter egg)

UX: add suggestions in case of typo in yt.load_sampel

---

.github/workflows/build-test-pytest.yaml
.github/workflows/build-test.yaml

revert temporary patch from #3396

CI: revert temporary patch

---

doc/source/quickstart/4)_Data_Objects_and_Time_Series.ipynb
doc/source/quickstart/5)_Derived_Fields_and_Profiles.ipynb
doc/source/reference/command-line.rst
doc/source/visualizing/streamlines.rst
doc/source/visualizing/unstructured_mesh_rendering.rst
scripts/iyt
yt/visualization/volume_rendering/tests/test_vr_cameras.py

DOC: cleanup remaining occurences of pylab in favour of matplotlib.pyplot

---

pyproject.toml

Update black configuration following currently supported Python versions.
This should have zero immediate impact on the code style.

MAINT: update black configuration

---

yt/visualization/profile_plotter.py

Reverts yt-project/yt#3425. I missed the fact that #3282.already exists and has a better solution to the problem.

Revert "Use a fancier repr for labels in Profile/PhasePlots. Fixes #3269"

---

doc/source/installing.rst

Fix an improperly shaped table and one sentence.

DOC: fix two mistakes in installing.rst

---

yt/visualization/plot_container.py

BUG: fix mpl data path handling for Windows

---

yt/frontends/boxlib/io.py

I have recently been having I/O issues with boxlib data and noticed that there was a missing close statement in the function. This is unlikely to fix the issues I was having but might offer slightly better performance.

Very minor update including a close statement in boxlib io

---

yt/frontends/ytdata/tests/test_outputs.py
yt/utilities/answer_testing/answer_tests.py
yt/utilities/answer_testing/testing_utilities.py

This function is duplicated (verbatim) from yt/utilities/answer_testing/framework.py
and not used anywhere

ENH: cleanup verbatim testing function duplicates

---

yt/visualization/plot_container.py

BUG: override image suffix with matplotlib argument in case of conflict

---

doc/source/visualizing/callbacks.rst

DOC: fix a broken example (change of api in the Athena frontend)

---

doc/source/yt4differences.rst

Fix #3451
This should be backported to the 4.0.x branch

DOC: add an exhaustive list of deprecations to the yt4differences page

---

yt/frontends/gadget_fof/data_structures.py
yt/frontends/halo_catalog/data_structures.py

Removes duplication in halo containers.
This is one step aimed at minimizing code duplication.
The duplicates are spotted using
```bash
pylint --disable=all --enable=duplicate-code yt/
```
Note that I have **not** attempted to fix all duplicate here.
I am not fully satisfied with the way I have de-duplicated code with chombo/boxlib. Any input is welcome!
I'd also be happy to split the PR in multiple chunks.

ENH: Factorize code in halo containers

---

yt/visualization/plot_container.py
yt/visualization/profile_plotter.py

This regroups the remaining PRs that affected the answer store
Contents:
- Merge pull request #3282 from chummels/phase_ion
- Merge pull request #3637 from neutrinoceros/fix_ylabel_frac

Backport typesetting patches to yt-4.0.x

---

doc/source/cookbook/complex_plots.rst
doc/source/reference/api/api.rst
yt/__init__.py
yt/config.py
yt/data_objects/derived_quantities.py
yt/data_objects/index_subobjects/octree_subset.py
yt/data_objects/static_output.py
yt/data_objects/time_series.py
yt/fields/field_info_container.py
yt/fields/local_fields.py
yt/fields/particle_fields.py
yt/fields/species_fields.py
yt/funcs.py
yt/loaders.py
yt/utilities/amr_kdtree/amr_kdtree.py
yt/utilities/answer_testing/framework.py
yt/utilities/command_line.py
yt/utilities/configure.py
yt/utilities/exceptions.py
yt/utilities/tests/test_config.py
yt/visualization/color_maps.py
yt/visualization/eps_writer.py
yt/visualization/image_writer.py
yt/visualization/plot_container.py
yt/visualization/plot_window.py

This removes all code that was targeted for removal for yt 4.1, and associated documentation, with the notable exception of ambiguous fields. This part is left to be solved with #3416 (also included in the 4.1 milestone).

DEPR: deprecation cycle (4.0 -> 4.1)

---

yt/geometry/coordinates/spherical_coordinates.py

Fix a small but fatal mistake that slipped in in #3533

BUG: fix a name error in SphericalCoordinateHandler

---

doc/source/visualizing/plots.rst

DOC: fix markup errors in spherical projections section

---

yt/visualization/_commons.py
yt/visualization/_mpl_imports.py
yt/visualization/plot_container.py
yt/visualization/profile_plotter.py
yt/visualization/tests/test_commons.py
yt/visualization/tests/test_save.py
yt/visualization/volume_rendering/scene.py

Manual backport for #3687, this time with correct branching (after I made a mistake in #3697)

Backport #3410 + #3687 to yt-4.0.x (image filename validation fixes)

---

doc/source/examining/loading_data.rst

Also remove a note that is not true anymore (the frontend was first released 2 years ago in yt 3.6.0 and hasn't changed much since then)

DOC: fix an error in AMRVAC specific documentation

---

tests/unpin_requirements.py

ENH: add unpin_requirements.py script to version control

---

yt/_maintenance/deprecation.py

~This branch is based on #3240 , only the last commit is exclusive. Opening as a draft.~
rebased !

ENH: improve deprecation interface (make 'removal' version optional)

---

doc/source/developing/deprecating_features.rst
setup.cfg

Pin jupyter_client. Fixes #3768

---

yt/testing.py

Found this while reviewing #3787
The implementation seems obviously broken to me unless I'm missing anything.
ping @jzhone for review

BUG: fix a broken decorator in testing framework

---

yt/visualization/fixed_resolution.py
yt/visualization/fixed_resolution_filters.py

Found a couple lines that are not needed since #2823 went in.
While I'm at it I'm also making `FixedResolutionBufferFilter` an abstract base class

ENH: cleanup frbfilter registration

---

yt/frontends/enzo/fields.py

BUG: fix an edge case in enzo frontend where dark matter-only dataset would fail to load

---

yt/geometry/coordinates/spherical_coordinates.py

This private method is not used anywhere and it's not general enough to be relevant, so I propose we just ditch it.

MNT: remove an unused and broken helper function

---

.tours/particle-indexing.tour

I think we broke the code tour in #3816, this should fix it.

BUG: fix particle indexing code tour

---

yt/frontends/flash/data_structures.py
yt/frontends/flash/io.py
yt/frontends/flash/tests/test_outputs.py
yt/sample_data_registry.json

This manual backport was a little delicate for me because of a conflict caused by #3526 (not part of the backport branch).
I think I solved it satisfyingly however I'd appreciate if @matthewturk could confirm.
The test should also help making this clear :)

Backport PR #3683: BUG: Track blockless particles

---

tests/ci_install.sh
yt/utilities/lib/geometry_utils.pyx
yt/utilities/lib/platform_dep.h

Close #3924
I am not 100% sure I know what I'm doing here.
I also added a small workaround to avoid pip 22.1, which also breaks CI. See https://github.com/pypa/pip/issues/11116, resolved upstream but not released yet.

BLD: fix a build error on Windows

---

yt/geometry/geometry_handler.py
yt/visualization/volume_rendering/old_camera.py

In response to one of my own, misguided, TODO comments from last year.

RFC: lift ambiguity on a custom implementation of cached_property

---

yt/data_objects/index_subobjects/grid_patch.py
yt/frontends/_skeleton/data_structures.py
yt/frontends/amrvac/data_structures.py
yt/frontends/athena/data_structures.py
yt/frontends/athena_pp/data_structures.py
yt/frontends/boxlib/data_structures.py
yt/frontends/enzo/data_structures.py
yt/frontends/fits/data_structures.py
yt/frontends/flash/data_structures.py
yt/frontends/gamer/data_structures.py
yt/frontends/nc4_cm1/data_structures.py
yt/frontends/stream/data_structures.py
yt/frontends/ytdata/data_structures.py

RFC: deduplicate __repr__ method for AMRGridPatch subclasses

---

doc/helper_scripts/show_fields.py
doc/source/visualizing/callbacks.rst

Complements #3963
- DOC: fix a broken helper script (this problem is a blocker)
- DOC: fix a syntax error where a text paragraph was interpreted as part of a code block

DOC: fix a couple errors in docs builds

---

yt/data_objects/selection_objects/data_selection_objects.py

Closes #3959.
I'm pretty sure this fix is both necessary and sufficient, but I'm still opening as a draft while I check that it doesn't break anything else within #3849

BUG: fix automated field unit detection for profiles

---

setup.cfg

Experimenting with ways to avoid failing CI. 
First push just avoids the latest pyart (1.12.5).

[TST] pyart deps

---

yt/data_objects/construction_data_containers.py
yt/data_objects/data_containers.py
yt/data_objects/derived_quantities.py
yt/data_objects/static_output.py
yt/data_objects/tests/test_dataset_access.py
yt/fields/derived_field.py
yt/fields/field_info_container.py
yt/fields/tests/test_ambiguous_fields.py
yt/frontends/fits/data_structures.py
yt/visualization/volume_rendering/off_axis_projection.py

A tentative to close #3839, this depends on #3921
I added a test inspired from https://github.com/yt-project/yt/issues/3839
This cuts deep into the field detection machinery, so I'm counting on existing tests to catch any mistake I made.

ENH: allow name-only field keys when all candidates are aliases

---

yt/fields/magnetic_field.py

Closes #4000
Turns out the existing implementation for cylindrical geometry is 100% reusable as is for polar geometry, so the fix is pretty trivial.
I'm also avoiding passing `function=None` to `add_derived_field` as this use case is intended for cases where `derived_field` is used as a decorator. See https://github.com/yt-project/yt/blob/e16331088faf7296672ce9d1987a09d036f458ea/yt/fields/field_info_container.py#L363-L369

BUG: fix toroidal/poloidal magnetic fields registration for geometries where they are not implemented

---

.github/workflows/bleeding-edge.yaml

In preparation for unyt's next release, let's check its integration with yt
Opening as a draft for now, will open for review as soon as the workflow suceeds

TST: test against unyt dev version

---

yt/visualization/plot_container.py

BUG: fix a typo in warning message

---

yt/utilities/exceptions.py

Another simple performance improvement
The effect of this patch can be measured with
```python
import yt
ds = yt.load("IsolatedGalaxy/galaxy0030/galaxy0030")
ds.r["gas", "density"]
```
```shell
python -m cProfile t.py | grep levenshtein
```
Without this patch, I see 0.15s (a few percent) is spent on evaluating suggestions for typos I didn't make.
With the patch, it's reduced to 0.

ENH: only compute field suggestions if YTFieldNotFound isn't caught

---

doc/source/analyzing/fields.rst
setup.cfg

This is a quick solution to #3966
It's also (I think) orders of magnitude easier than the more correct solution.

DOC: pin scipy in docs build to fix filters page

---

yt/fields/derived_field.py
yt/fields/field_info_container.py
yt/fields/magnetic_field.py
yt/fields/vector_operations.py

BUG: fix multiple issues with magnetic field derived fields definitions 

---

doc/helper_scripts/run_recipes.py

This is necessarilly dead code because it invokes Python 2, which is long gone.

MNT: cleanup dead branch in doc helper script

---

yt/frontends/stream/data_structures.py

A quick follow up to #2998
It seems to me this comment was implemented but we forgot to clean it up

cleanup a dead comment

---

yt/utilities/lodgeit.py

Fixes the errors reported by mypy
```
yt/utilities/lodgeit.py: note: In function "print_languages":
yt/utilities/lodgeit.py:193: error: Name "cmp" is not defined  [name-defined]
yt/utilities/lodgeit.py: note: At top level:
yt/utilities/lodgeit.py:332: error: Missing positional argument "filename" in call to "main"  [call-arg]
Found 2 errors in 1 file (checked 483 source files)
Error: Process completed with exit code 1.
```

BUG: fix a couple broken lines in lodgeit.py

---

doc/source/visualizing/callbacks.rst

DOC: document plot callbacks extensibility

---

.github/workflows/build-test.yaml
doc/source/installing.rst

Also patch CI so that answer tests are run even for pure docs patches.

DOC: update Python compatibility table

---

yt/visualization/tests/test_callbacks.py

TST: fix ref count error in a flaky test

---

yt/frontends/ramses/io.py
yt/visualization/fixed_resolution.py

- BUG: fix a self-triggered deprecation warning
- DEPR: fix an incorrect deprecation warning (marked for removal in a bugfix release which already happened, this can't be correct)

DEPR: fix a couple broken deprecations

---

doc/source/visualizing/geographic_projections_and_transforms.rst
tests/ci_install.sh
yt/utilities/on_demand_imports.py

DOC: update instructions and redirections for installing cartopy

---

doc/source/analyzing/fields.rst
yt/data_objects/data_containers.py

Goal: close #3969
This is written within the assumption that #3970 gets merged.
I'll need a hand from @matthewturk and @jzuhone to make sure the update is complete.

DOC: update 'fields' doc page for yt 4.1

---

setup.cfg

This contains updates in optional requirements mainly targetted at saving build time on CI

BLD: remove unused extra dependencies

---

doc/source/analyzing/fields.rst

This PR adds more info to the documentation about magnetic fields, especially following PR #3812.
Closes issue #4113.

Add more info to magnetic fields documentation

---

yt/frontends/artio/_artio_caller.pyx
yt/utilities/lib/cosmology_time.pyx
yt/utilities/lib/origami.pyx

Thanks to @papoteur-mga in #4204 for the fix!

FIX: Add libm to build for some cython files

---

doc/source/cookbook/fits_radio_cubes.ipynb

BUG: fix a broken docs example

---

tests/ci_install.sh
tests/windows_conda_requirements.txt

Cleanup some complexity that is now unneeded

TST: simplify build envs

---

.tours/particle-indexing.tour
yt/geometry/particle_geometry_handler.py

Reverts yt-project/yt#4218 on the backport branch. See #4249 
Ping @jzuhone

Revert "Backport PR #4198 on branch yt-4.1.x (Automatically find EWAH files with increased index_order2)"

---

doc/source/reference/configuration.rst
yt/utilities/configure.py

ENH: add upward directory lookup for local configuration file

---

yt/frontends/fits/misc.py
yt/utilities/on_demand_imports.py

ENH: implement lazy-loading (on-demand-import) for regions

---

yt/visualization/base_plot_types.py
yt/visualization/tests/test_plotwindow.py

BUG: fix calling PlotContainer.set_font to set font color

---

doc/source/cookbook/multiplot_2x2.py
doc/source/cookbook/multiplot_2x2_coordaxes_slice.py
doc/source/cookbook/multiplot_2x2_time_series.py
doc/source/cookbook/multiplot_phaseplot.py

Follow up to #4121 and #4181, hopefully this is the last batch

DOC: cleanup calls to private methods _setup_plots in cookbook

---

yt/loaders.py

BUG: fix a regression in yt.load where '/Users/robcleme' and '~' path weren't expanded

---

yt/frontends/flash/data_structures.py

BUG: fix domain edges padding in reduced dimensions (FLASH)

---

.github/workflows/bleeding-edge.yaml
.github/workflows/build-test.yaml
.github/workflows/type-checking.yaml
.github/workflows/wheels.yaml
doc/source/cookbook/multiplot_2x2.py
doc/source/cookbook/multiplot_2x2_coordaxes_slice.py
doc/source/cookbook/multiplot_2x2_time_series.py
doc/source/cookbook/multiplot_phaseplot.py
yt/frontends/flash/data_structures.py
yt/frontends/sdf/data_structures.py
yt/loaders.py
yt/visualization/base_plot_types.py
yt/visualization/tests/test_plotwindow.py

Manual backports for
- #4261
- #4264
- #4281
- #4285 (only b2762924275b937999d42a12d3fe180724201ccc)
- #4290
- #4297
- #4265 (only 8863b83b9a5ebe2650b8d984363dd7c5d5d4c1b5)

REL: Manual backports for 4.1.4

---

yt/frontends/_skeleton/data_structures.py

Fix a small oversight from #4244

DOC: update a comment in SkeletonDataset to follow changes in Dataset.geometry type

---

tests/ci_install.sh

Trying out a couple simplifications that I _think_ should be possible now.

TST: a couple improvements for ci_install.sh

---

doc/source/developing/creating_frontend.rst
doc/source/developing/extensions.rst
doc/source/installing.rst
yt/frontends/amrvac/fields.py
yt/frontends/arepo/fields.py
yt/frontends/enzo_e/fields.py
yt/frontends/gizmo/fields.py

DOC: (devguide) improvements to "How to build a frontend" docs

---

conftest.py

fix #4337
tested on my fork: https://github.com/neutrinoceros/yt/actions/runs/4182239891/jobs/7245089969

TST: filter deprecation warnings from setuptools + nose

---

conftest.py

fix #4337 (again)
follow up to #4338
validation: https://github.com/neutrinoceros/yt/actions/runs/4191499133

TST: filter deprecation warnings from setuptools + nose (round 2)

---

doc/source/developing/testing.rst
tests/ci_install.sh
tests/unpin_requirements.py
tests/windows_conda_requirements.txt
yt/_version.py

fixing an oversight from #4271

MNT: cleanup references to setup.cfg

---

.github/workflows/wheels.yaml
MANIFEST.in

Fix check-manifest (https://github.com/yt-project/yt/actions/runs/4234723837/jobs/7357419744)
follow up to #4346
Also remove unneeded exclude line for .flake8 (follow up #4320)

BLD: fixup MANIFEST.in

---

.github/workflows/wheels.yaml

TST: drop unneeded and unmaintained action in check-manifest

---

yt/utilities/lib/primitives.pxd
yt/utilities/lib/primitives.pyx
yt/utilities/lib/vec3_ops.pxd

Addresses a blocking issue from  #4355.
See https://github.com/cython/cython/issues/5288

BLD: fix a future incompatibility with Cython 3.0

---

.mailmap

In preparation for sending out invites for the paper, @Xarthisius started deduping the mailmap.  I'll continue it.

MNT: Dedup of mailmap aliases

---

doc/source/cookbook/power_spectrum_example.py
yt/data_objects/tests/test_covering_grid.py
yt/frontends/boxlib/io.py
yt/utilities/decompose.py
yt/utilities/tests/test_particle_generator.py

BUG: handle deprecation warning from numpy 1.25 (np.product is deprecated in favour of np.prod)

---

.github/workflows/bleeding-edge.yaml
setup.py
yt/utilities/lib/cykdtree/kdtree.pyx
yt/utilities/lib/cykdtree/utils.pyx

As explained in #4373, I expect this will fail to build on GHA.
I'm opening this as a draft so it can be used as a reference if I need to report the issue upstream

TST: test (bleeding-edge) with Cython 3.0

---

doc/source/analyzing/filtering.rst
doc/source/developing/building_the_docs.rst
pyproject.toml
yt/data_objects/static_output.py

Main goal: fix #4403 (by upgrading Sphinx)
I also fixed a couple problems I encountered while reproducing the error locally

DOC: fix docs builds

---

CONTRIBUTING.rst
doc/source/developing/extensions.rst
doc/source/examining/loading_data.rst
doc/source/visualizing/colormaps/index.rst
doc/source/visualizing/geographic_projections_and_transforms.rst
doc/source/visualizing/unstructured_mesh_rendering.rst

This fixes a few of the broken links identified by `make linkcheck`

a few doc fixes from Sphinx `make linkcheck`

---

doc/source/analyzing/fields.rst
doc/source/developing/creating_frontend.rst
doc/source/developing/testing.rst
doc/source/examining/loading_data.rst
doc/source/installing.rst
doc/source/visualizing/geographic_projections_and_transforms.rst
doc/source/yt4differences.rst

some spelling fixes

---

yt/frontends/ramses/field_handlers.py
yt/frontends/ramses/fields.py
yt/frontends/ramses/io.py

This allows reading the `rt_file_descriptor.txt` file (if any) to autodetect the fields within the file.

RAMSES: Read rt file descriptor

---

nose_ignores.txt
tests/tests.yaml
yt/utilities/cython_fortran_utils.pyx
yt/utilities/tests/test_cython_fortran_utils.py

Closes https://github.com/yt-project/yt/issues/4436.

 [BUG] Raise exception when a file does not exist

---

tests/tests.yaml

This bumps the answer tests that are failing due to incompatibilities between pickle formats in SymPy:
https://github.com/sympy/sympy/issues/25134

Bump answers for failing tests due to SymPy 1.12

---

.github/workflows/bleeding-edge.yaml
.github/workflows/wheels.yaml

fix small oversights from #2711 (just merged)

TST: add ewah-bool-utils to build time dependencies in wheels and tests workflows

---

yt/visualization/tests/test_offaxisprojection.py

resolves a silent conflict from merging #4444 and #4439 in that order

STY: hotfix linting issue

---

yt/geometry/particle_oct_container.pyx

BUG: fix overflows in ParticleBitmap hashing

---

doc/source/developing/deprecating_features.rst
yt/_maintenance/deprecation.py
yt/data_objects/data_containers.py
yt/data_objects/particle_unions.py
yt/data_objects/static_output.py
yt/fields/derived_field.py
yt/fields/field_info_container.py
yt/frontends/ramses/io.py
yt/funcs.py
yt/geometry/geometry_handler.py
yt/loaders.py
yt/testing.py
yt/visualization/fixed_resolution.py
yt/visualization/fixed_resolution_filters.py
yt/visualization/particle_plots.py
yt/visualization/plot_container.py
yt/visualization/plot_modifications.py
yt/visualization/plot_window.py

DEPR: remove default value for stacklevel in issue_deprecation_warning, fix missing arguments in call sites

---

yt/visualization/volume_rendering/render_source.py
yt/visualization/volume_rendering/scene.py

allow user to set the thickness of the coordinate lines in VR

---

.github/workflows/bleeding-edge.yaml
.github/workflows/build-test.yaml

This should reduce the build time for nightly tests as well as the logging noise.

TST: time saving optimisations in CI

---

yt/utilities/configure.py

BUG: fix a bug where setting boolean parameters from the command line would break at runtime validation

---

yt/utilities/on_demand_imports.py

Alternative to #4461, closes #4451

Move netcdf4 forced import from netcdf4_imports to h5py_imports

---

yt/visualization/profile_plotter.py

BUG: fix a bug where ProfilePlot and PhasePlot would be improperly validated at initialization

---

yt/visualization/plot_container.py

fix another issue from #4489 (see https://github.com/yt-project/yt/issues/4489#issuecomment-1585544353)

BUG: fix a bug where calling plot.render() would have no effect depending on internal state

---

yt/visualization/_handlers.py
yt/visualization/plot_window.py

BUG: fix noisy warnings when setting custom norm for fields with set_log=False

---

conftest.py
pyproject.toml
tests/windows_conda_requirements.txt
yt/funcs.py
yt/visualization/_commons.py
yt/visualization/_handlers.py
yt/visualization/base_plot_types.py
yt/visualization/color_maps.py
yt/visualization/profile_plotter.py
yt/visualization/tests/test_image_comp_2D_plots.py
yt/visualization/tests/test_splat.py
yt/visualization/volume_rendering/image_handling.py
yt/visualization/volume_rendering/transfer_functions.py

DEP: drop support for matplotlib<3.5

---

.github/workflows/wheels.yaml

BLD: stop building wheels for Windows 32

---

yt/frontends/__init__.py

close https://github.com/yt-project/yt/issues/4563
test with:
```shell
$ python doc/helper_scripts/show_fields.py
```

DOC: hotfix doc builds

---

doc/source/visualizing/plots.rst

Follow up to #4440, close #4528

DOC: update documentation on off-axis projections for non-SPH particle data

---

yt/visualization/profile_plotter.py

this partially adresses #4617 and fixes yt/doc/source/analyzing/mesh_filter.ipynb

BUG: fix an UnboundLocalError in PhasePlot._setup_plots

---

yt/utilities/on_demand_imports.py

BUG: fix error message when trying to use a feature that requires cartopy while it's missing

---

yt/frontends/halo_catalog/io.py
yt/frontends/ytdata/io.py
yt/visualization/plot_modifications.py

follow up to #4166 (I think I got them all this time)

BUG: fix future incompatiblities with unyt 3.0 (3/n)

---

CONTRIBUTING.rst

#4634 removed the install script, this PR removes the lingering references to it in CONTRIBUTING.rst

DOC: Remove installation script references from CONTRIBUTING

---

yt/funcs.py
yt/utilities/answer_testing/framework.py
yt/utilities/command_line.py

BUG: fix broken urllib imports

---

doc/source/cookbook/geographic_xforms_and_projections.ipynb

Fixes the deprecation warning in the geographic transforms notebook

use axis_order kwarg in geo nb

---

.github/workflows/build-test.yaml
yt/loaders.py

BUG: avoid a deprecation warning in yt.load_sample on Python 3.12

---

doc/source/cookbook/simple_slice_matplotlib_example.py

DOC: fix a broken docs example

---

yt/visualization/particle_plots.py

follow up to #4440 (see https://github.com/yt-project/yt/pull/4440#issuecomment-1560373627) in the spirit of #3489
I'm attempting this in order to salvage #4179, which grew a difficult conflict with #4440

RFC: refactor ParticleProjectionPlot for consistency with ProjectionPlot

---

yt/data_objects/selection_objects/slices.py

BUG: use the validated center for YTCuttingPlane set_field_parameter

---

nose_ignores.txt
tests/tests.yaml
yt/geometry/coordinates/geographic_coordinates.py
yt/geometry/coordinates/tests/test_geographic_coordinates.py

there were a couple stylistic conflicts with #4844

Manual backport for #4839

---

yt/data_objects/data_containers.py

Fixes #4903, but for the most straightforward case of specifying the weight field.

Move field resolution inside conditional.

---

yt/frontends/amrex/data_structures.py

Use context managers where the line length allows, and manually close all other files that are opened outside a `with` statement.
Fixes #4890.

BUG: avoid ResourceWarnings in the amrex frontend

---

yt/frontends/amrex/fields.py

This was discovered in https://github.com/yt-project/yt/pull/4908#discussion_r1619413275
Thanks to @yut23 for noticing the duplication

CLN: drop unused and duplicated parsing logic in AMRex frontend

---

yt/frontends/art/io.py

BUG: ensure type safety in a call to np.logspace

---

pyproject.toml
yt/frontends/rockstar/definitions.py

TYP: upgrade mypy and type-check extras

---

yt/frontends/amrvac/data_structures.py
yt/frontends/amrvac/io.py

Removed hardcoded He abundance for AMRVACDataset unit calculation. Instead, it is now read from the AMRVAC parfile.

AMRVAC: variable He abundance

---

pyproject.toml
yt/_maintenance/ipython_compat.py
yt/data_objects/static_output.py
yt/fields/field_type_container.py
yt/funcs.py
yt/visualization/image_writer.py
yt/visualization/plot_container.py
yt/visualization/profile_plotter.py
yt/visualization/volume_rendering/old_camera.py
yt/visualization/volume_rendering/scene.py

Ipywidgets and IPython are meant to be optional dependencies that we merely hook into if they are installed and actively used, however they were promoted to hard dependencies as a workaround in #4155, which I now think can be avoided.
I think this may close #4054 (but will ask @cphyc for confirmation)

DEP: make ipywidgets/IPython optional dependencies again

---

.github/workflows/wheels.yaml
pyproject.toml

Following #4971, this resolves 2 points on #4931

WHL: enable cp313 wheels

---

MANIFEST.in

Hotfix for the (hopefully) last unforseen consequence from #5009

MNT: fix manifest validation

---

yt/fields/field_info_container.py

Stumbled upon this needlessly complicated bit of logic while backporting #5025, so I worked out a more streamlined version.

RFC: clarify aliasing logic for non-cartesian geometries in `FieldInfoContainer.setup_fluid_aliases`

---

conftest.py

CLN: cleanup unused warning filters in conftest.py

---

yt/visualization/base_plot_types.py

make BACKEND_SPECS case insensitive

---

conftest.py

[example logs](https://github.com/yt-project/yt/actions/runs/16018141562/job/45188709812)
xref https://github.com/matplotlib/matplotlib/pull/30221

TST: filter out an indirect deprecation warning from Pillow via matplotlib

---

yt/utilities/parallel_tools/parallel_analysis_interface.py

It was a bit easier to fix #5220 than I thought.
Closes #5220.

BUG: Fix partition_index_2d

---

yt/units/__init__.py

this used the new interface
see https://github.com/ipython/ipython/pull/14657

IPython.core.display.display has been removed
