yt-project/yt

yt/frontends/adaptahop/api.py
yt/frontends/adaptahop/tests/test_outputs.py
yt/frontends/ytdata/tests/test_old_outputs.py

One day we'll get all of them...
follow up to #2753 (and #2396 (and #2298)).

cleanup: remove leftover copyright blurbs

---

yt/utilities/parallel_tools/task_queue.py

This resolves Issue #2987 by sending the entire `ResultsStorage` object instead of just the result.
For the example shown in the issue, I now get:
```
yt : [INFO     ] 2020-12-03 14:19:09,904 Global parallel computation enabled: 1 / 5
yt : [INFO     ] 2020-12-03 14:19:09,905 Global parallel computation enabled: 3 / 5
yt : [INFO     ] 2020-12-03 14:19:09,905 Global parallel computation enabled: 0 / 5
yt : [INFO     ] 2020-12-03 14:19:09,905 Global parallel computation enabled: 2 / 5
yt : [INFO     ] 2020-12-03 14:19:09,905 Global parallel computation enabled: 4 / 5
P000 yt : [INFO     ] 2020-12-03 14:19:09,906 Begin with dynamic=False.
P000 yt : [INFO     ] 2020-12-03 14:19:09,906 5, 5
P000 yt : [INFO     ] 2020-12-03 14:19:09,906 6, 6
P000 yt : [INFO     ] 2020-12-03 14:19:09,907 7, 7 …
```

[bugfix] preserve result_id with dynamic_parallel_objects

---

doc/source/developing/creating_frontend.rst
yt/frontends/_skeleton/data_structures.py

- Init required instance attributes in order to leave a valid Dataset structure.
- minor doc update (hopefully making the instructions a little clearer)
edit:
the changes to `SkeletonDataset` make it so the following code pass without error
```python
yt.load("myfile.from.a.new.format")
```
where the only changes required from the author of a new frontend are
- adding the frontend to `yt/frontends/api.py`
- implementing `NewDataset._is_valid()`

doc: add minimal structure to SkeletonDataset class

---

yt/visualization/base_plot_types.py
yt/visualization/plot_modifications.py

This is in response to an old email thread. If the user makes a plot, sets the axes unit, and then adds a scale annotation with a coefficient, the most appropriate behavior is to use the axes unit set by the user. The current behavior is to instead figure out an appropriate unit on its own, but this calculation does not take into account the user-provided coefficient. In other words, the following script creates a scale bar with units of Mpc, when Mpccm/h is probably more appropriate.
```
import yt
ds = yt.load('DD0046/DD0046')
p = yt.SlicePlot(ds, 'x', 'density')
p.set_axes_unit('Mpccm/h')
p.annotate_scale(corner='lower_right', coeff=5)
p.save()
```
This PR changes the behavior to use the axes unit in the case described above. This is a very minor issue, but I think this is the correct …

[bugfix] Use axes unit in scale bar if set by user.

---

yt/frontends/amrvac/data_structures.py
yt/frontends/athena/data_structures.py
yt/frontends/athena_pp/data_structures.py
yt/frontends/enzo/data_structures.py
yt/frontends/enzo_p/data_structures.py
yt/frontends/gdf/data_structures.py
yt/funcs.py

This is a follow up to #2893.
`ensure_tuple` is only used to sanitize `Dataset.periodicity` attributes in a such a fashion that it doesn't make any difference to use builtin tuple conversion. Hence, the function serves no purpose anymore and can be removed.

refactor: remove yt.funcs.ensure_tuple

---

yt/frontends/boxlib/data_structures.py

When reading in raw data from a WarpX plot file for a 2D run, at line 76 of the routine _read_raw_field in boxlib/io.py it does box[0] - nghost, but box[0] is length 2 and nghost is length 3, raising an error. nghost is length 3 when it was set in _read_header in boxlib/data_structures.py since it is nghost = [ng, ng, ng]. This fix checks the number of dimensions and instead sets nghost accordingly.

boxlib: Fix _read_header for 2D data

---

.pre-commit-config.yaml

- Add missing deps for isort and flake8 pre-commit hooks.
- reorder black and flynt hooks for better stability
- add a global exclude list (this is needed to later setup pre-commit.ci which run `pre-commit run --all-files`)

maint: fix several problems in .pre-commit-config.yaml

---

yt/frontends/ramses/fields.py
yt/frontends/ramses/tests/test_outputs.py

This is a followup on issues reported by Aniket Bhagwat with RAMSES-rt support.
This fixes the erroneous units set for the photon flux density.

[BUGFIX] RAMSES: Fix creation of photon flux

---

yt/visualization/plot_container.py
yt/visualization/profile_plotter.py

There is a minor mistake in the HTML representation of images that prevents the max-width to be correctly set to "100%". This PR fixes it.

[BUGFIX] Fix figure width in HTML output

---

yt/frontends/ramses/data_structures.py
yt/frontends/ramses/definitions.py
yt/frontends/ramses/tests/test_outputs.py

This adds the possibility to load a RAMSES dataset given the name of its folder, of any of its (supported) output file or the info filename (only the latter was supported before).
This comes very handy when you get tired of always writing
```python
import yt
ds = yt.load('output_00123/info_00123.txt')
ds = yt.load('output_00123')
ds = yt.load('output_00123/amr_00123.out00001')
```

More flexible RAMSES loader

---

yt/frontends/ramses/field_handlers.py

The RAMSES frontend was erroneously reporting a warning when reading gravity files because of a simple typo. This is not a bug _per se_, just a minor inconvenience.
Thanks to Aniket Bhagwat for reporting it!

[BUGFIX] Fix erroneous warning thrown when loading Ramses dataset

---

yt/data_objects/particle_trajectories.py

This addresses some issues on the particle trajectory machinery.
- prevent datasets from being loaded multiple times
- specify non-dynamic runs, to prevent bug if changes are made to the `piter` API

Particle trajectories minor improvements

---

yt/fields/field_info_container.py
yt/fields/tests/test_field_name_container.py

fix https://github.com/yt-project/yt/issues/2430
This is a hotfix, I'm convinced there are better ways to solve this but they would require much more work (refactoring).

hotfix: register "vertex" fields only in unstructured meshes

---

doc/source/cookbook/simulation_analysis.py
yt/data_objects/particle_trajectories.py
yt/data_objects/profiles.py

…when the differences do not matter any more: starting from Python 3.6, normal dict objects preserve insertion order.
I was originally aiming at replacing _all_ ordereddict by normal dict but I left every user-facing one untouched because _comparison_ is still different between the two classes, so I don't mean to cause bugs downwards where OrderedDict is possibly still relevant.

switch internal instances of collections.OrderedDict to regular dict

---

yt/__init__.py
yt/_maintenance/deprecation.py
yt/config.py
yt/data_objects/index_subobjects/octree_subset.py
yt/data_objects/static_output.py
yt/data_objects/time_series.py
yt/fields/field_info_container.py
yt/fields/particle_fields.py
yt/fields/species_fields.py
yt/loaders.py
yt/utilities/amr_kdtree/amr_kdtree.py
yt/utilities/answer_testing/framework.py
yt/utilities/exceptions.py
yt/visualization/color_maps.py
yt/visualization/eps_writer.py
yt/visualization/image_writer.py
yt/visualization/plot_container.py
yt/visualization/plot_window.py

As devs, we may want to silence some warnings when developing. For example, we may want to ignore the warning that both `~/.config/yt/ytrc` and `~/.config/yt/yt.toml` exist when working on both yt 3 and yt 4.
This PR adds supports for adding a list of warnings to simply ignore for devs convenience. I did *not* write any doc for this, as it is intended for devs only (otherwise users may simply ignore all warnings).
To use it, find the warning that is getting on your nerve, and save it in your config using
```toml
[yt.developers]
ignore_warnings = ["config:both_file_present"]
```

Add possibility to silence some warnings

---

yt/frontends/ytdata/data_structures.py

This fixes the `ytdata` frontend to set `self._periodicity` instead of `self.periodicity`, for which the setter function is deprecated.

Set _periodicity to avoid deprecated setter.

---

README.md

This will fail test for the same reason I discovered it was necessary: the main branch is currently broken against our test suite but the build badge reports that it's all good... because it hasn't been updated since we dropped travis.

doc: replace dead travis badge with corresponding GH workflow build status

---

README.md

And rearrange badges over two lines.
This is another attempt than #2976 to acknowledge our minimal supported Python version. This time with a custom static badge since pypi releases may often be out-of sync with the main branch, as is the case right now.
this also includes the change from #3057
Here's how it looks

doc: add badges for isort, precommit-ci, and minimal supported python

---

setup.cfg
yt/frontends/athena/fields.py
yt/frontends/athena_pp/fields.py
yt/frontends/enzo/fields.py
yt/frontends/flash/fields.py
yt/utilities/answer_testing/utils.py
yt/visualization/eps_writer.py

With the recent adoption of pyupgrade, some flake8 rules can stopped being ignored because they are de-facto enforced already (E231 and W605)
Additionally, I manually fix E306 and B302 because there were only a couple of surviving errors.

Cleanup flake8 conf

---

tests/test_prerequirements.txt

Attempt to circumvent breakage from just-released dependencies with no wheels available. Currently `cftime` 1.4.0 is breaking our CI because they don't have windows wheels yet.

ci: install wheel as part of our gh build workflows

---

yt/visualization/volume_rendering/tests/test_vr_orientation.py

This one answer test has been randomly failing in all PRs since the release of numpy 0.20.0 a week ago.
I suggest to deactivate it at least temporarily (I added a comment to explain the situation).

ci: deactivate a randomly failing answer test

---

yt/data_objects/construction_data_containers.py
yt/data_objects/tests/test_particle_trajectories.py
yt/frontends/adaptahop/io.py
yt/frontends/art/io.py
yt/frontends/artio/_artio_caller.pyx
yt/frontends/athena/data_structures.py
yt/frontends/athena_pp/data_structures.py
yt/frontends/boxlib/data_structures.py
yt/frontends/boxlib/io.py
yt/frontends/chombo/io.py
yt/frontends/enzo_p/misc.py
yt/frontends/open_pmd/data_structures.py
yt/frontends/open_pmd/fields.py
yt/frontends/open_pmd/misc.py
yt/frontends/ramses/hilbert.py
yt/frontends/stream/tests/test_stream_octree.py
yt/frontends/ytdata/data_structures.py
yt/geometry/grid_geometry_handler.py
yt/geometry/tests/test_particle_octree.py
yt/utilities/math_utils.py
yt/utilities/parallel_tools/parallel_analysis_interface.py
yt/utilities/sdf.py
yt/visualization/volume_rendering/render_source.py

Following their deprecation with the release of numpy 1.20.0, replace long-standing type aliases with their corresponding builtin types.
See release notes https://github.com/numpy/numpy/releases/tag/v1.20.0
This should not cause any change in behaviour but will prevent some deprecation warnings to pop up.

maint: replace numpy alias types with corresponding builtin types

---

setup.py
setupext.py

Some files require some C++14 features which aren't supported on old versions of GCC. This PR tries to find the most suitable compiler flags to supports these features (though it does not capture all cases).
I tested this PR with GCC 4.7.4 (can now compile yt, could not before). With GCC 4.6.4 and older versions, the compilation fails as the support for C++14 is unsufficient to compile yt.
Fixes #3071.

[BUGFIX] Support old gcc versions

---

doc/source/installing.rst

- add an `--upgrade` flag to pip install instruction to mitigate the problem with users getting broken installations when compiling with a more recent numpy than the one they have installed.
- fix an out of date indication for minimal python version

Update install doc

---

yt/frontends/adaptahop/io.py
yt/frontends/ahf/io.py
yt/frontends/art/io.py
yt/frontends/flash/io.py
yt/frontends/gadget_fof/io.py
yt/frontends/http_stream/io.py
yt/frontends/owls_subfind/io.py
yt/frontends/rockstar/io.py
yt/frontends/sdf/io.py
yt/frontends/ytdata/io.py

This removes the `_initialize_index` function from the frontend-specific io handler classes. These are no longer used after yt-3.x.

Remove unused _initialize_index functions.

---

doc/source/conf.py
doc/source/cookbook/custom_colorbar_tickmarks.ipynb
doc/source/visualizing/plots.rst
yt/visualization/plot_container.py
yt/visualization/profile_plotter.py

Please see: https://discourse.matplotlib.org/t/canonical-documentation-have-moved/21863

Update matplotlib canonical link

---

doc/source/developing/index.rst
doc/source/index.rst
doc/source/reference/api/api.rst

this fixes part of #3029
I'd like some feedback (@brittonsmith ?) for the following, currently unincluded pages
```
doc/source/analyzing/domain_analysis/index.rst
doc/source/analyzing/domain_analysis/xray_data_README.rst
```
Are they still relevant to the main project ? If so, where should they be referenced ?

docs: fix missing inclusions

---

yt/mods.py

I'm not actually convinced that the file should be kept (dead code ?) but it's easy enough to fix the NameError one gets with `import yt.mods` atm

fix a NameError in yt.mods

---

yt/data_objects/tests/test_time_series.py
yt/data_objects/time_series.py

Currently, calling
```python
>>> series = yt.load(valid_series_regexp, invalid_kwarg="hello")
>>> ds = series[0]
>>> print(type(ds))
str
```
Because a type error is being wrongfully captured. These changes are required to free that error:
```python
TypeError: __init__() got an unexpected keyword argument 'invalid_kwarg'
```
~While I'm at it, I believe that our implementation `DatasetSeries__iter__` actually constitutes unnecessary code duplication so I'm removing it (if I'm wrong I hope our tests catch it).~
edit: I'll redo this experiment in an isolated PR
todo

Fix: loading DatasetSeries with broken arguments

---

yt/utilities/logger.py

Currently, the following scripts runs correctly _but_ prints out a error message
```python
import yt
yt.set_log_level("debug")
```
error:
```
...
TypeError: %d format: a number is required, not str
...
```
This fixes it; `%s` will also work with integers

fix a string formatting error in yt.set_log_level

---

yt/frontends/enzo/data_structures.py

avoid raising the following warning
```
VisibleDeprecationWarning: Dataset.periodicity should not be overriden manually. In the future, this will become an error. Use `Dataset.force_periodicity` instead.
Deprecated since v4.0.0 . This feature will be removed in v4.1.0
self.periodicity += (False, False)
```

hotfix: avoid a deprecation warning in enzo frontend (periodicity)

---

yt/frontends/halo_catalog/data_structures.py

this is exactly the same motivation as #3091, for halo_catalog
I think this is solving the last occurence of the VisibleDeprecationWarning as seen in our CI logs

fix a visible deprecation warning (periodicity) for halo_catalog

---

yt/config.py

Related to #3044.
Here is the behaviour
- on yt 4, `yt.toml` and `ytcfg` are present: raise a warning
- on yt 4, `yt.toml` does not exist, `ytcfg` exists: raise another warning and **do not migrate**
- in any case, a `yt.toml` will be created (see #3045)

Migration script: warn and do not migrate

---

yt/funcs.py
yt/visualization/_commons.py
yt/visualization/base_plot_types.py
yt/visualization/image_writer.py
yt/visualization/plot_container.py
yt/visualization/profile_plotter.py
yt/visualization/tests/test_commons.py
yt/visualization/volume_rendering/scene.py

Refactoring around `yt.funcs.get_image_suffix`, which gives noisy warnings on Travis such as
```
WARNING:yt:Unsupported image suffix requested (.h5)
WARNING:yt:Unsupported image suffix requested (.h5_Slice_z_density)
WARNING:yt:Unsupported image suffix requested (.h5)
WARNING:yt:Unsupported image suffix requested (.h5_Projection_z_density)
```
while the images are still saved in the end, as png.
Since calls to this function are almost _always_ followed by some way to default to `".png"` as a suffix, I
replaced this function with `yt.visualization._commons.validate_image_name`
Doing so, I ended up removing duplicated code with the function `get_canvas`, which already existed but wasn't used
Since some of the affected parts of the code use a lot of nested ifs, I'm pretty sure I must have …

code deduplication: image filename validation

---

doc/source/reference/configuration.rst
yt/config.py
yt/utilities/parallel_tools/parallel_analysis_interface.py

I think the `log_file` config option isn't used or usable anymore. It looks like the one time we're checking this option in the code base is to force-disable it.
I discovered this while working on #3106

cleanup: remove dead config option

---

yt/frontends/stream/tests/test_stream_unstructured.py
yt/loaders.py
yt/testing.py
yt/visualization/plot_modifications.py
yt/visualization/tests/test_callbacks.py

This fixes several related issues that were causing `velocity_annotation` to fail for unstructured grids and improves some of the Stream frontend's unstructured mesh testing. 
The following reproduces the error on `main`:
```python
import yt
from yt.frontends.stream.sample_data import hexahedral_mesh
coords = hexahedral_mesh._coordinates
cons =  hexahedral_mesh._connectivity
node_data = {}
dist = np.sum(coords ** 2, 1) # distance from origin
node_data[("connect1", "test")] = dist[cons - 1]
for dim in ['x','y','z']:
node_data[("connect1", f"velocity_{dim}")] = dist[cons - 1]
ds =  yt.load_unstructured_mesh(cons - 1, coords, node_data=node_data)
sl = yt.SlicePlot(ds, "z", "test")
sl.annotate_velocity()
sl.save("/tmp/stream_z")
```
resulting in 
```
Traceback (most recent …
```

fix for velocity_annotation with unstructured grids

---

.pre-commit-config.yaml
yt/fields/field_info_container.py

This one try block catches a lot of unrelated stuff so I'm expanding it explicitly as a better signal this should be refactored.
Edit (march 4 2021);
The plan for this PR, as discussed in today's triage meeting is to write an lasting issue for it, then merge the expansion.
note: there's a bug upstream in flake8-bugbear that crashes flake8 with the code I'm writing here (is it _that_ bad ??)
https://github.com/PyCQA/flake8-bugbear/issues/153
I think I'll need to fix this myself at some point
edit: I fixed it here https://github.com/PyCQA/flake8-bugbear/pull/161
edit 2: and the fix is now part of bugbear 20.3.2 🎉

Expand an exception catching

---

yt/config.py
yt/fields/tests/test_fields_plugins.py
yt/funcs.py
yt/utilities/configure.py
yt/utilities/tests/test_config.py

This PR ensures that every time a "config path" is requested it respects the current value of XDG_HOME_DIR.

Make config related paths dynamical. Fixes #3104

---

yt/sample_data_registry.json

```python
import yt
yt.load_sample("CfRadialGrid")
```
fails with 
```
FileNotFoundError
```
This fixes it.
Note that this particular dataset still doesn't load (`YTUnidentifiedDataType`). I believe it was added in support to #1990 which is still in the shop. 
I except this will fail the same way #3118 does: the hash probably needs to be updated as well.
edit: nope. Must be a problem with changing the type (from null to str) of the field, which is not a concern here.

fix a broken load_name in data sample metadata

---

yt/utilities/lib/platform_dep.h

This PR should fix recent Windows compilation failures on Github action `windows-latest`. It appears the compiler has been updated.

[bugfix] Fix recent windows failures on github actions

---

yt/frontends/arepo/data_structures.py
yt/frontends/gadget/io.py
yt/geometry/particle_oct_container.pyx

This PR fixes a few issues related to SPH. 
* Arepo needed to have `"cmcm"` defined in its `_unit_base` but it did not.
* There was a string in the `particle_oct_container` code which didn't have enough format specifiers. I've fixed it and simply changed it to an f-string. 
* In `IOHandlerGadgetBinary`, we were not skipping a chunk/particle type combination in the `_read_particle_coords` method if it had no particles, which is what we should be doing (and what we do in `IOHandlerGadgetHDF5`). I've simply applied the same fix that is used in `IOHandlerGadgetHDF5`.

[bugfix] Various SPH fixes

---

doc/source/analyzing/objects.rst
doc/source/cookbook/profile_with_standard_deviation.py
yt/data_objects/data_containers.py
yt/data_objects/derived_quantities.py
yt/data_objects/tests/test_derived_quantities.py

This PR deprecates the `DerivedQuantity` `WeightedVariance` and adds `WeightedStandardDeviation`, since what `WeightedVariance` returns is actually a standard deviation. This is exactly what we did for a similar situation with respect to profiles (PR #1372). 
`WeightedVariance` is now a subclass of `WeightedStandardDeviation` and a deprecation warning is flagged when it is used.
Closes issue #2713.

Deprecate WeightedVariance in favor of WeightedStandardDeviation

---

doc/source/developing/creating_derived_fields.rst
doc/source/reference/configuration.rst
doc/source/visualizing/sketchfab.rst

fix #3108 
(hopefully I got all the broken examples)

doc: fix missing `sampling_type` keyword argument in `add_field` examples

---

setup.py

`distribute` was a compatibility layer that used to install setuptools. Now we require setuptool as an install-time dependency in pyproject.toml, so this workaround shouldn't be necessary anymore

cleanup unecessary workaround in setup.py

---

yt/frontends/sdf/data_structures.py

This function is not doing anything besides obfuscating the builtin `open` function.
It _used_ to have a conditional statement that made it different in Python 2 (Credits to @matthewturk for figuring this out), but now there is _no_ need for it

cleanup a shallow and unnecessary wrapper around builtin open function

---

yt/utilities/on_demand_imports.py

Fixing the one place in the code base where we use anything else than `distutils.version.LooseVersion` to check versions in optional deps.
Making this uniform will help later in greping for those and specifying requirements for optional dependencies properly (see #3078).

use distutils instead of pkg_resource to parse version in optional deps

---

setup.py
tests/test_minimal_requirements.txt
yt/visualization/base_plot_types.py
yt/visualization/plot_window.py
yt/visualization/profile_plotter.py
yt/visualization/tests/test_plotwindow.py
yt/visualization/volume_rendering/transfer_function_helper.py

Rationale:
matplotlib doesn't document their supported Python versions very well, which makes it a bit hard to guess which version should be considered minimal for us.
Here's what I got out of my research:
Python 3.6 (our current earliest supported Python version) came out on December 23, 2016
[Matplotlib 2.0.0](https://github.com/matplotlib/matplotlib/releases/tag/v2.0.0) was the very first release after that (January 17, 2017), and came out only a few months after [1.5.3](https://github.com/matplotlib/matplotlib/releases/tag/v1.5.3) (September 6, 2016), which is our  _currently_ earliest tested matplotlib version.
Because we have acquired a small but noticeable amount of technical debt in the form of compatibility layers as we attempt to support the broadest range of versions possible, …

maint: drop compatibility layers for matplotlib 1.5

---

doc/source/cookbook/streamlines.py
doc/source/cookbook/streamlines_isocontour.py
doc/source/visualizing/streamlines.rst
yt/data_objects/particle_trajectories.py
yt/visualization/streamlines.py

See https://matplotlib.org/2.0.2/faq/usage_faq.html#matplotlib-pyplot-and-pylab-how-are-they-related
> pylab is a convenience module that bulk imports matplotlib.pyplot (for plotting) and numpy (for mathematics and working with arrays) in a single name space. Although many examples use pylab, it is no longer recommended.
TLDR:
`matplotlib.pylab` is a wrapper that contains `matplotlib.pyplot` and `numpy`. The reason it exists was to help people migrating from Matlab to Python, but its usage is discouraged, so I'm replacing it with direct calls to pyplot in our documentation and docstrings.

maint: use matplotlib.pyplot in examples instead of matplotlib.pylab

---

README.md

Following recent discussions on Twitter... here's a reusable custom badge for downstream projects to show off
~I'm opening this as a draft with two temporary files (one for markdown, the other for rst), because I wasn't able to check locally that the rst version is correct.~
edit: done. Removed the files in question.
Note that this is based on a custom json endpoint : https://runkit.com/neutrinoceros/yt-support-badge
and largely based off this blog post https://dev.to/milkers/how-to-make-custom-badges-to-improve-your-markdown-documents-460k
I wasn't able to make the actual logo work for now, but hopefully it can be fixed in the future, at which point it will auto update in any page that uses it.
Here's what I've got thus far (as previewed from VSCode)
edit: current version
The badge is …

doc: add a custom badge for downstream projects supported by yt

---

setup.py
tests/test_requirements.txt

This is a hot fix for failing answer-tests following the release of matplotlib 3.4.0
Obviously this boundary should be lifted in the near future.

maint: pin matplotlib maximal supported version

---

yt/fields/tests/test_vector_fields.py
yt/visualization/volume_rendering/render_source.py

This is an attempt to fix issue #3126 to ensure that field parameters can be used with off-axis projections. ~~This is a work in progress.~~ 
I *think* that I only need to restore the underscore that was removed in this commit:
https://github.com/yt-project/yt/commit/cde25a88935c5a0a7b6fa17602bb27b7f2e8a864#diff-2d1d24ee7df2e3b516614aad6fa0d7bd09a0268684a1c6b748eee75c1b823002
which is here, in line 57: 
https://github.com/yt-project/yt/blob/bc33f4e188f9b29a55588a4f9f7e88d65a81f2cd/yt/visualization/volume_rendering/render_source.py#L52-L65
but it sounds like with it in there other things were broken, so we're going to see what happens with the tests. 
EDIT: All tests pass with just this one commit.

Fix field parameters not working with off axis projections

---

.github/workflows/build-test-pytest.yaml
conftest.py
tests/pytest_runner.py

Enable CI for tests that were merged with https://github.com/yt-project/yt/pull/3102. There are three additional jobs being enabled with this PR: unittest on GHA, unit and answer tests on Jenkins called *py38_unittests* and *py38_answertests* respectively. The latter will fail due to missing answers. The proposed way to deal with answer generation is:
1. pytest run @ Jenkins uses https://github.com/yt-project/answer-store to look for answers
2. if answers are not found, test are marked as failed for proper reporting (this is a change: before they were marked as skipped)
3. After the main run is finished, all tests that failed due to lack of answers are re-run with `--answer-store`
4. Resulting artifacts are published as Jenkins job artifacts (see e.g. …

Enable CI for pytest [02/NN]

---

yt/config.py
yt/utilities/configuration_tree.py

This fixes #3155 and improves support for inclusion statement (i.e. you can now use `"thing" in ytcfg`).
As a nice addition, this also adds rich display in the notebook (almost) for free

Bugfix #3155 + improvement in config handler

---

README.md

If this has been falling off my radar for months, I assume it is reasonable to say that we are collectively prone to forget about it when we bump our minimal supported python version in the future, so I rephrased it to a permanent truth.

rephrase comment in README to avoid pinning a specific minimal python version

---

yt/fields/field_detector.py
yt/frontends/athena/data_structures.py
yt/frontends/athena_pp/data_structures.py
yt/frontends/boxlib/data_structures.py
yt/frontends/enzo/data_structures.py
yt/frontends/fits/data_structures.py
yt/frontends/flash/data_structures.py
yt/frontends/gdf/data_structures.py
yt/frontends/moab/data_structures.py
yt/frontends/stream/data_structures.py

This attribute is supposed to be an int and is wrongly set to a float in some frontends.
It should really be an bool but that's beyond the scope of this PR
edit: while I'm at it I split separate statements into separate lines to clarify formatting in these regions

fix: typing for Dataset.cosmological_simulation

---

yt/visualization/color_maps.py

followup to #3143 and fix for a failing workflow in #3078 with the following error message
```
ValueError: Trying to re-register the builtin cmap 'cubehelix'.
```
Indeed we don't need to vendor this colormap anymore since it was already present in matplotlib 2.0.2
See https://matplotlib.org/2.0.2/users/colormaps.html?highlight=cubehelix
Note that registering an existing cmap name actually causes an error in matplotlib 3.4

cleanup: remove cubehelix colormap

---

yt/funcs.py

related to YTEP-0039 but not part of it 
I noticed the `parallel` flag from `yt.funcs.get_pbar` wasn't used anywhere so I removed the unnecessary code around it.
(This will conflict with #3114. I'd like the present change to go in first)

cleanup: simplify get_pbar by removing a vestigial class that's not used anymore

---

doc/source/analyzing/filtering.rst
yt/data_objects/selection_objects/cut_region.py
yt/fields/particle_fields.py

Cut regions fail for particle-based fields, as pointed out in issue #1976. 
Some work probably needs to be done to decide if we want to support them in cut regions at all, but @chummels made a good suggestion in that issue that we should update the docs to reflect the fact that particle filters should be used instead. This PR does that, and fixes an error on the same page. 
EDIT: We now provide a function that checks if the fields provided to filter a `YTCutRegion` object are mesh fields, and throws an error if not.

Update filtering docs to reflect that particles should not be used with cut regions

---

yt/data_objects/data_containers.py
yt/data_objects/index_subobjects/particle_container.py
yt/data_objects/static_output.py
yt/data_objects/tests/test_pickling.py
yt/geometry/particle_geometry_handler.py

Update: this PR has broadened a bit to include some wider pickle and `ParameterFileStore` fixes. Happy to split into separate PRs if warranted. 
The main update that may be worth some discussion is that I'm modifying the base `__reduce__` used by `YTDataContainer`. Since `save_as_dataset` is now the recommended method for long term dataset storage and the pickling seems to have been broken for some time, I assumed this was OK. But it does mean that if there happened to be any legacy pickled datasets out there for which the reload was NOT broken, this change will definitely break them. 
Original: 
I'm not sure this qualifies as a bug per se as this isn't something that you would do accidentally (feel free to remove the bug tag).... but currently on main, if you try to pickle a chunk of a …

making ParticleContainers pickleable

---

yt/data_objects/data_containers.py
yt/data_objects/profiles.py
yt/utilities/on_demand_imports.py

As remarked by @munkm in https://github.com/yt-project/yt/pull/3089#discussion_r601793845
pandas is currently not part of our `on_demand_imports`, but the only places it's imported are clearly documented as fragile because it's _not_ a hard dependency.

add pandas to yt.utilities.on_demand_imports

---

yt/frontends/http_stream/data_structures.py
yt/frontends/http_stream/io.py
yt/frontends/sdf/data_structures.py
yt/funcs.py

This is a quick follow up to #3100, cleaning up a unique mechanism that was used to specify requests as an optional dep, which is not necessary any more.

cleanup: remove yt.funcs.get_requests, use yt.utilities.on_demand_imports

---

yt/frontends/ramses/field_handlers.py
yt/frontends/ramses/fields.py
yt/frontends/ramses/tests/test_outputs.py

Until recently, the potential dumped by RAMSES was assumed to be in energy units, whereas it should be in specific energy units.

[bugfix] Fix units of potential

---

yt/frontends/_skeleton/__init__.py
yt/frontends/ahf/__init__.py
yt/frontends/art/__init__.py
yt/frontends/artio/__init__.py
yt/frontends/boxlib/__init__.py
yt/frontends/exodus_ii/__init__.py
yt/frontends/flash/__init__.py
yt/frontends/gamer/__init__.py
yt/frontends/nc4_cm1/__init__.py
yt/frontends/open_pmd/__init__.py
yt/frontends/ramses/__init__.py
yt/frontends/sph/__init__.py

I _think_ those docstrings predate the `yt/frontends/*/api.py` modules and are basically meaningless now, and confusing from a new-comer's perspective (which I got when I started writing the AMRVAC frontend). I propose to remove them.

remove false api docstrings in frontends

---

.pre-commit-config.yaml

See https://github.com/PyCQA/flake8/blob/e0116d8e77fb04acc62095734ec49e779f24ee54/setup.cfg#L43

remove mccabe from linting specs (already a direct dependency of flake8)

---

nose_unit.cfg
tests/tests.yaml
yt/tests/test_load_errors.py

I'm experiencing issues with these tests running on pytest in https://github.com/yt-project/yt/pull/3062, specifically:
https://tests.yt-project.org/job/yt_py38_unittests/18/testReport/junit/yt.tests/test_load_errors/test_load_nonexistent_data/
I originally wrote these tests for pytest but had to rewrite them to get them merged, so I'm rewriting them back in hopes that will help fixing the initial problem in #3062 
For reference I could not reproduce the issue locally but I assume pytest + Jenkins is less well behave with tests using a different framework.

rewrite load tests with the pytest framework

---

yt/testing.py

This function is meant as a drop-in replacement for the existing `required_module` decorator.
The end goal is to provide a pytest-compatible alternative (and eventual replacement when nose is dropped).
While I'm at it, and since it's relevant in the context of #3089 (containing the initial implementation), I added support for
an arbitrary number of arguments as an alternative to decorator stacking.
It is under testing in #3089 at the time of writing, and I confirm that it works as intended locally.

add a pytest-compatible version of requires_module

---

yt/visualization/plot_window.py

This PR fixes issue #2890, following a suggestion by @chrishavlin, which uses symlog scaling if there are zeros in the plot, avoiding a thrown exception by matplotlib if log-scaling is requested. 
I also updated the log messages to be more specific about why symlog scaling is being used.

[bugfix] Fix log plots when using matplotilb 3.3.x if there are zeros in the plot

---

doc/source/reference/api/api.rst

A number of data container classes were moved in recent reorgs, breaking the api docs links. I also encountered some that were missing.

update API docs for missing/moved classes

---

yt/testing.py

quick hotfix for #3159
I was too bold in cutting this function out of #3089 initially, now it's actually usable.

fix a broken import statement in requires_module_pytest

---

yt/visualization/fits_image.py
yt/visualization/tests/test_fits_image.py

There were bugs in propagating units correctly in `FITSImageData` instances if they were created from other instances using `pop` or `combine_images`. It was also the case that the code would attempt to make the units of a FITS image made from a cosmological simulation in terms of comoving quantities, little h, and the scale factor. For various reasons, this does not work well with AstroPy, so this code also ensures that "proper" units are used in the FITS files that are produced. 
This PR fixes those issues, and also adds the hubble parameter and the current redshift to FITS images made from cosmological simulations so that the cosmological units can be re-created if necessary.

[bugfix] Fix issues with FITS images

---

yt/data_objects/data_containers.py
yt/data_objects/static_output.py
yt/units/unit_systems.py
yt/visualization/plot_modifications.py
yt/visualization/plot_window.py
yt/visualization/tests/test_plot_modifications.py

This (again) fixes the issue that axis units are not displaying `code_length` for datasets loaded with `unit_system='code'` (issue: #2353, PR: #2354). This also extends to `annotate_timestamp` not displaying the units correctly (issue: #2432, PR: #2435). I assume that merging yt 4.0 undid these.
As far as I could see the unit systems no longer have 'us' in their name, but are simply 'cgs' or 'mks'. The code unit system however has the name 'e0ff37ce2df3cfe508167372302fd83d' (at least in my case) and I'm not sure where this comes from...
The fix is easy, but I don't know if this is going to break other stuff. If it's fine I'll add a test so this doesn't happen again.
```python
ds = yt.load('amrvac/bw_3d0000.dat', unit_system='code')
p = yt.SlicePlot(ds, 'x', 'density') …
```

[bugfix] ensure correct axis units when unit_system=code

---

doc/source/visualizing/colormaps/index.rst
yt/visualization/color_maps.py

The problem is discussed in #3165
Right now, using an env with yt's bleeding edge and
```
cmocean
matplotlib==3.4
```
breaks everything because of a naming collision that matplotlib used to tolerate but doesn't any more
```shell
$ python -c "import yt"
...
ValueError: Trying to re-register the builtin cmap 'gray'.
```
The solution is to stop registering cmocean's colormaps unprefixed.
Sadly this is a backward breaking change but it's necessary in order to make yt compatible with matplotlib 3.4, so I believe it's worth the cost.
Note that yt can still be used in combination with cmocean or similar projects (such as cmasher), at the discretion of the user.
This used to work (with cmocean installed)
```python
import matplotlib
import yt
ds = yt.testing.fake_amr_ds()
p = yt.SlicePlot(ds, "z", …
```

supporting MPL 3.4 : stop registering colormaps from cmocean

---

yt/tests/test_load_sample.py

as reported by @cphyc , #3089 introduced a fragility in our CI
(see a fresh broken run https://github.com/yt-project/yt/pull/3181/checks?check_run_id=2313285499)
The culprit is a fragile component of an otherwise large test, and I do expect it to crash much more often for bad reasons than good ones, so we might as well just remove it.

hotfix: remove fragile assert statement in a massive test

---

tests/ci_install.sh

Tries to make the OSx test run again by allowing brew to update itself.
The origin of the bug is due to:
1. hdf5 requires a library called szip
2. szip depends on a compiled binary that was hosted on bintray
3. which depends on jfrog.com, who announced recently they were dropping support for bintray (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).
This has been fixed quite a while ago (see the file history of https://github.com/Homebrew/homebrew-core/blob/master/Formula/szip.rb), but we still need to have brew update its recipe cache for it to take into account.

Allow `brew` to update to fix hdf5 installation issues

---

yt/frontends/ramses/data_structures.py
yt/frontends/ramses/tests/test_outputs.py

The `print_stats` function is broken for RAMSES datasets.

Fix `print_stats` function for RAMSES datasets.

---

setup.py
tests/test_minimal_requirements.txt
tests/test_requirements.txt

I don't know if they renamed the package, but there's no such thing as `more_itertools` package, only `more-itertools`. I'm surprised only py38_latest was failing due to this...

fix: correct more-itertools package name

---

yt/visualization/plot_container.py

fix #3208
edit: looks like my solution doesn't work across all versions of matplotlib.
For reference, I wrote it for ppl 3.3, now trying to generalise it.
edit 2: it also work with matplotlib 3.4
edit 3: should work for all currently supported versions of matplotlib now 🎉  (thanks to @cphyc  for his help in testing locally with "old" versions)

fix a bug where set_background_color wouldn't work with colormaps from third party libs

---

doc/source/yt4differences.rst

PR #3175 made a backwards incompatible change to yt dev that breaks existing scripts (it broke mine right under my nose).  This sort of thing needs to be documented in our yt4 differences page to minimize problems for users making a transition to yt4.  I've tried to update the docs appropriately.
Update1: Including @neutrinoceros 's changes.  
Update2: Ensuring the codeblocks work.

Adding note in docs about cmocean cmap changes.

---

yt/data_objects/static_output.py
yt/frontends/art/data_structures.py
yt/frontends/athena/data_structures.py
yt/frontends/athena_pp/data_structures.py
yt/frontends/enzo_p/data_structures.py
yt/frontends/gadget/data_structures.py
yt/frontends/gadget_fof/data_structures.py
yt/frontends/gdf/data_structures.py
yt/frontends/halo_catalog/data_structures.py
yt/frontends/http_stream/data_structures.py
yt/frontends/moab/data_structures.py
yt/frontends/open_pmd/data_structures.py
yt/frontends/ramses/data_structures.py
yt/frontends/tipsy/data_structures.py

Try to implement an idea mentioned in https://github.com/yt-project/yt/issues/2737#issuecomment-765740805
Following the insight from the accepted answer in https://stackoverflow.com/questions/1436703/what-is-the-difference-between-str-and-repr
I'm proposing this small change that I think will help in inspecting datasets in REPLs, while hopefully avoiding breakage in any code that relies on the current implem e.g. to format strings.
To be clear on what this (doesn't) change(s), lets run this script
```python
import yt
ds = yt.load_sample("ToroShockTube")  # our tiniest data sample <3
print("raw printing")
print(ds)
print("\nconverting to str")
print(str(ds))
print("\nusing string formatting")
print(f"{ds}")
print("\ncalling __repr__")
print(ds.__repr__())
```
output (main branch) (cutting …

implement a more useful __repr__ for the base Dataset class

---

yt/fields/fluid_fields.py

I wrote this warning a year ago when I added support for gradient computations in curvilinear geometries.
I now find that this warning provides little benefit, and breaks the rule that warnings should be emitted when and if the user is able to act upon them, which isn't the case here.
It also tends to discourage users to report errors this may be hiding.
What's more, it's also showing up quite a lot in our CI logs and makes any actual warning that we _should_ care about less discoverable.
Overall I think it creates way more problems than it solves.

remove a log warning that cannot be acted upon

---

doc/source/analyzing/filtering.rst
yt/data_objects/selection_objects/cut_region.py
yt/data_objects/selection_objects/data_selection_objects.py
yt/data_objects/tests/test_clone.py
yt/data_objects/tests/test_covering_grid.py
yt/data_objects/tests/test_extract_regions.py
yt/frontends/adaptahop/data_structures.py
yt/geometry/oct_geometry_handler.py
yt/visualization/tests/test_offaxisprojection.py

Updates a bunch of tuple access to always use the `data[("foo", "bar")]` syntax and update the cut_region doc to use tuples throughout.

Upading cut_region docs and use tuples everywhere - fixes #3201

---

yt/_maintenance/deprecation.py
yt/data_objects/construction_data_containers.py
yt/data_objects/data_containers.py
yt/data_objects/image_array.py
yt/data_objects/particle_filters.py
yt/data_objects/profiles.py
yt/data_objects/selection_objects/data_selection_objects.py
yt/data_objects/static_output.py
yt/data_objects/time_series.py
yt/fields/field_info_container.py

This uses https://github.com/Carreau/velin to try to automatically fix a
couple of issues in docstrings to match the numpydoc syntax.
- Space before colon in Parameter sections is necessary for numpydoc to
properly recognize parameter name and type.
- Naming of sections in numpydoc is plural usually
This also remove a couple of documented parameters that don't exists
(either removed, or copy-past is my guess).

DOC: Misc numpydoc syntax fixing.

---

yt/data_objects/derived_quantities.py

fix a deprecation warning where unyt_array instances would be constructed from 'ragged' arrays

---

yt/frontends/gizmo/data_structures.py
yt/frontends/gizmo/fields.py

Two small changes to fix the gizmo frontend.
One, gizmo is still expecting the `H_number_density` field to exist to calculate the free electron content.  Recently `H_number_density` got swapped to `H_nuclei_density`.  This corrects that.
Another issue is that increasingly the FIRE datasets are using variable numbers of metallicity fields above 11 elements.  When the gizmo frontend was first created, it was set to accept 11 and 17 metallicity fields to indicate it was a FIRE (i.e., gizmo) dataset to differentiate it from Gadget datasets.  This has been somewhat relaxed and there are a number of FIRE datasets with 12, 13, etc. metallicity fields floating around.  This fixes this so any gadget-like dataset with more than 11 metallicity fields gets flagged as a gizmo dataset. 
In the long …

Fix gizmo frontend

---

.pre-commit-config.yaml
CONTRIBUTING.rst

Anthony Sottile just implemented a switch to deactivate the auto-fixing feature from pre-commit-ci:
https://groups.google.com/u/0/g/pre-commit-ci/c/OdKCckDrv0A?pli=1
https://pre-commit.ci/#configuration
Given that it's the one feature that was deemed hurtful by the steering council (https://mail.python.org/archives/list/yt-dev@python.org/thread/EOEK3SOQJXOZY463UX6KPD5GAIWO7YWU/), I propose we take the opportunity to switch it off, and I hope we can continue using the rest of the service (static checking for PRs and auto-updates for .pre-commit-config.yaml).
hopefully fix #3122

ci: deactivate pre-commit-ci autofixing

---

doc/source/examining/loading_data.rst
yt/frontends/gadget/data_structures.py
yt/frontends/gizmo/data_structures.py

The GIZMO frontend by default sets the magnetic field code unit to be 1.0 Gauss, but it says [here](http://www.tapir.caltech.edu/~phopkins/Site/GIZMO_files/gizmo_documentation.html#params-generic-units) you can set the value of the magnetic unit to something else. This PR allows for that by adding the code to set the magnetic field from `unit_base` in the Gadget frontend, but the "sane default" is still 1.0 Gauss.

[bugfix] Allow the magnetic field unit to be set from unit_base in all Gadget-based frontends

---

setup.cfg
tests/test_requirements.txt

fix #3256 (?)
For now I'm just commenting out two tests functions that I strongly suspect are the ones generating the failing answers.
If CI validates my suspicions I'll be able to start digging into it for real.
update for posterity:
since I've rebased and force pushed a different fix, there is no trace left of the tests functions I was referring to, so here they are:
- `yt/visualization/tests/test_line_plots.test_line_plot`
- `yt/visualization/tests/test_line_plots.test_multi_line_plot`
eg the only tests that use the `LinePlot` class (that I'm aware of)

CI: hotfix failing answer tests

---

yt/frontends/arepo/data_structures.py

I currently have an AREPO dataset from the AURIGA simulation suite, and it is failing to get loaded in.  It appears that one of the requirements for the AREPO frontend is that all datasets must have a CONFIG group in their HDF5 file.  This one does not.  However, any datasets that have fields beginning with `GFM_` (for Galaxy Formation Model) *are* AREPO datasets, so I'm using that as an alternate hook for ID'ing AREPO datasets.
I have written to Dylan Nelson from TNG and Freeke van de Voort from Auriga to confirm that GFM fields mean AREPO, so this should not be merged until I report back here.
UPDATE1: I received word back from Dylan that GFM fields are only present in Auriga, SURGE, and TNG datasets (all part of AREPO), so this should be accurate and ready for review.

Accounting for AREPO datasets to be correctly identified.

---

yt/data_objects/construction_data_containers.py
yt/geometry/geometry_handler.py
yt/visualization/streamlines.py
yt/visualization/volume_rendering/image_handling.py
yt/visualization/volume_rendering/old_camera.py
yt/visualization/volume_rendering/transfer_functions.py

In the spirit of #3144
get rid of every remaining occurence of pylab

cleanup pylab-based code (switch to matplotlib.pyplot)

---

yt/data_objects/static_output.py
yt/frontends/owls_subfind/data_structures.py

It seems there are some variants of the OWLS Subfind frontend that are missing an attribute for the current time in Gyr. However, this is redundant given the current redshift and cosmological parameters, so we can set time off that if necessary.

Set current time off redshift if time attribute missing from data.

---

yt/data_objects/construction_data_containers.py

I'll admit: I don't know what I'm doing. If this gets merged in, there is a chance some unnamed PhD student will probably lose a couple of weeks trying to debug a subtle issue of nonconforming units somewhere affecting their results. They'll `git bisect` and then `git blame` and learn my name. They won't know me, but they'll hate me. With passion. 
However, on a slim chance that what I'm suggesting doesn't break the Universe horribly, let's run a full testsuite on this PR. Afterwards, I'll provide a concrete example how this benefits a specific use case.

fix: don't copy unit registry if it is already the same thing

---

doc/source/examining/loading_data.rst
yt/frontends/enzo_e/data_structures.py

It's now been four years since the Enzo-P/E frontend was implemented and there have not been any fundamental changes to Enzo-E data in that time. I think it's safe to do this now.

Remove warning labels on Enzo-E frontend.

---

tests/ci_install.sh

Pin proj library on osx until SciTools/cartopy#1140 is fixed.
Should fix failing OSX build.

Pin proj to 7.x per SciTools/cartopy#1140

---

yt/frontends/arepo/data_structures.py

`GadgetDataset` and its various subclasses allow for a `unit_base` argument to be passed in to set units if they aren't in the dataset. This was not working for `ArepoHDF5Dataset`, which usually (but not always) has the units in the file--if they weren't in the file, then whatever was in `unit_base` was simply being ignored, mainly because the attribute `_unit_base` was simply being clobbered by `ArepoHDF5Dataset` and erasing whatever had been inputted by the user. 
This fixes it by allowing Arepo to figure out what kind of units it has, save them, and then update the `_unit_base` dict with its values (if it has any) before letting the superclass `GadgetDataset` check them. 
However, whatever units are in the dataset must take precedence--and we will warn the user about this.

Make Arepo units play nice with unit_base

---

nose_unit.cfg
tests/tests.yaml
yt/visualization/plot_container.py
yt/visualization/tests/test_save.py

Intent: fix #3210
The patch is not elegant at all, but it works ™️ (at least the tests I wrote for it pass)
Note that in order to make this work I "sacrificed" a feature that was deemed unintuitive in the original disscussion. Namely,
`PlotContainer.save("img")` used to interpret `"img"` as a file prefix OR an output directory depending on wether such a directory existed already or not. This PR intentionally breaks this undocumented (AFAIK) feature to make room for the one @chummels wanted back in his original report.
Following the discussions in the issue, I think the best course of action in the foreseeable future would be rethink the amount of magic we want to support in saving functions, but for now, we've agreed that it's best to just try and restore the old behaviours in time for …

Restore auto creation of save dirs in PlotContainer.save

---

doc/source/examining/loading_data.rst
tests/tests.yaml
yt/fields/astro_fields.py
yt/frontends/gamer/data_structures.py
yt/frontends/gamer/fields.py
yt/frontends/gamer/tests/test_outputs.py
yt/sample_data_registry.json

This PR adds field definitions for special relativistic simulations to the GAMER frontend. This is a work in progress.
It uses the equations from https://arxiv.org/abs/2012.11130.
See also https://github.com/gamer-project/gamer/pull/41.
It also adds the general derived fields `lorentz_factor` and `four_velocity_[xyzt]` components for any frontend.

Special relativistic fields for GAMER

---

yt/visualization/volume_rendering/tests/test_vr_orientation.py

Revert #3068
Aim: fix #3069 
I'll try to reproduce the failure in 5 CI runs or less.
If it doesn't pop up, the PR could probably go in as is. If it does, we'll see if it can be fixed by increasing the precision tolerance for this specific test.
update
- run 1: passed ✅
- run 2: failed ❌ 
RMS Value: 0.005627314338711377
Tolerance:  1e-12
For posterity, here's the diff
It seems like a big jump to bump the tolerance from 1e-3 to 1e-2...

test: revert PR 3068. Reactivate a randomly failing answer test

---

doc/source/analyzing/fields.rst
doc/source/examining/loading_data.rst
doc/source/reference/api/api.rst
doc/source/visualizing/plots.rst

Resolves Issue #3230.
This adds a discussion of a method to plot particle data by depositing onto a grid data object ([smooth] covering grid, arbitrary grid), saving a new dataset, reloading, and plotting from that. I also add a little more visibility to the `add_SPH_fields` method. Finally, I caught some more cases of functions missing from the api reference.

Document particle visualization workarounds

---

yt/frontends/enzo_e/fields.py
yt/frontends/enzo_e/io.py
yt/frontends/enzo_e/tests/test_outputs.py
yt/sample_data_registry.json

This PR introduces support for outputs generated by Enzo-E's VL+CT integrator. This basically just adds handling for magnetic fields. It also adds proper handling for determining `"specific_thermal_energy"` when the dual-energy-formalism is being used.
I just wanted a little clarification on the tests I should be adding. Would it be adequate to introduce an answer test involving a new dataset generated with this integrator and an answer test similar to the `test_hello_world` in `enzo_p/tests/test_outputs.py`? Should I also be introducing an additional dataset for checking the dual-energy-formalism handling?

Support for enzop vlct

---

yt/sample_data_registry.json

in combination with https://github.com/yt-project/website/pull/97, this should fix #3178
A point that is not clear to me is how to better approach the proposed migration on the testing side. I imaging go as follow:
- install (download) the renamed datafiles on Jenkins,
- update yt/frontends/amrvac/tests files
- drop (delete) the old files on Jenkins
@Xarthisius, any thoughts ?
Since the issue was caused by non standardised packaging, I had to regenerate the hashes for each file.
While I'm at it, I also register the solar_prom2d dataset, which is already on the website but lacking a registration in the pooch registry.
note: I realise that this update breaks alphabetical ordering of the json file entries, but the patch was hard enough to keep track on, so I figure it's preferable to stick …

load_sample: update amrvac sample data files registry

---

yt/sample_data_registry.json

This is the first of a series of small PRs to fix remaining failures with yt.load_sample
This one is trivial and fixes the following script
```python
import yt
yt.load_sample('DMonly')
```

load_sample: fix a broken load_name (DMonly)

---

yt/sample_data_registry.json

Similar to #3328 
Next PRs will contain more than one fix at a time.
This one fixes
```python
import yt
yt.load_sample('ytdata_test')
```

load_sample: fix a broken load_name (ytdata_test)

---

doc/source/visualizing/plots.rst
tests/tests.yaml
yt/visualization/base_plot_types.py
yt/visualization/plot_container.py
yt/visualization/plot_window.py

Following a patch (PR #3161) for an upstream bug in MPL (see Issue #2890), yt now uses symlog scaling to plot some particle-based datasets.  But the default behavior of symlog sometimes guesses poorly at the `linthresh`, the transition value between scaling the data linearly vs log.  This PR attempts to do a slightly better job of this so users get a decent plot out of the box.
I am definitely open to suggestions on how to improve this behavior.  I feel like there is a lot to unpack here, and I'm not sure this is the right way to do it, but it's a start.  In particular, I realize that by choosing a `linthresh` that is the smallest non-zero value in a dataset, it's wasting the colorbar range between 0 and `linthresh`.  I think one could do a better job by modifying the values of …

Make symlog choose a better default linthresh

---

yt/sample_data_registry.json

This (with #3328 and #3329) exhausts the list of sample data files that can't currently load with `yt.load_sample` because of a simple "mistake" in the local json registry.
All of them can _download_ properly on the main branch already, but this patch is necessary to make them actually loadable with `yt.load_sample`.
I should add that all these changes were tested on my machine, and are in no way automated.

load_sample: fix a handful of broken load names

---

yt/sample_data_registry.json

I did a mistake last time I updated all of the AMRVAC datasets on the hub, here's the fix.
Companion PR: https://github.com/yt-project/website/pull/105

load_sample: fix a mistake in pointers to an AMRVAC dataset

---

setup.cfg

firefly-api seems to have suddenly been removed from Pypi today (not _yanked_, *removed*, which means we can not even require the last version specifically).
ATM I can't find information on this event, so I'm just proposing this hotfix in order to allow CI to pass on other PRs on the short term.
Further action will be required when we find out what happened.
edit: these were the urls for this package :
https://pypi.org/project/firefly-api/
https://github.com/agurvich/firefly_api

hotfix: don't require firefly_api even in full build as it's not available on Pypi any more

---

doc/source/faq/index.rst

This updates the FAQ (where it needs to be updated, which is not everywhere!) to reflect the current state of yt 4.0.
This addresses issue #3353.

Updating FAQ for 4

---

setup.cfg

Noticed this warning
```
WARNING: autodoc: failed to import module 'eps_writer' from module 'yt.visualization'; the following exception was raised:
No module named 'pyx'
```
while scanning through the logs in docs build, e.g.
https://tests.yt-project.org/job/yt_docs_new/1526/consoleFull
This is the quick-and-dirty fix, but maybe `pyx` should actually be either a hard dependency or an optional one referenced in the on_demand_import.py module

fix: add pyx to documentation build deps

---

yt/loaders.py
yt/sample_data_registry.json

This is also based on top of #3337 (only the last commit is exclusive to this branch), draft status shouldn't be removed before the previous PR goes in.
I will also perform a general test for this to make extra sure it's not breaking anything.
Here's a -likely, but not necessarily comprehensive- list of datasets that this patch makes loadable
- Gadget3-snap-format2
- snapshot_010
- agora_1e11.00400
On the main branch, and up to #3336, `load_sample(<any of the above>)` fails with a "YTUnidentifiedDataFormat".

load_sample: fix for load names matching directory names

---

yt/loaders.py
yt/sample_data_registry.json

This fixes a few leftovers from  #2699+#2951: datasets that cannot  currently load with `yt.load_sample` because they lack a default "load_name".
I needed to tweak `yt.load_sample` itself, and I want to stress that I've performed a systematic check that the change *doesn't* break any of the previously working cases (the check takes a few *hours* to download the whole database).
Note to reviewers: I encourage you to manually test this patch (I already did), but note that some of the datasets that this patch fixes are pretty big (between 5 and 15GB), so it might take a little while for them do download.

load_sample: fix datasets without a loadname + bugfix

---

doc/source/reference/api/api.rst
doc/source/visualizing/plots.rst

Changes the name of the dataset to an actual existing sample dataset.

Change sample dataset name.

---

.pre-commit-config.yaml
yt/__init__.py
yt/frontends/artio/_artio_caller.pyx
yt/frontends/artio/data_structures.py
yt/frontends/gdf/io.py
yt/startup_tasks.py

This cleans up reminiscent compatibility layers for Python 2, but more importantly, it fixes two bugs:
- in yt/startup_tasks.py where a conditional would break when Python 3.10 is released (later this year).
- in `yt/__init__.py`, where the version check would wrongfully pass under Python >=3.0;<3.5 
By adding a flake8 plugin to the pre-commit tool belt, I also prevent this kind of mishap to happen again in the future.

cleanup Python version checking 

---

tests/tests.yaml
yt/visualization/tests/test_plotwindow.py

With the release of numpy 1.21, the following answer tests finale images changed slightly
yt/visualization/tests/test_plotwindow.py:test_attributes_wt
here's the existing reference
and here's the new result
Here's a minimal script to reproduce this (thanks @Xarthisius for posting this on Slack)
```python
import yt
from yt.utilities.answer_testing.framework import data_dir_load
WT = "WindTunnel/windtunnel_4lev_hdf5_plt_cnt_0030"
plot_field = ("gas", "density")
ds = data_dir_load(WT)
ax = "z" 
slc = yt.SlicePlot(ds, ax, plot_field)
slc.set_zlim(plot_field, 1e-25, 1e-23)
slc.save()
```
The actual range in the data is [0.05956075, 6.61460495] (g/cm^3), so the resulting image is kinda irrelevant in both cases and the new one is actually consistent with what can be obtained with a very simple, …

CI: bump answers for numpy 1.21

---

yt/visualization/fits_image.py

This PR fixes the recently added `FITSParticleProjection` class. The bounds for the FITS image were incorrectly being calculated--they assumed that the appropriate values for the center of the image were those in the x and y axes, which is only true for a projection along the z-axis. This fix ensures that the correct values of the center coordinate are chosen depending on the axis of the projection.

[bugfix] Fix FITSParticleProjection for all axes

---

yt/frontends/gadget/io.py

In PR #2645 we added the capability to generate smoothing lengths for a Gadget HDF5 dataset that didn't have one. It turns out the example I used had 64-bit particle positions (which is not typical, Gadget datasets usually have 32-bit positions), and the `generate_smoothing_length` function expects 64-bit positions. 
There may be a better way of handling this (with a fused type or something) but this is a quick fix. Note that we have to cast the `positions` array upon entry into the `generate_smoothing_length` function so that the original array retains its original type.

[bugfix] generate_smoothing_length expects 64-bit positions

---

pyproject.toml
tests/ci_install.sh
tests/windows_conda_requirements.txt

Cython 3.0 is coming soon and already has some release-candidates available.
It seems very likely that yt will _not_ be compatible with it out of the box, but I don't think anyone has time to future proof this right now, so I think it's much preferable to forbid it completely for now. For reference, this is inline with the current specs in numpy itself, see
[numpy's pyproject.toml](https://github.com/numpy/numpy/blob/57863f598ddaade14b3d81e6e91ebecca881f996/pyproject.toml#L7)

Future proofing: forbid cython 3.0 until we can properly test against it

---

pyproject.toml

Old versions of wheel are not compatible with the latest updates in numpy + Python 3.10, see
https://github.com/numpy/numpy/pull/18389
This should make installation against Python 3.10 more reliable

Future proofing: set a minimal required wheel version in build system specs to improve compatibility with Python 3.10

---

.github/workflows/build-test-pytest.yaml
.github/workflows/build-test.yaml

This is a temporary measure to work around an external failure do to some update upstream (not sure where from exactly) that cascades down and breaks the GH action we use to setup conda on windows.
The failure affects #3380 and #3384 at the moment, and soon, everyone else.
See for instance:
https://github.com/yt-project/yt/runs/2954378672?check_suite_focus=true
Since only windows is affected, I think this can be merged as soon as both windows jobs pass

CI: deactivate conda update as a workaround to external failure

---

.github/workflows/rules-checks.yaml
conftest.py
setup.cfg
tests/windows_conda_requirements.txt
yt/data_objects/construction_data_containers.py
yt/data_objects/index_subobjects/grid_patch.py
yt/frontends/art/data_structures.py
yt/frontends/boxlib/data_structures.py
yt/frontends/gadget/data_structures.py
yt/geometry/oct_geometry_handler.py
yt/tests/test_load_errors.py
yt/utilities/fortran_utils.py
yt/utilities/tests/test_cosmology.py
yt/utilities/tests/test_interpolators.py
yt/visualization/color_maps.py
yt/visualization/plot_window.py
yt/visualization/volume_rendering/lens.py
yt/visualization/volume_rendering/old_camera.py

fix #3379
Though independent, this is complementary with #3376.
An important note is that there are some internal deprecation warnings with no obvious solution yet, so I'm adding them to the ignore-list in conftest.py but they will need to be addressed in future releases. Specifically, I'm talking about fields `("all", "px")` and `("gas", "px")` (respectively `"py"`, `"dpx"` and `"dpy"`), that are used internally in slice selectors, but never with explicit field/particle types. Getting to a stable solution here requires much more thought and design that what I'm solving here so I'll defer it to future works, and in any case it's not as urgent as other deprecation warnings because it's internal so it won't break haphazardly.

Future proofing: treat most warnings as errors in pytest, and fix existing ones

---

README.md

This improves two things in the README in preparation for the upcoming release
- hardlink logo to the github repo so it is properly included on the PyPI page, even without including the image in MANIFEST.in
- badge up for PyPI (display latest published version and corresponding supported Python versions)
Opening as a draft to signal that this should only be merged when the release is about to happen, since the badges will be visibly out of sync in the interval.

MAINT: grooming README.md for upcoming PyPI publication

---

yt/geometry/particle_deposit.pyx

Fixes #3399. Solution is to not use private CPython API. Fortunately, we weren't actually using it, just importing it for no reason.
Related Issues/PRs that helped me to identify the bug and find the solution:
* https://github.com/pyproj4/pyproj/issues/854
* https://github.com/h5py/h5py/pull/1515

Remove unused imports from private CPython API that break PyPi builds

---

setup.cfg
setupext.py
yt/frontends/open_pmd/data_structures.py
yt/funcs.py
yt/utilities/on_demand_imports.py
yt/visualization/base_plot_types.py
yt/visualization/plot_window.py
yt/visualization/profile_plotter.py

This is a first step in resolving #3384, though other parts of distutils are still used elsewhere in the code base.
Here I'm following official migration recommendations from [PEP 632](https://www.python.org/dev/peps/pep-0632/#migration-advice), in which `disutils`' removal was discussed.

Future proofing: drop distutils.version (targeted for removal in Python 3.12)

---

MANIFEST.in

`check-manifest` shows a lot of missing files. Especially `yt/geometry/_selection_routines/*.pxi` look critical, i.e. building yt from source will fail without them. I threw in `conftest.py` as a cherry on top. Prunes / excludes that I added are mostly cosmetic. With this PR I still get:
```
missing from sdist:
yt/utilities/lib/cykdtree/c_kdtree.cpp
yt/visualization/mapserver/html/Leaflet.Coordinates-0.1.5.css
yt/visualization/mapserver/html/Leaflet.Coordinates-0.1.5.src.js
```
`yt/utilities/lib/cykdtree/c_kdtree.cpp` is empty and I don't know if it's needed. Maybe we should remove it. What about vendored Leaflet?

Update MANIFEST.in to include *.pxi and conftest.py

---

.github/workflows/wheels.yaml
pyproject.toml

This adds GHA for building wheels. It covers both the release process and dev (building after every push to master).
Things noteworthy:
* We need to statically link `libstdc++` due to fact we're shipping/building a lot of C++14 code. Otherwise linux wheels are unusable  due to the ABI conflicts. Some info on this can be found [here](https://github.com/pypa/cibuildwheel/blob/184a9feb24ee38d0b0a39fa93b6bb8247cbd636b/docs/cpp_standards.md)
* I switched to `oldest-supported-numpy` for numpy build dependency.
* 32bit linux build fails and I disable it. I don't think anyone uses i686 these days anyway...

Port wheels build to GHA

---

yt/utilities/answer_testing/framework.py

Just to be extra sure that we're doing the right thing, we've been running the same `FieldValuesTest` **3 times** every time `small_patch_amr` was used. No big deal! It's better to be safe than sorry! However, as I grow older I discover a daredevil in me. So I say: let's live our lives dangerously and run this test only once! How about that?
This PR switches the order of loops in `small_patch_amr` to allow `FieldValuesTest` to be run once, since it's independent of `axis` parameter.

Change the loop order to avoid executing the same test 3 times

---

doc/source/conf.py
yt/frontends/amrvac/tests/test_outputs.py
yt/sample_data/api.py
yt/testing.py
yt/utilities/grid_data_format/conversion/conversion_athena.py
yt/utilities/logger.py
yt/visualization/plot_container.py

Prune out noqa statements that fell out of use, using [yesqa](https://pypi.org/project/yesqa/).
Not going to add yesqa to the pre-commit toolbelt however because it would force duplication
of the list of flake8 plugins there for an extremely marginal benefit.

STY: remove meaningless NOQA statement with yesqa

---

doc/cheatsheet.tex
doc/source/reference/command-line.rst
doc/source/reference/configuration.rst
scripts/iyt

This script can essentially be emulated with
```shell
$ ipython -i "import yt"
```
It hasn't received any significant update/maintenance for 13yrs, and doesn't have a clear added value now with a decade of improvements in IPython's autocompletion (and it's getting env better in IPython 8.0, thanks to our own @cphyc : https://github.com/ipython/ipython/pull/12395).
I think it should be removed.

DEPR: deprecate iyt

---

yt/data_objects/static_output.py

Found this while working on something else.
This guard condition is unreachable since PR #2556 made the base Dataset class abstract, which means it _cannot_ be instantiated.

MAINT: remove a unreachable conditional

---

doc/source/conf.py

Since the behavior mentioned in #3422 always applies to first item in the navbar, I inserted and empty link. However, I'm open to ideas if someone knows how to do it via e.g. css...

Insert empty link to navbar in hope it fixes #3422

---

.github/workflows/bleeding-edge.yaml
.github/workflows/build-test-pytest.yaml
.github/workflows/build-test.yaml
README.md
tests/windows_conda_requirements.txt

This adds a workflow to run essential tests against Python 3.10, with dev versions of numpy and matplotlib. The goal is to buy ourselves more time to fix issues (or reporting upstream) before it's too late.
The job is setup to be triggered at least once a day, as well as on every push to the main branch.
GH actions currently do not support a way to signal this properly ([yet](https://github.com/actions/toolkit/issues/399)),
so I won't make it trigger on PRs
This is _heavily_ inspired from a similar workflow in the pandas repo.
While I'm at it I'm updating the triggers for regular CI workflows so we can save a few hours of CPU time by skipping tests on PRs that only touch documentation.

Future proofing: add a scheduled job with dev versions of core deps

---

yt/visualization/profile_plotter.py

Handling of ion field labels only happens in `DerivedField.get_latex_display_name`. It has to be used whenever we need to display nicer labels. Fixes #3269

Use a fancier repr for labels in Profile/PhasePlots. Fixes #3269

---

yt/data_objects/profiles.py
yt/data_objects/tests/test_profiles.py

Attempts to fix Issue #3431 by checking if `extrema` values are all `None` when using a `PhasePlot`, and if so, treats as though `extrema` itself is `None`.  See description in #3431 notes for more details.

Checking if extrema are all None in PhasePlot; fixes #3431

---

yt/data_objects/data_containers.py
yt/data_objects/static_output.py

`_determine_fields(field)` is used (as name suggest) to create a list of fields needed to generate a `field`. It's not a particularly costly method, but it can be called *a lot* and it adds up. One example is iterating over all grids, like we do in `GridValuesTest`. This PR caches the result of `_determine_fields` and keeps it in the `Dataset` object.

Cache _determine_fields for a given dataset

---

yt/fields/derived_field.py
yt/fields/tests/test_fields.py

This is an alternative fix to #3434, and supersedes #3438.
The solution tried here was suggested by @forrestglines. It's not clear to me why the problematic check was ever necessary but it's
been here for 8yrs so my hypothesis is that it may have become inappropriate in Python 3 ?
I'm doubting this would break anything since there doesn't seem to be a single use case of lambdas in derived fields in the code base/docs/tests. On the other hand, the test I'm adding here fails on the main branch (as reported in #3434).

FIX: add support for setting up derived fields from lambdas

---

tests/tests.yaml
yt/frontends/boxlib/data_structures.py

The WarpX team has noticed that since the yt-4.0 release, some of our 2D CI jobs have been failing. To reproduce this, see the attached script and dataset. `ds.domain_dimensions` should be [64, 64, 1], but it is now shown as [64, 64, 64].  
I think this was introduced in [this](https://github.com/yt-project/yt/commit/8bcf84dbd938fc32f87f8ae476e583509866f74f#diff-d4ca70f009bc419366a8305237dfe5143869b6c6a781c363f4c4a0082f239a99) commit, which made changes to how 1d and 2d amrex datasets are set up. The issue is that we sometimes use inputs files that work for both 2D and 3D simulations. Hence, the `amr.n_cell` entry to `warpx_job_info` may have three values in it, even if the dataset is 2D. 
This PR seems to solve the issue for us. The fix was just to use `ds.dimensionality` to cap the …

Fix for 2D AMReX datasets in which 3 values are in the amr.n_cell entry in the job_info file.

---

yt/frontends/gadget/data_structures.py

Gadget 4 datasets have a `Parameters` group in the HDF5 file which store runtime parameters. Crucially, the parameters needed to determine the cosmology are now stored in this group and are not in the `Header` group. This PR ensures that these parameters can be found regardless of the Gadget version used.

Make sure we add the Parameters group to hvals if it's present

---

yt/visualization/fits_image.py
yt/visualization/tests/test_fits_image.py

…ed as the PrimaryHDU
The `combine_images` method of the `FITSImageData` class allows one to combine multiple images into one, but a FITS file is only valid if the first image is a `PrimaryHDU`. The previous implementation, when stitching multiple `FITSImageData` instances together, was attempting to create multiple `PrimaryHDU` instances (the first image from each instance). This PR fixes it and adds a single line to the `FITSImageData` tests which ensure that this functionality works correctly.

fix combining FITS images

---

yt/geometry/coordinates/coordinate_handler.py
yt/geometry/coordinates/cylindrical_coordinates.py
yt/geometry/coordinates/geographic_coordinates.py
yt/geometry/coordinates/spherical_coordinates.py

`CoordinateHandler` defines a base class that is clearly not meant to be instantiated as most of its methods go straight to `NotImplementedError`. While it is an easy way to implement base classes, it is not trivial for new comers to guess where the missing code should be injected in case they run into one of the raise statements, since it should really be added to the specialised child class rather than the base class that the traceback leads to.
To make things clearer, I'm making `CoordinateHandler` an actual abstract class.
I will use CI to discover which methods should be added to child classes, and write `NotImplementedError`s _there_.

make CoordinateHandler an abstract class

---

yt/data_objects/construction_data_containers.py
yt/data_objects/static_output.py
yt/frontends/boxlib/data_structures.py

Fixes Issue #3467 
Script to reproduce problem:
```python
import yt
import matplotlib.pyplot as plt
%matplotlib inline
diag_name = 'diag3' # E.g., diagnostics.diags_names = diag
iteration = 1
plotfile = './diags/{}{:05d}'.format(diag_name, iteration)
field = 'rho'
ds = yt.load( plotfile ) # Load the plotfile
all_data_level_0 = ds.covering_grid(level=0,left_edge=ds.domain_left_edge, dims=ds.domain_dimensions)
Bx = all_data_level_0['boxlib', field].v.squeeze()
extent = [ds.domain_left_edge[ds.dimensionality-1], ds.domain_right_edge[ds.dimensionality-1],
ds.domain_left_edge[0], ds.domain_right_edge[0] ]
fig, ax = plt.subplots()
clim = 1e-19
ax.imshow(Bx,aspect='auto', cmap = 'seismic', clim = [-clim, clim], extent= extent, origin='lower')
```
Dataset is attached. …

Add support for global_startindex != 0 to covering_grid

---

nose_unit.cfg
tests/tests.yaml
yt/visualization/plot_modifications.py
yt/visualization/tests/test_line_annotation_unit.py

When running plot.annotate_line() in a SlicePlot or ProjectionPlot, it modifies the existing array in-place, without correctly using the units in certain cases. When the same line is used again for another plot (say, at a different angle or something) it and its original source array are unexpectedly modified. Fixed by creating a new array converting with `.to` instead of `.convert_to_units`. Since this is used for 2 arrays which are only 3 elements long, the memory added is negligible.
This is the fix to issue #3449 suggested by @chrishavlin

Changed _project_coords to create new array instead of modifying in-place

---

.github/workflows/bleeding-edge.yaml

This will help closing #3473 faster by triggering a run of the bleeding edge CI job as this PR is merged.
It adds a button so the job can be triggered manually next time a similar situation occurs instead of having to wait the next natural trigger (scheduled or merge) to validate a patch upstream.

MNT: add button to manually run bleeding edge CI job

---

yt/frontends/athena/data_structures.py

This patch adresse (bug does not fix) #3001 (update: now it does !)
I ran into a random CI failure again because of this brittle validator, so I hope that this patch makes it even less likely and doesn't break anything.
~Long term, this validator must be refined into a more characteristic heuristic.~ update: done

implement AthenaDataset._is_valid

---

yt/visualization/fits_image.py

This is a follow on to PR https://github.com/yt-project/yt/pull/3375. It turns out that the order of the `axis_wcs` list here, which is used to figure out what the axes should be for a given projection direction, had the 0/x and 2/z axes in the wrong order to pass to the `ParticleImageBuffer`.

[bugfix] Get order of axes right for FITSParticleProjection

---

yt/frontends/athena/data_structures.py

this is a hotfix to #3424 that was merged slighlty before I could integrate this change required by @jzuhone

ENH: loosen header matching for Athena vtk files to allow compatibility with single variable 'vtk outputs'

---

yt/data_objects/construction_data_containers.py

This was indirectly reported by @pgrete on Slack when he stumbled upon this broken warning I authored a year ago.
Here it is as a minimal example:
```python
import warnings
warnings.warn(
"Something went wrong during field computation: %s",
"just kidding",
category=RuntimeWarning,
)
```
results in 
```
TypeError: argument for warn() given by name ('category') and position (2)
```
This is the correct version
```python
import warnings
insert = "just_kidding"
warnings.warn(
f"Something went wrong during field computation: {insert}",
category=RuntimeWarning,
)
```
and produces
```
RuntimeWarning: Something went wrong during field computation: just_kidding
```

BUG: fix a broken call to warnings.warn

---

README.md

DOC: use absolute links instead of relative path for quickstart guard linking with README.md

---

nose_unit.cfg
tests/tests.yaml
yt/testing.py
yt/visualization/eps_writer.py
yt/visualization/tests/test_eps_writer.py

Noticed that eps_writer didn't have tests so I ran an example from the documentation and was able to find a trivial but blocking bug.
While testing this I also fixed another bug where save_fig didn't accept Path objects.
[N/A] New features are documented, with docstrings and narrative docs

BUG: fix two bugs in yt.visualization.eps_writer

---

doc/source/examining/Loading_Generic_Array_Data.ipynb

Closes #3500
The problem is that this notebook was still using a deprecated (and now removed) h5py idiom, see
https://docs.h5py.org/en/stable/whatsnew/2.1.html?highlight=value#dataset-value-property-is-now-deprecated
- [N/A] New features are documented, with docstrings and narrative docs
- [N/A] Adds a test for any bugs fixed. Adds tests for new features.

BUG: fix an outdated h5py idiom in a documentation notebook

---

setup.cfg

This replaces #3504 (see therein for details), and fixes our remaining CI failures that weren't resolved upstream.
Explanation: setuptools 58.0 dropped support for the `use_lib2to3=True` flag, used to convert Python 2 code to Python 3 at build time, see
- https://github.com/pypa/setuptools/pull/2769
- https://github.com/pypa/setuptools/pull/2770
- https://github.com/pypa/setuptools/pull/2777
Exactly one of our dependencies is broken by this change, namely: IPython 1.0.0 (released on August 2013)
The earliest version of IPython that is still supported by the latest version of setuptools is 2.0.0 (released on April 2014), so I assume it is reasonable to just bump our minimal supported version and call it a day.

MNT: bump minimal required IPython version from 1.0.0 to 2.0.0

---

yt/data_objects/static_output.py

BUG: graciously fallback to a default repr for yt arrays in jupyter notebooks

---

nose_unit.cfg
tests/tests.yaml
yt/data_objects/static_output.py
yt/data_objects/tests/test_registration.py

Following a recent discussion on the Slack space in which we discussed how yt extensions
provided support to create third party frontends, which allows users to extend over native one as
```python
import yt
import yt.extensions.my_frontend
```
The only issue I was able to see with this workflow is that, in case such a frontend gets integrated
into yt itself, then users may not realize that the extension import became useless, or worse. Shadowing a "first citizen" frontend may actually be useful as temporary measure, which is why I'm not making this an error, but it seems fair to emit a warning as a forgiving gesture to transiting users.
[N/A] New features are documented, with docstrings and narrative docs
note : I want to add documentation for the whole extension frontend workflow later, …

ENH: warn user in case a Dataset subclass is redefined

---

yt/utilities/lib/cyoctree.pyx

Fix failed re-allocation of octree reported in #3523 .
There are strange edge cases where the creation of more nodes, some which are empty and some which need to be refined, can cause the total number nodes to overflow the maximum. By moving the check for re-allocation further up we ensure that re-allocation will always be performed.

BUG: Fix re-allocation of octree

---

.pre-commit-config.yaml

With [the latest bugbear release](https://github.com/PyCQA/flake8-bugbear/releases/tag/21.9.1) came a new rule (B904).
Fortunately this additional validation already pass in yt (see https://github.com/yt-project/yt/pull/2760), but there could be new things coming upstream at random times in the future, potentially causing disruption in CI. The pre-commit framework is meant to unify tool versions used between devs, so it is counter productive to keep version specifications loose.
Also note that flake8 plugins are currently out of reach for pre-commit.ci and `pre-commit autoupdate` so they still need manual maintenance.
I think it's reasonable to pin to the current latest versions for now, then we can upgrade manually as required (for bugfixes or features relevant to yt).
- [N/A] New …

MNT: pin flake8 plugins

---

yt/testing.py

I found this error message a is little misleading since we don't actually check wether a given backend is available, but only if it is currently active.
[N/A] New features are documented, with docstrings and narrative docs
[N/A] Adds a test for any bugs fixed. Adds tests for new features.

ENH: correct error message for requires_backend testing decorator

---

yt/sample_data/api.py

This is a second attempt at getting this function right after #3446
Here's the problematic edge case that this solves.
Assuming that `yt.test_data_dir` is correctly setup in in `yt.toml`
```python
import yt
yt.load("NotADir/NotADir")
```
on main
```
FileNotFoundError: No such file or directory: 'NotADir/NotADir'.
```
this branch
```
...
FileNotFoundError: No such file or directory: 'NotADir/NotADir'.
(Also tried '/Users/robcleme/dev/yt-project/test-data-dir/NotADir/NotADir').
```

BUG: fix error message in lookup_on_disk_data

---

yt/sample_data_registry.json

This simply remove a dataset which isn't used anywhere in the code and that cannot be loaded from `load_sample`.
This is due to the `.tar.gz` having the structure:
```
ramses_extra_fields
├── amr_00001.out00001
├── amr_00001.out00002
├── amr_00001.out00003
├── amr_00001.out00004
├── amr_00001.out00005
├── amr_00001.out00006
├── amr_00001.out00007
├── amr_00001.out00008
├── compilation.txt
├── cooling_00001.out
├── grav_00001.out00001
├── grav_00001.out00002
├── grav_00001.out00003
├── grav_00001.out00004
├── grav_00001.out00005
├── grav_00001.out00006
├── grav_00001.out00007
├── grav_00001.out00008
├── header_00001.txt
├── hydro_00001.out00001
├── hydro_00001.out00002
├── hydro_00001.out00003
├── hydro_00001.out00004
├── hydro_00001.out00005
├── hydro_00001.out00006
├── …
```

Remove unused RAMSES dataset

---

yt/visualization/volume_rendering/scene.py
yt/visualization/volume_rendering/tests/test_scene.py

Currently the answer test build's log is polluted with these warnings:
```
VRImageComparison_UniformGridData_vr_yaw_plane-parallel_0001 ... WARNING:yt:Previously rendered image exists, but rendering anyway. Supply 'render=False' to save previously rendered image directly.
INFO:yt:Rendering scene (Can take a while).
INFO:yt:Saving rendered image to /tmp/tmp7ivhf93i.png
ok
VRImageComparison_UniformGridData_vr_pitch_plane-parallel_0002 ... WARNING:yt:Previously rendered image exists, but rendering anyway. Supply 'render=False' to save previously rendered image directly.
INFO:yt:Rendering scene (Can take a while).
INFO:yt:Saving rendered image to /tmp/tmp4tvkj13k.png
ok
VRImageComparison_UniformGridData_vr_roll_plane-parallel_0003 ... WARNING:yt:Previously rendered image exists, but rendering …
```

make Scene.save less verbose

---

yt/geometry/coordinates/spherical_coordinates.py

BUG: fix incorrect default axis labels in 'r' oriented slice plots for spherical data

---

tests/tests.yaml
yt/visualization/base_plot_types.py
yt/visualization/plot_window.py

This is the patch I suggested in #3535
As far as I can tell the bug is very likely to be in Matplotlib itself, though I wasn't able to replicate it in isolation for now.
I'm opening this a a draft while I attempt to show that this buggy behaviour can be reproduced without yt, in which case I'll report upstream and link the report in a comment.

BUG: fix colorbar minor ticks drawing for symlog norms

---

yt/frontends/gdf/data_structures.py

Root cause that I was hitting this is that `b"piernik" != "piernik"`... However, I came to a conclusion that this clause is wrong for any GDF output, not just that one particular flavor. GDF already implies that RE/LE is a 3-element array, so there's no point in making assumptions about 1) which dimension is reduced or 2) what the value of dds in that dimension should be.
Using script from #3629:
```python
import yt
ds = yt.load("crwind_tst_0001.h5")
slc = yt.SlicePlot(ds, "x", "density")
slc.save("zy.png")
ds.coordinates.x_axis["x"] = 2
ds.coordinates.x_axis[0] = 2
ds.coordinates.y_axis["x"] = 1
ds.coordinates.y_axis[0] = 1
slc = yt.SlicePlot(ds, "x", "density")
slc.save("yz.png")
```
now I get:

[gdf] dimensionality doesn't imply which dimension is reduced

---

setup.cfg
tests/windows_conda_requirements.txt

Fix an out of sync windows-specific requirement

TST: sync version requirements for matplotlib across platforms

---

yt/visualization/plot_container.py

Goal: fix #3636
I'm cargo culting a bit here, so I'll open as a draft.

BUG: fix LaTeX typesetting for fractional ylabels in LinePlot

---

.github/workflows/wheels.yaml

I believe everything upstream is now ready, so let's start building wheels for Python's latest version.

BLD: drop wheel building for Python 3.6 and start building for 3.10

---

yt/visualization/volume_rendering/transfer_functions.py

Fix #3660
rerunning the script therein I obtain:
```
[1. 1. 1. 1. 1. 1. 1. 1.]
[0.96862745 0.8584083  0.73094963 0.53568627 0.32628989 0.16696655
0.04405998 0.03137255]
[0.98431373 0.91344867 0.83947712 0.74608228 0.61862361 0.48069204
0.33388697 0.18823529]
[1.         0.96456747 0.92132257 0.86425221 0.80279892 0.72915033
0.62445213 0.41960784]
```

BUG: fix an off-by-one error in ColorTransferFunction.to_map_colormap method

---

.pre-commit-config.yaml

This requirement apparently prevents devs that don't have the specific Python version to use pre-commit,
so let's just drop it.

MNT: loose exact Python runtime requirement in pre-commit configuration

---

.github/workflows/wheels.yaml

Similar to #3657 but for the backport branch, in preparation for the 4.0.2 release
A key difference with #3657 is that I'm not dropping wheels building for Python 3.6 on this branch

BLD: build wheels for 3.10, align workflow file with main branch (yt-4.0.x)

---

yt/data_objects/time_series.py
yt/loaders.py
yt/tests/test_load_errors.py
yt/utilities/exceptions.py
yt/utilities/hierarchy_inspection.py

This is based on @mameehan5's work with #3512
fix #3510, fix #3005
I'm opening this as a draft because I want to add some tests, but I believe the functionality in now ready:
```
>>> import yt
>>> yt.load("det_x_plt00000")
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ <ipython-input-2-62a091f562d4>:1 in <module>                                                     │
│                                                                                                  │
│ /Users/robcleme/dev/yt-project/yt/yt/loaders.py:102 in load                                      │
│                                                                                                  │
│     99 │   │   return candidates[0](fn, *args, **kwargs) …
```

ENH: implement hint keyword argument for yt.load to help lifting ambiguities in dataformat

---

yt/funcs.py
yt/utilities/on_demand_imports.py
yt/visualization/base_plot_types.py
yt/visualization/color_maps.py
yt/visualization/plot_container.py
yt/visualization/plot_window.py
yt/visualization/profile_plotter.py

Contents:
- Merge pull request #3494 from neutrinoceros/version_parsing
- Merge pull request #3538 from neutrinoceros/fixup_set_zlim_symlog
- Merge pull request #3556 from neutrinoceros/bugfix_symlog_ticks
- Merge pull request #3565 from neutrinoceros/hotfix_3564

Backport symlog norm patches to yt-4.0.x

---

tests/tests.yaml
yt/visualization/base_plot_types.py
yt/visualization/plot_window.py
yt/visualization/profile_plotter.py

I'm fixing a couple error messages here as an excuse to trigger CI so that I can update the answer store.
This PR will be a blocker unless it turns out that no update is needed.
goal ? fix #3558
why now ? matplotlib 3.5.0 just came out. I'm hoping that my work with the release candidate was enough to make this update pretty transparent
but I still expect we're going to see some small changes in our test images, at a level that will bother CI but not humans 🤞🏻

MNT: matplotlib 3.5 compat

---

yt/geometry/particle_oct_container.pyx
yt/utilities/lib/geometry_utils.pyx

On 32 bit machines (i386), argsort returns an `int32`, which is not automatically casted to the `uint64` target data type by Cython, so it raises an exception. This PR adds an explicit `.astype(np.uint64, copy=False)`
Closes: #3656

BLD: Explicitly cast np.argsort() result to target data type

---

setup.cfg

Fix #3559
This should be backported to the 4.0.x branch too.

MNT: loosen sympy version pinning in dependencies

---

yt/frontends/gadget/io.py
yt/geometry/particle_oct_container.pyx

The computation of the morton index only makes sense when dealing with positions within the bounding box. This particularly excludes non-normal (e.g. `inf` or `NaN`).
This should fix #3676 .
However, due to the way the logic was coded in `particle_oct_container.pyx`, non-normal value would happily be passed to compute the morton index... which would then be used to index an array.
The fix is simple: formulate the boundary check in a way that caught non-normal values!
In more details, even though they seem to be equivalent, the following two lines of codes differ!
```python
LE, RE, pos = 0, 1, np.nan
pos >= RE or pos < LE  # is False!
not (LE <= pos < RE)   # is True!
```

BUG: Take into account endianness when reading Gadget binary files

---

yt/visualization/plot_modifications.py

This should resolve the docs part of #3690
For reproduction:
```python
import yt
p = yt.SlicePlot(ds, "z", "density")
p.annotate_title("test")
p.save("/tmp/")
```

BUG: hotfix for a functional breakage introduced in #3546

---

doc/source/visualizing/plots.rst
tests/tests.yaml
yt/geometry/coordinates/spherical_coordinates.py
yt/utilities/lib/pixelization_routines.pyx
yt/visualization/plot_container.py
yt/visualization/plot_window.py

This is a jab at the first item in #1796
Spherical geometries need more work but this is a first step to improve maintainability.
Right now, the defintions of "theta" and "phi" are misaligned between the aitoff pixelizer and the rest of the code base.
Fortunately, the latter is correct (aligned with most common notations AFAIC), while the former isn't user facing so it's an easy fix.
edit: this now completes the 3rd item of #1796

BUG: fixes for Hammer-Aitoff projection (r-normal) 2D viz in spherical geometries

---

yt/visualization/plot_modifications.py
yt/visualization/tests/test_callbacks.py

Fix #3685
```python
import yt
plot = yt.SlicePlot(ds, "z", "density", width=(0.04, 0.01))
plot.annotate_quiver(
"velocity_x",
"velocity_y",
factor=(16, 64), # new !
normalize=True,
plot_args={"color": "white"},
)
plot.save("/tmp/factor.png")
```

ENH: make plot callbacks with 'factor' argument accept 2-tuples to distinguish x/y resolutions

---

yt/visualization/_commons.py
yt/visualization/plot_container.py
yt/visualization/profile_plotter.py
yt/visualization/tests/test_commons.py
yt/visualization/tests/test_save.py

fix #3677, see discussion therein

BUG: fix a bug where PlotContainer.save would wrongfully ignore specified field extension

---

setup.py
tests/tests.yaml
yt/frontends/gamer/cfields.pyx
yt/frontends/gamer/fields.py

The main goal of this PR is to optimize memory usage during field generation, by decreasing the amount of fields used as dependencies in derived fields. There's a significant performance boost, but it's just a side effect. As an example prior to this PR:
```
>>> pprint.pprint(list(ds.field_dependencies[("gas", "temperature")].keys()))
[('gamer', 'Dens'),
('gas', 'frame_density'),
('gamer', 'MomX'),
('gas', 'momentum_density_x'),
('gamer', 'Temp'),
('gas', 'four_velocity_x'),
('gamer', 'MomY'),
('gas', 'momentum_density_y'),
('gas', 'four_velocity_y'),
('gamer', 'MomZ'),
('gas', 'momentum_density_z'),
('gas', 'four_velocity_z'),
('gas', 'four_velocity_magnitude'),
('gas', 'lorentz_factor'),
('gas', 'density'),
('gas', 'pressure'),
('gas', 'temperature')]
```
with this PR:
```
>>> …
```

ENH: Cythonize Gamer's SRHD fields

---

.github/workflows/build-test-pytest.yaml
.pre-commit-config.yaml
setup.cfg

Python 3.10 is now available for GitHub Actions !
We might want to hold onto this PR for as long a upstream wheels are not stabilised. I think MacOS wheels for numpy are not stable yet, so I'll leave this as a draft for the time being.
Note that we still have two concurrent workflows for CI, namely `.github/workflows/build-test-pytest.yaml` and `.github/workflows/build-test.yaml`. The latter cannot be upgraded because it is based on nose, which is not compatible with Python 3.10, and never will be since it is unmaintained.
get non-image tests CI green on
glueviz has no wheels for Python 3.10 and fails to build so I'm excluding it from the "full" requirements on Python 3.10
Python 3.10 doesn't seem to be distributed by conda yet, which is blocking on windows. I do not currently know what's …

MNT: add explicit support for Python 3.10 on UNIX

---

yt/frontends/ramses/field_handlers.py

New RAMSES-RT info files contain information about the RT precision. This can be read in a backwards-compatible manner with a simple try / except.

Read new RAMSES info_rt format (compatible with old)

---

tests/tests.yaml
yt/utilities/answer_testing/framework.py
yt/visualization/base_plot_types.py

fix #3632
Running the script therein I get:
I expect this to fail CI because we surely have a couple images whose size is going to change, and unfortunately I don't think our testing infra is currently able to manage this properly (see #3602)

BUG: fix figure layout in case the long axis is vertical

---

.github/workflows/wheels.yaml

main difference: not building the repo in place before running cibuildwheels fixes the issue we had with musllinux wheels and reenable them.
The cost is that wheels take a bit longer to build on Linux (about an hour VS 20min), but this seems reasonable, especially given that an hour is also the typical time needed to complete the job on Windows, so it doesn't really affect the duration of a given run.

REL: update cibuildwheel, simplify wheel building workflow

---

.github/workflows/build-test-pytest.yaml
setup.cfg

Manual backport because of a couple conflicts, actually easy to resolve.

Backport #3543 to yt-4.0.x (MNT: add explicit support for Python 3.10 on UNIX)

---

.github/workflows/wheels.yaml

Manual backport because of a conflict (Python 3.6 is still supported on the 4.0.x branch)

Backport PR #3715 to yt-4.0.x (REL: update cibuildwheel, simplify wheel building workflow)

---

setup.cfg
tests/windows_conda_requirements.txt

Fix #3712
replaces #3713
Rationale:
I changed my mind about protective version capping after reading this blog post
https://iscinumpy.dev/post/bound-version-constraints/
Essentially, the reason why we're currently capping matplotlib (<3.6) is that we're used to seeing breaking changes in with every matplotlib minor release,
occasionally nasty ones (like the time matplotlib broke yt by erroring on colliding colormap names, see for instance https://github.com/yt-project/yt/issues/3165), _but_ there was always the possibility to fix these problems on the user side by downgrading matplotlib.
The problem with that approach is that by setting upper limits in advance, we just make users unable to use future versions of our dependencies, even when they would probably be fine, and there is no easy …

REL: drop overly protective version upper limits for hard dependencies

---

setup.cfg

problem resolved upstream, see
https://github.com/glue-viz/glue/issues/2257

MNT: readd glueviz to [full] env (optional deps) on Python 3.10 following the release of glue-core 1.2.3

---

setup.cfg
tests/windows_conda_requirements.txt

Backport PR #3721 (REL: drop overly protective version upper limits for hard dependencies)

---

nose_unit.cfg
tests/tests.yaml
yt/visualization/plot_window.py
yt/visualization/tests/test_normal_plot_api.py

fix #3722
Opening as a draft to make sure that CI stays green with existing tests, but I want to add the test cases from #3722 + tests for deprecations too
Note that the regression fixed here is on the main branch only so this doesn't need backporting.

BUG: fix a regression in SlicePlot and ProjectionPlot APIs

---

conftest.py
tests/cartopy_requirements.txt
tests/ci_install.sh
tests/windows_conda_requirements.txt
yt/visualization/base_plot_types.py

Fix #3705 using the relevant bits of #3706
I'm cleaning a bunch of temporary measures that were recently taken to mitigate incompatibility issues, but the main patch, which consist in setting `extent=None`, was suggested by @greglucas, who I kindly invite to review this PR, particularly yt/visualization/base_plot_types.py

BUG: restore compatibility with latest version of cartopy (0.20)

---

conftest.py
tests/ci_install.sh
yt/visualization/tests/test_normal_plot_api.py

Hopefully this bandaid will fix CI for now. When new releases of xarray and mpi4py are issues, this can be reverted/

MNT: mitigate CI instabilities

---

conftest.py
yt/utilities/answer_testing/framework.py

Attempt at fixing #3742
For now I'm just disabling astropy altogether, but a better solution would be prefered, I'm just not sure there's anything we can do about it on our side (other than pinning `numpy < 1.22`)

TST: fix compatibility with numpy 1.22

---

yt/visualization/plot_modifications.py

BUG: fix a bug in masking invalid values in line integral convolution callback

---

yt/visualization/plot_window.py
yt/visualization/tests/test_normal_plot_api.py

Fix #3736 
Incidentally add support for array-like normal arguments in (AxisAligned)ProjectionPlot

BUG: fix a regression in (AxisAligned)SlicePlot's API

---

setup.cfg

Alternative PR to #3748
If CI passes and doesn't take forever here I'll simply close the revert PR

BUG: ratarmount is broken on MacOS + Python 3.10, making this optional dep linux-only in test envs

---

.github/workflows/build-test-pytest.yaml
yt/testing.py
yt/visualization/tests/test_geo_projections.py

Complements #3543.
I've been testing this on my fork and I believe it is now ready.
I was also able to remove the pinning added in #3298 since [upstream issue](https://github.com/SciTools/cartopy/issues/1140) was resolved.
As a temporary measure I'm conditionally skipping the one test that fails with cartopy 0.20 (reported as https://github.com/yt-project/yt/issues/3705) because I don't think it is bad enough to prevent us from testing on windows + Python 3.10, the issue is linked in the test code. I assume the regression is actually upstream and should be reported there.

MNT: Add explicit support for Python 3.10 on windows

---

yt/fields/derived_field.py

Similar to #3282 and #3637, this time for volume rendering.
We might want to refactor this someday to avoid fixing the same mistake 3 times.

BUG: fix a typesetting bug with fractionnal units in colorbar labels for volume rendering

---

setup.cfg

An alternative solution to (currently failing) #3759
The problem appeared here:
https://github.com/yt-project/yt/runs/4969817599?check_suite_focus=true
and is caused by a new warning emitted on Python 3.10 with the latest version of glue-core released yesterday (https://pypi.org/project/glue-core/1.2.4/)
The issue is reported upstream  glue-viz/glue#2263, and a fix looks to be underway https://github.com/glue-viz/glue/pull/2264

TST: add a constraint to avoid latest glue-core version in CI

---

conftest.py
setup.cfg
tests/cartopy_requirements.txt
tests/ci_install.sh
tests/windows_conda_requirements.txt
yt/utilities/answer_testing/framework.py
yt/visualization/base_plot_types.py

In support to #3765, and in prep for the 4.0.2 release
Manual backports for the following PRs
- #3708
- #3733
- #3743
- #3760
all of which are focused on stabilizing CI

REL: manual backports to yt-4.0.x for stability

---

.github/workflows/bleeding-edge.yaml
yt/fields/tests/test_ambiguous_fields.py

Fix #3775, based on pytest's documentation https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests

TST: update tests using deprecated pytest api

---

tests/ci_install.sh

This reverts a temporary patch that was introduced in #3187, and closes #3189
I've checked on my fork that updating homebrew isn't necessary anymore and skipping it shaves off ~5 min off MacOS tests jobs.

TST: don't update homebrew on MacOS CI (revert #3187)

---

yt/fields/field_info_container.py

The string to denote the error message seems to not be formatted here:
https://github.com/yt-project/yt/blob/23e65e19700b3892bdabea0d918b8274fb8aa1ff/yt/fields/field_info_container.py#L295
which gives the output:
```py
ValueError: ('Invalid sampling type %s. Valid sampling types are %s', 'discrete', 'cell, particle, local')
```
if an incorrect `sampling_type` is input to the `@yt.derived_field` decorator.
This small change formats the string to get a, hopefully, better output.
Thanks!

Format error string

---

yt/frontends/enzo/data_structures.py

This was implemented 11yrs ago, when Python 2 was obviously still a thing. It looks like a way to selectively inherit a cool `__new__` method from `object`, but this is redundant in Python 3 where all classes inherit from `object`.

ENH: cleanup legacy Python, now noop, __new__ method

---

yt/visualization/volume_rendering/tests/test_off_axis_SPH.py

Fix a deprecation warning from [scipy 1.8](https://github.com/scipy/scipy/releases/tag/v1.8.0) that's breaking CI.
The warning reads as follow:
```
E       DeprecationWarning: Please use `maximum_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
```
it can be reproduced using SciPy 1.8 and running
```
pytest yt/visualization/volume_rendering/tests/test_off_axis_SPH.py::test_center_3
```

TST: fix a deprecation warning from scipy 1.8

---

yt/utilities/lib/pixelization_routines.pyx
yt/visualization/volume_rendering/tests/test_off_axis_SPH.py

Fix #3781
I found that the actual problem was that the jumps in r and theta were constrained only by `dx` (horizontal pixel size) when they needed to be constained by `dy` too.
Using a variation of the script from the issue to show the change
```python
import yt
shape = (32, 64, 1)
a = np.linspace(0, 1, 64)
b = np.ones((32, 64))
c = np.reshape(a*b, shape)
data = {("gas", "density"): c}
theta_min = np.pi / 2 - 0.1
data,
shape,
bbox=np.array([[0.5, 5.0], [theta_min, theta_min+0.1], [-0.1, +0.1]]),
geometry="spherical",
)
yt.SlicePlot(ds, "phi", "density").save("/tmp/")
```
on the main branch
this branch

BUG: fix pixelize_cylinder

---

yt/geometry/particle_oct_container.pyx

This PR fixes a bug where __fill_refined_ranges in ParticleBitmap was returning the total number of refined cells for a coarse cell instead of the number of new refined cells. This bug caused coarse cells to be marked as fully refined on subsequent passes and so they were not actually refined and resulted in some files not being identified as selected, particularly for selectors that rely on the refined index (e.g. slice selector).
This fixes #3672

Fix bug in bitmap index for particle datasets

---

README.md

We forgot to update this version string for yt 4.0.2, now the badge displays support for Python 3.6 to 3.9 (it should be 3.6 to 3.10). On second thought I don't think it's worth pinning there because ultimately it's just one more mistake we can make in the release process, so I'm going for the easy fix here that can be safely backported for 4.0.3 as is

DOC: don't pin a specific yt version in a badge that appears on PyPI

---

yt/utilities/lib/pixelization_routines.pyx

Welp, that was easy.
Fix #3794
Just to make it flagrant I'll make an even more drastic version of the script therein
```python
import yt
shape = (32, 16, 1)
a = np.linspace(1, 100, 16)
b = np.ones((32, 16))
c = np.reshape(a * b, shape)
data = {("gas", "density"): c}
data,
shape,
bbox=np.array([[0.0, 5.0], [np.pi / 2 - 0.2, np.pi / 2 + 0.2], [-0.1, +0.1]]),
geometry="spherical",
)
p = yt.SlicePlot(ds, "phi", "density")
p.save("/tmp/buff_default.png")
p.set_buff_size((10, 800))
p.save("/tmp/buff_10_800.png")
p.set_buff_size((10, 10))
p.save("/tmp/buff_10_10.png")
```

BUG: fix a bug in pixelize_cylinder where buffer shape was read backwards

---

yt/visualization/plot_window.py

This is a proposal to close #3170 by adding a version check for MPL so that the "hack" introduced in #3161 is only applied when strictly necessary (with matplotlib from 3.3 to 3.4)
Taking the example from the original issue #2890 for reference
```python
import yt
ds = yt.load_sample("FIRE_M12i_ref11/snapshot_600.hdf5")
yt.ProjectionPlot(ds, "x", ("gas", "density")).save()
```
Here are the results:
(the one difference is that minor colorbar ticks are drawn, due to unrelated changes upstream)
So my main motivation here is to make it clear when (if) we can drop the hack introduced in #3161 in the future, but
I also think the behaviour observed with this patch + Matplotlib 3.5 is more desirable from the user's standpoint.
I acknowledged that a counter argument would be that the current …

BUG: add missing MPL version check to a temporary hack introduced in #3161

---

yt/frontends/ramses/data_structures.py
yt/frontends/ramses/definitions.py

This adresses the surface problem reported in #3800, i.e., I'm demystifying errors raised by `RAMSESDataset` at validation time
```python
from yt.frontends.ramses.api import RAMSESDataset
RAMSESDataset("not_a_file")
```
On main
```python-traceback
ValueError: ('Invalid filename found when building a RAMSESDataset object: %s', 'not_a_file')
```
This branch
```python-traceback
FileNotFoundError: No such file or directory '/Users/robcleme/dev/yt-project/yt/not_a_file'
```
```python
import os
from yt.frontends.ramses.api import RAMSESDataset
RAMSESDataset(os.path.expanduser("~"))
```
On main
```python-traceback
ValueError: ('Invalid filename found when building a RAMSESDataset object: %s', '/Users/robcleme')
```
This branch
```python-traceback
ValueError: Could not determine output directory …
```

BUG: fix error messages in RAMSESDataset validation

---

yt/data_objects/image_array.py

This deprecation warning was written before we had a proper deprecation cycle policy, this makes it more explicit and more discoverable for maintainers.

DEPR: add missing (since/removal) info to a deprecation warning

---

yt/__init__.py
yt/testing.py

fix #3771
Opening as a draft because this will surely break CI until I refactor a couple imports

DEPR: deprecate yt.testing.run_nose and wrap it in the yt namespace

---

MANIFEST.in
pyproject.toml

Add an empty marker file that's required by type-checkers declare our inline-type annotations
This is necessary to make downstream type-checking able to rely on existing annotations in yt.
See
https://mypy.readthedocs.io/en/latest/installed_packages.html#creating-pep-561-compatible-packages
as an example here's how adding this file changes Mypy's report for https://github.com/neutrinoceros/yt_idefix
with main
```
yt_idefix/fields.py:1: error: Skipping analyzing "yt.fields.field_info_container": module is installed, but missing library stubs or py.typed marker
yt_idefix/fields.py:2: error: Skipping analyzing "yt.fields.magnetic_field": module is installed, but missing library stubs or py.typed marker
yt_idefix/io.py:6: error: Skipping analyzing "yt.utilities.io_handler": module is …
```

TYP: add py.typed marker file to improve downstream type-checking

---

.github/workflows/wheels.yaml
.pre-commit-config.yaml

We've been polishing this workflow on yt-astro-analysis and it's now working correctly so here's the port back to yt itself.
This workflow requires that a secret named "PYPI_TOKEN" be added to the repo (the name is arbitrary, that's just the name we've been using for yt-astro), this can be done by a PyPI maintainer.

REL: automate wheels publication to PyPI

---

.gitignore
doc/source/developing/creating_frontend.rst
doc/source/examining/Loading_Generic_Array_Data.ipynb
tests/tests.yaml
yt/data_objects/static_output.py
yt/fields/fluid_fields.py
yt/fields/tests/test_magnetic_fields.py
yt/frontends/_skeleton/data_structures.py
yt/frontends/athena_pp/tests/test_outputs.py
yt/frontends/boxlib/tests/test_outputs.py
yt/frontends/flash/tests/test_outputs.py
yt/frontends/stream/data_structures.py
yt/frontends/ytdata/data_structures.py
yt/units/tests/test_magnetic_code_units.py
yt/visualization/fits_image.py

(this is an attempt to do better than PR #3787)
Electromagnetic unit conversions in yt are complex. The reasons for this are:
* `unyt` uses MKSA as the base set of units, but `yt` assumes Gaussian CGS units by default
* MKSA has a fundamental unit for current, Ampere, which becomes a component unit of most electromagnetic units (e.g. Coulomb, Tesla, etc.)
* Gaussian CGS units do not have a fundamental unit of current, defining all electromagnetic quantities in terms of mass, length, and time units
This is described in more detail [here](https://ytep.readthedocs.io/en/master/YTEPs/YTEP-0028.html#special-handling-for-magnetic-fields). 
Some frontends assume Gaussian CGS EM units as the code units, and a few assume MKSA EM units for the code units. However, regardless of what one assumes, it …

Fix electromagnetic unit conversions (second try)

---

.github/workflows/wheels.yaml
.gitignore
.pre-commit-config.yaml
doc/source/developing/creating_frontend.rst
doc/source/developing/deprecating_features.rst
doc/source/examining/Loading_Generic_Array_Data.ipynb
setup.cfg
tests/tests.yaml
yt/data_objects/static_output.py
yt/fields/derived_field.py
yt/fields/field_info_container.py
yt/fields/fluid_fields.py
yt/fields/tests/test_ambiguous_fields.py
yt/fields/tests/test_magnetic_fields.py
yt/frontends/_skeleton/data_structures.py
yt/frontends/athena_pp/tests/test_outputs.py
yt/frontends/boxlib/tests/test_outputs.py
yt/frontends/flash/tests/test_outputs.py
yt/frontends/ramses/data_structures.py
yt/frontends/stream/data_structures.py
yt/frontends/ytdata/data_structures.py
yt/units/tests/test_magnetic_code_units.py
yt/utilities/lib/pixelization_routines.pyx
yt/visualization/fits_image.py
yt/visualization/plot_modifications.py
yt/visualization/volume_rendering/tests/test_off_axis_SPH.py

In support to the newly created 4.0.3 milestone https://github.com/yt-project/yt/milestone/19
This bundles manual backports for recent CI blockers
- #3770
- #3776 
- #3783
as well as a couple bugfix PRs that were merged since 4.0.2 was frozen
- #3780
- #3782 
- #3739 
- #3755
- #3786
- #3805
Also including #3758 which is supposed to be used to ease the release process itself.

Manual backports to yt-4.0.x (blockers and bugfixes)

---

yt/frontends/art/data_structures.py
yt/frontends/boxlib/data_structures.py
yt/frontends/boxlib/io.py
yt/frontends/owls/fields.py
yt/utilities/grid_data_format/conversion/conversion_athena.py

fix #3802
In many cases, using pathlib instead of os.path would help readability but it would also create a bigger diff and would take more time to implement and review, so I'm keeping a conservative approach here.

BUG: fixup POSIX-only path handling that can easily be made cross-platform

---

tests/tests.yaml
yt/frontends/arepo/data_structures.py
yt/frontends/arepo/fields.py
yt/frontends/arepo/tests/test_outputs.py
yt/sample_data_registry.json

* Alias the `("PartType0","pressure")` field to `("gas","pressure")` (not sure why this wasn't already one
* Create a `"cell_volume"` field
* Create a `"cosmic_ray_pressure"` field
* Rename `"cr_energy_density"` and `"specific_cr_energy"` to `"cosmic_ray_energy_density"` and `"specific_cosmic_ray_energy"`

Add three new derived fields to the AREPO frontend

---

doc/source/examining/loading_data.rst
yt/fields/magnetic_field.py
yt/frontends/athena/data_structures.py
yt/frontends/athena/tests/test_outputs.py
yt/frontends/athena_pp/data_structures.py
yt/frontends/athena_pp/tests/test_outputs.py

We've been having lots of fun with EM units, so let's have some more!
The relationship between the magnetic field strength and other related quantities, such as magnetic pressure and Alfvén speed, depends on what units are chosen for the magnetic field. For example, the magnetic pressure in CGS is:
but in SI/MKSA units it is:
We already take care of both of these cases in yt. However, the CGS convention above is known as the "Gaussian" convention, whereas in many MHD simulations and in some physics areas (such as particle physics/GR) it is more common to use the "Lorentz-Heaviside" convention, which is:
This was requested in issue #3471 for Athena datasets. This PR addresses that issue by allowing Athena/Athena++ datasets to set the factor for magnetic units in CGS, and then this needs …

Allow for different normalizations of magnetic fields in CGS

---

doc/source/visualizing/callbacks.rst
yt/visualization/plot_modifications.py

Improve wrapping around `matplotlib.axes.Axes.quiver`'s complicated signature to enable the optional 5th positional argument `C`.
I'm also refactoring `QuiverCallback` and `CuttingQuiverCallback` to avoid duplicating code as much as possible.
A 'bonus' change here is that I'm allowing arbitary keyword arguments to be passed down to the wrapped method, because it's much more intuitive to pass `cmap="inferno"` than `plot_args=dict(cmap="inferno")`. If requested I can remove this from the PR and possibly repurpose it as a new PR, making similar changes to all callbacks that allow it (i.e. the ones that have only one such dictionary argument)
Another bonus is that I fixed a small bug with the `normalize` bool flag where users would get a divide-by-zero warning when using normalisation for a …

ENH: add support for varying colors in quiver annotations

---

setup.cfg
yt/config.py

Fix #3830. Possibly not exactly the correct approach right now (I'm adding a conditional branch for Python 3.11 before it even has the feature implemented), but I'd like to see if this naive approach survives CI.

MNT: migrate from toml to tomli + tomli_w

---

setup.cfg

Context: sympy 1.9 broke unpickling of unyt_array instance that were pickled with older versions (https://github.com/sympy/sympy/issues/22241)
Sympy 1.10 was released yesterday but unfortunately the fix it shipped didn't completely resolve the problem. Now we have good reasons to think the next release will be usable again in yt's CI (see discussion upstream), but for now we need a hotfix to stabilize tests.
Because this issue is purely with our testing framework and infrastructure, I'm moving these constraints away from `install_requires` since we don't want our need to constraint users.
Also note that I'm removing the `>=1.2` constraint since it's already imposed by unyt itself and we don't actually use sympy directly in yt.

TST: add constraint to forbid sympy 1.10.0 in tests

---

yt/frontends/ramses/io.py

With recent version of RAMSES, which field are present on-disk is documented by a side-car file named `hydro_file_descriptor.txt` which lists which field is which.
Confusingly, yt expects variables to use the old yt convention (e.g. `HII` is ionized hydrogen), while RAMSES moved to follow yt's convention in `hydro_file_descriptor.txt`! The long-term solution would be to migrate everything to yt's convention (`H_p1_fraction` for example) but it would require refactoring a lot of code in the RAMSES frontend.
Instead, I map here the variables read from the file descriptor to the "old" convention used throughout the RAMSES handler, which then maps back to the new yt convention... In other words, yt reads that the n-th variable is `H_p1_fraction`, it reads it into `("ramses", "HII")` which is …

Add missing ionized species

---

yt/geometry/coordinates/coordinate_handler.py
yt/geometry/coordinates/cylindrical_coordinates.py
yt/geometry/coordinates/spherical_coordinates.py
yt/visualization/plot_window.py

Reutilizing some bits from #3533, fix #3819
Opening as a draft because there's a secondary problem to solve. Namely, axes ticks are incorrect (0, 0) should always be the origin, not the display center
```python
import yt
from yt.testing import fake_amr_ds, add_noise_fields
shape = (32, 64, 128)
{},
shape,
bbox=np.array([[1, 5], [0.1, np.pi / 2 - 0.1], [0, 1]]),
geometry="polar",
)
add_noise_fields(ds)
p = yt.SlicePlot(ds, "z", "noise1")
p.save("/tmp/")
```

BUG: fix plot bounds for slices in cylindrical coordinates

---

doc/source/cookbook/render_two_fields_tf.py

remove unneeded logs using private API

---

setup.cfg

Some deprecated features were removed in jinja2==3.1.0.
For details see e.g. https://github.com/pallets/jinja/issues/1626 and
https://github.com/readthedocs/readthedocs.org/issues/9037
We should probably update sphinx instead, but that breaks other
things...

Pin jinja2 for docs build

---

yt/frontends/ramses/fields.py
yt/frontends/ramses/io.py

Fix definition of particle age/times

---

yt/visualization/plot_modifications.py
yt/visualization/tests/test_callbacks.py

Fix #3869
Turns out that the custom error reraising introduced in #2728 is apparently not necessary since #3618, and combining both created a regression
```python
import yt
from yt.testing import fake_random_ds
ds = fake_random_ds(64, unit_system="code")
p = yt.SlicePlot(ds,"x",("gas", "density"))
p.annotate_timestamp(draw_inset_box=True)
p.save("timestamp.png")
```

BUG: fix a regression where calling annotate_timestamp on a plot from a dataset with code units would crash

---

setup.cfg

Follow up to the discussion in #3830, let's experiment with making IPython actually optional as a dependency.
I expect CI could fail at first because we haven't been using on_demand_import.py for IPython.
I note that there's also something weird with yaml support, where we currently require `pyyaml` in `install_deps` but `pyyaml` in the optional `full` environment.

MNT: remove pyyaml and IPython from install_requires as they are both de facto optional dependencies

---

CONTRIBUTING.rst

This is aimed at fixing #2554
what's missing still is a link to the document where we define the number of reviews needed for all kinds of PRs, because I couldn't find it back.
Keeping this as a draft until then

DOC: update contribution guidelines

---

yt/frontends/owls/fields.py

The `("PartType0","El_number_density")` field function in the OWLS frontend is not returning a value. This fixes that.
Fixes issue #3838.

OWLS Electron number density field should return a value

---

yt/frontends/ramses/data_structures.py
yt/frontends/ramses/tests/test_outputs.py

Fix for #3867.
Use `cm_per_mpc` instead of 3.08e24 for conversion from Mpc to cm. Also partly addresses #2098:
```
ds = yt.load('output_00080/info_00080.txt')
tA = ds.current_time.to('Myr')
tB = ds.cosmology.t_from_z(ds.current_redshift).to('Myr')
print(tA-tB)
```
where `tA-tB` is now `-0.5628994599301222 Myr` where it was `-22.47323433951169 Myr`.

BUG: Use cm_per_mpc instead of 3.08e24 #3867

---

yt/data_objects/selection_objects/data_selection_objects.py
yt/visualization/particle_plots.py
yt/visualization/plot_window.py

fix #3862 by moving the responsibility of switching to `origin="native"` from `AxisAlignedSlicePlot` an `AxisAlignedProjectionPlot` to `PlotWindow`. Note that I'm not making any change to `OffAxis...Plot` classes, because they don't have support for non-cartesian geometries anyway, and they also don't expose the origin keyword argument.

BUG: fix a bug where PlotWindow origin parameter wasn't handled correctly in non-cartesian geometries

---

conftest.py
tests/tests.yaml
yt/geometry/coordinates/cartesian_coordinates.py
yt/geometry/coordinates/cylindrical_coordinates.py
yt/geometry/coordinates/geographic_coordinates.py
yt/utilities/lib/pixelization_routines.pyx
yt/visualization/tests/test_offaxisprojection.py

Goal: fix #3854
Applying the patch from the issue. Let's see what image tests fail.

BUG: fix buffer masking in cartesian geometry

---

.pre-commit-config.yaml
conftest.py

CI is currently broken by a deprecation warning emmitted from Pillow via Matplotlib, that we have no control over, so let's just filter it.
See https://github.com/matplotlib/matplotlib/pull/22766 for context

TST: workaround upstream instabilities

---

nose_unit.cfg
tests/tests.yaml
yt/frontends/ramses/data_structures.py
yt/frontends/ramses/definitions.py
yt/frontends/ramses/tests/test_file_sanitizer.py

This brings back support to RAMSES folder structures like `output_XXXXX/group_YYYYY`. Fixes #3785.
In particular, the output number should be read off the `XXXXX` part, not the `YYYYY` part.
Note: I have tested the bugfix on a (massive) simulation with the following script. Unfortunately, we do not have any simulation dataset with the group structure on yt-data so testing would imply more work that I can reasonably put
```python
import yt
yt.mylog.setLevel(40)
eps = 0.0001
bbox = [[0.5-eps]*3, [0.5+eps]*3]
def test_me(path):
print(f"Testing {path=}")
ds = yt.load(path, bbox=bbox)
ds.index
assert len(ds.index.domains) > 0
ds.r["density"]
ds.r["DM", "particle_identity"]
test_me("/data84/obelisk/RHD/OUTPUT_DIR/output_00075")
test_me("/data84/obelisk/RHD/OUTPUT_DIR/output_00075/group_00001/") …
```

BUG: bring back support to group folder structure in RAMSES

---

tests/tests.yaml
yt/utilities/lib/pixelization_routines.pyx

This fixes an issue with the cylindrical pixelizer routine discovered in #3817, where pixels that are not completely within the data domain.
Although a bug fix, I don't think this change is really important before #3817 is merged, so I think this can go to the next feature relase and not be backported.
I'll demonstrate the change using the script from #3817
opening as a draft because this branch is based on #3817 for testing purposes

BUG: don't colorize pixels that are not completely within the data domain in pixelize_cylinder routine

---

yt/frontends/gadget/data_structures.py

This fixes an issue where some Gadget2 files can't be loaded because their names aren't compatible with the filename template we have.
This problem was reported on Slack by @Gustav-Madsen. Here's an example dataset to test this on http://skun.iaa.es/SUsimulations/UchuuDR1/ShinUchuu/SamplingParticle/snapdir_070/
I was able to make a simple plot of this dataset, only downloading the first 3 files
```python
import yt
ds = yt.load("snapdir_070")
yt.ParticleProjectionPlot(ds, "z", ("all", "Mass")).save("/tmp/")
```

BUG: fix compatibility with gadget 2 files using '*.gad.*' template

---

.github/workflows/wheels.yaml

Simple one line patch so we can use the current version of cibuildwheel for our next release
the one patch that I think is relevant to us is: https://github.com/pypa/cibuildwheel/pull/975
see complete release notes : https://github.com/pypa/cibuildwheel/releases
A test job is running on my fork for this branch: https://github.com/neutrinoceros/yt/actions/runs/2140271185

REL: upgrade cuilbuildwheel (2.3.0 -> 2.4.0)

---

yt/visualization/color_maps.py

Fix #3911
Since matplotlib 3.6 is likely to be available before yt 4.1.0, we should consider backporting this to 4.0.x

BUG: fix an upcoming incompatibility with matplotlib 3.6

---

.tours/particle-indexing.tour
yt/geometry/particle_geometry_handler.py

This is a follow up to #3816 where I missed a break statement, which can lead to an `UnboundLocalError` being raised, as noted by @Gustav-Madsen on Slack.

BUG: fix an UnboundLocalError

---

yt/utilities/exceptions.py

I noticed a couple error messages were still refering to stuff that has been deprecated and removed.
While making sure I got all of them, I made some consistency improvements to most YTException messages.
Mostly, I'm using the `!r` formatter to ensure consistent quoting for strings instead of hardcoded quotation marks.
Specifically `f"{a!r}"` is equivalent to `repr(a)` while `f"{a}"` (or `f"{a!s}"`) is equivalent to `str(a)`

RFC: improve formatting consistency in YTException error messages

---

yt/data_objects/static_output.py
yt/fields/field_info_container.py
yt/fields/local_fields.py

A couple fixes for this method. Most importantly fixes some broken leftovers from https://github.com/yt-project/yt/pull/3240
- BUG: fix a broken internal function call
- ENH: clarify FieldInfoContainer.add_field's signature (add missing force_override kwarg)
- ENH: avoid confusing exception chaining in sanitizer method
The bug this fixes isn't present on the backport branch so this gets triaged to 4.1

BUG: fixup FieldInfoContainer.add_field

---

yt/visualization/volume_rendering/transfer_function_helper.py

Simple cleanup for dead code bits
For reference, we currently support MPL>=2.2.3
There are other similar workarounds to cleanup but AFAICT they are all dealt with in #3849 so I'll avoid doing it here too.

MNT: cleanup unused workarounds for unsupported version of MPL

---

nose_unit.cfg
setup.cfg
setup.py
tests/tests.yaml
yt/__init__.py
yt/_version.py
yt/tests/test_version.py

fix #3761
As mentionned in the issue, I'm waiting/hoping for the discussion upstream to settle on a shared convention for the name of this attribute, which is why I'm opening this as a draft.
I'll also need to add a paragraph of documentation somewhere.

ENH: add a yt.version_info named tuple to ease version comparison downstream

---

yt/__init__.py
yt/config.py
yt/data_objects/data_containers.py
yt/data_objects/index_subobjects/grid_patch.py
yt/data_objects/static_output.py
yt/fields/tests/test_fields_plugins.py
yt/frontends/ramses/definitions.py
yt/funcs.py
yt/mods.py
yt/sample_data/api.py
yt/utilities/command_line.py
yt/utilities/configure.py
yt/utilities/logger.py
yt/utilities/parallel_tools/parallel_analysis_interface.py
yt/utilities/tests/test_config.py
yt/visualization/volume_rendering/render_source.py

This patch postpones the "live" part of the configuration to the very end of `yt.__init__` and disentangle the configuration code a bit. This is achieved by
- never importing yt.config at the top of any module. Import statements are relocated to inside functions that need to access the global `yt.config.ytcfg` object. This is in line with the existing practice in the `yt.funcs` module
- making yt.config depend on yt.utilities.configure (instead of the other way around). This means a sizeable part of the diff here is simply due to relocating the `YTConfig` class
- adding a small callback system in `yt.utilities.configure`, allowing any module to perform configuration at runtime, but delaying it until `yt.config` is imported from for the first time (in `yt.__init__`)
The first commit fixes …

RFC: decouple yt.config from initialization

---

CONTRIBUTING.rst

The link to the re-licensing blog post wasn't quite right and 404s. Updating to the correct link.

updating link to re-licensing blog post

---

setup.cfg

Hopefully fixes:
```
Building wheels for collected packages: yt
Building wheel for yt (pyproject.toml): started
Building wheel for yt (pyproject.toml): finished with status 'done'
Created wheel for yt: filename=yt-4.1.dev0.._.keep.in.sync.with.yt_version._version_-cp38-cp38-linux_x86_64.whl size=14904256 sha256=541f863de95e286b2b1715bb05e42af01bf9907e929fa58e03e8231c24db28b3
Stored in directory: /tmp/pip-ephem-wheel-cache-721ymkwl/wheels/cb/e3/d4/d236de7552d18e164ff4dc42cb58a5ecaa7380e764833058b8
WARNING: Built wheel for yt is invalid: Metadata 1.2 mandates PEP 440 version, but '4.1.dev0..-.keep.in.sync.with.yt-version.-version-' is not
Failed to build yt
ERROR: Could not build wheels for yt, which is required to install pyproject.toml-based projects
Build step 'Virtualenv Builder' marked …
```

Drop a comment that was treated as a part of key=value

---

yt/data_objects/tests/test_glue.py
yt/fields/tests/test_sph_fields.py
yt/frontends/ytdata/tests/test_old_outputs.py
yt/testing.py
yt/tests/test_testing.py
yt/utilities/answer_testing/framework.py

This is a small step in trying to make the testing framework smaller in size and easier to maintain with the migration from nose to pytest in mind.
The central idea is to systematically use the `unittest.SkipTest` exception to (conditionally) skip tests, because it's supported by all frameworks.

RFC: simplify test skipper decorators

---

yt/visualization/tests/test_save.py

fix a pytest fixture that was broken in #3773
I don't know how this hasn't been caught up to now but the problem can easily be reproduced by invoking
```shell
pytest yt/visualization/tests/test_save.py
```

TST: fix a broken pytest fixture

---

yt/data_objects/static_output.py
yt/fields/field_info_container.py
yt/fields/local_fields.py

closes #3933, also fix a sibling issue introduced in #3919
- BUG: fix internal warning bleeding (partially revert https://github.com/yt-project/yt/pull/3919)
- BUG: fix an error where a warning was unreachable

BUG: fix internal warning bleeding

---

nose_unit.cfg
tests/tests.yaml
yt/testing.py
yt/utilities/on_demand_imports.py
yt/utilities/tests/test_on_demand_imports.py

My latest attempt at making on_demand_imports.py less repetitive and error prone
I expect I'll need to iterate a couple times on this.
Gains:
- developer experience: far less boilerplate required to add optional dependencies, and an overall lighter module
- user experience: no more necessary startup overhead for some optional deps (like pandas and requests) who were imported even when not used.
TODO:

RFC: encapsulate try blocks from on demand imports

---

yt/frontends/enzo_e/data_structures.py
yt/frontends/enzo_e/fields.py
yt/frontends/enzo_e/io.py
yt/frontends/enzo_e/misc.py

Enzo-E has been updated to include a new way of distinguishing whether particles are saved as masses or densities. This is done using the "mass" or "density" parameter in the parameter file. Previously, particle masses were to be considered as densities if the simulation was cosmological. To preserve backward compatibility, Enzo-E now uses an "is_gravitating" group name that I use to tell if the data was produced before or after this change.

ENH: Update Enzo-E particle mass/density distinction

---

doc/source/cookbook/yt_gadget_analysis.ipynb

This fixes a typo in the Gadget notebook (and thus in the Gadget cookbook) where we create a new object, `ad2`, and then say we will use it, but we *don't*.  Thanks to @EwanBJones98 for spotting it and letting me know!

DOC: Fix typo in Gadget notebook

---

yt/utilities/configure.py

Fix #3952
I don't know how to write an isolated test for this since it involves importing yt

BUG: gracefully recover in case of invalid TOML file

---

yt/visualization/plot_modifications.py

Seems to me that the base `PlotCallback` class is abstract in all but name, let's make it explicit.

ENH: make PlotCallback an abstract class

---

nose_unit.cfg
tests/tests.yaml
yt/data_objects/selection_objects/data_selection_objects.py
yt/data_objects/tests/test_add_field.py
yt/fields/derived_field.py
yt/fields/field_detector.py
yt/fields/field_info_container.py
yt/fields/tests/test_fields.py
yt/frontends/amrvac/fields.py
yt/frontends/ramses/tests/test_outputs.py
yt/visualization/volume_rendering/off_axis_projection.py
yt/visualization/volume_rendering/old_camera.py

This makes life easier for clumsy users like myself who can never remember what argument goes first in a derived field function, so you get a clear error message instead of whatever happens when the malformed function gets called with reversed arguments. Incidentally adds support and tests for passing arbitrary callables as the `function` argument.
edit: I also reworked the way `units="auto"` works to make the `dimensions` argument optional even in that case. This is an opinionated change but I think it's reasonable as long as a warning is displayed when needed.

ENH: improve error messages when add_field receives a malformed function argument

---

conftest.py
pyproject.toml
setup.cfg
setupext.py

- remove unused optional `toml-types` dep (not needed since https://github.com/yt-project/yt/pull/3831)
- remove unused temporary warning filter in `conftest.py` (the simple fact that test pass validate that we don't need it anymore)
- partial migration away from distutils (see #3384): 
- `logging` is the official recommended replacement for `disutils.log`[source](https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html?highlight=distutils#prefer-setuptools)
- `distutils.errors` is re-exported within `setuptools.errors` since `setuptools 59.0.0` (see https://github.com/pypa/setuptools/pull/2858)
- remove `setuptools` from runtime dependency (this is a left over from an old misunderstanding: setuptools was in fact never a runtime dependency)

MNT: housekeeping

---

.github/workflows/wheels.yaml

In #3951 I cleaned up setup.cfg where setuptools was incorrectly declared as a runtime dependency, but this broke the wheel build CI job which was (also incorrectly) relying on this.
This should fix it

BUG: explicitly install setuptools in check-manifest test env

---

doc/source/visualizing/plots.rst

The swap/flip keyword arguments were removed in favor of callbacks-only during development of #3640, looks like the corresponding docs were not updated to reflect that.

BUG: cleanup swap/flip docs

---

yt/frontends/enzo_e/data_structures.py

This fixes a bug where the `sample_pfields` attribute on the io handler wasn't getting set for all non-root processes. This only comes up when querying particle fields in parallel.

Broadcast missing attribute

---

yt/visualization/fixed_resolution.py
yt/visualization/fixed_resolution_filters.py
yt/visualization/plot_container.py
yt/visualization/plot_modifications.py
yt/visualization/plot_window.py
yt/visualization/tests/test_callbacks.py

Fix #3945
Right now this is a proof of concept, there's still work to do, but I think it's promising so I'm opening to see how many tests are currently broken.
It should backwards compatible, and retain compatibility with externally defined plot callbacks (such as `HaloCatalogCallback` from `yt_astro_analysis`).
If I can manage to get it 100% complete while keeping a reasonable diff size, I'll propose this for yt 4.1
Note: I ended up cleaning up a lot of signatures in `PlotCallback` subclasses `__init__` methods (making most arguments keyword only). This change is technically not backward compatible. It is motivated by future compatibility concerns: some arguments are already deprecated, but sometimes occupy early positions, so there is *no* way to actually remove them in the future …

RFC: refactor plot callbacks registration

---

yt/data_objects/construction_data_containers.py

Fix #3941
There are a dozen deprecation warnings in `plot_modifications.py` that are currently impossible to fix because of how plot callbacks' init is delayed until the plot is actually setup.
I'll see if I can refactor this slightly so we at least validate arguments when they are passed.

DEPR: fix a broken deprecation warning (missing stacklevel)

---

yt/visualization/color_maps.py

These are not used anywhere. I don't think `yt.visualization.color_maps` is considered public API so I just removed them.
If anyone argues that it _is_ public (nothing actually signals privacy), I'm happy to deprecate them instead

MNT: remove 2 unused internal functions

---

yt/data_objects/image_array.py
yt/data_objects/tests/test_image_array.py
yt/visualization/volume_rendering/scene.py
yt/visualization/volume_rendering/tests/test_save_render.py

This closes #3979 and fixes an unreported bug in which not providing a `sigma_clip` value while trying to save a non-png results in a crash. 
There were several spots where `sigma_clip` was used to calculated a clipping value, the version in `save_annotated` incorrectly included the alpha channel in the calculation. I added a `ImageArray._clipping_value` method to cut down on some of the duplicate code.
Here's a script based on the cookbook example mentioned in #3979 
```python
import yt
ds = yt.load("Enzo_64/DD0043/data0043")
sc = yt.create_scene(ds, lens_type="perspective")
source = sc[0]
source.set_field(("gas", "density"))
source.set_log(True)
sc.camera.focus = ds.domain_center
sc.camera.resolution = 800
sc.camera.north_vector = [0, 0, 1]
sc.camera.position = [1.7, 1.7, 1.7] …
```

[BUG] volume rendering: sigma_clip normalization 

---

conftest.py
yt/frontends/cf_radial/data_structures.py

This switches CFRadial's `_is_valid` method to use yt's  `NetCDF4FileHandler` instead of xarray following the nc4_cm1 frontend. xarray is still used for opening and loading data after the dataset is identified as a CFRadial dataset. 
Closes #3987

[BUG] adjust CFRadial's _is_valid

---

yt/funcs.py

I encountered a ResourceWarning here while testing downstream in yt_idefix
https://github.com/neutrinoceros/yt_idefix/runs/7199942525?check_suite_focus=true

BUG: fix a ResourceWarning (file is never closed)

---

yt/frontends/enzo/answer_testing_support.py
yt/utilities/cosmology.py

This PR updates the field names to be tuples in the answer testing of the Enzo frontend. The `hubble_constant` parameter is also not necessarily always written as a float (i.e. 1), so it is read as an int, which causes problems in unyt downstream. Forcing it to be float at initialization.

ENH: Update to fields used in Enzo answer testing

---

yt/data_objects/construction_data_containers.py
yt/data_objects/tests/test_add_field.py
yt/fields/field_info_container.py
yt/fields/local_fields.py

Closes #4001 and adds a basic test to avoid this regression comes back
I found that the `derived_field` decorator was not tested at all, and the way it's implemented right now is evidently fragile, so I may attempt a refactor to make it more maintainable in the future, but for this PR I'm just focusing on getting it in a working state again.

BUG: fix a regression where @yt.derived_field decorator would crash

---

yt/data_objects/index_subobjects/grid_patch.py

The current behavior results in an error:
```
File "/home/mturk/yt/yt/yt/data_objects/index_subobjects/grid_patch.py", line 146, in __repr__                                                                                                                        return f"{cls_name}_{self.id:04i} ({self.ActiveDimensions})"                                                                                                                                                    ValueError: Unknown format code 'i' for object of type 'int'
```
This fixes that error.

BUG: Use format string 'd' not 'i' in grids

---

tests/tests.yaml
yt/frontends/boxlib/data_structures.py

Fixes #3993.
This change uses the correct index for the z dimension when setting less-than-three-dimension boundaries.
The cascading set of things that happen as a result of this include the dds[2] set to 2.0, rather than 1.0, which in the particular cases identified by @NeilZaim set our point/grid selection to exclude the underlying grid.  With this change, we correctly set the grid *cell* size to not exceed the *domain* size, and now the selection process works OK.
The reason this was caught by the specific instance identified in the reproducer script was that we called the grid selector for setting the base chunk for `ad_particles` in that script, but then used `particle_select` rather than grid select, so the cached mask was incorrect.  When using the covering grid selection, we …

BUG: Make sure Boxlib DLE/DRE are correct index

---

doc/cheatsheet.tex
doc/source/analyzing/filtering.rst
doc/source/cookbook/annotations.py
doc/source/cookbook/simple_contour_in_slice.py
doc/source/examining/loading_data.rst
doc/source/reference/api/api.rst
doc/source/visualizing/callbacks.rst
doc/source/visualizing/plots.rst
yt/visualization/plot_modifications.py

This is a follow up to https://github.com/yt-project/yt/pull/3957
fix a bunch of docs using deprecated API + fix a bug in `annotate_arrow` method where `**kwargs` were accepted, but ignored.

DOC: fixup deprecated API in docs

---

.pre-commit-config.yaml
yt/data_objects/tests/test_particle_trajectories.py
yt/data_objects/time_series.py
yt/frontends/exodus_ii/tests/test_outputs.py
yt/frontends/gadget/fields.py
yt/frontends/ramses/fields.py
yt/frontends/ramses/io.py
yt/frontends/tipsy/io.py
yt/visualization/volume_rendering/tests/test_vr_orientation.py

Follow up to #3994
Upgrade flake8-bugbear and fix newly detected gotchas: late-binding errors in closures
If, like me, you didn't know about this problem, here's a helpful blog post to explain what the problem is and its solution(s)
https://docs.python-guide.org/writing/gotchas/#late-binding-closures
Content:
- MNT: manually upgrade flake8-bugbear
- BUG: fix late-binding errors in closures, detected with flake8-bugbear (B023)
- MNT: add noqas to flase positives (B023) in generator based tests

BUG: fix late-binding errors in closures

---

yt/utilities/lib/image_samplers.pyx

Changes the octree sampler to initialize image pixel values to the initial image rather than 0 so that any already rendered sources (like points) will show up. 
The following works as expected now:
```python
import yt
from yt.units import kpc
from yt.visualization.volume_rendering.api import PointSource
ds=yt.load_sample("output_00080")  # output_00080or "ramses_star_formation" or 
sc = yt.create_scene(ds, field=("gas","density"), lens_type="perspective")
np.random.seed(1234567)
npoints = 1000
vertices = np.random.random([npoints, 3])
colors = np.ones([npoints, 4])
colors[:,3]=0.01
points = PointSource(vertices, colors=colors, radii=np.full((npoints,), 2))
sc.add_source(points)
sc.show(sigma_clip=2)
```
for reference, here is the output of the above code before this …

BUG: fix for composite volume rendering with octree sources

---

setup.cfg

For context, see https://github.com/yt-project/yt/issues/3384, and https://github.com/pypa/setuptools/issues/2806

MNT: remove upper bound for supported Python version

---

doc/source/cookbook/simple_plots.rst
doc/source/visualizing/plots.rst
yt/utilities/exceptions.py

Closes #4035
- DOC: add notes that only certain data types have support for off-axis operation
- UX: add information to error message

DOC: add notes that only certain data types have support for off-axis operation

---

yt/data_objects/construction_data_containers.py
yt/data_objects/tests/test_fluxes.py

Nominally, when one creates a `YTSurface` object using `ds.surface`, and then uses `calculate_flux` on the object to calculate a flux through the surface, if no `fluxing_field` is provided it should default to `1.0 dimensionless`. I discovered by accident today that this isn't the case--mainly because `np.ones_like` now preserves units (see code below). This is the fix for that. The test has been improved to catch it.

BUG: Fix flux calculation on surface when there is no fluxing_field

---

yt/visualization/plot_window.py

Closes #2619
Note to reviewers: I have no idea if OffAxisSlicePlot and OffAxisProjectionPlot actually work with spectral cubes, I'm not even sure it would make sense, though I don't know of a sample dataset with this geometry or how to create a fake one

ENH: improve clarity of error messages for OffAxisSlicePlot with curvilinear geometries

---

yt/fields/astro_fields.py
yt/fields/stress_energy.py
yt/fields/tensor_fields.py
yt/frontends/gamer/fields.py
yt/frontends/gamer/tests/test_outputs.py

yt has support for vector fields--but of course in some domains tensor fields are also useful. This is especially true in applications involving special relativity. 
This PR takes a first stab at adding tensor fields to yt by adding the [stress-energy tensor for a perfect fluid](https://en.wikipedia.org/wiki/Perfect_fluid), which is used by GAMER (implemented here) and Athena++ (to be implemented later). 
So for example, accessing the "T^00" component of a tensor field works like this: `dd["T00"]`, and the "T^10" would work like this: `dd["T10"]`, and so on. Have to think about how to handle raising/lowering indices (if at all) and if one wants to support other coordinates than just cartesian (harder, but doable I guess).
I expect there may be some conversation about the field naming …

Preliminary support for tensor fields

---

conftest.py
setup.cfg
yt/funcs.py
yt/sample_data/api.py
yt/utilities/png_writer.py
yt/visualization/_commons.py
yt/visualization/_mpl_imports.py
yt/visualization/color_maps.py
yt/visualization/plot_window.py
yt/visualization/profile_plotter.py

Reduce yt's import time by 35-60%
This estimation was performed using other optimizations for core dependencies (cmyt and unyt).
To be clear, I'm comparing yt's import time with and without the present patch, but I'm including cmyt and unyt optimizations in both cases.
Here's the command I've used to measure and target main offenders:
```
python -X importtime -c "import yt" 2> tuna.log && tuna tuna.log
```

ENH: reduce import time by avoiding top-level expensive imports

---

yt/data_objects/static_output.py
yt/data_objects/tests/test_add_field.py
yt/fields/field_functions.py
yt/fields/field_info_container.py
yt/fields/local_fields.py

`inspect.signature` is an expensive function
Using this simple profiling routine
```python
import yt
ds = yt.load("IsolatedGalaxy/galaxy0030/galaxy0030")
ds.r["gas", "density"]
```
```shell
python -m cProfile -o log.pstats t.py
gprof2dot --colour-nodes-by-selftime log.pstats | dot -Tsvg -o out.svg
```
I was able to measure that ~3.5% of the total runtime is spent validating field functions that are defined internally, so let's restrict its use to user-defined fields to minimise the overhead.
Follow up to #3921

ENH: only validate user-defined field functions (save inspection overhead)

---

yt/frontends/stream/data_structures.py
yt/frontends/stream/tests/test_outputs.py
yt/loaders.py

This adds the `parameters` dictionary to the `StreamHandler` so that it can be supplied as a keyword argument to all the stream loaders so that there's a convenient way to pass in metadata that is useful to have around. 
closes #4047

add parameters to StreamHandler and loaders

---

yt/data_objects/tests/test_sph_data_objects.py
yt/geometry/_selection_routines/region_selector.pxi

This PR fixes the issue raised by #3916 and seen in other contexts where sometimes particles which properly belong to a rectangular region straddling a periodic boundary would get missed. 
I think something was not quite right in the overall logic, but I have to be honest I am not certain. What I do know for sure is that instead of checking the particle position itself for particles that lay outside the boundary of a region, we should be checking the "left_edge" and "right_edge" of the particle in question (defined by the +/- the radius away from the position), and then computing the radius of the particle to the edge. That was inspired by considering the region/cell intersection implementation: 
https://github.com/yt-project/yt/blob/6c0780f0e00a6ef6ed4f40510d4570d04f7cf59a/yt/geometry/_se …

BUG: Fix intersections between SPH particles and regions when the boundary is periodic

---

yt/frontends/stream/tests/test_stream_stretched.py

This adds an extremely short, small test that projections of stretched grids give the correct results.  It currently passes.

Adding a projection correctness test for stretched

---

yt/geometry/coordinates/geographic_coordinates.py
yt/visualization/base_plot_types.py
yt/visualization/tests/test_geo_projections.py

This changes how the `extent` for GeoAxes is handled -- this version calls `set_extent` only if the data is not global and always passes the `extent` kwarg to imshow. Seemed to work well locally, but we'll see how CI does...
~~I may broaden the scope of this PR to include changing the default projection to set the `central_longitude` kwarg from the plot arguments when available, but if that proves to be too complex I'll just keep this PR to the `extent` modification.~~ EDIT: Will look into this for a follow up PR.

BUG: setting GeoAxes extent

---

yt/visualization/volume_rendering/off_axis_projection.py

I discovered that off-axis projections of filtered gas particles have incorrect scaling. This can be seen clearly in the following notebook:
https://gist.github.com/f97283ce13c4850e31f4b0715f31202f
where the colorbar ranges for the on-axis and off-axis projection should be the same (same axis, different methods), but they are not. The difference arises because the off-axis projection code for SPH particles scales by the units of the `smoothing_length` field to compute the path length, and this is done incorrectly for filtered particles. The reason for this is because the projection calculation is done in code units, and for non-filtered gas particles the path length scaling is done in the units of the `smoothing_length`, which is always `code_length`. However, for filtered gas particles, …

BUG: Off-axis projections of filtered gas particles are not scaled correctly

---

yt/data_objects/index_subobjects/grid_patch.py
yt/geometry/geometry_handler.py

Profiled script
```python
import yt
from yt import derived_field
import unyt as u
for fn in range(5):
ds = yt.load_sample("HiresIsolatedGalaxy")
ds._periodicity = (False, False, False)
v, c = ds.find_max(("gas", "density"))
sp = ds.sphere(c, 10 * u.kpc)
profiles = yt.create_profile(
sp,
"radius",
[
("gas", "density"),
("gas", "radial_velocity"),
("gas", "tangential_velocity"),
("gas", "sound_speed"),
("gas", "mach_number"),
("gas", "temperature"),
],
weight_field=("gas", "cell_mass"),
units={"radius": "pc", "density": "amu/cm**3"},
logs={"radius": True},
)
profiles.save_as_dataset("/tmp/test.h5")
```
Profiling and viz
```
python -m cProfile -o test.profile t_prof.py && snakeviz test.profile
```
on main:
This branch:
- [N/A] New features are documented, with docstrings …

ENH: perf improvements by skipping unnecessary symbolic unit computations

---

yt/fields/field_info_container.py
yt/geometry/grid_geometry_handler.py
yt/loaders.py

revert 2ffd0a246c83dd846f988eefbeb38e37d18c0f24
for context, this patch was intended to answer https://github.com/yt-project/yt/issues/1053
but the example given in the issue is currently invalid and fails with
```python-traceback
TypeError: Expected a 2-tuple of strings formatted as
(field or particle type, field name)
Received invalid field key: dust_density, with type <class 'str'>
```
This failure is intentional and aligns with the overarching goal of dropping support for single-string field ids in yt 4.1
I hope reverting the patch doesn't break anything else, but the intended use case has clearly not been tested continuously for a while.
edit: looks like not !

MNT: revert a patch that was written in support to a now unsupported use case

---

yt/data_objects/index_subobjects/octree_subset.py
yt/data_objects/region_expression.py
yt/data_objects/static_output.py
yt/fields/field_type_container.py
yt/frontends/_skeleton/data_structures.py
yt/frontends/adaptahop/data_structures.py
yt/frontends/amrvac/data_structures.py
yt/frontends/athena/data_structures.py
yt/frontends/athena_pp/data_structures.py
yt/frontends/boxlib/data_structures.py
yt/frontends/enzo/data_structures.py
yt/frontends/enzo_e/data_structures.py
yt/frontends/exodus_ii/data_structures.py
yt/frontends/fits/data_structures.py
yt/frontends/flash/io.py
yt/frontends/gadget/data_structures.py
yt/frontends/gadget/io.py
yt/frontends/gadget_fof/data_structures.py
yt/frontends/gdf/data_structures.py
yt/frontends/halo_catalog/data_structures.py
yt/frontends/http_stream/data_structures.py
yt/frontends/moab/data_structures.py
yt/frontends/nc4_cm1/data_structures.py
yt/frontends/open_pmd/data_structures.py
yt/frontends/sdf/data_structures.py
yt/frontends/stream/data_structures.py
yt/frontends/swift/data_structures.py
yt/frontends/ytdata/data_structures.py

Some systematic (but manual) upgrade of all places where `functools.cached_property` is relevant but currently not used.
`functools.cached_property` is only available since Python 3.8 but we already vendor a backport for Python 3.7 that can be used transparently. The boilerplate code will eventually be auto-cleaned with pre-commit + pyupgrade when we drop support for Python 3.7
Content:
- ENH: use functools' @cached_property decorator where appropriate to simplify code
- ENH: cleanup all implementations of the Dataset.unique_identifier property (guarantee str type, drop unneeded frontend-specific, historic implementations)

ENH: upgrade cached_properties, uniformize Dataset.unique_identifier

---

yt/fields/vector_operations.py
yt/frontends/stream/fields.py
yt/visualization/plot_modifications.py
yt/visualization/plot_window.py
yt/visualization/tests/test_callbacks.py

minimal demo
```python
import yt
from unyt import cm, s
shape = (32, 128, 1)
a = np.sin(np.linspace(-np.pi/2, np.pi/2, 128))
b = np.ones((32, 128))
c = np.zeros((32, 128))
data = {
("gas", "velocity_r"): np.reshape(a * b, shape) * cm/s,
("gas", "velocity_theta"): np.reshape(a * c, shape) * cm/s,
}
data,
shape,
bbox=np.array([[0.0, 5.0], [np.pi / 2 - 0.5, np.pi / 2 + 0.5], [-0.1, +0.1]]),
geometry="spherical",
)
p = yt.SlicePlot(ds, "phi", "velocity_r")
p.annotate_velocity()
p.save("/tmp/")
```
image actualized on 2022-08-01
<details> <summary>older version</summary>
note that the quiver plot is drawn well outside of the actual data domain. I think this effect is due to the current implementation of the pixelizer routine (`pixelize_cylinder`), …

ENH: add support for VelocityCallback and MagFieldCallBack in spherical coordinates

---

yt/fields/field_functions.py

Changes one of the routines that calculated spherical radius. 
`get_radius` in `fields/field_functions.py`
It runs approximately twice as fast as the original routine it replaces. 
Performance benefits come from minimizing allocations and triggering unit conversions. 
The script I used for testing is here: 
```python
import yt
for i in range(10):
ds = yt.frontends.enzo.EnzoDataset(fn)
ds._periodicity = (False, False, False) # Checking periodicity is slow in yt
readit = ds.all_data()  # already defines xyz
r = readit[("index", "radius")]
yt.SlicePlot(ds, "z", ("index", "radius")).save()
```
where `fn` can be obtained in a separate script as
```python
import yt
fn = yt.load_sample("HiresIsolatedGalaxy").filename
```

ENH: Optimized radius calculation. 

---

.github/workflows/build-test.yaml
.github/workflows/wheels.yaml
.pre-commit-config.yaml
setup.cfg
tests/ci_install.sh
yt/utilities/lib/platform_dep.h

Upgrade CIBuildWheel [now with support for CPython 3.11](https://github.com/pypa/cibuildwheel/releases/tag/v2.9.0)
In short, CPython 3.11 has reached ABI stability with their first release candidate (3.11.0-rc1), so it's now safe to build wheels for it, even if the final release isn't out yet (expected early October).
Note that numpy has already successfully published some wheels for CPyhton 3.11 (look for "cp311" at https://pypi.org/simple/numpy/) with similar infrastructure.

BLD: build wheels for CPython 3.11

---

yt/data_objects/static_output.py
yt/fields/tests/test_ambiguous_fields.py

Goals:
- close #3416
- fix corresponding errors in our documentation (if any) -> close #3235 (edit: no errors to report, issue closed)
this depends on #3948 (edit: now merged)

DEPR: Turn ambiguous fields warnings into errors

---

yt/frontends/gamer/data_structures.py

Hi, this is a `GAMER` frontend modification for the `current_time` definition for `GAMER` cosmology simulation, thank you!
* Modify definition for `current_time` in `GAMER` cosmology simulation (`COMOVING` is on)
* Before modification, `current_time` **equals to scale factor `a`**, resulting in **problematic value when annotating timestamp**.
* After modification, `current_time` **equals to cosmological age at given redshift**. 
* Definition for `current_time` is intact for `COMOVING` is off
* Add explanation for code lines

`GAMER` frontend modification for incorporating lookback time in cosmological simulation

---

yt/utilities/on_demand_imports.py

Recently, when the on-demand imports were being cleaned up in [#c501b8c](https://github.com/yt-project/yt/commit/c501b8cc746b4504a9cdcb6d48b85138d6bda390), scipy.optimize was removed as an alias.  It turns out that this broke Trident, so I'd like to add it back in.

Re-adding scipy optimize to on-demand imports

---

doc/source/visualizing/colormaps/cmap_images.py
yt/visualization/color_maps.py
yt/visualization/eps_writer.py
yt/visualization/plot_container.py
yt/visualization/tests/test_splat.py
yt/visualization/volume_rendering/image_handling.py
yt/visualization/volume_rendering/transfer_functions.py

Fix #4088
running the bleeding edge CI workflow on my fork at https://github.com/neutrinoceros/yt/actions/runs/2894300482

BUG: avoid using deprecated matplotlib.cm API

---

yt/visualization/_handlers.py

BUG: avoid using deprecated matplotlib.cm API in volume rendering (round 2)

---

yt/visualization/_handlers.py

Fix #4093
the bleeding edge CI job is running on my fork at https://github.com/neutrinoceros/yt/actions/runs/2911689231

BUG: fix crash in image normalization for RGBA image arrays

---

yt/fields/field_functions.py

PR #4079 changed results for particle_radius calculation within a yt frontend embedded in ytree. After some digging, I discovered that positions for that frontend are returned in "unitary" units which, for that data, are not the same as "code_length". Unless we have a specification requiring positions to be returned in "code_length" for all frontends, this change is probably necessary. This may be quietly failing for other frontends.

Make sure positions are in code_length in get_radius function.

---

doc/source/visualizing/plots.rst
tests/tests.yaml
yt/visualization/_handlers.py
yt/visualization/tests/test_plotwindow.py

This is an attempt at updating how the linthresh value is calculated for SymLogNorms when not provided. Note that I based it off of #3849 , so I'm submitting in draft mode until that one is cleared. The changes here are simple enough that it should be easy to update this PR after #3849 is fully reviewed. 
IMO the linthresh calculation here nicely handles all of the concerns of #3944 without too much complexity. I need to update/add some tests and the docs would need a little updating, but it'd be great to get some feedback on the approach. 
Conceptually, the calculation here uses the minimum absolute nonzero value as a starting guess at linthresh (as in  #3295) but then limits the dynamic range of the symlog scale when necessary to avoid the floating point precision issues that caused the …

Updating the linthresh guessing

---

yt/frontends/enzo_e/data_structures.py
yt/frontends/enzo_e/io.py

More recent versions of `Enzo-E` record the version number in the outputs. This PR now stores that in the `parameters` attribute of `EnzoEDataset` instances (the value is associated with 'version_string').
The primary reason that `Enzo-E` now saves this version number is to make it easier to interpret the data, when the interpretation changes in newer versions.
At present, the version string only affects one thing: the distinction between particle masses and densities.
- Several months back `Enzo-E` started to save particle masses such that they should be interpreted as masses (previously they were usually treated as densities).
- At the time, to differentiate the interpretation of this data from outputs written by older code versions, we started to have `Enzo-E` append a parameter called …

ENH: Store the Enzo-E version number in parameters attribute of EnzoEDataset

---

yt/visualization/base_plot_types.py

There is a warning that has a typo in it, which is misleading.  I searched the docs and the codebase but couldn't find any reference to `draw_axis` kwarg, until I stumbled upon `draw_axes` instead.  But even after having identified the correct kwarg, I still don't even know what function to pass this kwarg to.  `set_background_color()`? `save()`?

Correcting deceptive typo in error message.

---

yt/frontends/enzo_e/data_structures.py
yt/frontends/enzo_e/fields.py
yt/frontends/enzo_e/misc.py

The primary purpose of this PR is to modify the way that the Enzo-E frontend determines generic fluid properties (namely the adiabatic index and whether the internal_energy field is an alias of the `('gas', 'specific_thermal_energy')` field). This is necessary to reflect a recent change in how this information is specified in Enzo-E's parameter files (this information is now a lot more centralized than it used to be).
This also introduces a handful of minor tweaks.
- I modified some logic to more correctly handle some parsing corner cases (to more accurately reflect the behavior of Enzo-E). This relates to determining cosmological parameters and the older approach for determining if the simulation used the dual-energy formalism.
- I modified the way that the frontend determines whether …

ENH: Improved Enzo-E frontend's determination of fluid properties

---

.github/workflows/build-test.yaml

It's time to fix #3932, as matplotlib is starting the release process for version 3.6 [without wheels for Python 3.7](https://pypi.org/project/matplotlib/3.6.0rc1/#files), which means our reference answers will soon be out of sync with their latest release.
This will require a supporting PR to the answer store submodule to create reference answers for Python 3.9
Edit: here https://github.com/yt-project/answer-store/pull/32

TST: bump Python from 3.7 to 3.9 in answer testing

---

doc/source/examining/low_level_inspection.rst
yt/data_objects/construction_data_containers.py
yt/data_objects/tests/test_covering_grid.py

This adds a `data_source` keyword (only) argument to the `YTCoveringGrid` and then intersects  that `data_source` with the region used for the covering grid in order to create a regularized sampling of, e.g., a sphere. 
Here's an example:
```python
import yt
import matplotlib.pyplot as plt 
cg = ds.covering_grid(2, left_edge=[0.0, 0.0, 0.0], dims=[128, 128, 128])
gridded_dens = cg[("gas", "density")]
sp = ds.sphere(ds.domain_center, 0.2)
cg_sp_intx = ds.covering_grid(2, left_edge=[0.0, 0.0, 0.0], dims=[128, 128, 128], data_source=sp)
gridded_dens_in_sphere = cg_sp_intx[("gas", "density")]
f, axs = plt.subplots(nrows=1, ncols=2)
axs[0].imshow(np.log10(gridded_dens[:,:,64]))
axs[1].imshow(np.log10(gridded_dens_in_sphere[:,:,64]))
``` …

Adds `data_source` argument to covering grid

---

yt/frontends/boxlib/io.py

Currently, yt cannot read in 1D particle data using the Boxlib frontend. The target code, WarpX, allows 1D simulations so this capability is needed. The issue traces down to the code in `boxlib/io.py` where the particle data arrays are read in. The code explicitly handles 2D and 3D data, but not 1D (which falls back to the 3D case). This puts erroneous data in the y and z positions and when the selector is used to chose only particles within the domain, the erroneous data is out of the bounds and so all of the particles are rejected.
The fix is to include a test for 1D data. The bit of code was rewritten to use a loop over dimensionality to avoid messy if checks of the dimensionality.
No changes are needed in the documentation. The updated code is commented.

For Boxlib frontend, allow reading of 1D particle data

---

.github/workflows/bleeding-edge.yaml
.github/workflows/build-test.yaml

I recently realized that GitHub action supports colored logs, but pytest currently doesn't enable them by default.
I think this is an uncontroversial quality of life improvement for devs.

TST: enable colored logs for pytest colored in GHA CI

---

yt/fields/field_info_container.py
yt/frontends/stream/data_structures.py
yt/funcs.py
yt/utilities/operator_registry.py
yt/utilities/sdf.py

Subclassing builtin types like `dict` is error prone because overriden methods are mostly ignored.
This can lead to very subtle bugs where custom classes don't behave as one would expect
```python
class DoubleDict(dict):
def __setitem__(self, key, value):
return super().__setitem__(key, [value] * 2)
d = DoubleDict(a=1)
d["b"] = 2
print(d)
```
outputs
```
{'a': 1, 'b': [2, 2]}
```
We see that the user-defined `__setitem__` method is correctly used when setting a new value, but is ignored at initialization.
subclass `collections.UserDict` instead, which is intended to avoid these subtle issues

ENH: avoid subclassing builtin dict

---

conftest.py
tests/ci_install.sh
tests/windows_conda_requirements.txt

Cartopy 0.21 was released a few hours ago. This patch is mostly a pretext to run CI with the newest version and see if we find any new incompatibilities.
[The release notes](https://github.com/SciTools/cartopy/releases/tag/v0.21.0) also hint that PROJ headers are not a dependency anymore, which may allow for a couple other simplifications in our infrastructure, so I may iterate a couple commits here before I open to reviews.

TST: test against cartopy 0.21

---

doc/source/developing/testing.rst
doc/source/examining/loading_data.rst
doc/source/reference/changelog.rst
doc/source/visualizing/callbacks.rst
doc/source/visualizing/plots.rst

This adresses #3369
Currently we're at 37 warnings, 23 of which are similar errors with docstrings in `yt.utilities.lib.cykdtree.kdtree`.
Here I want to focus on fixing everything else.

DOC: fix multiple warnings in docs build

---

doc/source/analyzing/objects.rst
doc/source/cookbook/simple_plots.rst
doc/source/cookbook/simple_projection_stddev.py
doc/source/visualizing/plots.rst
yt/data_objects/construction_data_containers.py
yt/data_objects/data_containers.py
yt/data_objects/tests/test_projection.py
yt/fields/vector_operations.py
yt/funcs.py
yt/geometry/coordinates/cartesian_coordinates.py
yt/geometry/coordinates/tests/test_sph_pixelization.py
yt/utilities/math_utils.py
yt/visualization/fits_image.py
yt/visualization/fixed_resolution.py
yt/visualization/plot_container.py
yt/visualization/plot_window.py
yt/visualization/tests/test_fits_image.py
yt/visualization/tests/test_offaxisprojection.py
yt/visualization/volume_rendering/off_axis_projection.py

Weighted projections are essentially averages along the line of sight of a field. For some fields (like velocity), projecting the weighted standard deviation is also a useful quantity. This PR adds that functionality for both on-axis and off-axis projections to yt, including `ProjectionPlot`s and projections to FITS images. The functionality is demonstrated in this notebook: 
https://gist.github.com/388e2b53d1b848fc19a125669d422cec
Still need to add docs ~~and tests~~. When viewing the diff, you may want to turn off changes in whitespace since I fixed the indentation of a bunch of docstrings. 
I'm not entirely crazy about what I had to do in order to take care of cancellations in the computation of the standard deviation in the final map--basically if we end up with a negative difference …

ENH: Projections of a field's standard deviation

---

yt/visualization/particle_plots.py

A small improvement found out while working on #4118

ENH: allow passing a dataset as a data source to ParticlePhasePlot

---

yt/frontends/cf_radial/data_structures.py
yt/frontends/cf_radial/tests/test_outputs.py
yt/frontends/fits/data_structures.py
yt/frontends/fits/tests/test_outputs.py
yt/utilities/answer_testing/framework.py

fixes #4126
The third commit isn't strictly necessary but it's an improvement; running the following module with pytest
```python
from yt.testing import requires_module
from yt.utilities.answer_testing.framework import requires_ds
@requires_module("xarray")
@requires_ds("CfRadialGrid/grid1.nc")
def test_1():
pass
@requires_ds("CfRadialGrid/grid1.nc")
@requires_module("xarray")
def test_2():
pass
```
gives
```
t.py::test_1 SKIPPED (Missing required module xarray)
t.py::test_2 SKIPPED (cannot load dataset)
```
The reason why we can't load the dataset *being* that `xarray` isn't available, the first option is clearer.

BUG: fix issues with `requires_ds` + pytest

---

yt/frontends/athena/data_structures.py
yt/frontends/athena_pp/data_structures.py

Found these while working on pytest-mpl tests
```
DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information
```

ENH: stop using deprecated np.int

---

.github/workflows/build-test.yaml

`fail-fast` defaults to true. This leads to situations where failing answer tests (typically much faster to run than unit tests) leads to cancelation of all other jobs.
When image answer tests are translated to pytest-mpl, this behaviour will be an inconvenience when adding new tests (pytest-mpl "fails" when no previous result exists), preventing unit tests to run.
This behaviour is also annoying these days as the answer tests job is flaky, and we regularly need to manually relaunch CI hoping for better results.

TST: don't fail GHA tests fast

---

setup.cfg

Tentative fix for #4128
Even if this works (not sure yet), we might not want to merge this, depending on how reactive NETCDF4 is.
I'm opening mostly to _check_ my assumption that this is the source of instability.

BLD: forbid netcdf4 1.6.1

---

setup.cfg
tests/tests.yaml

Following the release of matplotlib 3.6, I'll use this PR to generate updates for the answer store submodule. I participated in the discussions leading to that release and I'm confident that it shouldn't have unwanted effects on yt plots, but it _does_ have desirable effects, so an update is still warranted.
Currently based on #4131

TST: bump image tests for matplotlib 3.6

---

doc/source/visualizing/geographic_projections_and_transforms.rst
yt/utilities/answer_testing/answer_tests.py
yt/utilities/answer_testing/framework.py
yt/visualization/fixed_resolution.py
yt/visualization/plot_container.py
yt/visualization/plot_window.py
yt/visualization/tests/test_filters.py

A simple addition to the public interface would be useful in #4118 to avoid using private methods directly.
Content:
- ENH: add a PlotContainer.render method (public interface for _setup_plots)
- DOC: avoid using private `_setup_plots` method in user docs
For backward compatibility, I avoided simply renaming `_setup_plots`.
Hopefully the intented usage is clear from the docstring and the docs update.
I'm not completely certain that my use of the `@validate_plot` is warranted or justified, and I would particularly appreciate feedback specifically on this.

ENH: public API `render` methods to `PlotContainer` and `FixedResolutionBuffer`

---

setup.cfg

Follow up to #4131 in which I accidentally commented out an existing lower limit for netcdf4.

BLD: fix broken constraint on netcdf4 requirement

---

yt/frontends/flash/io.py

BUG: Use any() on numpy array in flash blockless check

---

.github/workflows/wheels.yaml

upgrading cibuildwheel so that CPython 3.11 wheels are built with version 3.11.0rc2 instead of 3.11.0rc1
see release notes
https://github.com/pypa/cibuildwheel#v2100

BLD: upgrade CIBW

---

tests/tests.yaml
yt/fields/xray_emission_fields.py

Zsun is itself a unit that needs to be removed. Otherwise the emission from metal cooling is reduced by ~0.013 (unless I misunderstood the definition of the metallicity field ?).

Update xray_emission_fields.py - metallicity field values

---

yt/frontends/ramses/data_structures.py

RAMSES stores along with its output the namelist containing the parameters of the simulation. Unfortunately, with old version of RAMSES, this file may be in binary format (this was a bug that has now been fixed). This then may lead to `f90nml`, the package we rely on to parse the namelist, to raise an `AssertionError`.
This PR catches it.
See also: https://github.com/marshallward/f90nml/issues/147

RAMSES: catch assertion errors with ill-written namelist files

---

setup.cfg

BLD: promote ipywidget to a hard dependency

---

yt/geometry/oct_container.pyx

This fixes a memory leak issue reported in https://mail.python.org/archives/list/yt-users@python.org/thread/H3WCK5PA2WNGEDBVHOCWV5YCPV2ZYIXY/.
The root cause of the issue is that, for octree datasets (RAMSES, ART), the base grid is stored using a tree-like structure that is allocated in C. Unfortunately, when associated Python gets deleted, we were not freeing the memory in the process.
This PR fixes this by explicitely removing all entries in the query tree updon deallocation of the Python object.
For _very_ large datasets, the operation may be quite slow `O(N log(N))`, where `N` is the number of base grid elements. For a RAMSES dataset with `levelmin=8`, that would be `~3 × 8 × (2^8)^3` operations.
It should in principle be possible to deallocate everything in `3 × N` operations by …

[BUGFIX] Memory leak: free C++ memory before deallocing Python object

---

yt/visualization/plot_modifications.py

Fix 2 regressions from #3957 :
- BUG: fix a regression where adding plot annotations would not invalidate plot
- BUG: fix a regression where calling plot annotation method would not trigger new render in interactive notebooks
Closes #4159

BUG: hotfix iterative plot annotations

---

yt/data_objects/construction_data_containers.py
yt/data_objects/data_containers.py
yt/data_objects/selection_objects/ray.py
yt/data_objects/tests/test_chunking.py
yt/data_objects/tests/test_compose.py
yt/data_objects/tests/test_rays.py
yt/fields/particle_fields.py
yt/frontends/gadget/io.py
yt/frontends/ytdata/data_structures.py
yt/geometry/coordinates/cartesian_coordinates.py
yt/geometry/geometry_handler.py
yt/units/__init__.py
yt/units/_numpy_wrapper_functions.py
yt/utilities/particle_generator.py
yt/utilities/tests/test_particle_generator.py
yt/visualization/volume_rendering/lens.py
yt/visualization/volume_rendering/old_camera.py

Follow up to #4136 and https://github.com/yt-project/unyt/pull/293, this adapts yt to stay compatible with latest development in unyt (#4162).
Here's my reasoning:
- some of unyt's API is now marked as deprecated (on the dev branch). Specifically, all unit-preserving numpy wrapper functions (e.g. `unyt.udot` and `unyt.uconcatenate`)
- we cannot yet migrate to the vanilla numpy API (e.g., `np.dot` and `np.concatenate`) that _will_ be the replacement because that will not work _before_ unyt 3.0 is available.
- both the `yt` and `yt.units` namespace currently re-expose this unyt API directly
The simpler option I can see to get around the deprecation warnings in CI *without* simply filtering them is to
vendor specifically this part of unyt's API, but do so in an isolated and hidden module …

BUG: fix future incompatiblities with unyt 3.0 (2/n)

---

nose_unit.cfg
pyproject.toml
tests/tests.yaml
yt/data_objects/tests/test_glue.py
yt/testing.py

Quick fix for #4188
- TST: configure pytest to ignore test modules using deprecated nose support
- TST: migrate a test from nose to pytest API

TST: resolve compatibility with pytest 7.2

---

yt/frontends/artio/_artio_caller.pyx
yt/frontends/gamer/cfields.pyx
yt/frontends/ramses/io_utils.pyx
yt/geometry/oct_container.pyx
yt/geometry/oct_visitors.pyx
yt/geometry/particle_deposit.pyx
yt/geometry/particle_oct_container.pyx
yt/geometry/particle_smooth.pyx
yt/utilities/lib/_octree_raytracing.pyx
yt/utilities/lib/allocation_container.pyx
yt/utilities/lib/autogenerated_element_samplers.pyx
yt/utilities/lib/bounding_volume_hierarchy.pyx
yt/utilities/lib/cykdtree/kdtree.pyx
yt/utilities/lib/cyoctree.pyx
yt/utilities/lib/distance_queue.pyx
yt/utilities/lib/element_mappings.pyx
yt/utilities/lib/embree_mesh/mesh_construction.pyx
yt/utilities/lib/embree_mesh/mesh_samplers.pyx
yt/utilities/lib/fixed_interpolator.cpp
yt/utilities/lib/fnv_hash.pyx
yt/utilities/lib/fortran_reader.pyx
yt/utilities/lib/geometry_utils.pyx
yt/utilities/lib/line_integral_convolution.pyx
yt/utilities/lib/misc_utilities.pyx
yt/utilities/lib/origami_tags.c
yt/utilities/lib/particle_kdtree_tools.pyx
yt/utilities/lib/particle_mesh_operations.pyx
yt/utilities/lib/pixelization_routines.pyx
yt/utilities/voropp.pyx

This removes all unused variables in Cython files as flagged by https://github.com/MarcoGorelli/cython-lint (see #4193).
Additional nits:
- removed a few useless variables. The few catches were found by compiling with `CC="gcc -Werror=unused" CXX="g++ -Werror=unused" python setup.py develop`. Note that the project does not compile with the above-mentioned flags due to some function being defined deep in Numpy and not used by yt.
- brought back support for parallel raycasting for octrees. The issue was that the `.hpp` file was not compiled with the `-fopenmp` flag on, so that the OMP pragma was just ignored.

MNT: Remove useless variables in Cython code

---

yt/frontends/amrvac/data_structures.py

I wrote these comments 3 years ago when Python 3.8 was brand new and I couldn't wait to use it.
Now that we _can_ (3.8 is the oldest version we support), I actually disagree with my past self that using the walrus operator *in those instances* is desirable as it hurts readability and doesn't add value.

MNT: cleanup a pair of useless comments

---

yt/visualization/plot_window.py
yt/visualization/tests/test_set_zlim.py

DOC: cleanup calls to private methods _setup_plots in doctests

---

yt/visualization/base_plot_types.py

This example script doesn't work with matplotlib <= 3.5 and crashes with an `AttributeError`
```python
import yt
from yt.testing import fake_random_ds
from matplotlib.colors import TwoSlopeNorm
ds = fake_random_ds(16)
field = ("gas", "density")
p = SlicePlot(ds, "z", field)
p.set_norm(field, norm=TwoSlopeNorm(vcenter=0, vmin=-0.5, vmax=1))
```
However this error is not critical so this patch makes it non-fatal, with a clear warning message.
This is extracted from #4122 to enable backporting.
Backporting the tests that come with it in #4122 would be much more complicated, so I hope it's okay to backport just the patch.

BUG: make a MPL failure non-fatal for set_norm with old version of MPL

---

yt/utilities/lib/points_in_volume.pyx

Manual backport for a small bugfix from #4197

BUG: fix a missing type declaration in Cython file

---

setupext.py
yt/geometry/_selection_routines/selector_object.pxi
yt/geometry/fake_octree.pyx
yt/geometry/grid_container.pxd
yt/geometry/oct_container.pxd
yt/geometry/oct_container.pyx
yt/geometry/oct_visitors.pxd
yt/geometry/oct_visitors.pyx
yt/geometry/particle_deposit.pyx
yt/geometry/particle_oct_container.pyx
yt/geometry/particle_smooth.pxd
yt/geometry/particle_smooth.pyx
yt/geometry/selection_routines.pxd
yt/geometry/selection_routines.pyx
yt/utilities/lib/cykdtree/kdtree.pyx
yt/utilities/lib/fortran_reader.pyx
yt/utilities/lib/grid_traversal.pyx
yt/utilities/lib/image_samplers.pyx
yt/utilities/lib/lenses.pxd
yt/utilities/lib/marching_cubes.pyx
yt/utilities/lib/mesh_triangulation.pyx
yt/utilities/lib/misc_utilities.pyx
yt/utilities/lib/pixelization_routines.pyx
yt/utilities/lib/primitives.pxd

This should be a noop, and gets us more in line with Cython 3.0 upcoming standards. See https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html?highlight=language_level#python-3-syntax-semantics

RFC: upgrade Cython 'language level' to Python 3

---

yt/frontends/arepo/fields.py
yt/frontends/arepo/tests/test_outputs.py

yt computes "nuclei density" fields by summing up ion number density fields for the same nuclei with different ionization states. The Arepo frontend currently has `"H"`, `"H_p0"`, and `"H_p1"` all added to the `species_names` attribute in `ArepoFieldInfo`, which is then used to compute the set up the species fields and compute the fields for specific abundances. 
The `"H_p0"` and `"H_p1"` do not belong in this list for two reasons:
1. Their respective associated fields are handled later on in the method `ArepoFieldInfo.setup_gas_particle_fields`, and do not need to be handled by `setup_species_fields`.
2. Putting them in `species_names` results in the number of hydrogen nuclei being double-counted
This PR removes those ionization species from the `species_names` attribute and also removes …

[bugfix] H nuclei are being double-counted in the Arepo frontend

---

.github/workflows/codetour-check.yaml

For context, see #4213 and #4198

MNT: temporarily switch off codetour-watch workflow

---

.tours/particle-indexing.tour
yt/geometry/particle_geometry_handler.py

When loading particle datasets, a morton index is either created and stored to an EWAH file or is loaded from an already existing file. 
PR #3198 allowed for the automatic updating of the refined index to be more efficient. However, since both the coarse and the fine index are in the filename, an existing EWAH file with the updated index order is not found and thus the index must be re-generated again. 
This PR changes the logic slightly so that EWAH filenames with either the original refined index or the updated one can be found and used. 
Closes Issue #3487.

Automatically find EWAH files with increased index_order2

---

yt/visualization/eps_writer.py

Fix #4215
Apparently CI didn't capture this regression because the one test that was designed for it has heavy requirements (LaTeX) that are never met, but provided `pyx` is correctly installed, the breakage/fix can be reproduced/verified with 
```
pytest yt/visualization/tests/test_eps_writer.py
```

BUG: fix compatibility between eps_writer and yt 4.1

---

yt/visualization/fixed_resolution.py

`ParticleProjectionPlot` and `FITSParticleProjection` have a `density` option that divides the projected map by the area of the pixel of the fixed resolution buffer to compute a projected particle density. The computation of the pixel area was being handled incorrectly--it was using the width of the underlying `data_source` for the projection instead of the `bounds` of the FRB to compute the pixel sizes. This PR fixes that.

Fix pixel size calculation for density option in particle projection plots and FITS images

---

doc/source/visualizing/FITSImageData.ipynb
yt/visualization/fits_image.py
yt/visualization/tests/test_fits_image.py

This PR adds two new features to FITS image writing. 
1. When adding a celestial coordinate system to a FITS image created from yt using the `create_sky_wcs` method, it overwrites the existing, linear coordinate coordinate system by default. This PR changes the behavior so that the old coordinate system is retained in the FITS header but is moved to the "second" slot for coordinate systems. 
2. Adding an `origin` keyword argument to `FITSSlice`, `FITSProjection`, and `FITSParticleProjection` that optionally allows the center coordinates to be set to (0,0) if `origin="image"`.

Two new features for writing FITS images

---

setup.cfg
yt/_typing.py
yt/data_objects/static_output.py
yt/loaders.py
yt/visualization/plot_modifications.py
yt/visualization/volume_rendering/render_source.py

- TYP: upgrade mypy (0.971 -> 0.991) and additional typecheck dependencies
- TYP: cleanup obsolete 'type: ignore' comments
- TYP: fix PEP 484 errors (implicit None) in function signatures
All newly detected errors are fixed here, but it's worth noting that `mypy yt` now produces a short list of warnings hinting at unannotated functions that have small bits of typing information in their bodies:
```
yt/data_objects/static_output.py: note: In member "__init__" of class "Dataset":
yt/data_objects/static_output.py:240: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
yt/data_objects/static_output.py: note: In member "_get_field_info_helper" of class "Dataset":
yt/data_objects/static_output.py:921: note: By default …
```

TYP: typing improvements using latest mypy (0.991)

---

doc/source/cookbook/fits_radio_cubes.ipynb
doc/source/cookbook/fits_xray_images.ipynb
doc/source/examining/loading_data.rst
setup.cfg
yt/frontends/fits/misc.py
yt/utilities/on_demand_imports.py

BUG: migrate away from broken optional dependency (pyregion -> regions)

---

yt/visualization/_handlers.py

Fix #4241 for good
In insight, the logic here could be simplified a lot by using clearer sentinel values instead of special casing `None` AND some strings, but I'll keep the patch minimal so it's easier to review and backport

BUG: avoid a deprecation warning from numpy

---

conftest.py

For context, see https://github.com/SciTools/cartopy/issues/2113

TST: ignore a deprecation warning triggered from cartopy

---

setup.cfg

Just spotted these two out-of-sync requirements from install_requires.

BLD: fix missing specs from minimal requirements

---

.pre-commit-config.yaml
doc/helper_scripts/run_recipes.py
setup.cfg
tests/test_install_script.py
yt/data_objects/static_output.py
yt/data_objects/time_series.py
yt/exthook.py
yt/fields/field_detector.py
yt/frontends/adaptahop/definitions.py
yt/frontends/chimera/data_structures.py
yt/frontends/enzo/simulation_handling.py
yt/frontends/gadget/simulation_handling.py
yt/frontends/halo_catalog/data_structures.py
yt/frontends/stream/definitions.py
yt/loaders.py
yt/tests/test_testing.py
yt/utilities/answer_testing/framework.py
yt/utilities/minimal_representation.py
yt/utilities/parameter_file_storage.py
yt/utilities/sdf.py
yt/visualization/plot_modifications.py
yt/visualization/plot_window.py

Opening as a draft because it's not obvious that adding `@abstractmethod` decorators here and there will not crash tests
TODO:

STY: upgrade flake8-bugbear and fix newly detected errors

---

yt/_maintenance/deprecation.py
yt/loaders.py
yt/tests/test_load_errors.py

This is a proposed solution to close #2879:
IMO, the name of the first argument to yt.load is bound to be meaningless.
It's current name `fn` is short for "filename", but we support loading from directories and in some cases, urls !
I think that making it a positional-only argument lifts out the weigh of carying a meaningless name forever.
Now, the difficult part is in continuously evolving the API to avoid sudden breaking changes, which is why 99% of this patch consists in adding a custom decorator to do just that, so existing code that might rely on loading data as `yt.load(fn=..., ...)` will not immediately break but will still emit some warnings, and we can keep backward compatibility for a while.
TODO:

DEPR: deprecate calling yt.load with first argument passed as keyword

---

yt/frontends/arepo/tests/test_outputs.py
yt/geometry/particle_geometry_handler.py

In PR #4198 I implemented a feature to automatically find EWAH files with increased `index_order2` for SPH/Lagrangian datasets. 
There was an oversight in these changes, which involves the fact that although the file with the updated `index_order2` is correctly found and loaded, `index_order2` is not increased by 2 when creating the `ParticleBitmap` object. The result is that for some analyses that try to look on small scales the code either crashes or it gives odd-looking results. 
This PR fixes this issue, but it required a bit of moving things around so that we detect the new value of `index_order2` from the filename before we create the `ParticleBitmap` object.

A bugfix for the new expanded EWAH file reading capability

---

nose_unit.cfg
tests/tests.yaml
yt/frontends/stream/tests/test_callable_grids.py

This PR adds a test for calling `load_uniform_grid` with data specified via a function. It also moves the whole `test_callable_grids.py` suite to pytest-only.

add some missing test for stream grids with callables

---

yt/_maintenance/deprecation.py

A hard-learned lesson from yt 4.1 was that making promises about when deprecated features would be removed can sometimes come back at us and make releases much more difficult to polish.
In most recent feature releases (4.0, 4.1, and soon 4.2), we made some eager cuts through stuff that was deprecated in the previous 7 or so years, but long term it's probably better to just _not_ try to anticipate too accurately when deprecated code is actually going to be removed, and we can probably just live with it as long as it doesn't impede further developments.

DEPR: do not try to predict removal dates in deprecation warnings by default

---

conftest.py
yt/data_objects/construction_data_containers.py
yt/frontends/tipsy/io.py
yt/funcs.py
yt/utilities/command_line.py
yt/utilities/rpdb.py
yt/visualization/base_plot_types.py

Reduces yt's startup time by ~30% (from 1.57s to 1.07s on my machine, averaged over 100 runs)
Measured with this simple script
```python
from time import monotonic_ns
tstart = monotonic_ns()
import yt
tstop = monotonic_ns()
print(f"{(tstop-tstart)/1e9:.3f}")                                                                      
```

ENH: delay expensive imports

---

yt/utilities/exceptions.py

Fix a collection of minor, related design issues:
- all `YTXxxxxxxError` class derive from `YTException`
- fix `super()` usage
- simplify base class design so that it contains *no* init code

ENH: uniformize YTException class hierarchy

---

yt/data_objects/construction_data_containers.py
yt/data_objects/data_containers.py
yt/data_objects/index_subobjects/grid_patch.py
yt/data_objects/static_output.py
yt/fields/derived_field.py
yt/fields/domain_context.py
yt/fields/field_info_container.py
yt/frontends/ramses/particle_handlers.py
yt/utilities/exceptions.py
yt/utilities/io_handler.py
yt/visualization/fits_image.py
yt/visualization/fixed_resolution.py
yt/visualization/plot_container.py
yt/visualization/plot_modifications.py
yt/visualization/profile_plotter.py

A noop followup to the introduction of type hint shortcuts in #4227

TYP: use FieldKey type aliases instead of Tuple[str, str]

---

doc/source/installing.rst
pyproject.toml

Fix #4270
I still need to add documentation, but I'm opening as a draft to see how it goes with CI
- [N/A] Adds a test for any bugs fixed. Adds tests for new features.

ENH: add support for installing yt with cherry-picked, frontend specific optional dependencies with pip

---

yt/data_objects/static_output.py
yt/utilities/command_line.py
yt/visualization/plot_modifications.py
yt/visualization/plot_window.py

Complements #4229 in fixing the remaining warnings from mypy (`[annotation-unchecked]`)
```
yt/data_objects/static_output.py: note: In member "_assign_unit_system" of class "Dataset":
yt/data_objects/static_output.py:1254: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
... 
```

TYP: add missing type hints

---

pyproject.toml

In #4271 I forgot to manually migrate comments contained in `setup.cfg`. This fixes that.

MNT: re-add lost comments from setup.cfg

---

MANIFEST.in

As noted by @matthewturk, the `Check MANIFEST.in` step of the wheel s workflow has been broken since #4271
This fixes it.
To validate this patch, I ran the workflow on my fork, see https://github.com/neutrinoceros/yt/actions/runs/3802301284/jobs/6467650714

BUG: fix missing entries in MANIFEST.in

---

doc/helper_scripts/show_fields.py
yt/data_objects/construction_data_containers.py
yt/data_objects/data_containers.py
yt/data_objects/index_subobjects/grid_patch.py
yt/data_objects/index_subobjects/octree_subset.py
yt/data_objects/region_expression.py
yt/data_objects/selection_objects/data_selection_objects.py
yt/data_objects/static_output.py
yt/data_objects/tests/test_cutting_plane.py
yt/data_objects/tests/test_data_containers.py
yt/data_objects/tests/test_firefly.py
yt/fields/field_detector.py
yt/fields/particle_fields.py
yt/fields/tests/test_fields.py
yt/fields/xray_emission_fields.py
yt/frontends/enzo_e/data_structures.py
yt/frontends/stream/tests/test_stream_particles.py
yt/frontends/ytdata/data_structures.py
yt/funcs.py
yt/utilities/exceptions.py
yt/utilities/lib/octree_raytracing.py
yt/visualization/fits_image.py
yt/visualization/fixed_resolution.py
yt/visualization/plot_container.py
yt/visualization/plot_modifications.py
yt/visualization/plot_window.py
yt/visualization/tests/test_geo_projections.py
yt/visualization/volume_rendering/old_camera.py

While working on #4227 I stumbled again on this method, which turns out to be extremely delicate to correctly type.
Because this method is private, it doesn't *need* the amount of type flexibility it currently has: being strict on input type would make it much easier to maintain, and wouldn't take anything away from users.
I'll use this PR as an experimental playground to see how much of the codebase actually falls apart if I take away type flexibility and how much work is needed to fix it. I'm hoping the answer to both questions is "not that much".

TYP: add static typing to Dataset._get_field_info_helper

---

yt/data_objects/data_containers.py
yt/data_objects/static_output.py

fix current warning from mypy:
```
yt/data_objects/data_containers.py: note: In member "__init__" of class "YTDataContainer":
8
yt/data_objects/data_containers.py:91: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
```
It'd be useful to turn these notes into proper errors to avoid leaking them constantly, I'll look into it.

TYP: fix mypy warnings about unchecked hints

---

.github/workflows/bleeding-edge.yaml
.github/workflows/build-test.yaml
.github/workflows/type-checking.yaml
.github/workflows/wheels.yaml

See
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Updating `setup-python` to v4 should fix that

CI: silence `set-output` warning

---

doc/source/developing/extensions.rst
nose_unit.cfg
tests/tests.yaml
yt/frontends/sdf/data_structures.py
yt/loaders.py
yt/tests/test_external_frontends.py

This PR modifies the behavior of `yt.load` to auto-include subclasses of `Dataset` from external, installed packages. External packages must define an entry point in `yt.frontends` linked to the Dataset subclass (see docs for an example).

ENH: automatically load external frontends in load()

---

setupext.py
yt/funcs.py
yt/sample_data/api.py
yt/utilities/command_line.py

fix #4287
Turns out it was super easy, barely an inconvenience.

ENH: migrate from pkg_resources to importlib.resources on Python 3.9+

---

pyproject.toml
tests/tests.yaml
yt/frontends/arepo/tests/test_outputs.py
yt/frontends/gadget/tests/test_outputs.py
yt/geometry/particle_geometry_handler.py
yt/geometry/particle_oct_container.pyx
yt/geometry/tests/test_particle_octree.py

My attempt at fixing https://github.com/yt-project/yt/issues/3327. The main "upgrade" is that we can now store indices of the same order for different domain sizes, which we currently don't allow. Each cached index is identified by: `left_edge`, `right_edge`, hash of data file, `periodicity`, `index_order1`, `index_order2` and `nfiles`.
Drowback is that `h5py` is a strict requirement now.

ENH: Allow to store multiple bitmap indices in the ewah-sidecar

---

.github/workflows/build-test.yaml

Now that h5py 3.8 was released with Python 3.11 wheels, we can bump the bulk of CI to that version.
Note that this currently adds a few minutes of overhead as compared with Python 3.10 because a couple of our optional (some, indirect) dependencies still need to be built from source, but I'll give a hand upstream to remedy that on the medium term.

TST: bump CI from Python 3.10 to 3.11

---

doc/source/examining/loading_data.rst

the url specification was missing a space, so the link wasn't rendering properly (see docs page here https://yt-project.org/doc/examining/loading_data.html#simple-hdf5-data )

fix docs typo in load_hdf5_file description

---

yt/frontends/gizmo/fields.py

Fix the error `'GizmoFieldInfo' object has no attribute 'nuclei_names'` complained by Line 122
https://github.com/yt-project/yt/blob/bd6357eea0121c4071a6580bedcf543122824d35/yt/frontends/gizmo/fields.py#L122-L124
when loading a non-cosmological `Gizmo` dataset.

BUG: fix the error when loading a non-cosmological `Gizmo` dataset

---

.github/workflows/type-checking.yaml
pyproject.toml

This is a noop PR to celebrate mypy going out of beta.
The 1.0.0 release is advertised as 40% faster than 0.991 (which I was able to verify in the case of yt), so even without using new features it still brings *something* to the table.
A feature I've been waiting for also has landed in this version ([Support for `Self` type](https://github.com/python/mypy/pull/14041)), though I'd prefer leveraging it in a following PR.
I'm also adding a `workflow_dispatch` trigger to the type-checking workflow, which was useful for me to test the upgrade on my fork.

TYP: upgrade mypy (0.991 -> 1.0.0)

---

nose_unit.cfg
tests/tests.yaml
yt/_typing.py
yt/frontends/stream/misc.py
yt/frontends/stream/tests/test_stream_stretched.py
yt/loaders.py

This PR:
* adds some validation for the cell_widths argument to load_uniform_grid (including dtype checks)
* adds a missing docstring entry for cell_widths
* adds some tests (and makes test_stream_stretched.py pytest-only)
This started as a bug fix for when the cell_widths do not have a dtype of float64 and expanded a bit to better capture what cell_widths has to be. The bug can be replicated with:
```python
import yt
N = 8
data = {"density": np.random.random((N, N, N))}
cell_widths = []
for i in range(3):
widths = np.random.random(N)
widths /= widths.sum()  # Normalize to span 0 .. 1.
cell_widths.append(widths.astype(np.float32)) # <----------- note cell width dtype
data,
[N, N, N],
bbox=np.array([[0.0, 1.0], [0.0, 1.0], [0.0, 1.0]]), …
```

cell_widths validation for load_uniform_grid

---

.pre-commit-config.yaml

After two years of weekly updates, I think the time is ripe to slow down a little.

MNT: diminish pre-commit.ci autoupdate frequency (weekly -> monthly)

---

pyproject.toml
setupext.py
yt/funcs.py
yt/sample_data/api.py
yt/utilities/command_line.py

Follow up to #4292
Rationale: see warning at the top of [this page](https://setuptools.pypa.io/en/latest/pkg_resources.html)

BLD: drop pkg_resources as a dependency on Python 3.8

---

doc/source/examining/loading_data.rst

The SlicePlot call in the first load_unstructured_mesh generic example is missing a field type for the field argument.

DOC: load unstructured mesh SlicePlot

---

.github/dependabot.yml

MNT: enable dependabot autoupdates for GitHub workflows

---

doc/source/visualizing/plots.rst
nose_unit.cfg
tests/tests.yaml
yt/data_objects/construction_data_containers.py
yt/data_objects/data_containers.py
yt/data_objects/selection_objects/slices.py
yt/data_objects/static_output.py
yt/data_objects/tests/test_cutting_plane.py
yt/funcs.py
yt/geometry/coordinates/cartesian_coordinates.py
yt/geometry/coordinates/coordinate_handler.py
yt/geometry/coordinates/tests/test_sanitize_center.py
yt/visualization/base_plot_types.py
yt/visualization/fits_image.py
yt/visualization/fixed_resolution.py
yt/visualization/particle_plots.py
yt/visualization/plot_modifications.py
yt/visualization/plot_window.py
yt/visualization/tests/test_plotwindow.py

Original goal: make errors much more informative than the current `RuntimeError(f'center keyword "{center}" not recognized')` raised by `PlotWindows.sanitize_center`, and improve the discoverability of the rich API that's actually implemented via error messages.
I've extended the goal to providing a more uniform API between plot windows and data selectors (which also have a "center" argument), because there was a lot of similar-yet different code basically accomplishing the same task there, as well as a couple things that worked with one but not the other.
I've added extensive tests for `CoordinateHandler.sanitize_center` and made the following changes:
- add much more verbose error message in case of invalid data type or incorrect value
- invalidate `center=YTArray(...)` if the array has …

ENH: uniformize API for "center" argument for plot windows

---

yt/frontends/boxlib/fields.py

this fixes the detection of how temperature is defined

MAESTROeX uses namespaces for paramters

---

tests/ci_install.sh
yt/tests/test_load_sample.py

fix yt configuration file used in CI
The solution is given by a warning
```
/home/runner/work/yt/yt/yt/utilities/configure.py:96: UserWarning: Could not load configuration file /home/runner/work/yt/yt/yt.toml (invalid TOML: Expected newline or end of document after a statement (at line 1, column 5))
```
fix my own mistake from #4311

TST: fixup logger configuration in CI

---

yt/utilities/answer_testing/answer_tests.py
yt/visualization/fixed_resolution.py

While working on pytest port I realized I have some local changes that should be pushed to yt repo first.
1. https://github.com/yt-project/yt/commit/3ed51d58491426c9dcfd4860050ff08c0788fa85 is fairly easy, it's just makes pytest do the same thing as nose. Otherwise some tests were broken on pytest side.
2. https://github.com/yt-project/yt/commit/8b35efb1666ab4836e8dcd270eb74dfb8c675a30 is clearly not tested by nose right now...
```
>>> import h5py as h5
>>> h5.File("/tmp/foo.h5", "w").create_dataset(("gas", "density"))
File "<stdin>", line 1, in <module>
File "/home/xarth/codes/xarthisius/yt/venv/lib/python3.8/site-packages/h5py/_hl/group.py", line 156, in 
create_dataset
name = self._e(name)
File …
```

Minor updates to answer tests infra

---

pyproject.toml

Small peeve, but we should not use upper bounds unless we have to (known incompatibilities). For a much more elaborated take on the matter, see https://iscinumpy.dev/post/bound-version-constraints/
I authored both constraints I'm lifting here. They do not correspond to any known incompatibilities.

BLD: drop unjustified upper bounds to optional dependencies

---

.github/workflows/type-checking.yaml

Citing [the documentation for `actions/checkout`](https://github.com/actions/checkout)
> Only a single commit is fetched by default, for the ref/SHA that triggered the workflow. Set fetch-depth: 0 to fetch all history for all branches and tags.
I think that I may have read this backwards or something when I explicitly added this option (or maybe I was just copy-pasting code from somewhere) ... anyway it's not needed and it wastes about 20s, let's clean it up.

TST: accelerate type-checking workflow

---

yt/geometry/_selection_routines/selector_object.pxi
yt/geometry/particle_oct_container.pyx
yt/geometry/selection_routines.pyx
yt/utilities/lib/contour_finding.pyx
yt/utilities/lib/geometry_utils.pyx
yt/utilities/lib/primitives.pxd
yt/utilities/lib/primitives.pyx
yt/utilities/lib/vec3_ops.pxd

Follow up to #4357 in response to https://github.com/cython/cython/issues/5288#issuecomment-1453161940
this one is a pure refactor (not a fix, and backward compatible) that just adopts the dominant import style for `cython.floating`

RFC: uniformize cython.floating usage

---

.github/workflows/wheels.yaml
pyproject.toml
yt/frontends/ramses/io_utils.pyx
yt/utilities/lib/basic_octree.pyx
yt/utilities/lib/geometry_utils.pyx

Fix most of the remaining compilation errors with Cython 3.0.0b1
Address the current top blocking problem in #4355
For context see https://github.com/cython/cython/issues/5299

BLD: fix compilation errors with Cython 3.0.0b1 (pow return type)

---

yt/geometry/oct_container.pyx

This resolves the last compilation error on Cython 3.0.0b1 currently listed in #4355
While this is sufficient to enable compilation on my personal dev machine, compilation still fails on GHA, so I won't enable continuous testing yet, and will tackle *these* issues next.

BLD: add missing noexcept qualifier (Cython 3 compat)

---

yt/geometry/particle_deposit.pxd
yt/geometry/particle_deposit.pyx
yt/utilities/lib/bounded_priority_queue.pxd
yt/utilities/lib/bounded_priority_queue.pyx
yt/utilities/lib/image_samplers.pxd
yt/utilities/lib/lenses.pyx
yt/utilities/lib/particle_kdtree_tools.pxd
yt/utilities/lib/particle_kdtree_tools.pyx

Fix a deprecation warning from Cython 3.0.0b1
```
The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython
```
reduce the compatibility gap with Cython 3.1
This is a noop on Cython 0.29.x

RFC: handle a deprecation warning from Cython (The keyword 'nogil' should appear at the end of the function signature line.)

---

yt/fields/vector_operations.py
yt/visualization/plot_modifications.py
yt/visualization/tests/test_callbacks.py

- Fixed typos in vector operations in spherical geometry
- Enable `Streamline` and `LineIntegralConvolution` callbacks for spherical geometry
- Callback tests added
Some further thoughts -- when using `Quiver`, `Streamline` and `LineIntegralConvolution` callbacks for curvilinear geometries, we assume users know what vector fields to plot (`_cartesian_x`, `_conic_x`, `_cylindrical_radius` etc.), while this is obscure and hidden in the source code. Maybe improvement could be made in future to generate a warning message when users try to use `inappropriate` vector fields in those callbacks.

BUG: Fix typo in vector operations and enable plot modifications for spherical geometry

---

pyproject.toml
yt/visualization/plot_window.py

The only reason why `pyparsing` is currently declared as a dependency is that `matplotlib.mathtext.MathTextParser` (which we actually use) may raise exceptions from within `pyparsing`, but this behaviour isn't actually specified by the API we actually depend on. From yt's standpoint, it's an implementation detail in matplotlib.
In retrospect it seems cleaner to just catch any exceptions, since all we do is reraise as a controlled exception type anyway.
This allows us to remove `pyparsing` as a dependency.

BLD: do not require pyparsing

---

doc/source/analyzing/saving_data.rst

I stumbled across an error in the [render of the docs](https://yt-project.org/docs/dev/analyzing/saving_data.html#generic-array-data). This should fix it.

Fix field access in ytdata docs.

---

yt/frontends/exodus_ii/data_structures.py

This makes two changes.  One is to fix an incorrect docstring.  The other is to
address an issue where if displacement fields do not exist, supplying
displacement values will result in the coordinates being set uniformly to zero.
This behavior can be seen to break with:
```python
ds = yt.load_sample("SecondOrderTets", step=-1,
displacements = {'connect1': (1.0, [0.0,0.0,0.0])})
s = yt.SlicePlot(ds, "y", ("all", "ux"))
```
The error message is confusing because it shows up as being an issue with the
selector.  This defaults to the behavior expected if the nodes are not named,
which should be the behavior for if displacement fields aren't found.

BUG: Fix example in docs and missing displacement for unstructured mesh

---

yt/utilities/lib/fp_utils.pxd

Partially addresses the performance regression with Cython 3.0 discussed in #4355 (in particular, for the scope of this PR, see https://github.com/yt-project/yt/issues/4355#issuecomment-1485895507)
`noexcept` is a new qualifier in Cython 3 (backported as a noop in Cython 0.29.33 for ease of transition), which allows to disable error propagation (which is the default behaviour in Cython 0.29).

PERF: add explicit noexcept qualifiers to fp_utils functions

---

yt/frontends/cholla/data_structures.py

The CHOLLA frontend identifies its dataset based on the presence of a couple of HDF5 attributes.  When a yt `LightRay` dataset is created from any frontend, it inherits all of the attributes from that frontend.  So when someone tries to load a `LightRay` dataset created from a CHOLLA frontend, yt gets confused as it thinks it's both a CHOLLA frontend as well as a `LightRay `dataset and it barfs.  This removes that degeneracy by specifically looking for the `LightRay` attribute in the HDF5 file and not counting it as a CHOLLA dataset when it finds it.  Bug reported by @evaneschneider .

Avoiding issue for CHOLLA LightRay datasets

---

yt/frontends/artio/_artio_caller.pyx
yt/geometry/_selection_routines/always_selector.pxi
yt/geometry/_selection_routines/boolean_selectors.pxi
yt/geometry/_selection_routines/compose_selector.pxi
yt/geometry/_selection_routines/cut_region_selector.pxi
yt/geometry/_selection_routines/cutting_plane_selector.pxi
yt/geometry/_selection_routines/disk_selector.pxi
yt/geometry/_selection_routines/ellipsoid_selector.pxi
yt/geometry/_selection_routines/grid_selector.pxi
yt/geometry/_selection_routines/indexed_octree_subset_selector.pxi
yt/geometry/_selection_routines/octree_subset_selector.pxi
yt/geometry/_selection_routines/ortho_ray_selector.pxi
yt/geometry/_selection_routines/point_selector.pxi
yt/geometry/_selection_routines/ray_selector.pxi
yt/geometry/_selection_routines/region_selector.pxi
yt/geometry/_selection_routines/selector_object.pxi
yt/geometry/_selection_routines/slice_selector.pxi
yt/geometry/_selection_routines/sphere_selector.pxi
yt/geometry/selection_routines.pxd
yt/utilities/lib/field_interpolation_tables.pxd
yt/utilities/lib/image_samplers.pxd
yt/utilities/lib/image_samplers.pyx

As tested on my fork, this resolves _most_ of the performance regressions seen in smoke tests with bleeding-edge CI (getting testing airtime from ~17min to ~8 min).
follow up to #4386

PERF: add explicit noexcept qualifiers to resolve perf regressions (Cython 3)

---

yt/geometry/_selection_routines/ray_selector.pxi
yt/utilities/lib/grid_traversal.pxd
yt/utilities/lib/grid_traversal.pyx

Follow up to #4386 and #4390
As far as I can tell, this is the last change in this series to bring perfs back to their baseline level with Cython 0.29.*, as -loosely- measured from the bleeding-edge CI airtime

PERF: add explicit noexcept qualifiers to resolve perf regressions in volume rendering (Cython 3)

---

yt/geometry/particle_oct_container.pyx
yt/utilities/lib/_octree_raytracing.pyx
yt/utilities/lib/amr_kdtools.pyx
yt/utilities/lib/grid_traversal.pyx

`IF` and `DEF` macros are deprecated in Cython 3. While it is not urgent to migrate to long term replacements, here I'm eliminating only occurences that are actually unused.

RFC: eliminate some unused deprecated Cython macros

---

yt/loaders.py
yt/tests/test_load_errors.py
yt/utilities/hierarchy_inspection.py

This PR allows users to explicitly select a specific class in a `Dataset` hierarchy, even if one or more of its subclasses are valid. I'm currently trying to improve the boxlib detection code by adjusting the class hierarchy (as brought up in https://github.com/yt-project/yt/issues/3005#issuecomment-809182817), but making e.g. `NyxDataset` inherit from `AMReXDataset` would break cases like #3510.

ENH: allow hint keyword for yt.load to select superclasses

---

yt/data_objects/static_output.py
yt/visualization/tests/test_fits_image.py

This is a very small fix.  For datasets that are in units of centimeters, any
zooming in on plots will switch from 1cm to 1e3 um in the base units of the
image axes.
This minor change inserts `mm` as an option for switching, which changes it to
allow for a middle-ground.  Seconds already allows `ms` so I think this should
also be fine.

ENH: Add millimeter to smallest units

---

yt/utilities/hierarchy_inspection.py
yt/utilities/tests/test_hierarchy_inspection.py

If a child class and its grandparent (or another ancestor) are the only classes in `candidates`, the previous implementation of `find_lowest_subclasses` would return both the child class and the parent class. This PR changes the logic so that it will only return classes passed in as candidates.
Needed by #4402.
```python
>>> import inspect
>>> from collections import Counter
>>> from functools import reduce
>>> class Grandparent:
...     pass
... class Parent(Grandparent):
...     pass
... class Child(Parent):
...     pass
>>> candidates = [Grandparent, Child]
>>> mros = [inspect.getmro(c) for c in candidates]; mros
[(__main__.Grandparent, object),
(__main__.Child, __main__.Parent, __main__.Grandparent, object)]
>>> counters = [Counter(mro) for mro in mros]; counters …
```

BUG: make sure find_lowest_subclasses doesn't add extra classes

---

yt/utilities/hierarchy_inspection.py
yt/utilities/tests/test_hierarchy_inspection.py

This implementation is more straightforward than the original one with fewer edge cases that need special handling.
It ended up being quite similar to the final implementation in #4405, except it can handle having the same class show up in candidates more than once.
It simply makes a set of all the superclasses of the candidates, and filters out any candidates that appear in that set.

RFC: rewrite find_lowest_subclasses to better match its intent

---

yt/_maintenance/backports.py
yt/_maintenance/deprecation.py
yt/data_objects/static_output.py
yt/data_objects/tests/test_registration.py
yt/fields/local_fields.py
yt/frontends/artio/artio_headers/LICENSE
yt/frontends/cf_radial/data_structures.py
yt/frontends/chimera/data_structures.py
yt/frontends/enzo_e/data_structures.py
yt/frontends/ramses/data_structures.py
yt/frontends/stream/data_structures.py
yt/geometry/coordinates/spherical_coordinates.py
yt/geometry/coordinates/tests/test_sanitize_center.py
yt/loaders.py
yt/units/_numpy_wrapper_functions.py
yt/utilities/logger.py
yt/utilities/on_demand_imports.py
yt/utilities/tests/test_config.py
yt/utilities/tests/test_on_demand_imports.py
yt/visualization/_handlers.py
yt/visualization/base_plot_types.py
yt/visualization/color_maps.py
yt/visualization/fixed_resolution.py
yt/visualization/plot_window.py
yt/visualization/tests/test_plotwindow.py
yt/visualization/tests/test_save.py

Fix a bunch of typos detected (and mostly auto-fixed) with `codespell`

DOC: fix typos

---

yt/frontends/ramses/tests/test_hilbert.py
yt/loaders.py
yt/visualization/volume_rendering/transfer_functions.py

closes #4421 
running bleeding-edge CI on my fork for validation at https://github.com/neutrinoceros/yt/actions/runs/4764348746

DEPR: avoid deprecated implicit casting of single element arrays to scalar types

---

tests/tests.yaml
yt/frontends/arepo/data_structures.py
yt/frontends/arepo/fields.py
yt/frontends/sph/fields.py

This PR:
* Makes the `"cell_volume"` field for Arepo datasets have `"gas"` type
* Make `"star_formation_rate"` an alias for `"StarFormationRate"` in Gadget and its derivatives
* Expand the number of places that yt looks for unit definitions in Arepo HDF5 files
* Fixes an issue with the pressure field (should be `sampling_type="local"` and not `"particle"`)
* If the H mass fraction is in the dataset, use that to construct the `H_number_density` field if there is no `NeutralHydrogenAbundance` field
In the course of testing this PR @Xarthisius and I found that Jenkins did not have the same version of the `TNGHalo` test dataset as yt-project.org/data, hence also the answer bump.

Small Arepo/Gadget enhancements

---

nose_ignores.txt
tests/tests.yaml
yt/data_objects/static_output.py
yt/frontends/flash/data_structures.py
yt/frontends/halo_catalog/data_structures.py
yt/frontends/ytdata/data_structures.py
yt/geometry/particle_geometry_handler.py
yt/geometry/particle_oct_container.pyx
yt/geometry/tests/test_ewah_write_load.py
yt/geometry/tests/test_particle_octree.py

Issue #4371 highlighted some problems with EWAH files for SPH data and @matthewturk outlined a possible route to fix them. 
The following script fails on `main`, assuming no EWAH file has been written:
```python
import yt
from yt.testing import assert_almost_equal
ds = yt.load("TNGHalo/halo_59.hdf5")
_, c = ds.find_max(("gas","density"))
c += ds.quan(0.5, "Mpc")
sp = ds.sphere(c, (20.0, "kpc"))
mass = sp.sum(("gas","mass"))
#print(ds.index.pii.filename)
del ds
ds2 = yt.load("TNGHalo/halo_59.hdf5")
_, c2 = ds2.find_max(("gas","density"))
c2 += ds2.quan(0.5, "Mpc")
sp2 = ds2.sphere(c, (20.0, "kpc"))
mass2 = sp2.sum(("gas","mass"))
assert_almost_equal(mass, mass2)
```
In the first load of the dataset, there is no EWAH file, and it creates the bitmasks, caches them in the new EWAH file, and …

BUG: More robust detection and checking of EWAH files

---

tests/tests.yaml
yt/fields/derived_field.py
yt/visualization/_commons.py
yt/visualization/plot_container.py
yt/visualization/plot_window.py
yt/visualization/profile_plotter.py

closes #4416
follow up to #3282 and #3637

BUG: fix inconsistent units labelling between plot axis and colorbar

---

yt/sample_data/api.py

Reprod: leaving `test_data_dir` unset, and running
```python
import yt
ds = yt.load("not_a_file")
```
output
```python-traceback
FileNotFoundError: No such file or directory: 'not_a_file'.
(Also tried '/Users/robcleme/dev/yt-project/yt/not_a_file').
```
where `/Users/robcleme/dev/yt-project/yt/` is the current work directory, so it looks like yt is considering the *absolute* version of cwd as an alternative, which is both confusing and unintended.
with this patch, the error is reduced to 
```python-traceback
FileNotFoundError: No such file or directory: 'not_a_file'.
```

BUG: fix confusing error message when yt fails to locate data

---

yt/geometry/coordinates/coordinate_handler.py
yt/utilities/minimal_representation.py

Some low-hanging simplifications I found while working on #4179 
`functools.cached_property` wasn't available before Python 3.8 which explains why these properties didn't use it already.
As a side bonus, I also discovered and replaced two occurrences of `abc.abstractproperty`, which is deprecated since Python 3.3

RFC: simplify base CoordinateHandler implementation (cached properties)

---

yt/data_objects/construction_data_containers.py
yt/data_objects/tests/test_sph_data_objects.py
yt/fields/field_info_container.py

The following script fails on `main`:
```python
from yt import load
bbox = [[40669.34, 56669.34], [45984.04, 61984.04], [54114.9, 70114.9]]
ds = load("TNGHalo/halo_59.hdf5", bounding_box=bbox)
w = ds.quan(0.2, "Mpc")
le = ds.domain_center-0.5*w
re = ds.domain_center+0.5*w
g = ds.r[le[0]:re[0]:128j,le[1]:re[1]:128j,le[2]:re[2]:128j]
print(g["gas","temperature"].min())
print(g["gas","kT"].min())
```
with this error:
```pycon
File "/Users/jzuhone/fix_grid.py", line 9, in <module>
print(g["gas","kT"].min())
~^^^^^^^^^^^^
File "/Users/jzuhone/Source/yt/yt/data_objects/data_containers.py", line 235, in __getitem__
self.get_data(f)
File "/Users/jzuhone/Source/yt/yt/data_objects/construction_data_containers.py", line 899, in get_data
self._fill_sph_particles(fields)
File …
```

[BUG] Allow smoothing of derived SPH fields onto covering grids

---

yt/frontends/ramses/data_structures.py
yt/geometry/grid_geometry_handler.py

reprod: `python -c "import yt; yt.load_sample('IsolatedGalaxy').print_stats()"`
output (main):
```
...
Smallest Cell:
Width: 1.221e-04 Mpc Mpc
Width: 1.221e+02 pc pc
Width: 2.518e+07 AU AU
Width: 3.767e+20 cm cm
```
output (this branch):
```
...
Smallest Cell:
Width: 1.221e-04 Mpc
Width: 1.221e+02 pc
Width: 2.518e+07 AU
Width: 3.767e+20 cm
```
`unyt_array` already implements str formatting in a way that includes units, so including it a second time is redundant

BUG: fix a bug in Dataset.print_stats() where length units would be printed twice

---

yt/fields/particle_fields.py

All this PR does is whitelist the SPH `star_formation_rate` field so that it automatically gets aliased to `"gas"` from its SPH particle type.

Whitelist the SPH star_formation_rate field

---

yt/visualization/volume_rendering/camera_path.py

This fixes a minor issue with the `Keyframe` class.

BUG: Turn range into a list for keyframes

---

yt/data_objects/selection_objects/data_selection_objects.py

BUG: fix a confusing warning emitted when a dimensionless derived field is registered with implicit units

---

yt/visualization/fixed_resolution.py
yt/visualization/tests/test_particle_plot.py

The new off-axis particle projections currently fail when a `weight_field` is provided:
```python
p = yt.ParticleProjectionPlot(ds, L, ("PartType4", "particle_velocity_z"), 
weight_field=("PartType4","particle_mass"))
```
gives:
```pycon
---------------------------------------------------------------------------
File ~/Source/yt/yt/visualization/particle_plots.py:454, in ParticleProjectionPlot.__init__(self, ds, normal, fields, color, center, width, depth, weight_field, axes_unit, origin, fontsize, field_parameters, window_size, aspect, data_source, deposition, density, north_vector, axis)
450     plt_origin = "center-window"
452 self.projected = weight_field is None
--> 454 PWViewerMPL.__init__(
455     self,
456     ParticleSource,
457     bounds,
458     origin=plt_origin,
459 …
```

BUG: Fix off-axis particle projections with a weight field

---

yt/visualization/plot_modifications.py
yt/visualization/tests/test_callbacks.py

This callback already works as intended with simple parametrization, I think it's worth unlocking now.
```python
import yt
from yt.testing import fake_amr_ds
ds = fake_amr_ds(geometry="spherical")
p = yt.SlicePlot(ds, "r", "Density")
p.annotate_timestamp(draw_inset_box=True)
p.save("/tmp/sph.png")
```

BUG: unlock annotate_timestamp callback for polar and spherical geometries

---

yt/geometry/particle_geometry_handler.py

see https://github.com/yt-project/yt/issues/3825#issuecomment-1050746232

BUG: fix confusing formatting in log message when allocating <10k particles

---

doc/source/visualizing/callbacks.rst
yt/visualization/plot_modifications.py
yt/visualization/tests/test_callbacks.py

Closes #4454, incidentally fix a couple small issues with `StreamlineCallback`'s implementation.
demo:
```python
import yt
ds = yt.load("IsolatedGalaxy/galaxy0030/galaxy0030")
p = yt.ProjectionPlot(ds, "z", ("gas", "density"))
p.annotate_streamlines(
("gas", "velocity_x"),
("gas", "velocity_y"),
linewidth=("gas", "velocity_z"),
linewidth_upscaling=3,
color=("gas", "velocity_magnitude"),
cmap="turbo",
)
p.zoom(20)
p.save("/tmp/")
```

ENH: add support for passing field keys for colors and linewidth in streamline plot annotations

---

conftest.py
yt/data_objects/profiles.py
yt/data_objects/static_output.py

I am (perhaps naively) thinking this may be a low hanging fruit, let's see how many tests actually raise this warning and if they're fixable.

BUG: fix internal divide-by-zero warnings

---

yt/visualization/plot_window.py

I encountered a crash while trying to use yt's CLI to plot a dataset. I'm not sure what conditions lead to `normal` being a numpy integer yet but this patch fixes my problem.

BUG: fix an issue where NormalPlot.sanitize_normal_vector would raise an error when receiving a numpy integer

---

yt/testing.py

Closes #4507 by moving the pytest import to within the only function that uses it in `yt.testing`.

nest the pytest import in yt.testing

---

yt/frontends/nc4_cm1/io.py

Fixes 4512.
We need to convert chunks to a list so we don't exhaust it the first time we iterate, and we also need to reset offset to 0 every loop over fields.

BUG: Fix cm1 chunk reader

---

yt/loaders.py
yt/sample_data/api.py
yt/tests/test_load_sample.py

Context: internally, `yt.load_sample` uses `pooch` to retrieve data from the hub server. Because data is obtained most often as compressed archives, we first download it to a temporary directory (`yt_download_cache`). This is an implementation detail that should not be directly visible to users.
This PR does two things:
- clean up the directory after it's served its purpose (this doesn't prevent pooch from re-creating it during the same session if needed)
- ~prepend a `.` to its name so its "hidden" in the conventional POSIX sense~

ENH: cleanup empty cache directory after a successful call to load_sample

---

conftest.py

closes #4515
These filters *should* quickly become unneeded, as discussed in #4515 , but they should get CI working again in the mean time.

TST: filter numpy 1.25 deprecation warnings triggered by other deps

---

yt/_maintenance/deprecation.py
yt/tests/test_load_errors.py
yt/visualization/tests/test_set_zlim.py

DEPR: use builtin DeprecationWarnings

---

yt/frontends/fits/data_structures.py

closes #4532 (regression from #3772)
Explanation: #3772 made a change to `ds.parameter_filename` causing it to always be a "resolved path", which in the case of in-memory fits dataset makes no sense, and breaks `FitsDataset.unique_identifier`.

BUG: fix a regression preventing loading of fits datasets

---

yt/fields/derived_field.py

This PR:
* moves the docstrings for the `FieldValidator` subclasses up out of their `__init__` methods so they get picked up by the docs build
* adds some details to the docstrings
* adds some minimal typing 
* auto-populates the base `FieldValidator` docstring to point to the available subclasses. 
Background: I was working using one of the `FieldValidator`and noticed that all the docstrings [here](https://yt-project.org/doc/reference/api/yt.fields.derived_field.html#yt.fields.derived_field.FieldValidator) were empty despite their presence in the `__init__` methods. Thought it'd be useful to bump those up so we catch them during the docs build... and then I made an effort to improve the docstrings. 
I'm not **super** familiar with the different validators, so it's possible I …

improve docs for FieldValidator objects

---

tests/ci_install.sh

Apparently conda now knows how to parse pip requirement files natively, so we should be able to remove this hack.

TST: simplify install script on windows

---

yt/visualization/color_maps.py

Taking only the objectively-better part of #4538

RFC: avoid double-copies of cmyt colormaps

---

yt/frontends/moab/data_structures.py

This fixes a couple issues with *loading* in-memory PyNE datasets, discussed in #4535 (one regression from #3772, and one compatibility issue).
At the time I'm opening this, it doesn't resolve *all* integration issues we're seeing with PyNE (`SlicePlot` is still broken), but it is possible that remaining problems should be resolved in PyNE rather than yt.

BUG: fix a regression preventing loading of pyne/moab datasets

---

yt/funcs.py
yt/utilities/png_writer.py
yt/visualization/base_plot_types.py
yt/visualization/tests/test_save.py

Store information about used software (yt, matplotlib, numpy, PIL) in metadata of generated plots.
1. Generate simple SlicePlot, ProjectionPlot, off-axis projection / VR png.
2. Use e.g. ImageMagick to inspect resuting pngs:
```
$ identify -verbose galaxy0030_offaxis_projection.png | grep Software
Software: PIL-9.5.0|yt-4.3.dev0
$ identify -verbose *.png | grep Software
Software: Matplotlib version3.7.1, https://matplotlib.org|NumPy-1.24.2|yt-4.3.dev0
```

enh: store basic software info in png metadata

---

doc/source/examining/loading_data.rst
tests/tests.yaml
yt/frontends/athena_pp/data_structures.py
yt/frontends/athena_pp/io.py
yt/frontends/athena_pp/tests/test_outputs.py

This PR provides support for stretched grids in Athena++. I've restored the `test_disk` test that was causing issues before. 
Closes (or probably closes) several issues, including #1585, #3389, #3619, and #4557, because it removes the buggy code that was previously handling grids with non-uniform cell spacing.

Athena++ stretched grids support

---

doc/source/visualizing/callbacks.rst

update annotate_contours docs to avoid deprecated API

---

yt/fields/field_detector.py

The `FieldDetector` class mocks up a fake dataset from a `defaultdict` if a dataset is not passed. It has to attach a number of basic yt attributes to this `fake_dataset` class, but at the end it tries to use the `force_periodicity` method, which of course exists on the `Dataset` class but not here. I'm just setting the periodicity here by hand, which is the previous behavior and should never have been changed here. 
I ran into this bug on accident--not sure if it affects anything, but this is the right fix for now until we do something better.

Fix fake_dataset periodicity attribute in FieldDetector

---

yt/funcs.py
yt/loaders.py
yt/sample_data/api.py
yt/tests/test_external_frontends.py
yt/utilities/command_line.py
yt/utilities/configure.py
yt/utilities/on_demand_imports.py
yt/utilities/parameter_file_storage.py
yt/visualization/_commons.py
yt/visualization/plot_container.py

- `import netCDF4` is responsible for ~6% startup overhead, let's delay it when we can afford it.
- `import importlib.metadata` is about ~3% (we still need to import it to determine matplotlib's version at runtime, which we'll be able to avoid [when support for mpl<3.5 is dropped](https://github.com/yt-project/yt/issues/4379))
- multiprocessing, tarfile, tomllib, tomli_w are (collectively) about ~1%
nothing life-changing here but every % counts (yt's CLI still takes a couple seconds to do *anything*).

PERF: delay rarely used imports (netcdf4, importlib, multiprocessing, tarfile, tomllib, tomli_w)

---

.github/workflows/bleeding-edge.yaml

Automate reporting of failures in scheduled tests with future dependencies, also reduce their frequency from daily to weekly. This technique is taken from matplotlib. As a test, I deployed it in a personal repo and found that it worked without any further configuration.
closes #3731

TST: switch future-dependencies tests from daily to weekly frequency, add auto-reporting in case of failure

---

yt/frontends/flash/data_structures.py

reprod: `python -Werror doc/source/cookbook/render_two_fields.py`
see https://numpy.org/doc/stable/release/1.25.0-notes.html#deprecations

BUG: avoid deprecated numpy API in flash frontend (implicit conversion of 1-sized arrays to scalar types is deprecated in numpy 1.25)

---

yt/data_objects/construction_data_containers.py

For exporting surfaces to 3D objects there are a few options, for example `export_blender` and `export_sketchfab.`  `export_sketchfab` does not include the ability to limit the range of the color field (`export_blender` does).  This PR brings that functionality to `export_sketchfab` through optional arguments.
- [ x ] New features are documented, with docstrings and narrative docs

option to include min/max limits on the color field for export_sketchfab

---

doc/source/cookbook/particle_filter.py

DOC: fix string interpolation (units double-printing) in particle_filter cookbook recipe

---

yt/utilities/amr_kdtree/amr_kdtree.py

reprod: `python -Werror doc/source/cookbook/render_two_fields.py`
note that with numpy>=1.25.0, #4585 also gets in the way

BUG: avoid divide-by-zero runtime warning from np.log10 in AMRKDTree.get_brick_data

---

yt/frontends/ytdata/io.py

The main change in this PR is to avoid unnecessarily building a mask for particle selection when the selector is `all_data()`. This cuts down the load time **significantly** for particle counts in the range of 1e6+  (and probably lower, but I only tested above 1e6)
To test out this PR, I built some test particle datasets with 1e6 to 1e7 particles:
```python
import yt
from yt.testing import fake_particle_ds
def create_tst_data_on_disk(nparticles):
nparticles = int(nparticles)
ds = fake_particle_ds(npart=nparticles)
fn = f"test_data_{nparticles}"
ad.save_as_dataset(fn, fields = ds.field_list)
return fn + ".h5"
fn = create_tst_data_on_disk(1e7)  # repeat for other particle counts...
```
and then reloaded each 
```python
ds = yt.load(fn)
ds.field_list
ds.index
```
and timed …

ytdata: check for `all_data` in particle selection

---

yt/frontends/ytdata/io.py

Ok, this one should actually Close #4565 
The problem was that the `ytdata` `IOHandlerYTDataContainerHDF5` was not using the `data_file` `start` and `end` index ranges when processing each chunk, so every iteration was loading the full index range. Given that `_count_particles` **does** use the proper index range, it seemed better to correct `_read_particle_coords` and `_read_particle_data_file` to also use the index range rather than disable chunking for particles here. 
Looking through the other `ytdata` IOHanlders, it does seem that those should be updated as well. I'm going to open another issue for that though, as I'd like to get this one through on the faster side if possible.

ytdata io: use data_file.start and .end index range

---

yt/frontends/stream/data_structures.py
yt/frontends/stream/tests/test_stream_octree.py
yt/geometry/oct_container.pxd
yt/geometry/oct_container.pyx
yt/geometry/oct_visitors.pxd
yt/geometry/oct_visitors.pyx
yt/geometry/particle_oct_container.pyx

Fixes #4545.
We don't store the level trait for an Oct as an attribute of the Oct itself, so it has to be collected during the initial traversal.  This adds it to the `load_octree` command via the `LoadOctree` visitor, and then it sets an attribute on the dataset.  I looked and this only causes problems for the stream octrees.
This fixes an issue wherein loading an octree then results in just the root oct being selected regardless of the selection method.

BUG: Fix initialization of max level in load_octree

---

doc/source/cookbook/tests/test_cookbook.py

Extracted from #4575
This is helpful in reproducing tests jobs locally. In particular, when some test hangs the process, it helps decipher which one.
Also improves portability for Windows

TST: run cookbook recipes in a deterministic order

---

yt/frontends/ramses/data_structures.py
yt/geometry/grid_geometry_handler.py

BUG: fix string interpolation (units double-printing) in GridIndex

---

doc/source/cookbook/tests/test_cookbook.py

This utility function doesn't seem to be used anywhere (I think `check_recipe` is doing the same job, but is actually used)

TST: cleanup unused test code

---

yt/frontends/gizmo/data_structures.py
yt/frontends/gizmo/tests/test_outputs.py
yt/sample_data_registry.json

I'd like to suggest two changes to the GIZMO frontend to fix what I believe is a potential bug and to handle updates to the hdf5 interface (this was mentioned on the Slack #help channel in December(?) but I no longer have access to that post and can't reference it). I'm starting with a draft because a) technically these are two separate issues and could go into two separate PR's, but the first is so minor it seemed unnecessary and b) I'm not sure I've resolved the 2nd issue in the proper yt fashion.
1. dmetal check - GIZMO runs with METALS flag enabled but without COOL_METAL_LINES_BY_SPECIES, GALSF_FB_FIRE_RPROCESS, GALSF_FB_FIRE_AGE_TRACERS, or STARFORGE_FEEDBACK_TRACERS enabled will have a per-particle metallicity field (loaded as dmetal) with shape `(NUM_PARTICLES, )`.  Thus, the …

BUG: Update GIZMO frontend to handle newer GIZMO versions

---

yt/frontends/adaptahop/io.py
yt/frontends/ahf/io.py
yt/frontends/gadget_fof/io.py
yt/frontends/halo_catalog/io.py
yt/frontends/http_stream/io.py
yt/frontends/owls_subfind/io.py
yt/frontends/rockstar/io.py
yt/frontends/sdf/io.py
yt/frontends/stream/io.py
yt/frontends/tipsy/io.py
yt/frontends/ytdata/io.py
yt/utilities/io_handler.py

This PR reduces duplicated code related to iterating over `data_file` chunks in `_read_particle_coords` and `_read_particle_fields` across IOHandlers. Shouldn't affect any behavior...

reduce code duplication in IOHandler _read_particle_coords and _read_particle_fields 

---

setup.py

Sort input file list similar to #2206
so that `grid_traversal.cpython-310-x86_64-linux-gnu.so` builds in a reproducible way
in spite of non-deterministic filesystem readdir order and http://bugs.python.org/issue30461
See https://reproducible-builds.org/ for why this is good.
This PR was done while working on [reproducible builds for openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).

BLD: Sort input file list

---

yt/frontends/gadget/data_structures.py

This change updates the `_parse_parameter_file` function in the Gadget frontend to match the changes developed in PR #4470. In summary:
1. Change try/except to if/else
2. Remove only_on_root wrapper to mylog.info
3. Change fall-back omega_matter from 1 to 0
4. Condense prefix logic
I've left the for/else structure in, since in #4470 I just removed it (didn't need to support Gadget-2 format for Gizmo files) and so haven't fully thought of what the replacement should look like. 
I believe this neither adds new features, nor fixes any bugs, and is more of a code cleanup than anything else.

Updates to the _parse_parameter_file function following PR 4470

---

yt/frontends/ramses/fields.py
yt/frontends/ramses/io.py
yt/frontends/ramses/particle_handlers.py
yt/utilities/on_demand_imports.py

Hi everyone,
this pull request is to implement a reader to read the output from ramses sink particle algorithm. 
For now, the sink ouput from the standard ramses (the one from the bitbucket) cannot be read. It's only an other format.
In each output_*****, the sink algo write a single sink_****.csv file with the properties of the sinks. I have added an example in attached file. 
We need to read a single file per output folder in the csv format. 
I think that the ideal would be to have a single ptype corresponding to the sinks (do not create a 'sink_csv' type). The read_header would have to be modified and specified as appropriate. For now, I have impleneted a new name 'sink_csv' to differentiate from the first class. 
The main issue I had is the ` IOHandlerRAMSES._read_particle_fields ` …

[ENH] support for sinks in csv format for RAMSES frontend

---

setupext.py

BLD: forbid deprecated numpy C API

---

.github/workflows/wheels.yaml
pyproject.toml

follow up to #4575 , fix wheels workflow (see the latest broken run on https://github.com/yt-project/yt/actions/runs/5764087947)

BLD: fix wheels workflow (sync build requirements with pyproject.toml)

---

pyproject.toml

I'm setting [the implicit value `build-backend`](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#fallback-behaviour) explicitly, as recommended.
`setuptools`' doc also clarifies that `wheel` requirement isn't needed as it's *implied* by using the `setuptools_meta` backend, so I'm removing it. See https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use
>  You should only include wheel in requires if you need to explicitly access it during build time (e.g. if your project needs a setup.py script that imports wheel).

BLD: explicitly specify build-backend

---

.github/workflows/build-test.yaml
conftest.py
pyproject.toml
tests/ci_install.sh
tests/windows_conda_requirements.txt
yt/geometry/tests/test_geometries.py

Cartopy 0.22 was just released and is supposed to resolve a couple workarounds we've been using to test it.
Most notably, this version doesn't depend on GEOS, and as such, it can afford to have *wheels*, which should allow us to properly test it on all platforms for cheap !

TST: simplify cartopy integration testing (using cartopy 0.22)

---

pyproject.toml
setupext.py

 BLD: migrate from oldest-supported-numpy to NPY_TARGET_VERSION (Python >= 3.9)

---

yt/data_objects/selection_objects/data_selection_objects.py
yt/data_objects/tests/test_add_field.py

close #4636
Opening as a draft with just the tests, patch incoming.

BUG: fix a crash with certain combinations of kwargs for adding dimensionless derived fields to datasets

---

yt/frontends/artio/_artio_caller.pyx
yt/geometry/_selection_routines/selector_object.pxi
yt/geometry/oct_container.pxd
yt/geometry/oct_container.pyx
yt/geometry/oct_visitors.pxd
yt/geometry/particle_deposit.pxd
yt/geometry/selection_routines.pxd
yt/geometry/selection_routines.pyx
yt/utilities/lib/bounding_volume_hierarchy.pxd
yt/utilities/lib/bounding_volume_hierarchy.pyx
yt/utilities/lib/cykdtree/kdtree.pxd
yt/utilities/lib/cyoctree.pyx
yt/utilities/lib/distance_queue.pyx
yt/utilities/lib/embree_mesh/mesh_intersection.pxd
yt/utilities/lib/embree_mesh/mesh_intersection.pyx
yt/utilities/lib/embree_mesh/mesh_samplers.pxd
yt/utilities/lib/embree_mesh/mesh_samplers.pyx
yt/utilities/lib/field_interpolation_tables.pxd
yt/utilities/lib/fnv_hash.pxd
yt/utilities/lib/fnv_hash.pyx
yt/utilities/lib/geometry_utils.pyx
yt/utilities/lib/image_samplers.pyx
yt/utilities/lib/lenses.pxd
yt/utilities/lib/mesh_triangulation.pyx

With the release of Cython 3.0, we've had some issues with performance regressions due to missing `noexcept` declarations.  This goes through and changes all functions that are `nogil` into `noexcept nogil`.  Earlier PRs had done a fair bit of this, but this does the remainder.

MNT: All nogil into noexcept nogil

---

yt/data_objects/static_output.py

In some cases, particularly when instantiating lots of child masks, the way the `MutableAttribute` object is set up could lead to `find_spec` being called inside some tight loops.
But, the results of `find_spec` shouldn't change during the course of one interpreter's existence.  So we can move the checks to the outside of the `__get__` call, which reduces costs of grid indexing considerable in some cases.

ENH: Only call find_spec sometimes

---

yt/visualization/_handlers.py
yt/visualization/base_plot_types.py
yt/visualization/volume_rendering/scene.py

~this is a test-only PR, not meant to be merged.
In particular, test newly supported type-checking for Python >= 3.9~
edit: this has now survived type-checking with matplotlib 3.8.0rc1, so I rewrote the branch history to preserve dependencies and fix newly discovered type-checking incompatibilities instead.

TYP: fix type-checking incompatibilities with matplotlib 3.8

---

yt/visualization/plot_modifications.py

At the moment, when you use `annotate_grids()` to show boxes and compare simulations with different
numbers of refinement levels, the colors don't correspond to one another across simulations.  For example,
here are 4 different simulations.  One has base + 1 level, then next 2 levels, then 3, and finally 4 levels of refinement
(all are jumps of 2x).  Notice that the color for level 1 is not the same across all simulations:
Here's the output with this PR if I pass `use_max_level_in_cmap=True` to `annocate_grids()`.
Note: I am unsure why the original behavior was desired, but I left it in place.

allow annotate_grids to force cmap to respect max_levels

---

pyproject.toml
yt/_typing.py
yt/geometry/coordinates/cartesian_coordinates.py
yt/geometry/coordinates/coordinate_handler.py
yt/geometry/coordinates/cylindrical_coordinates.py
yt/geometry/coordinates/geographic_coordinates.py
yt/geometry/coordinates/spherical_coordinates.py
yt/utilities/lib/pixelization_routines.pyx
yt/visualization/base_plot_types.py
yt/visualization/fixed_resolution.py
yt/visualization/plot_window.py
yt/visualization/tests/test_image_comp_2D_plots.py
yt/visualization/volume_rendering/off_axis_projection.py
yt/visualization/volume_rendering/tests/test_off_axis_SPH.py

Close #4639
At the time of opening, this is at the proof-of-concept level and only works for the specific case that was used to illustrate the issue, but breaks pixelizing data in all other geometries.
I'll iterate some more until all tests are green again.
TODO:
*edit now that this is marked as ready for review:*
I've made my best to preserve backward compatibility and make the new behaviour in pixelizers opt-in. However there are a couple questions I would like to discuss with reviewers:
- would an actual masked array make more sense as a return type than a tuple (image, mask) ?
- should additional computations be made optional too ? In the present implementation, masks are computed in all cases, but may not be returned (to preserve backward compat).
- I know I broke backward …

ENH: make unused pixels actually transparent in all imshow-based 2D visualisations

---

.pre-commit-config.yaml

As per https://github.com/psf/black/releases/tag/23.9.0, the new mirror repo makes black 2x faster when run through pre-commit using mypyc-compiled wheels

MNT: switch to faster black pre-commit hook, and upgrade black

---

yt/loaders.py
yt/utilities/parallel_tools/parallel_analysis_interface.py

One option to Close #4635 
This separates the data fetching and path construction from the `yt.load` call that `load_sample` does so that the first part can be easily moved to a blocking root-only call and then the valid path can be broadcast to the mpi processes.

make load_sample MPI-safe

---

doc/source/examining/loading_data.rst
yt/fields/particle_fields.py
yt/frontends/arepo/fields.py
yt/frontends/gadget/definitions.py
yt/frontends/gadget/fields.py
yt/frontends/gadget/io.py
yt/frontends/gadget/tests/test_outputs.py
yt/frontends/gizmo/fields.py
yt/frontends/sph/fields.py

Continuing to find improvements to be made to detection of SPH fields:
* Supporting Gadget fields such as `"ColdFraction"`, `"CloudFraction"`, and `"HotPhaseTemperature"` with yt-like aliases. 
* Support AREPO/TNG fields `"cooling_rate"` and `"cooling_time"`.
* Metal fields can be of `"local"` `sampling_type` or `"particle"` `sampling_type` depending on if they are star or gas particles. 
* The core of the PR is to make detection of metal fields much more flexible for Gadget and its derivatives, accounting for the (somewhat unfortunate) variety of naming schemes for how these fields are stored in files.
Tests, and probably a bit of documentation about how metal fields are detected, are incoming.

more SPH field improvements

---

yt/visualization/_handlers.py
yt/visualization/base_plot_types.py

follow up to #4629 now that matplotlib 3.8.0 is finalised.

TYP: fix type-check incompatibilities with matplotlib 3.8

---

yt/frontends/stream/tests/test_callable_grids.py
yt/loaders.py

`load_hdf5_file` serves as a way to load arbitrary HDF5 files with the stream frontend as a wrapper around `load_amr_grids`. It accepts a bounding box argument `bbox` that can be used to determine the grid decomposition, but this bounding box is not passed to `load_amr_grids` itself and therefore the actual bounding box does not change. This PR addresses that issue and provides a test.

BUG: load_hdf5_file doesn't pass bounding box to load_amr_grids

---

conftest.py

This filter should never be used anymore since we now require numpy >= 1.19.3 (first version with Python 3.9 support)

TST: remove unused warning filter

---

yt/data_objects/index_subobjects/grid_patch.py
yt/geometry/_selection_routines/data_collection_selector.pxi
yt/geometry/_selection_routines/grid_selector.pxi
yt/geometry/_selection_routines/ortho_ray_selector.pxi
yt/geometry/_selection_routines/ray_selector.pxi
yt/geometry/_selection_routines/selector_object.pxi
yt/geometry/_selection_routines/slice_selector.pxi
yt/utilities/amr_kdtree/amr_kdtree.py

While working on #4630 , I noticed that we could avoid an np.sum() by having fill_mask_regular_grid return the selection count that it's already tracking. Savings are small, but I thought it was worth the change to avoid recalculating a number we already have.

PERF: return the count from fill_mask_regular_grid

---

yt/data_objects/tests/test_image_array.py
yt/utilities/lib/tests/test_alt_ray_tracers.py
yt/utilities/tests/test_set_log_level.py
yt/visualization/image_writer.py

Restore numpy's error handling settings and yt's logging level during module teardown.
I found that `test_fisheye` in `yt/visualization/volume_rendering/tests/test_vr_cameras.py` was failing when I ran just the visualization tests, but not the full test suite.

TST: restore global state modified during tests

---

.github/workflows/bleeding-edge.yaml
conftest.py
pyproject.toml

matplotlib started shipping (unstable) wheels on pypi.anaconda.org, let's try and see where we're at.
edit: no they didn't, I just misread [the index](https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/matplotlib/). I'll refresh this PR when it actually happens.

TST: start testing nightlies on CPython 3.12

---

.github/workflows/build-test.yaml

This is made possible by #4621
I tested it on my fork and saw that testing time for windows dropped from ~30min to ~20, with *less* tests being skipped.

TST: stop using conda on Windows CI

---

yt/visualization/plot_container.py

This is a fun one.  After profiling profiling operations for both memory and time, I noticed that the memory was doubling right at the end.  (Turns out, so was the time, but that's not as obvious always.)  What was happening was that the profile, which was being created using chunked IO/processing, was not sufficient for computing the units -- instead, the base `plot_container.py:1106` line would access the field inside the base object.  This has the effect of, on every processor, doing a `chunk_all` on the `data_source`, which means now we have every element resident in memory.
This uses the `field_info` container instead.

BUG: Don't access `data_source[field]` to get units

---

yt/loaders.py
yt/tests/test_load_sample.py

Closes #4691 
Was easiest to just move the check for `fn is None` out of `_get_sample_data` to the main `load_sample`. Also added a minimal test.

BUG: fix load_sample with no arguments

---

yt/visualization/plot_modifications.py
yt/visualization/tests/test_callbacks.py

BUG: make annotate_sphere and annotate_arrow safe when run after plot invalidation

---

yt/frontends/ramses/data_structures.py

The f90nml package is only required to parse the parameter file for RAMSES dataset, but that's not a hard requirement of the RAMSES frontend.

[BUGFIX] The f90nml package is *optional* to load RAMSES

---

yt/frontends/cholla/data_structures.py

Previously, the ``domain_right_edge`` attribute of ``ChollaDataset`` was initialized by assigning it the values of the ``"domain"`` attribute stored in the hdf5 file. This patch adjusts the logic so that the ``domain_right_edge`` attribute is now the sum of that array and the array stored in the ``domain_left_edge`` attribute.
Given the simplicity of this fix, I don't really think there's any need for new documentation. Plus adding a test is probably not worth the effort (we would need to either introduce a new cholla dataset OR duplicate and mutate the existing dataset).

minor bugfix in cholla frontend

---

doc/source/examining/Loading_Generic_Particle_Data.ipynb
yt/frontends/stream/data_structures.py
yt/frontends/stream/tests/test_stream_particles.py

Currently, the stream frontend checks for the presence for a SPH particle type by checking for simultaneous presence of the fields `("io", "smoothing_length")` and `("io","density")`, which mandates that the SPH particle type be `"io"`. This PR makes the specification of this field type more flexible. It also checks that only one SPH type is present (because we currently do not support more than one SPH particle type in general).
I edited the "Loading Generic Particle Data" doc to reflect this, and fixed it because it was no longer working in any case.

Allow names for the SPH particle type other than "io" in the stream frontend

---

yt/data_objects/particle_trajectories.py
yt/frontends/adaptahop/data_structures.py
yt/visualization/plot_modifications.py

Fix remaining usage of deprecated API. See https://numpy.org/devdocs/release/2.0.0-notes.html#deprecations

BUG: handle deprecation warnings from numpy 2.0.0dev0 (np.row_stack -> np.vstack and np.in1d -> np.isin)

---

yt/data_objects/data_containers.py
yt/data_objects/profiles.py

The `YTDataContainer.profile` wrapper of `create_profile` is missing the `override_bins` argument. Maybe could be considered a bug since the docs imply this should work (https://yt-project.org/doc/analyzing/generating_processed_data.html#profiles-and-histograms). 
Thanks to @BenWibking for pointing this out.

add override_bins to data_container.profile

---

.github/workflows/bleeding-edge.yaml

Goal: fix #4721
I suspect that the `labels` parameter is malformed (this is the only one I'm using that's not used in the matplotlib model workflow, and it's not well documented)
I'm going to test this by removing the conditional trigger.

MNT: fix auto-reports for bleeding edge CI

---

yt/frontends/ramses/field_handlers.py
yt/frontends/ramses/io_utils.pyx
yt/geometry/oct_container.pxd
yt/geometry/oct_container.pyx
yt/utilities/cython_fortran_utils.pxd
yt/utilities/cython_fortran_utils.pyx

RAMSES files require lots of random access in the file. In particular, when you have a lot of fields in the outputs, the performance drastically decreases if you're skipping most of them. In this PR,  I precompute how many "jumps" one needs to do ahead of time, and then do all jumps at once.
The code should be functionally equivalent but results in fewer reads.
| slice | Timing on `main` [s] | Timing with this PR [s]|
|-------|----------------------|------------------------|
| all   | 52                   | 23|
| ::2   | 43 | 17 |
| ::4   | 39 | 12 |
| :4    | 35 | 9 |
To estimate the timings, the following code is being run, with the slice as reported in the table above. This is run on [Dial 3](https://dial3-docs.dirac.ac.uk/).
```python
import yt
p = …
```

Ramses-speedup

---

.pre-commit-config.yaml
pyproject.toml

One less hook required to accomplish the same thing. Ruff has had builtin support for *.ipynb files since [v0.0.276](https://github.com/astral-sh/ruff/releases/tag/v0.0.276)
See https://docs.astral.sh/ruff/faq/#does-ruff-support-jupyter-notebooks

MNT: opt-in ruff's builtin support for jupyter notebooks

---

yt/frontends/enzo/data_structures.py

similar to #4708, follow up to #4275
The issue here is that `EnzoDataset` is used for Enzo 2 *and* Enzo 3 data, but `libconf` is only required with the latter, so warning about `libconf` not being installed is just noisy when working with Enzo 2 data (including everyone's favourite dataset, IsolatedGalaxy).

BUG: avoid a noisy self-triggered warning about libconf being a hard dependency to load any enzo data

---

doc/source/examining/loading_data.rst
yt/frontends/athena/data_structures.py
yt/frontends/fits/data_structures.py
yt/frontends/stream/misc.py
yt/frontends/stream/tests/test_stream_stretched.py
yt/loaders.py
yt/utilities/decompose.py
yt/utilities/tests/test_decompose.py

Working on getting `load_uniform_grid` to work with nproc > 1 for stretched grids (when `cell_widths` is allowed). Most the changes here are to the grid decomposition. 
Closes #4330 
Sample from the version just pushed:
```python
import yt
N = 64
data = {"density": np.random.random((N, N, N))}
cell_widths = []
for _ in range(3):
cw = 0.1 + np.random.random(N)
cw /= cw.sum()
cell_widths.append(cw)
data,
data["density"].shape,
bbox=np.array([[0.0, 1.0], [0.0, 1.0], [0.0, 1.0]]),
cell_widths=cell_widths,
nprocs=32,
)
slc = yt.SlicePlot(ds, 'x', 'density')
slc.set_log('density', False)
slc.annotate_grids(edgecolors='w', linewidth=4)
```

ENH: allow cell_widths and nproc > 1 for load_uniform_grid

---

yt/utilities/exceptions.py

A recent question on slack revealed that the error message left users confused about what to do. It should be very clear which strings are considered valid values to the `simulation_type` argument in `yt.load_simulation`, especially since it happens to be case sensitive.

UX: add info about supported simulation types in YTSimulationNotIdentified

---

yt/frontends/gamer/cfields.pyx
yt/frontends/gamer/data_structures.py
yt/frontends/gamer/fields.py
yt/frontends/gamer/tests/test_outputs.py

GAMER recently included support for cosmic ray fluids. This PR supports these fields by adding a `gamma_cr` attribute to the GAMER `Dataset` if it is found in the runtime parameters, adds the fields `("gas", "cosmic_ray_energy_density")` and `("gas", "cosmic_ray_pressure")`, and modifies the computation of the non-cosmic ray gas thermal energy, pressure, and temperature to account for the existence of the cosmic ray energy if it is available.
Will add a test, but I tried this out on the cosmic ray shock tube problem in GAMER and it seems to work.

Support for cosmic ray fields in GAMER

---

yt/data_objects/tests/test_covering_grid.py

Fix a `FutureWarning` emmited in all Python 3.12 CI jobs, from `xarray`.
```
FAILED yt/data_objects/tests/test_covering_grid.py::test_xarray_export - FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`.
```

TST: update xarray integration test to use non-deprecated API

---

yt/frontends/enzo/answer_testing_support.py

This bug was found while [fixing the Enzo CI testing](https://github.com/enzo-project/enzo-dev/pull/223). It seems to have been induced by the upgrade to unyt v3. The bug is as follows: 
The `ShockTubeTest` class supports comparing simulation results to an exact solution saved to file; however, the solution in that file doesn't have any units associated with it. When trying to compare solutions, unyt complains. 
This is a very simple change that removes units from the simulation data before comparing. 
The test for it is essentially the Enzo test infrastructure over at https://github.com/enzo-project/enzo-dev? So I'm not sure how I would add a test for this within yt.

BUGFIX: Enzo testing framework - ignore units for ShockTube tests

---

.github/workflows/build-test.yaml
pyproject.toml

This PR set's the minimum Python version explicitly to 3.9.2, which is currently the functional minimum version in the 3.9 series. 
Currently with Python 3.9.0 or 3.9.1, yt 4.3.0 errors on import:
```
>>> import yt
File "<stdin>", line 1, in <module>
File "/home/chavlin/.pyenv/versions/yt_391/lib/python3.9/site-packages/yt/__init__.py", line 12, in <module>
import yt.utilities.physical_constants as physical_constants
File "/home/chavlin/.pyenv/versions/yt_391/lib/python3.9/site-packages/yt/utilities/physical_constants.py", line 3, in <module>
from yt.units.yt_array import YTQuantity
File "/home/chavlin/.pyenv/versions/yt_391/lib/python3.9/site-packages/yt/units/yt_array.py", line 3, in <module>
from yt.funcs import array_like_field  # NOQA: F401
File …
```

explicitly set minimum Python to 3.9.2

---

yt/frontends/boxlib/data_structures.py
yt/frontends/boxlib/tests/test_outputs.py
yt/sample_data_registry.json

Removes the check that disallows cylindrical coordinates in 1D. It looks like yt learned how to support these sometime since this code was added in 2014. It also fixes an error in `_parse_header_file()` introduced by #4641.
I tested against an example dataset output by https://github.com/AMReX-Astro/Castro/tree/main/Exec/hydro_tests/Sedov using `inputs.1d.cyl`, and the cell volumes checked out (proportional to 1/r).

ENH: allow boxlib frontend to read 1D cylindrical datasets

---

yt/data_objects/derived_quantities.py
yt/data_objects/tests/test_derived_quantities.py

This PR adds a `check_finite` kwarg to `quantities.extrema` so that you can find the extrema of fields that include `np.nan` values.  Default value is `False` so that default behavior does not change.

ENH: add check for finite values in extrema

---

conftest.py

As noted by @jzuhone in #4782, this warning makes half of CI red.
I don't think we care about it, but for completion, here it is in full:
```
DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
```

TST: ignore deprecation warning from pandas (Pyarrow will become a required dependency)

---

yt/frontends/flash/data_structures.py

In non-fixed block size grids FLASH output the domain is output as a single block, rather than being domain decomposed as is assumed for the fixed block size UG. This PR checks for this case
so that yt correctly determines `domain_dimensions`.

correct domain_dimensions in non-fixed block size uniform grid FLASH output

---

yt/data_objects/particle_trajectories.py

In the `_get_data` method of `particle_trajectories`, `self.data_series[0]` might still be unloaded (not sure if that's the right word?) when running in parallel. That was causing the `if` statement that checks if the particle_type of missing field exists to fail, incorrectly adding fields to the `grid_fields` list. Since `ds_first` is loaded (because we called all_data() on it earlier), this is now more likely to succeed.
Essentially
```python
ds_first = self.data_series[0]
dd_first = ds_first.all_data()
fds = {}
new_particle_fields = []
for field in missing_fields:
fds[field] = dd_first._determine_fields(field)[0]
if field not in self.particle_fields:
ftype = fds[field][0]
if ftype in ds_first.particle_types:
self.particle_fields.append(field)
new_particle_fields.append(field)
```
In my …

Fix bug where race condition results in incorrect fields categorization when computing particle_trajectories

---

yt/frontends/athena_pp/data_structures.py

Changes the ordering of coordinates for Athena++ cylindrical datasets to $(r,\theta,z)$ within the Athena++ frontend.
Addresses #4796

Fix order of Athena++ cylindrical coords

---

conftest.py

Since Python 3.12, `os.fork()` throws a deprecation warning when called from multiple threads.
This causes the tests relying on ratarmount (to mount archives) to fail. In this PR, I superficially address the issue by catching the warning on the test side.
The long-term solution would be to update `ratarmount` to a more recent version.

Catch Py312+ warning when using ratarmount

---

yt/_maintenance/numpy2_compat.py

Follow up to #4632
xref https://github.com/numpy/numpy/pull/25738
This can be considered a bugfix since the previous solution (shipped in yt 4.3.0) erroneously circumvents NEP 18 implementations in `unyt`.

RFC: replace vendored version of numpy.trapz with supported API in numpy 2

---

yt/arraytypes.py
yt/frontends/fits/data_structures.py

Combined with #4806, this replaces usages of `numpy.core` with public API.
Context: `np.core` was always private API, but in numpy 2.0, it was moved to `np._core` to make it clearer. `np.core` continues to be available as an alias for now but importing from it now triggers deprecation warnings. In the few places that we actually import it, we can now easily switch to public API, so let's.

RFC: avoid usage of deprecated usage numpy.core (numpy 2 compat)

---

yt/geometry/coordinates/cartesian_coordinates.py
yt/geometry/grid_container.pyx
yt/geometry/grid_visitors.pxd
yt/utilities/lib/alt_ray_tracers.pyx
yt/utilities/lib/interpolators.pyx
yt/utilities/lib/mesh_triangulation.pyx
yt/utilities/lib/pixelization_routines.pyx
yt/utilities/linear_interpolators.py

This fixes *building* yt against numpy 2.0
Context:
The `np.int_t` alias was removed from numpy's C API
example error:
```
Error compiling Cython file:
------------------------------------------------------------
...
np.float64_t left_edge_y
np.float64_t left_edge_z
np.float64_t right_edge_x
np.float64_t right_edge_y
np.float64_t right_edge_z
np.int_t children_pointers
^
------------------------------------------------------------
yt/geometry/grid_visitors.pxd:34:4: 'int_t' is not a type identifier
```
Replacing it with a fixed-size portable `int64` fixes building.
This might not be an exact replacement on Windows where, historically, numpy used int32 by default, but numpy 2.0 will consistently use int64 everywhere so this change feels in line with future behaviour. Furthermore it only …

BLD: Ditch `np.int_t`, removed in numpy 2's C API (use `np.int64_t` instead)

---

yt/frontends/boxlib/data_structures.py
yt/frontends/boxlib/tests/test_outputs.py

Castro (since 18.04), MAESTROeX (since 20.09), and MAESTRO (since 2013) add a prefix `[*]` before runtime parameters that are changed from their defaults. This was being handled by the Dataset subclasses individually, leading to duplicated and inconsistent logic (CastroDataset wasn't stripping the parameter names, leading to duplicates with trailing spaces).
This PR moves the prefix handling into BoxlibDataset, and removes the prefix so analysis scripts don't need to check for both versions in `ds.parameters`.

BUG: fix parameter parsing for Castro and MAESTRO

---

.pre-commit-config.yaml
pyproject.toml

Following #4807, this avoids seeing deprecation warnings in ruff messages.
see release notes https://github.com/astral-sh/ruff/releases/tag/v0.2.0
While I'm in there I also added *useful* verbosity to ruff fixes so now you get to *see* what's being fixed, not just that some file was edited.

MNT: move ruff configuration to non-deprecated namespaces

---

pyproject.toml

In replacement of #4851
The proper fix is to migrate out of a compatibility shim for nosetest that was removed in pytest 8.0, but it turns out non trivial (see #4852) so I suggest just pinning for now to quickly get CI back to a useful state.

TST: temporarily pin pytest<8.0

---

yt/fields/field_detector.py
yt/testing.py
yt/utilities/initial_conditions.py
yt/visualization/volume_rendering/zbuffer_array.py

#4863 caught some uses of the legacy np.random.random api missed by #4733. Since one of the uses is within a test function, I thought it'd be clearer to create a separate PR instead of pushing to #4863 (in case there are failures related to changing the test function)

RFC: Replace np.random.random use with np.random.default_rng

---

pyproject.toml

numpy 2.0.0rc1 was just released, meaning it's now ABI stable, so we can (and should) start publishing wheels built against.
This is the last blocker for yt 4.3.1

BLD: add support for numpy 2

---

pyproject.toml

manual backport to  workaround a small conflict (numpy was pinned to <2 on the backport branch but not on main)

Backport PR #4859: BLD: add support for numpy 2

---

yt/utilities/lib/image_utilities.pyx
yt/utilities/lib/interpolators.pyx
yt/visualization/volume_rendering/off_axis_projection.py

On main, off-axis projections are very slow due to the need to cast rays through the domain.
This is particularly the case for octree-datasets to to the hot-loop [for grid, mask in data_source.blocks:](https://github.com/cphyc/yt/blob/f8d38de9fc71cd83b40ab74eb2527644bbc1f4be/yt/visualization/volume_rendering/off_axis_projection.py#L446-L464). Indeed, this iterates over all octs in the domain, one-by-one.
While one solution might be to move this chunk to a Cython-accelerated code, it will remain somewhat slow no matter what.
In this PR, I take a completely different approach.
In the first part of the code, I compute the projected depth of a cube as seen from the camera position (i.e. how long is the segment traversing the cube at different pixel locations). One way of seeing this is that …

Use stamping approach to deposit off-axis cells

---

yt/frontends/ramses/fields.py
yt/frontends/ramses/io.py

Hello, 
I correct some mistakes in this PR in the reader for Ramses sink files. 
I add this in the code 1yr ago and I just realize there were a mistake with a capital letter. 
In Ramses, the header of the csv file for the sinks has the header `acc_rate` and not `acc_Rate` as was in yt.
Here, I correct this mistake (line 391 of io.py)
Also for consistency I modify the name of the `particle_accretion_rate` field. It use to be called `particle_accretion_Rate` with a capital letter. But none of the others fields has a capital letter in it, so it seems more logical to me to delete this capital letter.
Best regards
Romain Lenoble

correct errors in capital letter

---

yt/visualization/base_plot_types.py

Closes #4881 
This adds `QtAgg` to `BACKEND_SPECS`, removes `Qt4agg` (which is no longer valid as of matplotlib 3.5.0, yt's current minimum matplotlib version) and raises an error when a backend is not present in `BACKEND_SPECS` (rather than silently returning `None`).
I'm not sure there's a way to add a test for this, but locally I was able to reproduce the error in #4881 and verify that this PR fixes the error by running the following from ipython:
```python
%matplotlib qt
import yt 
yt.toggle_interactivity()
slc = yt.SlicePlot(ds, 'x', 'Density')
slc.show()
```

BUG: Update Qt backend entries in BACKEND_SPECS

---

yt/utilities/parallel_tools/parallel_analysis_interface.py

…codes
This PR modifies `yt.enable_parallelism()` to create a duplicate of the MPI communicator it uses. That communicator is either passed in via the named argument, or the communicator `MPI.COMM_WORLD` is used internally by default. To create the duplicate, the MPI call `comm.Dup()` is used.
Issue description: In the original implementation, a copy of the handle of the original MPI communicator was kept. Internally an instance of `class Communicator()` is created.  However, this class has a destructor which explicitly calls the method `Free()` of the communicator. This is clearly not wanted in case the global communicator `MPI.COMM_WORLD` is used. In that case `mpi4py` should do the cleanup internally. In case a communicator was passed in by the user, the call to `Free()` is also not …

BUG: create duplicate of MPI communicator, to avoid double comm.Free

---

yt/frontends/ramses/hilbert.py
yt/frontends/ramses/tests/test_hilbert.py

- replaces a Python-backed Hilbert implementation with yt's
- pre-extract the Hilbert keys once to improve perfs
On a dataset with 4096 domains, this brings down the time to compute intersection
of a box from ~ 200s to less than a few seconds.

ENH: Make Hilbert intersection faster

---

yt/frontends/tipsy/io.py

Using `skip_footer` in `np.genfromtxt` requires scanning the whole file and so slows down the tipsy ascii aux file reads **significantly** for large files. Switching to `max_rows` avoids this.

ENH: tipsy use max_rows instead of skip_footer for ascii aux read

---

.git-blame-ignore-revs
.pre-commit-config.yaml
README.md
pyproject.toml
tests/report_failed_answers.py
yt/data_objects/construction_data_containers.py
yt/data_objects/level_sets/clump_handling.py
yt/data_objects/profiles.py
yt/data_objects/tests/test_dataset_access.py
yt/frontends/chimera/io.py
yt/frontends/chombo/data_structures.py
yt/frontends/enzo/data_structures.py
yt/frontends/enzo/simulation_handling.py
yt/frontends/gamer/data_structures.py
yt/frontends/ramses/data_structures.py
yt/frontends/ramses/io.py
yt/frontends/ramses/tests/test_outputs.py
yt/frontends/sdf/io.py
yt/frontends/stream/io.py
yt/funcs.py
yt/geometry/coordinates/tests/test_geographic_coordinates.py
yt/utilities/answer_testing/framework.py
yt/visualization/volume_rendering/render_source.py

Closes #4748
The formatting commit is "semi-automated" because ruff was, in some places, somewhat akwardly moving around some strings formatted with `%`, but I found manually changing them to fstrings helped.

STY: migrate formatting from black to ruff-format

---

.github/workflows/wheels.yaml

Now that GitHub Actions and cibuildwheel support amr64, we don't need cross compilation for these wheels, and we can lift that burden off of the macOS x86 job, which is by far the longest running job in the matrix (see for example https://github.com/yt-project/yt/actions/runs/8852696165/usage)

MNT: build macOS amr64 wheels without cross-compiling

---

yt/geometry/coordinates/geographic_coordinates.py
yt/geometry/coordinates/tests/test_geographic_coordinates.py

BUG: Fix geographic coords convert_to_cartesian with units

---

setup.py
setupext.py
yt/utilities/lib/grid_traversal.pyx
yt/utilities/lib/image_samplers.pyx
yt/utilities/lib/marching_cubes.pyx
yt/utilities/lib/partitioned_grid.pyx

Avoid a race condition on fixed_interpolator.o during parallel builds by building it only once and storing it in a static library.
Hopefully fixes #4278.

BLD: only compile fixed_interpolator.cpp once

---

.github/workflows/bleeding-edge.yaml
setup.py
setupext.py
yt/funcs.py

Updates the bleeding-edge CI workflow script to run only pip and adds the numpy API macros to the clib defines.
Fixes #4896.

BLD: fix bleeding-edge build script

---

CONTRIBUTING.rst
doc/cheatsheet.tex
doc/source/analyzing/fields.rst
doc/source/developing/testing.rst
yt/frontends/halo_catalog/io.py

some spelling fixes

---

yt/utilities/amr_kdtree/amr_kdtools.py
yt/utilities/amr_kdtree/amr_kdtree.py
yt/visualization/volume_rendering/render_source.py

This addresses issue #4871, where volume renders of multiple fields with MPI would only produce a portion of the second field in the final image. 
I believe I have found where this bug occurs. It mainly has to do with the combining of image arrays in `yt/utilities/amr_kdtree/amr_kdtools.py:receive_and_reduce()` and how the alpha channel is set in `yt/visualization/volume_rendering/render_source.py:VolumeSource.finialize_image()`
After the first source is rendered, the last step of `finalize_image()` sets the alpha channel of the image array to `1`'s 
https://github.com/yt-project/yt/blob/6d121f58543bedb1f587492cd0601a69f06a736a/yt/visualization/volume_rendering/render_source.py#L535-L537
This causes issues when the second source is combining the image arrays in `recieve_and_reduce()` as …

Reduce rendered images without considering opacity

---

yt/frontends/ramses/io_utils.pyx
yt/frontends/ramses/tests/test_outputs.py

This fixes #4880.
The issue was that the reader would assume fields were passed in the order they appeared on file, so that depending on the order in which one would load the data, we'd get different results.

BUG: Make sure fields are read in the order they appear in the file

---

.github/workflows/wheels.yaml

A quick alternative to #4906, since I cannot seem to figure out (yet) how to run properly pytest from outside the repository, this will at least implement *some* level of safety regarding distributed artifacts (which we need in order to implement stuff like #4905)

BLD: minimally test wheels and sdist

---

.github/workflows/wheels.yaml

Follow-up to https://github.com/yt-project/yt/pull/4909.
We originally had static linking enabled due to ABI conflicts, as discussed in https://github.com/yt-project/yt/pull/3406. However, the cibuildwheel docs currently say that manylinux2014 supports all C++ standards up to C++17 (https://cibuildwheel.pypa.io/en/stable/cpp_standards/).
I think the segfaults may have to do with multiple versions of libstdc++ being loaded at the same time. A couple of compiled modules in matplotlib dynamically link to `libstdc++.so.6`, which seems like it could cause this sort of issue.

BLD: fix segfault with manylinux2014

---

conftest.py

I am now almost sure that the comment I wrote for this filter (circa 2021) was ill-informed and misleading. Astropy's wheels in fact were already being built in a forward-compatible way with `oldest-supported-numpy` at the time and continue to be (now using the more modern mechanism introduced in numpy 1.25). I suspect the real reason why we were seeing this warning was that we installed numpy from conda and then astropy from PyPI, which we haven't been doing since https://github.com/yt-project/yt/pull/4624

TST: cleanup unnecessary warning filter

---

yt/frontends/amrex/data_structures.py
yt/frontends/athena/data_structures.py
yt/frontends/chombo/data_structures.py
yt/frontends/gdf/data_structures.py
yt/frontends/stream/data_structures.py

BUG: fix deprecated implicit casting of arrays with ndim>0 to int scalar

---

nose_ignores.txt
tests/tests.yaml
yt/frontends/amrex/fields.py
yt/frontends/amrex/tests/test_field_parsing.py

The boxlib dataset parsing (for CASTRO/MAESTROeX) are currently set up for usual atomic species like "He4" or "C12", or descriptive names like "ash" with no numbers.  The parsing breaks for e.g. molecules like "H2O" or "C6H6".  This fix escapes those cases.
Ideally, we could have some fancy regex to correctly parse the molecules (and create proper a TeX string), but this is a very niche use of those codes.

ENH: add support for molecular fields (AMRex)

---

yt/frontends/tipsy/io.py

This should not change anything functionally, but can save some time for opening file handles that may be expensive.
Closes #4883.

BUG: Fix tipsy file handler opening

---

doc/source/developing/debugdrive.rst

The relevant code is here: https://github.com/yt-project/yt/blob/13dc4fbcba564439c90e9bdd8db013f797dfc9a9/yt/startup_tasks.py#L45-L55

DOC: fix typo in the debugging signal names

---

pyproject.toml
tests/tests.yaml
yt/_maintenance/numpy2_compat.py
yt/fields/vector_operations.py

Numpy 2.0 just dropped on PyPI (🎉). This change is a pretext to make sure everything still runs smoothly. From the conversation on #4874, I expect I'll need to bump a couple answer tests but everything else I expect to stay green.
Closes #4874

BLD: require numpy 2.0.0 (stable) at build time

---

yt/frontends/ramses/particle_handlers.py

Some simulations (like NewHorizon and Horizon-AGN) have weird record lengths that aren't multiple of 1, 2, 4 or 8. This allows to read the dataset nonetheless (but the corresponding records won't work though)

[BUG] RAMSES: allow reading datasets with slightly broken records.

---

yt/frontends/amrex/data_structures.py

One of our group members ran into this today when doing `ds = CastroDataset('~/delta_ims/en_20/planar_plt02346')`, with an error like:
```
yt/frontends/boxlib/data_structures.py", line 1116, in _parse_parameter_file
jobinfo_filename = os.path.join(self.output_dir, self.cparam_filename)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen posixpath>", line 90, in join
File "<frozen genericpath>", line 164, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```
`self._lookup_cparam_filepath()` was being passed the version of `output_dir` before having the tilde expanded, and was returning `None` as `./~/` doesn't exist.
I'm not sure how to add a test for this.

BUG: fix loading of AMReX datasets with `~` in the filename

---

yt/geometry/tests/test_particle_deposit.py

TST: add missing `@requires_module` decorators in particle deposition tests

---

yt/frontends/cf_radial/data_structures.py

This PR adjusts the cf_radial frontend `_is_valid` to look in an additional attribute (`Sub_conventions`). 
NEXRAD (https://cmr.earthdata.nasa.gov/search/concepts/C2020894988-GHRC_DAAC.html) uses CFradial but has slightly different metadata from what we're checking for. In this case it's got the following attributes:
```
Conventions :
CF-1.7
Sub_conventions :
CF-Radial instrument_parameters radar_parameters radar_calibration
```

add check for Sub_conventions for CFradial

---

yt/frontends/enzo_e/data_structures.py
yt/frontends/enzo_e/io.py

The primary purpose of this PR was to add support for Enzo-E simulations with 0 ghost zones.
While I was here, I added support for Enzo-E simulations where the x, y, and z axes have different numbers of ghost zones (this is a feature that Enzo-E supports, but it's not really used). I also added some explanatory comments.

Add support for Enzo-E simulations with 0 ghost zones

---

yt/utilities/lib/quad_tree.pyx

This is a bug that causes memory leakage in projections.
It forgot to free `vorig` when returning inside the if block.
Since `vorig` won't be used inside that if block anyway, it should be moved under the if block.

Fix memory leakage

---

pyproject.toml
setup.py

This is a continuation of #4583.
`setuptools.build_meta:__legacy__` is not considered stable:
https://github.com/pypa/setuptools/blob/48f95c0a1b8aa033d5a489eff8c4a6abc881b743/setuptools/build_meta.py#L468-L4778
The only reason we need it is that we need to ensure that `setupext.py` can be imported from `setup.py`, so migration is actually quite simple.

BLD: switch to stable setuptools build backend

---

yt/tests/test_load_sample.py

This single test has been flaky for at least weeks and caused a lot of jobs to fail when really it's no big deal if this cannot be consistently tested on windows, so let's just skip it there.
[example logs](https://github.com/yt-project/yt/actions/runs/10027348660/job/27712898850?pr=4949)

TST: skip a flaky test on Windows

---

yt/utilities/answer_testing/framework.py

I'm adding prefixes to the file names produced in `yt/yt/utilities/answer_testing/framework.py`, `dump_images` function. This should make it straightforward to see which image is the baseline for the comparison and which has been produced by the pull request branch in the `nose` testing output.
This addresses issue #4954.

new prefix for images produced in testing: baseline_ or thisPR_

---

.github/workflows/wheels.yaml
pyproject.toml

This should help testing wheel building locally, and was also an opportunity to clean up our cibuildwheel configuration.

MNT: cleanup cibuildwheel configuration and move it to `pyproject.toml`

---

doc/source/developing/testing.rst

I added a note to the development -> testing page of the docs, [Answer Testing](https://yt-project.org/docs/dev/developing/testing.html#answer-testing) section, indicating that the current instructions do not reflect current practice, as described [here](https://github.com/yt-project/yt/pull/4939#issuecomment-2241559129) by @neutrinoceros. This will hopefully save people some time when working on pull requests. 
I added this text to the very beginning of the 'Answer Tests' section, in a note (`.. note::`):
"This section documents answer tests run with `pytest`. The plan is to switch to using `pytest` for answer tests at some point in the future, but currently (July 2024), answer tests are actually run using `nose`."

DOC: added note that answer tests are currently run with nose

---

pyproject.toml

A workaround #4953 while the issue is being discussed upstream.

DEP: exclude numpy 2.0.1 on macOS arm64

---

conftest.py
yt/config.py

This doesn't seem to be used anywhere and the release notes for pytest 8.3.0 make it clear that it's even redundant so we shouldn't ever actually need it.
See https://github.com/pytest-dev/pytest/pull/12153

CLN: cleanup unused internal conf parameter `within_pytest`

---

pyproject.toml

explicitly disallow imageio 2.35.0 in testing deps

---

yt/frontends/tipsy/io.py
yt/frontends/tipsy/tests/test_outputs.py

Partial fix for #4963 
This fixes the error when reading the smoothing length for tipsy. Does not address the question of the changing coordinate values when the bounding box changes.

BUG: tipsy, reading just smoothing length

---

.pre-commit-config.yaml
pyproject.toml

Reading through the migration guide for ruff 0.6.0, and opening this PR while this is on my mind.
See https://astral.sh/blog/ruff-v0.6.0#jupyter-notebooks-are-now-linted-and-formatted-by-default

MNT: bump ruff to v0.6

---

.github/workflows/wheels.yaml
yt/utilities/lib/platform_dep.h

This is a tentative fix for #4972
Been working on this iteratively by reading MSVS documentation and running github actions on my fork since i don't have windows... but I'm fairly certain that we've been effectively pinning yt on windows to using at least Visual Studio 2019 version 16.8, 16.9 for a while now (based on my reading of https://learn.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance), which seems reasonable to me and in which case we can remove most of the windows-specific definitions (and fix the errors in #4972 ).

adjust platform_dep.h for recent MSVS versions

---

yt/visualization/base_plot_types.py
yt/visualization/tests/test_image_comp_2D_plots.py

BUG: fix orientation of colorbar in multiplanel plot

---

pyproject.toml
yt/data_objects/static_output.py
yt/frontends/ramses/io.py
yt/visualization/fixed_resolution.py
yt/visualization/plot_window.py
yt/visualization/profile_plotter.py

Changeset obtained with
```shell
ruff check yt --fix --unsafe-fixes --select TCH
```
This helps with making sure (potentially expensive) type-check-only import statements do not impact startup time (see  for instance matplotlib imports moved in #4265)

RFC: enable `flake8-type-checking` ruleset

---

tests/unpin_requirements.py

This allows running this script as `uvx run tests/unpin_requirements.py` without manually managing virtual environments.
Note that this format isn't specific to `uv/uvx`, but a standard defined by an official PEP ([723](https://peps.python.org/pep-0723/))

MNT: add pep723 metadata to test helper script

---

pyproject.toml

Follow up to #4844: this new linting rule will allow auto-fixing deviations in the future.
For context, it's not a coincidence if this rule so closely matches what @cphyc did in #4844:
this rule was added to ruff after I requested it *in response* to his PR :)

STY: autofix RUF031 (`incorrectly-parenthesized-tuple-in-subscript`)

---

yt/data_objects/selection_objects/slices.py
yt/data_objects/tests/test_sph_data_objects.py
yt/funcs.py

Found that for sph data, calling `ds.slice(axis, center).to_frb(...)[field]` would error if the `center` argument was a plain float. For other dataset types (and other data objects), a plain float is assumed to be in units of `code_length`. Easiest fix is to ensure that `YTSlice.coord` attribute is a unyt object, following the other data objects.
Here's the stack trace from the error on main:
```python
import yt
ds = yt.load_sample("snapshot_033")
frb = ds.slice(0, 0.25).to_frb(ds.domain_width[0], (64, 64))
print(frb["gas", "density"])
``` 
- ~~[ ] New features are documented, with docstrings and narrative docs~~ N/A

BUG: ensure YTSlice.coord has units

---

.github/dependabot.yml
requirements/typecheck.txt

Follow up to #4983, after closing unwanted PRs #4985 #4987 and #4988
I also included the desirable part of #4988

MNT: restrict dependabot pip updates to requirements/typecheck.txt

---

.github/workflows/type-checking.yaml
pyproject.toml
requirements/typecheck.txt
yt/data_objects/construction_data_containers.py

Hotfix a problem I just created by merging #4989 (which apparently didn't run typechecking at all)
[example logs](https://github.com/yt-project/yt/actions/runs/11036617135/job/30655473559)

TYP: hotfix unsolvable type-checking requirements

---

doc/source/visualizing/plots.rst

`north_vector` was being defined but not used, so removing it in this PR. Could instead supply it to `off_axis_projection`, but a `north_vector` gets used in the next example.

DOC: remove unused north_vector in off_axis_projection example

---

.github/workflows/bleeding-edge.yaml
.github/workflows/wheels.yaml
pyproject.toml
yt/geometry/particle_deposit.pxd
yt/utilities/lib/geometry_utils.pxd
yt/utilities/lib/geometry_utils.pyx
yt/utilities/lib/image_samplers.pxd
yt/utilities/lib/image_samplers.pyx

Close #4044
Following [Cython's migration guide](https://docs.cython.org/en/latest/src/userguide/migrating_to_cy30.html#deprecation-of-def-if)

BLD: fix compatibility with Cython 3.1

---

yt/frontends/rockstar/data_structures.py
yt/frontends/rockstar/tests/test_outputs.py

This allow to read member data from Rockstar catalogues.

[ENH] Read Rockstar members

---

doc/source/analyzing/fields.rst
yt/data_objects/tests/test_data_containers.py
yt/fields/particle_fields.py
yt/fields/tests/test_particle_fields.py
yt/fields/vector_operations.py

yt already supports ["line-of-sight" fields](https://yt-project.org/doc/analyzing/fields.html#line-of-sight-fields) for gas field types. These are fields that result from taking the component of a vector field along a particular sight line (such as in a projection, but it can be more general). This PR enables the same functionality for particle fields, and turns it on for the particle velocity.

ENH: Support line-of-sight fields for particle types

---

yt/frontends/flash/data_structures.py

We do not support particle data in FLASH data before version 3, but we do support reading in FLASH 2.x datasets.
The current logic for detecting a FLASH particle file which corresponds to a FLASH plotfile checks the filename for the string `"hdf5_plt"` and replaces it with `"hdf5_part"`. It then generates a file handler for the particle file:
https://github.com/yt-project/yt/blob/7ebe857f9c38215976ca058142a78a107d39e1e8/yt/frontends/flash/data_structures.py#L192-L206
This works just fine for plot and particle files that match, but this logic completely misses checkpoint files with the string `"hdf5_chk"`.  But this falls through silently, because it will not change the filename at all in line 196 above and will open a separate file handler for the same input file. 
Then shortly after …

[BUG] Better logic for detection of particle handle for checkpoint files

---

yt/funcs.py
yt/tests/test_funcs.py

Replace use of `urllib.request.FancyURLopener` with `urlretrieve()`. The former has been deprecated since Python 3.3.
Fixes #5027

Stop using deprecated `urllib.request.FancyURLopener`

---

yt/testing.py
yt/visualization/tests/test_image_comp_2D_plots.py

In support of #5035 after identifying such cases as blind spots in the test suite.
update: [companion PR](https://github.com/yt-project/yt_pytest_mpl_baseline/pull/8)

TST: add image tests for cylindrical pixelization of a box with rmin>0

---

.github/workflows/bleeding-edge.yaml
.github/workflows/build-test.yaml
.github/workflows/wheels.yaml

close #4931, and replace #4958

TST: add CPython 3.13 to regular test matrix

---

pyproject.toml

This is a temporary fix for #5041 on yt's side that should get tests passing but will need to be updated when a fix on the the arm-pyart side is released (at which point we could pin a min version for arm-pyart for the tests).

pin xradar<0.8.0 in tests

---

yt/data_objects/selection_objects/ray.py
yt/data_objects/tests/test_rays.py

Fixes a (possible) bug in the calculation of path lengths dl for SPH/non-grid data in the YT Ray objects. This affects e.g., column density and absorption spectrum calculations, like those done in the Trident package.
Replace
`dl = itab.interpolate_array(b / hsml) * mass / dens / hsml**2 `
by 
`dl = itab.interpolate_array((b / hsml)**2) * mass / dens / hsml**2`
in the `_generate_container_field_sph` method of the YT Ray object (https://github.com/yt-project/yt/blob/main/yt/data_objects/selection_objects/ray.py).
This is the proposed fixed for the possible bug mentioned in issue #4781. 
In short, the `_generate_container_field_sph` retrieves path lengths dl for normalized SPH kernels by linearly interpolating values calculated for a smallish set of (impact parameter / smoothing length) …

Ray object dl for SPH data: interpolate kernel table for (b/hsml)**2 instead of b/hsml

---

yt/utilities/lib/pixelization_routines.pyx

release the gil!
This surprisingly seemed to work with minimal effort... took the pixelization time from 53s to 27s for one example (see [this slack thread](https://yt-project.slack.com/archives/C1YCPSX08/p1727899750601519)).

PERF: release the GIL in cylindrical pixelizer

---

pyproject.toml

new arm-pyart release is out. So close #5044 ... and hopefully #5047 ??

switch xradar pin to arm-pyart pin in tests

---

conftest.py
nose_ignores.txt
tests/tests.yaml
yt/frontends/cf_radial/data_structures.py
yt/frontends/cf_radial/tests/test_cf_radial_pytest.py

While working on #5042 I noticed a deprecation warning from cf_radial, e.g., from [this run](https://tests.yt-project.org/job/yt_py310_git/8572/testReport/yt.frontends.cf_radial.tests/test_outputs/test_cf_radial_gridded/):
```
/home/fido/workspace/yt_py310_git/yt/frontends/cf_radial/data_structures.py:281: FutureWarning: The return type of
`Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent
with`DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`.
dims = [xr_ds_handle.dims[d] for d in "xyz"]
```
This PR fixes that warning, adds some pytest-only tests (using a mocked dataset), and fixes a subsequent deprecation warning that was revealed by the new pytest.

cf_radial: fix deprecated dims access, add pytest tests with mock ds

---

yt/frontends/stream/tests/test_stream_stretched.py
yt/loaders.py

Turns out #4732 did not test out what happens when the data dict supplied to `load_uniform_grid` contains multiple fields... and it turns out that it errors. But it's a simple fix to indentation level.

BUG: fix load_uniform_grid with cell_widths and multiple fields

---

yt/frontends/parthenon/data_structures.py

Fix a small oversight from #4323
reprod:
install pooch, pandas, uninstall h5py
```python
import yt
yt.load_sample("parthenon_advection")
```
error message on main:
```python-traceback
File "<python-input-1>", line 1, in <module>
yt.load_sample("parthenon_advection")
~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/clm/dev/yt-project/yt/yt/loaders.py", line 1684, in load_sample
return load(loadable_path, **load_kwargs)
File "/Users/clm/dev/yt-project/yt/yt/_maintenance/deprecation.py", line 68, in inner
return func(*args, **kwargs)
File "/Users/clm/dev/yt-project/yt/yt/loaders.py", line 141, in load
return cls(fn, *args, **kwargs)
File "/Users/clm/dev/yt-project/yt/yt/frontends/parthenon/data_structures.py", line 153, in __init__
self._handle = …
```

BUG: fix error message when trying to load a Parthenon dataset without h5py installed

---

yt/data_objects/selection_objects/data_selection_objects.py
yt/data_objects/static_output.py
yt/fields/field_info_container.py
yt/fields/magnetic_field.py
yt/frontends/amrex/data_structures.py
yt/frontends/athena_pp/data_structures.py
yt/frontends/flash/data_structures.py
yt/frontends/parthenon/data_structures.py
yt/visualization/plot_modifications.py
yt/visualization/plot_window.py

Now that we don't support 3.9 anymore we have access to `match`/`case` statements (pattern matching). Arguably this improves readability in these instances, albeit at the cost of an additional indentation level.

RFC: refactor geometry matching clauses with Python 3.10's pattern matching

---

yt/visualization/plot_window.py
yt/visualization/tests/test_offaxisprojection.py
yt/visualization/volume_rendering/off_axis_projection.py

The off-axis renderer introduced in #4741 has an issue when the center and the center in rotated frame do not coincide (which happens when it isn't 0.5, 0.5, 0.5 afaik).
In addition, it wraps around the boundaries of the width of the plotting window rather than the simulation domain (if required).
This PR fixes both.
```python
import yt
ds = yt.load_sample("output_00080")
center = ds.arr(ad.argmax("density"))
sp = ds.sphere(center, (200, "kpc"))
n = np.array([1, 1, 1.])
n /= np.linalg.norm(n)
p = yt.ProjectionPlot(ds, n, "density", center=center, data_source=sp, width=(400, "kpc"), weight_field=("gas", "density"))
p.set_zlim(("gas", "density"), 1e-4, 5)
p.save("frames/")
```
| Before | With this PR |
|---|---|
| …

[BUG] Fix off-axis rendering when center is not [0.5, 0.5, 0.5], fix periodicity

---

yt/data_objects/tests/test_derived_quantities.py
yt/data_objects/tests/test_particle_trajectories_pytest.py
yt/data_objects/tests/test_rays.py
yt/frontends/amrex/tests/test_outputs.py
yt/frontends/parthenon/tests/test_outputs.py
yt/frontends/stream/io.py
yt/frontends/stream/tests/test_stream_stretched.py
yt/geometry/coordinates/geographic_coordinates.py
yt/geometry/coordinates/tests/test_sph_pixelization_pytestonly.py
yt/visualization/tests/test_offaxisprojection_pytestonly.py

Follow up to #4844 and #4998 after I realized that simply selecting the rule was insufficient to trigger auto-fixes as it's still under preview mode.
While configuring a narrow preview mode is supported (https://docs.astral.sh/ruff/preview/#using-rules-that-are-in-preview), I found that it's still impractical for us for now because it would result in triggering all `UP031` violations without auto-fixes available (addressed in #5064).
for reference, this patch is obtained via
```
ruff check yt --select RUF031 --preview --fix
```

STY: apply autofixes for RUF031

---

yt/visualization/tests/test_offaxisprojection.py
yt/visualization/volume_rendering/off_axis_projection.py

[FIX] Correctly normalize off-axis projections for octree datasets

---

doc/source/cookbook/custom_colorbar_tickmarks.ipynb
doc/source/cookbook/geographic_xforms_and_projections.ipynb

Since we already have the public API `.render`, it’s recommended for users to rely on it rather than using the private method `._setup_plots` in the docs.

use .render instead of ._setup_plots in docs

---

yt/visualization/base_plot_types.py

BUG: fix compatibility with matplotlib 3.10 for images that have both a custom background color and a non-transparent 'bad' color

---

yt/visualization/plot_modifications.py

Closes #5094 
Using the sample dataset in #5094, on this branch:
```python 
import yt
ds = yt.load("plt00450")
slice_plot = yt.SlicePlot(ds, "y", ("boxlib", "theta"))
slice_plot.set_width((6000, 10000)) # This sets the width in both directions
slice_plot.annotate_cell_edges(line_width=0.0001) # Add grid lines to the plot
slice_plot.swap_axes() # Swap the axes
slice_plot.show() # Display the plot
```
results in the correctly rotated cell edges

BUG: fix swap_axes bug wih CellEdgesCallback

---

yt/_maintenance/numpy2_compat.py

TYP: Fix typing in numpy2_compat.py

---

yt/data_objects/region_expression.py
yt/data_objects/tests/test_dataset_access.py

FRBs of slices made with `ds.r` were selecting the wrong area when the center of the slice didn't match the center of the domain. The existing tests didn't catch this, as they only check regions that have the same center as the domain. I've added a test case that covers this.
Example code and resulting plots:
```python
import yt
import matplotlib.pyplot as plt
region = ds.r[0:0.5:100j, 0.5:1.0:100j, 0.5]
cmap = plt.colormaps["viridis"]
cmap.set_bad(color="red")
plt.imshow(region["index", "x"], origin="lower", vmin=0, vmax=1, cmap=cmap)
plt.colorbar()
```

BUG: fix NaNs in off-center FRB slices from ds.r

---

yt/data_objects/profiles.py
yt/data_objects/tests/test_profiles.py

This fixes Issue #5089 .  The weight field was not being properly referenced in the profiling code when a `weight_field` was specified for particle-based datasets.  This code also adds a test to the profiling code to ensure it doesn't break again.

BUG: Properly reference weight field in profile code for particle-based datasets

---

.github/workflows/wheels.yaml

manual backport for #5108
(cherry picked from commit dc8b3144c9b349232521fd551fb6bb01cf4ba995)

Backport PR #5108 to yt-4.4.x (Bump pypa/gh-action-pypi-publish to 1.12.4)

---

yt/frontends/amrex/data_structures.py
yt/frontends/amrex/tests/test_outputs.py
yt/sample_data_registry.json

Manual backport for #5025, including bits from #5051 that created a merge conflict.

Backport PR #5025 to yt-4.4.x (BUG: fix ds.all_data() for spherical AMReX datasets)

---

nose_ignores.txt
tests/tests.yaml
yt/visualization/base_plot_types.py
yt/visualization/tests/test_base_plot_types.py

Closes #5138 
I also added a test for the existing `BACKEND_SPECS`, just checking that the backend keys are valid, which resulted in me realizing that gtk, gtkagg and gtkcairo have all been deprecated for a while (https://github.com/ipython/ipython/issues/14368 , https://github.com/matplotlib/matplotlib/pull/10426) in favor of versioned keys (e.g., GTK3Agg). I removed the deprecated keys. 
Also worth noting that with this change, for folks using matplotlib>=3.9, yt plotting should now work with all the interactive backends listed at https://matplotlib.org/stable/users/explain/figure/backends.html#interactive-backends , which includes some that were missing from `BACKEND_SPECS`, e.g.: `GTK4Agg` and `GTK4Cairo`.

Use matplotlib backend registry when possible

---

.gitignore

Stop @chrishavlin from accidentally committing `cosmology_time.cpp` again.

add cosmology_time.cpp to gitignore

---

yt/testing.py

update testing.integrate_kernel type hints

---

yt/visualization/profile_plotter.py
yt/visualization/tests/test_image_comp_2D_plots.py
yt/visualization/tests/test_profile_plots.py

Removing code that removes field type in set_title().  Not sure why this was ever here.  It is not present for any other plot annotations.
This resolves Issue #5087 .

BUG: Removing code that removes field type in set_title() 

---

yt/frontends/cholla/data_structures.py
yt/frontends/cholla/fields.py

Currently, the Cholla frontend always tries to read the ``"mu"`` attribute from the hdf5 files. However, this is not a standard attribute written by Cholla. When this attribute is missing, the frontend falls back to a value of ``1.0``. This is almost always wrong (it is usually ``0.6``,  but in some cases it can be hardcoded to different values).
It's on my todo list to start having Cholla write out the ``"mu"`` attribute (when not using species fields).
This patch tweaks the frontend to achieve better behavior for all existing Cholla datasets without the ``"mu"`` attribute. Namely, we don't set a default value. The patch also enures that we don't define a temperature field unless the ``"mu"`` attribute is explicitly defined (or the ``default_species_fields`` keyword argument is specified …

BUG: Better behavior when Cholla doesn't write "mu" attribute

---

yt/frontends/ramses/field_handlers.py
yt/frontends/ramses/tests/test_outputs.py

This prevents issues when trying to load two snapshots/simulations with different variables. It makes all the detection specific to the one dataset at hand
```python
import yt
ds0 = yt.load_sample("output_00080")
ds1 = yt.load_sample("ramses_mhd_128")
#sp0 = ds0.sphere([0.5]*3, 0.01)
sp1 = ds1.sphere([0.5]*3, 0.01)
sp0 = ds0.sphere([0.5]*3, 0.01)
print(ds0.parameters)
sp0["gas", "velocity_x"].max().to("km/s")
```
Traceback:
```
ValueError
Cell In[28], line 12
8 # sp0 = ds0.sphere([0.5]*3, 0.01)
10 print(ds0.parameters)
---> 12 sp0["gas", "velocity_x"].max().to("km/s")  # this raises an OSError when reading the Fortran records.
[...]
File yt/frontends/ramses/field_handlers.py:264, in FieldFileHandler.offset(self)
250     min_level = self.domain.ds.min_level
252     # The file is as …
```

[BUGFIX] RAMSES: Use one registry per dataset

---

yt/frontends/ramses/data_structures.py

For RAMSES, temperatures are returned in T/µ, so it should not be included in the definition of the temperature unit.
To be clear, this does *not* affect the values of the temperature fields read from disk. However, should one read from disk a field akin to a temperature and assume it is expressed in `code_temperature`, there will be a factor 0.76 off.

[BUG] RAMSES: temperature units are incorrect

---

yt/data_objects/static_output.py

This changes the default latex representation of comoving axes from $\mathrm{Mpc}/(1+z)$ to being $\mathrm{cMpc}$, the latter being the convention, while the former - albeit correct - is quite confusing and cumbersome.
Happy to *not* merge this if this is deemed controversial.

Represent comoving with a `c` prefix

---

.github/workflows/wheels.yaml
pyproject.toml

cibuildwheel 3.1.0 includes `cp314` and `cp314t` targets by default.
Testing on `cp314` requires a bit of fiddling since our dependencies are not there yet, but it's tractable.
I'm excluding `cp314t` since we've done exactly 0 effort towards supporting free threading so far.

WHL: bump cibuildwheel to 3.1.1, start testing wheels on CPython 3.14

---

yt/data_objects/selection_objects/data_selection_objects.py

This fixes #5203. It prevents the issue by returning a copy of the bounding box rather than try to modify it in place.

[BUGFIX] Fix #5203

---

.github/workflows/build-test.yaml

Looks like images tests are currently doubly broken: 2 of them fail, but the reporting step is itself broken on `pytest>=8.4`, so I'm starting with a fix for this last part, as a follow up to #5176. I'll see if I can fix the tests themselved then.

TST: fix image tests reporting-on-error and update failing tests

---

.github/workflows/wheels.yaml
pyproject.toml

If I recall correctly the rationale for not testing these wheels was that NumPy didn't support the platform at the time, but they do now, so let's give it a try.

WHL: test musllinux wheels

---

yt/data_objects/static_output.py

When loading a dataset whose path contains non-ASCII characters (e.g. emoji, Chinese, Greek letters), yt currently raises:
```bash
File "/Users/jisuoqing/Downloads/🔥/slice.py", line 5, in <module>
ds = yt.load(filename)
File "/opt/homebrew/Caskroom/miniforge/base/envs/yt/lib/python3.10/site-packages/yt/_maintenance/deprecation.py", line 68, in inner
return func(*args, **kwargs)
File "/opt/homebrew/Caskroom/miniforge/base/envs/yt/lib/python3.10/site-packages/yt/loaders.py", line 141, in load
return cls(fn, *args, **kwargs)
File "/opt/homebrew/Caskroom/miniforge/base/envs/yt/lib/python3.10/site-packages/yt/frontends/athena_pp/data_structures.py", line 164, in __init__
Dataset.__init__(
File "/opt/homebrew/Caskroom/miniforge/base/envs/yt/lib/python3.10/site- …
```

[BUG] minor Fix dataset hashing for non-ASCII paths by encoding `parameter_filename` as UTF-8

---

yt/data_objects/selection_objects/spheroids.py
yt/utilities/exceptions.py
yt/visualization/volume_rendering/tests/test_composite.py
yt/visualization/volume_rendering/tests/test_points.py
yt/visualization/volume_rendering/tests/test_zbuff.py

The check on grid size cause the building of the entirety of the index.
This causes a massive slowdown for e.g. RAMSES dataset where the smallest cell size requires reading the entirety of the AMR structure.
The fix? Remove this check and live on the edge.
Note: this makes https://github.com/yt-project/yt/pull/5060 more or less useless.

Removing YTSphereTooSmall

---

yt/fields/field_functions.py
yt/frontends/tipsy/io.py
yt/utilities/amr_kdtree/amr_kdtools.py
yt/utilities/initial_conditions.py
yt/visualization/volume_rendering/old_camera.py

xref https://github.com/numpy/numpy/pull/29052

BUG: fix an incoming deprecation warning from numpy 2.4 (np.minimum and np.maximum's out argument must be passed as keyword)

---

yt/frontends/stream/tests/test_stream_unstructured.py
yt/loaders.py

This fixes a bug preventing users to pass in data with units to the unstructured mesh loaders.
- ~[ ] New features are documented, with docstrings and narrative docs~

[BUG] Allow data to have units when creating unstructured datasets

---

yt/visualization/tests/test_image_comp_2D_plots.py

[example logs](https://github.com/yt-project/yt/actions/runs/18231134374)
xref: https://github.com/matplotlib/matplotlib/pull/30531
The blessed replacement is available since matplotlib 3.4, and we already require >=3.6 so we can simply migrate.
backporting to improve testability on the backport branch

TST: avoid mpl API pending-deprecation (`Colormap.set_bad`)

---

pyproject.toml
setup.py
setupext.py

While setting up abi3 wheels for another package (h5py), I discovered this cleaner way to achieve the same result; instead of overriding the `get_tag` method, we just pass `py_limited_api` as an option.

BLD: avoid direct dependency on wheel library
